### ISSUE TITLE
[Feature Request]: Drag a model into an existing node, from the Model Library.

### ISSUE THREAD

**Issue by JorgeR81** [Comfy-Org/ComfyUI_frontend#1000]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

When we drag a model into the canvas, a new node is created. 
This is very useful to build new workflows. 

But I'd like to load the model into an existing node, if the model is dragged into that node.
Currently, a new node is created.

![lib](https://github.com/user-attachments/assets/f34d3d2d-a5bd-4be5-be27-461b7e065e84)

### Proposed workflow

Just drag the model on top of a compatible loader node. 

You could add a visual indicator ( while clicking down ), to make sure the model will be loaded on the existing node ( on click up ).
( It could be, for example, a blue line around the node ).

---

If the current workflow only has a loader node for the selected model, this could also be done via right click menu.
It could be similar to the workflow right click menu, but just with the insert option. 

( This may be too complex to implement but, ideally, the right click menu could list all the loader nodes, in the current workflow, that would accept the model. )

![libw](https://github.com/user-attachments/assets/a89c34bb-54fc-4377-98a4-c79494f5cdbb)

**Comment by mcmonkey4eva** [comment]
PR for this https://github.com/Comfy-Org/ComfyUI_frontend/pull/1004
