### ISSUE TITLE
[Feature Request]: Make the new Queue toolbar moveable in Comfy Front-End v1.3.0

### ISSUE THREAD

**Issue by camoody1** [Comfy-Org/ComfyUI_frontend#1001]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I would like the new Queue toolbar to have a "grip/grab" textured section on the extreme right of the bar that the user can click on to drag the toolbar to different positions on the graph.

### Proposed workflow

1. Go to ....
2. Press ....
3. ...

**Comment by JorgeR81** [comment]
Ideally, the queue menu could be moveable and dockable, if dragged on to the Top Bar.

An option in the user settings to add it to the top bar would also do, but dockable menus would be pretty cool ... 

---


**EDIT:**

OK, I just noticed the Top Bar has a different implementation from the Sidebar and the Floating menu ( e.g. different tool tooltips and slightly different button styles )

So docking would probably not look very good, unless the Top Bar implementation is updated.

**Comment by UrzasLegacy** [comment]
Would love for it to be moveable, preferably dockable as there's a ton of unused real estate in the top bar currently.

**Comment by huchenlei** [comment]
> Would love for it to be moveable, preferably dockable as there's a ton of unused real estate in the top bar currently.

BTW we do support displaying opened workflows as tabs on the topbar. https://github.com/Comfy-Org/ComfyUI_frontend/pull/952
![image](https://github.com/user-attachments/assets/b0ff81d0-2f70-43fa-8a14-d1b7c4ddd51e)

It's possible to manually edit (ComfyUI)/user/default/comfy.settings.json to have "Comfy.Workflow.WorkflowTabsPosition": "Topbar" to get access to this behavior.

Read more on https://github.com/Comfy-Org/ComfyUI_frontend/issues/995

**Comment by JorgeR81** [comment]
So the queue buttons were moved out of the Top Bar to make room for workflows tabs ?

Why not make this an user option ?
I like the workflows tabs, but I would prefer to have the queue buttons in the Top bar.

Alternatively, if we just use icons ( instead of text ) for all the Top Bar options, we probably have space for both.
And the workflow tabs ( with text ) would be easier to differentiate.

**Comment by camoody1** [comment]
Oh, please yes. Make the open workflows available as tabs in the top toolbar. I hate having to open the side bar to switch between workflows. And then having to click it again to close it. A Tab option in the User Settings would be outstanding.

**Comment by camoody1** [comment]
> Would love for it to be moveable, preferably dockable as there's a ton of unused real estate in the top bar currently.

In an IDEAL world, this team could work with the author of Crystools to add his monitors to the top toolbar. I can't live without his monitors showing me my current CPU, RAM, VRAM and GPU Temp. Making this happen would be outstanding.

https://github.com/crystian/ComfyUI-Crystools

**Comment by huchenlei** [comment]
> Oh, please yes. Make the open workflows available as tabs in the top toolbar. I hate having to open the side bar to switch between workflows. And then having to click it again to close it. A Tab option in the User Settings would be outstanding.

It is explicitly hidden for browser users as @yoland68 think it would be bad/confusing for current users who has multiple browser level tabs open, and we currently lack a mechanism to sync the opened workflows across multiple browser tabs.

We are trying to listen for explicit metric / petition / feedback to send the message that this feature will make those users who previous use multiple browser level tabs no longer open multiple browser level tabs to make this the default behavior.

**Comment by camoody1** [comment]
> > Oh, please yes. Make the open workflows available as tabs in the top toolbar. I hate having to open the side bar to switch between workflows. And then having to click it again to close it. A Tab option in the User Settings would be outstanding.
> 
> It is explicitly hidden for browser users as @yoland68 think it would be bad/confusing for current users who has multiple browser level tabs open, and we currently lack a mechanism to sync the opened workflows across multiple browser tabs.
> 
> We are trying to listen for explicit metric / petition / feedback to send the message that this feature will make those users who previous use multiple browser level tabs no longer open multiple browser level tabs to make this the default behavior.

I was once someone who used multiple browser windows to bounce back and forth between workflows. But once the new gui gave me an easy mechanism for opening multiple workflows, the old method of multiple windows became much more difficult. If you went a step further and actually added TABS for each workflow at the top of the Comfy window, it would FEEL like having multiple browser windows open without the extra difficulty of making sure everything was synced. This new method is much more user friendly and I, for one, am glad I switched.

**Comment by mijuku233** [comment]
> > Oh, please yes. Make the open workflows available as tabs in the top toolbar. I hate having to open the side bar to switch between workflows. And then having to click it again to close it. A Tab option in the User Settings would be outstanding.
> 
> It is explicitly hidden for browser users as @yoland68 think it would be bad/confusing for current users who has multiple browser level tabs open, and we currently lack a mechanism to sync the opened workflows across multiple browser tabs.
> 
> We are trying to listen for explicit metric / petition / feedback to send the message that this feature will make those users who previous use multiple browser level tabs no longer open multiple browser level tabs to make this the default behavior.

I don't quite understand what you mean, why do you want to synchronize the workflows that are open?
People open multiple browser-level tabs just to edit/use different workflows, right?
I don't know if it's because of the synchronization of workflows, I can't create a copy of the same workflow, so the new workflow browser has no use value for me (I still use the most original method, export the workflow directly), I originally planned to raise an issue to explain this matter later.

**Comment by yoland68** [comment]
> So the queue buttons were moved out of the Top Bar to make room for workflows tabs ?
> 
> Why not make this an user option ? I like the workflows tabs, but I would prefer to have the queue buttons in the Top bar.
> 
> Alternatively, if we just use icons ( instead of text ) for all the Top Bar options, we probably have space for both. And the workflow tabs ( with text ) would be easier to differentiate.

Would love to hear more about your preference of keeping queue at the top? What's breaking or annoying to move the action-bar to the center of the screen? How did you handle this issue before the new beta UI is implemented in place?

**Comment by yoland68** [comment]
> > So the queue buttons were moved out of the Top Bar to make room for workflows tabs ?
> > Why not make this an user option ? I like the workflows tabs, but I would prefer to have the queue buttons in the Top bar.
> > Alternatively, if we just use icons ( instead of text ) for all the Top Bar options, we probably have space for both. And the workflow tabs ( with text ) would be easier to differentiate.
> 
> Would love to hear more about your preference of keeping queue at the top? What's breaking or annoying to move the action-bar to the center of the screen? How did you handle this issue before the new beta UI is implemented in place?

Also, if you have a bit time, would love to see a screen recording of you interacting with the 1.3.1 release vs the previous top bar queue button. Feel free to DM me on Discord to share if you don't feel comfortable! 🙏🙏 Really appreciate your time! If you don't have time, it's all good!

**Comment by JorgeR81** [comment]
> > So the queue buttons were moved out of the Top Bar to make room for workflows tabs ?
> > 
> > Why not make this an user option ? I like the workflows tabs, but I would prefer to have the queue buttons in the Top bar.
> > 
> > Alternatively, if we just use icons ( instead of text ) for all the Top Bar options, we probably have space for both. And the workflow tabs ( with text ) would be easier to differentiate.
> 
> Would love to hear more about your preference of keeping queue at the top? What's breaking or annoying to move the action-bar to the center of the screen? How did you handle this issue before the new beta UI is implemented in place?

The floating queue menu looks good and it could be nice as default, for new users that use simple workflows. 
I would agree that's probably the more convenient configuration to use with the Comfy UI default workflow.
But if you have larger workflows, you don't want floating panels in front of your nodes.

My suggestion is having user options for :
- floating queue menu - or - integrated in the Topbar 
- workflow tabs inside Comfy UI - or - using multiple browser tabs ( having both is unnecessary and can be confusing )

If necessary, I wouldn't mind having 2 rows in the topbar, but floating panels over a complex workflow is too distracting.

**Comment by JorgeR81** [comment]
> BTW we do support displaying opened workflows as tabs on the topbar. https://github.com/Comfy-Org/ComfyUI_frontend/pull/952

> It's possible to manually edit (ComfyUI)/user/default/comfy.settings.json to have "Comfy.Workflow.WorkflowTabsPosition": "Topbar" to get access to this behavior.

Just tried this.  It works great ! Didn't notice any issues.

You should make this the default, or at least make it an option in  the GUI settings.

----

The draggable bar also works fine.
Aesthetically, it would look better, if the topbar had the same implementation / style.

![bt](https://github.com/user-attachments/assets/19598dd9-33de-4c0d-9872-5009e499c8c9)

**Comment by JorgeR81** [comment]
If it's not possible to make the floating panel dockable, could you consider making it a little smaller, to better fit on top of the Topbar.   

![bt2](https://github.com/user-attachments/assets/5cc04307-a520-43cf-ac2f-58389baf4826)

---

With this positioning, I still can fit workflow 4 tabs ( which is more than enough most people ) in a single row, even with custom buttons, in a 1920 x 1080 display.

I could fit another tab if the `Show Image Feed` button had no text ( like before v1.3.0 )

![bt3](https://github.com/user-attachments/assets/438d81dc-76b8-43d6-a70a-f42e572e5079)


![bt3](https://github.com/user-attachments/assets/2663a64d-cd9c-4afa-a4bc-e6199d9ef165)
