### ISSUE TITLE
[Bug]: Model Library doesn't show Lora 

### ISSUE THREAD

**Issue by ronan36880** [Comfy-Org/ComfyUI_frontend#1003]
### Frontend Version

1.3.1

### Expected Behavior

Expect to be able to see the amount of steps of any given lora.
![image](https://github.com/user-attachments/assets/093f384b-9b61-450a-896b-471297da7c08)

### Actual Behavior

The file name briefly flashes for half a second until the metadata is loaded, then, once the metadata has been loaded, the file name information is no longer accessible.

![image](https://github.com/user-attachments/assets/aa92c179-d6c4-40d9-8a91-626f19a72364)

### Steps to Reproduce

Have a Lora whose metadata name doesn't match the file name.

An example would be the file name being `GamBark8_prototype-step00001200.safetensors` but the metadata name is just `GamBark8_prototype`.

### Debug Logs

```powershell
(No logs relevant to this)
```

### Browser Logs

(No logs relevant to this)

### What browsers do you use to access the UI ?

Google Chrome

### Other

While this could seem inconsequential, the Model Library turns out less useful for me than I expected since I experiment with Lora training settings - relying on file names to keep track of some things.

Maybe a way of working around this would be to add the filename to the model preview on hover?

The hover preview doesn't show up on any of my Loras because it requires either [(source)](https://github.com/Comfy-Org/ComfyUI_frontend/blob/05f999903d5bca6ed6115689ef5a86a81d9e87c9/src/components/sidebar/tabs/modelLibrary/ModelTreeLeaf.vue#L86-L98):
- An author
- A description
- A usage hint
- A trigger phrase
- An image

**Comment by mcmonkey4eva** [comment]
Not bug - the first visible bit of text is the filename, what it gets replaced by is the metadata title. You should probably just configure your training software to emit a title that's in line with your expectations?

**Comment by mcmonkey4eva** [comment]
Submitted PR https://github.com/Comfy-Org/ComfyUI_frontend/pull/1005 which adds the filename to the preview box, and enables the preview if the title is mismatched from the filename

**Comment by JorgeR81** [comment]
This also happens to me in loras I've got from Citivai.

_sidebar :_
![l1](https://github.com/user-attachments/assets/8785038c-e778-44be-904b-ae3a232d78e7)

_lora loader node :_
![l2](https://github.com/user-attachments/assets/6d9287fd-9c95-4b97-b934-e6c067957536)

_windows 10 file explorer :_
![l3](https://github.com/user-attachments/assets/5afe2449-73af-4e4d-b310-7a7fbc2641a8)

**Comment by JorgeR81** [comment]
OK, so in the sidebar we see the metadata title, not the filename, right ?

Why not have a global option to show either the metadata title or the filename, across the whole GUI ?

---

In the Sidebar "**_Realistic Stock Photo v1_**" ( from Civitai ) shows up as "**_GettyImageFinally_**"

![sd2](https://github.com/user-attachments/assets/51fd6624-61dd-4f6e-ab78-d848a472fb03)


![sdxl](https://github.com/user-attachments/assets/1db377b7-ba86-4ae6-bd96-0c334f7627ea)

**Comment by ronan36880** [comment]
> Submitted PR #1005 which adds the filename to the preview box, and enables the preview if the title is mismatched from the filename

Awesome, thank you so much! 

> You should probably just configure your training software to emit a title that's in line with your expectations?

That could be a temporary workaround, but I'd say that most people don't control the metadata of 90% of the Loras they use on a day-to-day basis 😅

**Comment by LukeG89** [comment]
Similar problem here, I was looking for `juggernautXL`
![model_name_mismatch](https://github.com/user-attachments/assets/9bb5957f-e146-4270-a0ee-5cf00e375662)

**Comment by mcmonkey4eva** [comment]
Eventually, it should be easy to edit metadata entirely in UI to self-correct, that's just not possible if you're using core comfy exclusive yet.

If you care about user-friendly features like that, you should probably be running [SwarmUI](https://github.com/mcmonkeyprojects/SwarmUI) around your comfy install, which does already have metadata editing in-UI.

However the user settings option is a good idea for a workaround pending in-comfy metadata editing support, so I've added it to the linked PR as well
![image](https://github.com/user-attachments/assets/16510591-59c6-4f25-852c-0be859782590)

**Comment by mcmonkey4eva** [comment]
PR merged, the setting is now available
