### ISSUE TITLE
[Feature Request]: Model Library should auto-expand subfolders like Node Library

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI_frontend#1006]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Currently, when you search for a model, you have to manually expand the subfolders to get to the model.

https://github.com/user-attachments/assets/b867c686-a141-45c7-8827-f7ab5664ba08

The folders should auto-expand like in Node Library:

![auto_expand_folders](https://github.com/user-attachments/assets/2f9d73f8-8ea8-4592-958e-1ecc9a358671)

### Proposed workflow

.

**Comment by mcmonkey4eva** [comment]
~~PR for it https://github.com/Comfy-Org/ComfyUI_frontend/pull/1080~~ I misunderstood context
