### ISSUE TITLE
[Bug]: Rgthree's Progress Bar no longer compatible with the new 1.3.x frontend

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI_frontend#1009]
### Frontend Version

1.3.1

### Expected Behavior

Rgthree's Progress Bar is compatible with the new frontend.

### Actual Behavior

If it's set at the top, it doesn't appear.
If it's set at the bottom, it's over the setting button.

### Steps to Reproduce

https://github.com/user-attachments/assets/73b1deea-a264-4fcb-ba5d-c81ddc6d28b4

### Debug Logs

```powershell
no errors
```

### Browser Logs

no errors

### What browsers do you use to access the UI ?

Google Chrome

### Other

I know this is not a frontend bug. I already opened a bug report to rgthree repository (https://github.com/rgthree/rgthree-comfy/issues/339), but he asked me to report the bug here.

**Comment by rgthree** [comment]
Was able to fix this forward from rgthree-comfy and should be working for 1.3.x, which had changed the style attribute on `body` that rghtree-comfy was using to try to detect the newer comfy version for css positioning.
