### ISSUE TITLE
[Feature Request]: Store settings server-side

### ISSUE THREAD

**Issue by christian-byrne** [Comfy-Org/ComfyUI_frontend#1013]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Settings would be centralized on the server.

Benefits:
- User settings persist across browsers
- User settings ported when moving Comfy install to new device
- Easier multi-user configuration
- Custom node developers can more easily communicate between backend and frontend bidirectionally
- Custom node developers can create settings in the UI without having to write any JS.

### Proposed workflow

1. Settings are stored and loaded by the backend.
2. Settings are accessed/changed via server's API, allowing GET/PATCH from frontend, backend, extension, custom node, etc.
3. Settings fields can be configured/added in the `pyproject.toml`

**Comment by huchenlei** [comment]
Is this feature about some backend configurations that can be hot-changed? such as load device, dtype, etc?

**Comment by christian-byrne** [comment]
> Is this feature about some backend configurations that can be hot-changed? such as load device, dtype, etc?

It's about storing all settings values on server instead of local storage.

**Comment by huchenlei** [comment]
> > Is this feature about some backend configurations that can be hot-changed? such as load device, dtype, etc?
> 
> It's about storing all settings values on server instead of local storage.

Currently that is already the case for settings. They are eagerly pushing changes to settings.json. The issue now is only lacking of mechanism to sync settings across multiple browser tabs.

**Comment by christian-byrne** [comment]
Can you briefly explain the system? I did not see the server endpoints for changing/acessing settings.

**Comment by christian-byrne** [comment]
I see it is in `user_manager.py`. The frontend is accessing these settings via server as source of truth?

**Comment by huchenlei** [comment]
Related code:
https://github.com/Comfy-Org/ComfyUI_frontend/blob/9050591ff978efb6eb6d2ea65cc2c0195c1f4094/src/scripts/ui/settings.ts#L138-L156

In short we call `api.storeSettings` to update settings in the server side.

https://github.com/Comfy-Org/ComfyUI_frontend/blob/9050591ff978efb6eb6d2ea65cc2c0195c1f4094/src/scripts/api.ts#L572-L591

**Comment by christian-byrne** [comment]
Thanks, I understand much better now. So settings are loaded from server, and changes are pushed to server.

Can they be GET from server on access as well? Instead of returning the client copy? It may be debounced. I think the server should be the source of truth.

**Comment by christian-byrne** [comment]
> The issue now is only lacking of mechanism to sync settings across multiple browser tabs.

Would it be solved by having the server manage the settings and accessing setting value on client side occurs through server API?

**Comment by huchenlei** [comment]
> > The issue now is only lacking of mechanism to sync settings across multiple browser tabs.
> 
> Would it be solved by having the server manage the settings and accessing setting value on client side occurs through server API?

One thing we can do is using ws message to boardcast setting change to all clients.

**Comment by christian-byrne** [comment]
Yes it seems that is good. I did not fully understand the trade offs before.

![Selection_425](https://github.com/user-attachments/assets/20ee3bde-3e1e-4cc1-acbb-274cdc0ab748)

**Comment by christian-byrne** [comment]
For this

> - Custom node developers can more easily communicate between backend and frontend bidirectionally
> - Custom node developers can create settings in the UI from the backend

There may be a better solution
