### ISSUE TITLE
[Feature Request]: Pls keep the workflow in the top bar menu

### ISSUE THREAD

**Issue by pandayummy** [Comfy-Org/ComfyUI_frontend#1025]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Workflow list is one of the most frequently used features in ComfyUI, and should be kept in the top menu instead of sidebar.

![image](https://github.com/user-attachments/assets/641dbd8b-84d6-46ba-86ae-d9d2c0fb6cc5)

![image](https://github.com/user-attachments/assets/5493f7c1-9f6c-44e8-9951-01bcee11b8ba)

### Proposed workflow

And the sidebar items should be in this order:

1. Queue
2. (Workflows)  -- better in top bar menu
3. (Nodes Map) -- what's the meaning of this? workflow itself is visually friendly, we can operate on any node in the main workspace.
4. Node Library
5. (Model Library) -- Model Library is not useful at all, I think.  People just use Windows Explorer to manage models.

![image](https://github.com/user-attachments/assets/57c89939-af5b-48b3-a17d-948e4470fa22)

### Additional information

And it would be more visually friendly to place all submenu of Settings into the sidebar.
![image](https://github.com/user-attachments/assets/8ce8c966-5358-4065-a549-ec9226ea4a01)

**Comment by JorgeR81** [comment]
> Workflow list is one of the most frequently used features in ComfyUI, and should be kept in the top menu instead of sidebar.

The workflows in the sidebar are better if you have many workflows.
 
My ideal solution would be to pin / bookmark some saved workflows in the sidebar ( about 3 or 4 for me ), and they will show up in the Topbar pop down menu.

---

> (Nodes Map) -- what's the meaning of this? workflow itself is visually friendly, we can operate on any node in the main workspace.

Where is the Nodes Map ? Is that the bottom icon on your Sidebar ? I don't have it.
Is that from a custom node suite ?

---

> (Model Library) -- Model Library is not useful at all, I think. People just use Windows Explorer to manage models.

The model library will be more useful, when more features are added : https://github.com/Comfy-Org/ComfyUI_frontend/issues/1000

**Comment by tiptinker** [comment]
The nodes map might come from EaseUse
![image](https://github.com/user-attachments/assets/d153e8a1-ef75-44c1-a65b-44409572fb68)
![image](https://github.com/user-attachments/assets/48c6f8a9-bc76-4ab7-82c7-2c88904b05f5)

**Comment by yoland68** [comment]
How many workflows do you have saved? What is your typical experience of interacting with the workflows in the top menu?

**Comment by tiptinker** [comment]
![image](https://github.com/user-attachments/assets/f3d52b60-13d3-4d8e-819a-b13540104f55)

All my workflows can be reached in the top menu.  It's more convenient than sidebar.

Maybe you can add a scroll bar in the drop down  in case of tooo many workflows.

![image](https://github.com/user-attachments/assets/8c09b908-e44c-4bde-91cf-fd43c8635444)

**Comment by yoland68** [comment]
The top menu is almost the same as side menu here for you. What's the reasoning for your preference for the previous mechanism? Is it mostly existing habits?

**Comment by tiptinker** [comment]
It's a habit, and more importantly, when moved to sidebar, I can't distinguish which one is which, they are just some similar icons.

![image](https://github.com/user-attachments/assets/2cb5ed67-acbd-409a-8a17-06ab5cf15498)


I have to click one by one to find what I want.  Maybe after sometime I will get used to that to some extent, but will get confused sometimes.

Maybe you can use Text instead of Icons in sidebar menu. That will be more visually friendly. Like those in settings.

![image](https://github.com/user-attachments/assets/a0a59672-3a3b-4a37-bbc0-53cd105d6eb1)

**Comment by yoland68** [comment]
Ya, text definitely would be helpful to help for user education and discoverability here.

**Comment by tiptinker** [comment]
Maybe some icons with text on it
![image](https://github.com/user-attachments/assets/ceb8aabb-faa4-48b2-b8c7-cfef0c790589)

or

Icon + Text

**Comment by JorgeR81** [comment]
@yoland68, If you decide you add text to the sidebar ( instead of just icons ), please make it optional.

**Comment by mijuku233** [comment]
> Ya, text definitely would be helpful to help for user education and discoverability here.

Additionally, allowing users to adjust the sidebar button position can improve this problem.
Put the workflow browser at the top so that users can find it quickly.

**Comment by amimi818** [comment]
I support putting workflow on the sidebar, but it's best to have the corresponding shortcut keys for the sidebar menus (e.g., nodes, workflows).

**Comment by camoody1** [comment]
I'd like to jump in here to vote for moving some aspect of opening workflows to the topbar "Workflow" menu. I find it a bit illogical to have some workflow options on the top bar and others in the side bar. It's a bit like having a refrigerator on one side of the kitchen and a freezer on the other side. It just doesn't make much sense to my brain. Also, having the Workflows listed in the sidebar means that I have to click a sidebar button to first open the workflow list, then resize the sidebar so I can read my workflow names, then select a workflow, and finally click the sidebar button AGAIN to close the sidebar. That's a lot of clicks to just open a workflow. It seems much easier to have a droplist from the topbar Workflows menu, just as you had with the previous iteration of the front-end.

**Comment by JorgeR81** [comment]
I think we could have both.

The sidebar is already a "duplication" of other features ( e.g. node library vs adding nodes via right click menu ).
The sidebar is usually less convenient to use, unless we need to select items from a very long list ( if you have many workflows; custom nodes, models, etc. ... ) so I think there is a place for both methods.

**Comment by LukeG89** [comment]
I agree with @camoody1, and also the workflow tab on sidebar is pretty inconvenient since you have to close the other tabs (Queue, Node Library, Model Library, etc.) in order to access the workflows.
The best solution in my opinion would be:

- Merging workflow dropdown menu and workflow tab together
   - **Only one place to manage workflows**
- Moving workflow tab back on topbar to make it independent from the others
   - This way, you can easy open/switch workflows and keep one tab open

**Comment by camoody1** [comment]
> I think we could have both.
> 
> The sidebar is already a "duplication" of other features ( e.g. node library vs adding nodes via right click menu ). The sidebar is usually less convenient to use, unless we need to select items from a very long list ( if you have many workflows; custom nodes, models, etc. ... ) so I think there is a place for both methods.

I'd like to add that I love having the Node list in the side bar. I love being able to search for nodes easily and pinning my favorites. There is definitely no need to change that functionality. 👍🏼

**Comment by camoody1** [comment]
Booooo
