### ISSUE TITLE
[Feature Request]: Option to have toolbar transparency ( tying everything together )

### ISSUE THREAD

**Issue by JorgeR81** [Comfy-Org/ComfyUI_frontend#1030]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

This could be a good way to deal with the floating panel configuration. 
I think the issue is not so much about the space we lose, but the fact that floating panels can be distracting, in a node interface.

In Blender most floating panels are really toolbars with full transparency, so you can only see the buttons. 
And if you followed Blender development you may remember it started with full opacity, then some transparency and now full transparency, by default. 

### Proposed workflow

So you could have:

- The current Sidebar, on the left side ( **with full opacity** )
- An optional Topbar just for workflows tabs ( **with full opacity** ) ( https://github.com/Comfy-Org/ComfyUI_frontend/pull/952 )
- The current Topbar, below that ( with user selectable transparency )
- A Bottombar, with the queue buttons ( with user selectable transparency )
_( and maybe ... )_
- A Sidebar, on the right side, with the zoom buttons ( with user selectable transparency ) ( https://github.com/Comfy-Org/ComfyUI_frontend/pull/1023 )
 
This will give plenty of space for new buttons or custom extensions, in the future.

We can have full transparency by default ( similar to Blender )
Some users may prefer the look of partial transparency ( like a glass panel ),
And users that don't like floating panels, just turn on full opacity. 

And, in the future, if some of these toolbars are moveable ( https://github.com/Comfy-Org/ComfyUI_frontend/issues/1001 ), full transparency could be enabled automatically, if they are not docked ( not adjacent to the borders of the canvas ).

**Comment by mijuku233** [comment]
The main reason it's annoying is that floating panels obscure nodes.
You have to move the canvas/node to see and edit it.
It feels like "You must attack the minion with Taunt.", which is pretty annoying.
The suggestion you made doesn't solve the problem, it shrinks the canvas further, which makes it worse.

**Comment by mijuku233** [comment]
I think the best solution is to make these floating panels optional settings. 
People who like them can turn them on in the settings, and people who hate them can turn them off in the settings.

**Comment by yoland68** [comment]
@mijuku233, oh man, you must dislike this feature here. We are traveling right now but will definitely revisit this feature here. Meanwhile if you have more specific recording of you using/explain the failures when floating panel s obstructing you, please post here (or DM me on Discord if you don't feel comfortable posting publicly) 🙏

Thank you for all the feedback!

**Comment by JorgeR81** [comment]
> I think the best solution is to make these floating panels optional settings.

Yeah, but if the floating panels are "disabled", the buttons need to go in a toolbar anyways.
 
Maybe we could have a hotkey just to hide all the toolbars / panels, when we need every inch of canvas space.

**Comment by JorgeR81** [comment]
> oh man, you must dislike this feature here.

I think the new feature looks good and may be the best option for many users. 

But users ( especially Comfy UI users ) like to be able to customize things.

**Comment by yoland68** [comment]
FYI, my discord is @yoland_y

**Comment by mijuku233** [comment]
@yoland68 
Without the floating menu options, I can directly see and edit the values ​​for the preprocessor and resolution.
![屏幕截图 2024-09-27 231844](https://github.com/user-attachments/assets/b743d5c2-14e4-403c-9a2b-bb0a6f92a6bc)
When the floating menu option is present, I cannot directly view or edit the values ​​of preprocessor and resolution.
![屏幕截图 2024-09-27 233531](https://github.com/user-attachments/assets/9dc55539-2254-49c6-90c7-83a7b7218952)

**Comment by mijuku233** [comment]
@yoland68 
The floating menu option is beautiful and it is friendly to ultra-wide screens.
But for some users, it will bring a bad experience.
Please allow future floating panels to be freely fixed to the top bar.
Finally, happy travels!

**Comment by dchatel** [comment]
An image says a lot...

If you're going to have long menu bars, why not use them in the first place?
![image](https://github.com/user-attachments/assets/6d529e0f-0a7e-4bdd-96ec-a9e786f77810)
What's worse with the graph resize menu at the bottom right corner is that:
- the reset view button used to be at in the top bar. Then in the floating queue menu. And now there. Let's break users habits all the time. I'm sure they'll be happy.
- the current resize menu is part of the div used for the graph itself. Meaning, you cannot easily move it outside of the graph area. I tried to move it in the top bar (where it belongs in my opinion), but the parents (graph-canvas-container, and another one) both have overflow: hidden property set. So if you move the resize menu **outside of the graph** it becomes invisible.

If the ultimate goal is to remove the menu bars completely, and instead introduce tons of floating elements in the graph, that's a regression. The top/side menu bars were introduced to remove the original large floating menu.
