### ISSUE TITLE
Is there a development tutorial for the new comfyui?

### ISSUE THREAD

**Issue by planb788** [Comfy-Org/ComfyUI_frontend#1037]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Although the official sample nodes already provide guidance on how to write a custom backend node, there is very little assistance provided on how to modify the frontend interface. Additionally, the new version of the interface has adopted Vue for its creation, which introduces many differences compared to traditional JavaScript. Therefore, for those who are looking to get started with developing this frontend interface, it can be somewhat confusing.

### Proposed workflow

Is there an existing tutorial on this?

**Comment by christian-byrne** [comment]
Have you seen the docs? https://docs.comfy.org/essentials/javascript_overview

**Comment by planb788** [comment]
> Have you seen the docs? https://docs.comfy.org/essentials/javascript_overview

Thank you so much. This is exactly what I need!

**Comment by christian-byrne** [comment]
You can also create sidebar tab, topbar menu item, and toasts https://github.com/Comfy-Org/ComfyUI_frontend?tab=readme-ov-file#node-developers-api. These should be added to the docs
