### ISSUE TITLE
[Bug]: Fullscreen changes draggable menu position

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI_frontend#1039]
### Frontend Version

1.3.3

### Expected Behavior

If you place the menu at the bottom of the screen, the menu should keep its position every time you enter or exit fullscreen.

### Actual Behavior

When entering and exiting fullcreen, the position of the menu changes.

### Steps to Reproduce

https://github.com/user-attachments/assets/1fa4ee41-0406-4ef6-8b98-81d126a063e7

### Debug Logs

```powershell
No errors
```

### Browser Logs

No errors

### What browsers do you use to access the UI ?

Google Chrome

**Comment by JorgeR81** [comment]
It would be nice if the floating menu position was dynamically adjusted, when it's placed near the bottom, and also near the top of the canvas.

If we have many workflows open and the Top Bar is in a 2 row configuration, it will be partially covered by the floating menu. 

![wf11](https://github.com/user-attachments/assets/90c0b378-01b9-4575-93ae-4e463c9c9212)

**Comment by mcmonkey4eva** [comment]
Confirmed, have seen the same. I saw even worse too: with some browser resizes, the bar goes off the bottom of the screen and becomes unusable
This needs, imo, two fixes:
- 1: Boundary boxes. It should be blocked from going past the edges of the screen
- 2: autoanchoring. That is: if it's near the bottom of the screen, when the screen is resized, it should retain its position relative to the bottom (say eg it was 200px above bottom before a resize, it needs to be 200px above bottom after a resize). Similarly, if near the top, it should instead retain position relative to the top. Same idea for left/right.

**Comment by LukeG89** [comment]
This commit fixed the issue I reported (not the one reported by @JorgeR81): https://github.com/Comfy-Org/ComfyUI_frontend/commit/2d5faa7f3d33bcd2bc87a5f5d4ac8613f9625a51

But after the implementation of the docking Queue Menu, it doesn't make sense to keep it under the topbar.
So, I close the issue.
