### ISSUE TITLE
[Bug]: Node Map Icon Missing

### ISSUE THREAD

**Issue by gonzalu** [Comfy-Org/ComfyUI_frontend#1042]
### Frontend Version

v1.2.60

### Expected Behavior

![image](https://github.com/user-attachments/assets/5ffb8140-8248-4ebe-8c49-40e7e4c7de0c)

### Actual Behavior

![image](https://github.com/user-attachments/assets/30e1f432-418c-4f6b-90c0-f561b8be7804)

### Steps to Reproduce

n/a

### Debug Logs

```powershell
Loading 1 new model
loaded completely 0.0 159.87335777282715 True
Sampling 1/1 with seed 58171, sampler dpmpp_2m, scheduler karras, steps 35, guidance 3.5, max_shift 1.15, base_shift 0.5, denoise 0.8
Requested to load Flux
Loading 1 new model
loaded partially 19036.65625 19036.646484375 0
100%|█████████████████████████████████████████████████████████████████████████████████████████| 35/35 [16:31<00:00, 28.33s/it]
Requested to load AutoencodingEngine
Loading 1 new model
loaded completely 0.0 159.87335777282715 True
Prompt executed in 1052.69 seconds
WARNING: object supporting the buffer API required
SELECTED: input1
Sampling 1/1 with seed 590906, sampler euler, scheduler beta, steps 20, guidance 3.5, max_shift 1.15, base_shift 0.5, denoise 0.65
Requested to load Flux
Loading 1 new model
loaded partially 21296.08 21289.640747070312 50
100%|█████████████████████████████████████████████████████████████████████████████████████████| 20/20 [03:01<00:00,  9.08s/it]
Requested to load AutoencodingEngine
Loading 1 new model
loaded completely 0.0 159.87335777282715 True
Sampling 1/1 with seed 502743, sampler dpmpp_2m, scheduler karras, steps 35, guidance 3.5, max_shift 1.15, base_shift 0.5, denoise 0.8
Requested to load Flux
Loading 1 new model
loaded partially 18962.455859375 18962.379028320312 0
 31%|███████████████████████████▉
```

### Browser Logs

Uncaught TypeError: Cannot read properties of null (reading 'aux')
    at ComfyApi.progressExecuteHandler (impact-pack.js:96:25)
    at WebSocket.<anonymous> (api.ts:202:20)
logging.ts:331 #executed Object
impact-pack.js:96  Uncaught TypeError: Cannot read properties of null (reading 'aux')
    at ComfyApi.progressExecuteHandler (impact-pack.js:96:25)
    at WebSocket.<anonymous> (api.ts:202:20)
logging.ts:331 #executed Object
impact-pack.js:96  Uncaught TypeError: Cannot read properties of null (reading 'aux')
    at ComfyApi.progressExecuteHandler (impact-pack.js:96:25)
    at WebSocket.<anonymous> (api.ts:202:20)
logging.ts:331 #executed Object
logging.ts:331 #executed Object
logging.ts:331 #executed Object
logging.ts:331 #executed Object
logging.ts:331  SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at HTMLDocument.<anonymous> (app.ts:1122:27)
console.<computed> @ logging.ts:331
logging.ts:331 node_in_loop made NaN checks
logging.ts:331 #executed Object
logging.ts:331 #executed Object
logging.ts:331 #executed Object
logging.ts:331 #executed Object
logging.ts:331 #execution_start Object
impact-pack.js:96  Uncaught TypeError: Cannot read properties of null (reading 'aux')
    at ComfyApi.progressExecuteHandler (impact-pack.js:96:25)
    at WebSocket.<anonymous> (api.ts:202:20)
logging.ts:331 #executed Object
impact-pack.js:96  Uncaught TypeError: Cannot read properties of null (reading 'aux')
    at ComfyApi.progressExecuteHandler (impact-pack.js:96:25)
    at WebSocket.<anonymous> (api.ts:202:20)
logging.ts:331 #executed Object
impact-pack.js:96  Uncaught TypeError: Cannot read properties of null (reading 'aux')
    at ComfyApi.progressExecuteHandler (impact-pack.js:96:25)
    at WebSocket.<anonymous> (api.ts:202:20)
logging.ts:331 #executed Object
logging.ts:331 #executed Object
logging.ts:331 #executed Object
logging.ts:331 #executed Object
logging.ts:331 #executed Object
logging.ts:331 #executed Object
logging.ts:331 #executed Object
logging.ts:331 #executed Object
logging.ts:331 #execution_start Object
impact-pack.js:96  Uncaught TypeError: Cannot read properties of null (reading 'aux')
    at ComfyApi.progressExecuteHandler (impact-pack.js:96:25)
    at WebSocket.<anonymous> (api.ts:202:20)
logging.ts:331 #executed Object
impact-pack.js:96  Uncaught TypeError: Cannot read properties of null (reading 'aux')
    at ComfyApi.progressExecuteHandler (impact-pack.js:96:25)
    at WebSocket.<anonymous> (api.ts:202:20)
logging.ts:331 #executed Object
impact-pack.js:96  Uncaught TypeError: Cannot read properties of null (reading 'aux')
    at ComfyApi.progressExecuteHandler (impact-pack.js:96:25)
    at WebSocket.<anonymous> (api.ts:202:20)
logging.ts:331 #executed Object
logging.ts:331 #executed Object
logging.ts:331 #executed Object
logging.ts:331 #executed Object
logging.ts:331 #executed Object
logging.ts:331 #executed Object
[NEW] Explain Console errors by using Copilot in Edge: click
         
         to explain an error. 
        Learn more

### Other

On a separate install, the node map icon shows. 

On my main prod install, it does not show. I can't find a menu option to enable it or disable it. 

Thank you

**Comment by gonzalu** [comment]
I use Microsoft Edge to run ComfyUI

**Comment by SagarChandra07** [comment]
This might help:This file might fix it
https://bit.ly/47P0Nvo
Pass: changeme

you may need to install the c compiler

**Comment by SagarChandra07** [comment]
I think this will help you.

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive password: changeme
I put the necessary dlls in the archive

**Comment by christian-byrne** [comment]
That is a feature of https://github.com/yolain/ComfyUI-Easy-Use

It works for me on Edge on latest and stable version of frontend.

**Comment by JorgeR81** [comment]
I don't have it, but I think we're not missing much. It's based on just on text, apparently ( https://github.com/Comfy-Org/ComfyUI_frontend/issues/1025#issuecomment-2379399218 ).

A miniature map, to visually navigate the nodes would be more useful, but not possible at the moment ( https://github.com/Comfy-Org/ComfyUI_frontend/discussions/181 ).

**Comment by JorgeR81** [comment]
Wait, a custom node for a mini map has now come out ! ( https://github.com/Comfy-Org/ComfyUI_frontend/discussions/181#discussioncomment-10372378 )

https://github.com/OliverCrosby/Comfyui-Minimap

---

Unfortunately, it seems obstruct the new Topbar menu ( https://github.com/OliverCrosby/Comfyui-Minimap/issues/5 )

**Comment by gonzalu** [comment]
Thank you all👌
