### ISSUE TITLE
[Feature Request]: Add a quick way to clear unsaved workflows

### ISSUE THREAD

**Issue by JorgeR81** [Comfy-Org/ComfyUI_frontend#1044]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Most of the time, my "unsaved workflows" are just a PNG or JSON file I dragged in, to check the workflow.

This way, I can have 10 unsaved workflows or more.
And sometimes I just want to clear all the clutter ( especially using workflow tabs ) but now need to confirm every time I close an workflow.

### Proposed workflow

We could have shortcut  ( e.g. shift+click ) to clear unsaved workflows, bypassing the "unsaved prompt", as suggested here: 

https://github.com/Comfy-Org/ComfyUI_frontend/pull/999#issuecomment-2381078351

**Comment by LukeG89** [comment]
Now you can fast close unsaved workflows with shift+click!
