### ISSUE TITLE
[Feature Request]: Provides a function to update the badge after changing the node id

### ISSUE THREAD

**Issue by lldacing** [Comfy-Org/ComfyUI_frontend#1045]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

My custom nodes, [comfyui-easyapi-nodes](https://github.com/lldacing/comfyui-easyapi-nodes), can reset node id to regularize node serial number. 
But now I have to refresh the page or click the refresh button, otherwise the badge will not change. I have called `app.graph.setDirtyCanvas(true, true);`

### Proposed workflow

![image](https://github.com/user-attachments/assets/c13c96d8-bb6d-41dd-9eb0-430dfcb4d506)
![image](https://github.com/user-attachments/assets/46be914f-ed4d-4b9e-a751-8e1aedb2b167)

**Comment by christian-byrne** [comment]
Does this work?

```typescript
app.graph.nodes.forEach((node) =>
  node.badges.forEach((badge) => {
    badge().text = `#${node.id}`
  })
)
app.graph.setDirtyCanvas(true, true)
```

You will have to select the correct badge in the badge list

**Comment by lldacing** [comment]
> Does this work?
> 
> ```ts
> app.graph.nodes.forEach((node) =>
>   node.badges.forEach((badge) => {
>     badge().text = `#${node.id}`
>   })
> )
> app.graph.setDirtyCanvas(true, true)
> ```
> 
> You will have to select the correct badge in the badge list

it works, but it also remove the custom nodes name.
![image](https://github.com/user-attachments/assets/4912f97d-1bda-48d4-95a7-682cd41f19d4)

**Comment by lldacing** [comment]
Maybe I can replace it with regular matching
