### ISSUE TITLE
[Bug]: Can't close new saved workflow tabs

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI_frontend#1048]
### Frontend Version

1.3.3

### Expected Behavior

I can close the tab after saving new workflows.

### Actual Behavior

I can't close the tab.
And also the tab duplicates when clicking.

### Steps to Reproduce

https://github.com/user-attachments/assets/acdfa536-b718-400a-b585-b8fae3782e2f

### Debug Logs

```powershell
No errors
```

### Browser Logs

No errors

### What browsers do you use to access the UI ?

Google Chrome

**Comment by JorgeR81** [comment]
Yes, this also happens to me.

Sometimes I have a duplicated workflow tab, from a saved workflow, that I'm not able to close.   

This can usually be fixed by refreshing the browser.

It may be related to this issue: https://github.com/Comfy-Org/ComfyUI_frontend/issues/996
