### ISSUE TITLE
[Feature Request]: Don't clutter the graph area for no reason.

### ISSUE THREAD

**Issue by dchatel** [Comfy-Org/ComfyUI_frontend#1054]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

![image](https://github.com/user-attachments/assets/36a5b4f0-7162-4837-83ff-81915a5ac1f5)
Do not do that kind of thing, or at least give an option to put these kind of menu in other places.

I know it looks pretty to put floating menus everywhere in the working area, but it really makes no sense, when...

... these menus can be put in a place where there's an absolute ton of free space:
![image](https://github.com/user-attachments/assets/f596570e-b992-4180-86c8-c1c277093dd0)

**Comment by huchenlei** [comment]
The topbar space is currently reserved for opened workflow tabs which is a controversial feature. See https://github.com/Comfy-Org/ComfyUI_frontend/issues/1001#issuecomment-2378137095

You can disable the canvas menu in settings 
![image](https://github.com/user-attachments/assets/f8853473-d1b5-4266-bdee-795e1aa18565)

We are going to add custom keybinding support and custom action bar support later if you frequently use the reset view button.
