### ISSUE TITLE
[Feature Request]: Improve "drag link to widget" feature: Input turns back to Widget

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI_frontend#1064]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I would like to propose an improvement to the new "dragging link to widget" feature.

Currently, when you connect a link to a widget, the widget turns into input.

![dragged_link](https://github.com/user-attachments/assets/94796933-491f-4c41-bd94-34fe3937aff6)

But when you disconnect the input, the input remains.

![disconnected_input](https://github.com/user-attachments/assets/93151ae6-f7b5-49a5-b7cd-48f8957399c3)

Is it possible to automatically turn the input back to widget?

That would improve the user experience even more and be a better "Blender-like" feature as requested here: https://github.com/Comfy-Org/ComfyUI_frontend/issues/870

### Proposed workflow

- Drag the link on Widget -> Widget turns into Input
- Disconnect the link from Input -> Input turns back to Widget

### Additional information

@pythongosssss You did an awesome job implementing this great feature, really love it! ❤️

**Comment by LukeG89** [comment]
@huchenlei Are there any chances to implement this feature request?
It is about instant widget/input conversion, people would love it!

**Comment by Amorano** [comment]
This feature would be a useful addition, but it should not be the default behavior unless explicitly enabled, either by activating a setting or using a modifier key.

For example, holding Ctrl or Alt while dragging could make the element snap to a compatible widget, provided the widget matches the element’s type. 

This functionality should also work in reverse—holding Alt (or another modifier) over a widget and dragging it into an appropriate slot would turn it into a slot input.
