### ISSUE TITLE
[Feature Request]: View info on UNET models ( like on checkpoints )

### ISSUE THREAD

**Issue by JorgeR81** [Comfy-Org/ComfyUI_frontend#1068]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Many Flux models on Civitai are UNET's.

Is it possible to view info on these models, like on a checkpoint ? 

( not sure if the UNET's have the metadata for that )

### Proposed workflow

We could have a right click on option for that, like on the `Load Checkpoint` node.

![info](https://github.com/user-attachments/assets/4bfb191f-d7ed-4761-a7c4-ea853e8979c5)

**Comment by LukeG89** [comment]
@JorgeR81 The checkpoint info comes from [ComfyUI-Custom-Scripts](https://github.com/pythongosssss/ComfyUI-Custom-Scripts)

**Comment by JorgeR81** [comment]
Ah, yes ! I will ask there.
