### ISSUE TITLE
[Playwright Test] Restore backend state when test finishes

### ISSUE THREAD

**Issue by huchenlei** [Comfy-Org/ComfyUI_frontend#1094]
The playwright test currently has sideeffect of causing backend state change such as removing files under `users/workflows` and modify `user.setting.json` setting config file. The model downloading endpoint test can also add/remove files from `models/` directory.

This can be annoying especially when many of our developers don't have a separate comfyui backend setup for running test.

**Comment by christian-byrne** [comment]
Using mocks? Or save/restore `ComfyUI/users` in global setup/teardown when not in CI env?
