### ISSUE TITLE
KSampler error,

### ISSUE THREAD

**Issue by alva0077** [Comfy-Org/ComfyUI_frontend#1096]
2024-10-04 10:19:50,327 - root - INFO - Prompt executed in 0.68 seconds
2024-10-04 10:25:52,329 - root - INFO - got prompt
2024-10-04 10:25:52,566 - root - ERROR - !!! Exception during processing !!! 0
2024-10-04 10:25:52,567 - root - ERROR - Traceback (most recent call last):
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\nodes.py", line 1434, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\nodes.py", line 1401, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 248, in motion_sample
    return orig_comfy_sample(model, noise, *args, **kwargs)
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\samplers.py", line 829, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\samplers.py", line 729, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\samplers.py", line 716, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\samplers.py", line 695, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\samplers.py", line 600, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\k_diffusion\sampling.py", line 843, in sample_lcm
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\samplers.py", line 682, in __call__
    return self.predict_noise(*args, **kwargs)
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\samplers.py", line 685, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\samplers.py", line 202, in calc_cond_batch
    c['control'] = control.get_control(input_x, timestep_, c, len(cond_or_uncond))
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 468, in get_control_inject
    return self.get_control_advanced(x_noisy, t, cond, batched_number)
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control.py", line 32, in get_control_advanced
    return self.sliding_get_control(x_noisy, t, cond, batched_number)
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control.py", line 37, in sliding_get_control
    control_prev = self.previous_controlnet.get_control(x_noisy, t, cond, batched_number)
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 468, in get_control_inject
    return self.get_control_advanced(x_noisy, t, cond, batched_number)
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control.py", line 32, in get_control_advanced
    return self.sliding_get_control(x_noisy, t, cond, batched_number)
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control.py", line 79, in sliding_get_control
    return self.control_merge(None, control, control_prev, output_dtype)
  File "F:\sd-cui\sd-ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 575, in control_merge_inject
    x = control_output[i]
KeyError: 0

2024-10-04 10:25:52,569 - root - INFO - Prompt executed in 0.17 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":66,"last_link_id":102,"nodes":[{"id":24,"type":"ControlNetLoaderAdvanced","pos":{"0":473.709716796875,"1":67.85017395019531},"size":{"0":350,"1":70},"flags":{"collapsed":false},"order":0,"mode":0,"inputs":[{"name":"timestep_keyframe","type":"TIMESTEP_KEYFRAME","link":null,"label":"帧间隔"}],"outputs":[{"name":"CONTROL_NET","type":"CONTROL_NET","links":[36],"shape":3,"label":"ControlNet"}],"properties":{"Node name for S&R":"ControlNetLoaderAdvanced"},"widgets_values":["control_v11f1e_sd15_tile.pth"]},{"id":27,"type":"TilePreprocessor","pos":{"0":473.709716796875,"1":187.8501739501953},"size":{"0":350,"1":90},"flags":{"collapsed":false},"order":14,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":44,"label":"图像"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[42],"slot_index":0,"shape":3,"label":"图像"}],"properties":{"Node name for S&R":"TilePreprocessor"},"widgets_values":[3,512]},{"id":16,"type":"ControlNetLoaderAdvanced","pos":{"0":473.709716796875,"1":347.85015869140625},"size":{"0":367.79998779296875,"1":58},"flags":{"collapsed":false},"order":1,"mode":0,"inputs":[{"name":"timestep_keyframe","type":"TIMESTEP_KEYFRAME","link":null,"label":"帧间隔"}],"outputs":[{"name":"CONTROL_NET","type":"CONTROL_NET","links":[24],"shape":3,"label":"ControlNet"}],"properties":{"Node name for S&R":"ControlNetLoaderAdvanced"},"widgets_values":["control_v11p_sd15_lineart.pth"]},{"id":18,"type":"LineArtPreprocessor","pos":{"0":473.709716796875,"1":467.85015869140625},"size":{"0":360,"1":90},"flags":{"collapsed":false},"order":15,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":45,"label":"图像"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[26],"slot_index":0,"shape":3,"label":"图像"}],"properties":{"Node name for S&R":"LineArtPreprocessor"},"widgets_values":["disable",512]},{"id":15,"type":"ControlNetApplyAdvanced","pos":{"0":993.709716796875,"1":317.85015869140625},"size":{"0":315,"1":186},"flags":{},"order":23,"mode":0,"inputs":[{"name":"positive","type":"CONDITIONING","link":34,"label":"正面条件"},{"name":"negative","type":"CONDITIONING","link":35,"label":"负面条件"},{"name":"control_net","type":"CONTROL_NET","link":24,"slot_index":2,"label":"ControlNet"},{"name":"image","type":"IMAGE","link":26,"label":"图像"},{"name":"vae","type":"VAE","link":null}],"outputs":[{"name":"positive","type":"CONDITIONING","links":[20],"slot_index":0,"shape":3,"label":"正面条件"},{"name":"negative","type":"CONDITIONING","links":[21],"slot_index":1,"shape":3,"label":"负面条件"}],"properties":{"Node name for S&R":"ControlNetApplyAdvanced"},"widgets_values":[0.63,0,0.78]},{"id":23,"type":"ControlNetApplyAdvanced","pos":{"0":993.709716796875,"1":87.85017395019531},"size":{"0":315,"1":186},"flags":{"collapsed":false},"order":21,"mode":0,"inputs":[{"name":"positive","type":"CONDITIONING","link":32,"label":"正面条件"},{"name":"negative","type":"CONDITIONING","link":33,"label":"负面条件"},{"name":"control_net","type":"CONTROL_NET","link":36,"slot_index":2,"label":"ControlNet"},{"name":"image","type":"IMAGE","link":42,"label":"图像"},{"name":"vae","type":"VAE","link":null}],"outputs":[{"name":"positive","type":"CONDITIONING","links":[34],"slot_index":0,"shape":3,"label":"正面条件"},{"name":"negative","type":"CONDITIONING","links":[35],"slot_index":1,"shape":3,"label":"负面条件"}],"properties":{"Node name for S&R":"ControlNetApplyAdvanced"},"widgets_values":[0.61,0,0.634]},{"id":59,"type":"Note","pos":{"0":262.7309265136719,"1":-579.9999389648438},"size":{"0":300,"1":90},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[],"properties":{"text":""},"widgets_values":["帧数读取上限frame_load_cap：\n0就是全部帧都导入，测试效果可以先改小的数字\n\n模选select_every_nth=1，这个值意思是不跳帧\n\n"],"color":"#223","bgcolor":"#335"},{"id":65,"type":"Note","pos":{"0":612.7308959960938,"1":-579.9999389648438},"size":{"0":300,"1":90},"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[],"properties":{"text":""},"widgets_values":["宽度高度确保和上传的视频保持一致"],"color":"#223","bgcolor":"#335"},{"id":57,"type":"Reroute","pos":{"0":672.7308959960938,"1":-459.99993896484375},"size":[75,26],"flags":{},"order":9,"mode":0,"inputs":[{"name":"","type":"*","link":88}],"outputs":[{"name":"","type":"IMAGE","links":[89],"slot_index":0}],"properties":{"showOutputText":false,"horizontal":false}},{"id":28,"type":"ImpactImageBatchToImageList","pos":{"0":642.7308959960938,"1":-259.99993896484375},"size":{"0":210,"1":26},"flags":{"collapsed":true},"order":8,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":43,"label":"图像"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[44,45],"slot_index":0,"shape":6,"label":"图像"}],"properties":{"Node name for S&R":"ImpactImageBatchToImageList"},"widgets_values":[]},{"id":31,"type":"RebatchLatents","pos":{"0":862.7308959960938,"1":-259.99993896484375},"size":{"0":315,"1":58},"flags":{"collapsed":true},"order":17,"mode":0,"inputs":[{"name":"latents","type":"LATENT","link":53,"label":"Latent"}],"outputs":[{"name":"LATENT","type":"LATENT","links":[54],"slot_index":0,"shape":6,"label":"Latent"}],"properties":{"Node name for S&R":"RebatchLatents"},"widgets_values":[1]},{"id":40,"type":"ImageListToImageBatch","pos":{"0":1516.7686767578125,"1":-230.88148498535156},"size":{"0":210,"1":26},"flags":{"collapsed":false},"order":27,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":87,"label":"图像"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[64,94],"slot_index":0,"shape":3,"label":"图像"}],"properties":{"Node name for S&R":"ImageListToImageBatch"},"widgets_values":[]},{"id":32,"type":"VHS_VideoCombine","pos":{"0":1999.6917724609375,"1":-2.148493766784668},"size":[510,310],"flags":{},"order":30,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":56,"label":"图像"},{"name":"audio","type":"VHS_AUDIO","link":null,"label":"音频"},{"name":"meta_batch","type":"VHS_BatchManager","link":null,"label":"批次管理"},{"name":"vae","type":"VAE","link":null}],"outputs":[{"name":"Filenames","type":"VHS_FILENAMES","links":null,"shape":3,"label":"文件名"}],"properties":{"Node name for S&R":"VHS_VideoCombine"},"widgets_values":{"frame_rate":24,"loop_count":0,"filename_prefix":"smoothvideo","format":"video/h264-mp4","pix_fmt":"yuv420p","crf":20,"save_metadata":true,"pingpong":false,"save_output":false,"videopreview":{"hidden":false,"paused":false,"params":{"filename":"smoothvideo_00002.mp4","subfolder":"","type":"temp","format":"video/h264-mp4"}}}},{"id":25,"type":"SmoothVideo","pos":{"0":1990,"1":-370},"size":{"0":315,"1":270},"flags":{},"order":29,"mode":0,"inputs":[{"name":"orginalframe","type":"IMAGE","link":90,"label":"orginalframe"},{"name":"keyframe","type":"IMAGE","link":94,"label":"keyframe"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[56],"slot_index":0,"shape":3,"label":"IMAGE"}],"properties":{"Node name for S&R":"SmoothVideo"},"widgets_values":[1,3,16,0,5,5,10]},{"id":60,"type":"Note","pos":{"0":2320,"1":-380},"size":{"0":210,"1":110},"flags":{},"order":4,"mode":0,"inputs":[],"outputs":[],"properties":{"text":""},"widgets_values":["accuracy:总共三档，越高越慢\n"],"color":"#432","bgcolor":"#653"},{"id":64,"type":"Note","pos":{"0":-390,"1":-50},"size":{"0":310,"1":60},"flags":{},"order":5,"mode":0,"inputs":[],"outputs":[],"properties":{"text":""},"widgets_values":["可以自定义额外添加lora"],"color":"#223","bgcolor":"#335"},{"id":62,"type":"LoraLoader","pos":{"0":-390,"1":70},"size":{"0":315,"1":126},"flags":{},"order":12,"mode":4,"inputs":[{"name":"model","type":"MODEL","link":97,"label":"模型"},{"name":"clip","type":"CLIP","link":98,"label":"CLIP"}],"outputs":[{"name":"MODEL","type":"MODEL","links":[99],"slot_index":0,"shape":3,"label":"模型"},{"name":"CLIP","type":"CLIP","links":[100],"slot_index":1,"shape":3,"label":"CLIP"}],"properties":{"Node name for S&R":"LoraLoader"},"widgets_values":["功能\\SDMAI繁花肖像写真fanhua_V1.0.safetensors",0.7000000000000001,0.7000000000000001]},{"id":12,"type":"CLIPSetLastLayer","pos":{"0":-730,"1":260},"size":{"0":315,"1":58},"flags":{},"order":11,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":14,"label":"CLIP"}],"outputs":[{"name":"CLIP","type":"CLIP","links":[15,16],"slot_index":0,"shape":3,"label":"CLIP"}],"properties":{"Node name for S&R":"CLIPSetLastLayer"},"widgets_values":[-2]},{"id":7,"type":"CLIPTextEncode","pos":{"0":-320,"1":460},"size":{"0":420,"1":120},"flags":{},"order":19,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":16,"label":"CLIP"}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[33],"slot_index":0,"label":"条件"}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["nsfw, (worst quality, low quality, extra digits:1.4),text,embedding:badhandv4,embedding:negative_hand-neg"]},{"id":13,"type":"ModelSamplingDiscrete","pos":{"0":-20,"1":-60},"size":{"0":315,"1":82},"flags":{},"order":22,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":17,"label":"模型"}],"outputs":[{"name":"MODEL","type":"MODEL","links":[91],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"ModelSamplingDiscrete"},"widgets_values":["lcm",false]},{"id":63,"type":"Reroute","pos":{"0":550,"1":-70},"size":[75,26],"flags":{},"order":13,"mode":0,"inputs":[{"name":"","type":"*","link":101}],"outputs":[{"name":"","type":"VAE","links":[102],"slot_index":0}],"properties":{"showOutputText":false,"horizontal":false}},{"id":47,"type":"Reroute","pos":{"0":850,"1":-80},"size":[75,26],"flags":{},"order":24,"mode":0,"inputs":[{"name":"","type":"*","link":91}],"outputs":[{"name":"","type":"MODEL","links":[79],"slot_index":0}],"properties":{"showOutputText":false,"horizontal":false}},{"id":8,"type":"VAEDecode","pos":{"0":1520,"1":-350},"size":{"0":210,"1":46},"flags":{},"order":26,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":7,"label":"Latent"},{"name":"vae","type":"VAE","link":102,"slot_index":1,"label":"VAE"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[87],"slot_index":0,"label":"图像"}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":58,"type":"Reroute","pos":{"0":1600,"1":-460},"size":[75,26],"flags":{},"order":16,"mode":0,"inputs":[{"name":"","type":"*","link":89}],"outputs":[{"name":"","type":"IMAGE","links":[90],"slot_index":0}],"properties":{"showOutputText":false,"horizontal":false}},{"id":44,"type":"VHS_VideoCombine","pos":{"0":1500,"1":10},"size":[440,310],"flags":{},"order":28,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":64,"label":"图像"},{"name":"audio","type":"VHS_AUDIO","link":null,"label":"音频"},{"name":"meta_batch","type":"VHS_BatchManager","link":null,"label":"批次管理"},{"name":"vae","type":"VAE","link":null}],"outputs":[{"name":"Filenames","type":"VHS_FILENAMES","links":null,"shape":3,"label":"文件名"}],"properties":{"Node name for S&R":"VHS_VideoCombine"},"widgets_values":{"frame_rate":24,"loop_count":0,"filename_prefix":"KSampler","format":"video/h264-mp4","pix_fmt":"yuv420p","crf":20,"save_metadata":true,"pingpong":false,"save_output":false,"videopreview":{"hidden":false,"paused":false,"params":{"filename":"KSampler_00013.mp4","subfolder":"","type":"output","format":"video/h264-mp4"}}}},{"id":17,"type":"VHS_LoadVideoPath","pos":{"0":253,"1":-430},"size":[320,238],"flags":{},"order":6,"mode":0,"inputs":[{"name":"meta_batch","type":"VHS_BatchManager","link":null,"label":"批次管理"},{"name":"vae","type":"VAE","link":null}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[43,88],"slot_index":0,"shape":3,"label":"图像"},{"name":"frame_count","type":"INT","links":[27],"slot_index":1,"shape":3,"label":"帧计数"},{"name":"audio","type":"VHS_AUDIO","links":null,"shape":3,"label":"音频"},{"name":"video_info","type":"VHS_VIDEOINFO","links":null,"shape":3,"label":"视频信息"}],"properties":{"Node name for S&R":"VHS_LoadVideoPath"},"widgets_values":{"video":"input/10月3日(2).mp4","force_rate":0,"force_size":"Disabled","custom_width":512,"custom_height":512,"frame_load_cap":0,"skip_first_frames":0,"select_every_nth":1,"videopreview":{"hidden":false,"paused":false,"params":{"frame_load_cap":0,"skip_first_frames":0,"force_rate":0,"filename":"input/10月3日(2).mp4","type":"path","format":"video/mp4","select_every_nth":1}}}},{"id":4,"type":"CheckpointLoaderSimple","pos":{"0":-740,"1":90},"size":{"0":315,"1":98},"flags":{},"order":7,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[97],"slot_index":0,"label":"模型"},{"name":"CLIP","type":"CLIP","links":[14,98],"slot_index":1,"label":"CLIP"},{"name":"VAE","type":"VAE","links":[101],"slot_index":2,"label":"VAE"}],"properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["majicMIX realistic 麦橘写实_v7.safetensors"]},{"id":10,"type":"LoraLoader","pos":{"0":-30,"1":70},"size":{"0":315,"1":126},"flags":{},"order":20,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":99,"label":"模型"},{"name":"clip","type":"CLIP","link":100,"label":"CLIP"}],"outputs":[{"name":"MODEL","type":"MODEL","links":[17],"slot_index":0,"shape":3,"label":"模型"},{"name":"CLIP","type":"CLIP","links":null,"shape":3,"label":"CLIP"}],"properties":{"Node name for S&R":"LoraLoader"},"widgets_values":["lcm\\SD1.5\\lcm-lora-sdv1-5.safetensors",1,1]},{"id":3,"type":"KSampler","pos":{"0":1110,"1":-570},"size":{"0":330,"1":500},"flags":{},"order":25,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":79,"label":"模型"},{"name":"positive","type":"CONDITIONING","link":20,"label":"正面条件"},{"name":"negative","type":"CONDITIONING","link":21,"label":"负面条件"},{"name":"latent_image","type":"LATENT","link":54,"label":"Latent"}],"outputs":[{"name":"LATENT","type":"LATENT","links":[7],"slot_index":0,"label":"Latent"}],"properties":{"Node name for S&R":"KSampler"},"widgets_values":[606405836679857,"fixed",6,1.54,"lcm","sgm_uniform",1]},{"id":5,"type":"EmptyLatentImage","pos":{"0":612.7308959960938,"1":-429.99993896484375},"size":{"0":315,"1":106},"flags":{},"order":10,"mode":0,"inputs":[{"name":"batch_size","type":"INT","link":27,"widget":{"name":"batch_size"},"label":"批次大小"}],"outputs":[{"name":"LATENT","type":"LATENT","links":[53],"slot_index":0,"label":"Latent"}],"properties":{"Node name for S&R":"EmptyLatentImage"},"widgets_values":[1920,1080,1]},{"id":6,"type":"CLIPTextEncode","pos":{"0":-320,"1":250},"size":{"0":420,"1":160},"flags":{},"order":18,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":15,"label":"CLIP"}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[32],"slot_index":0,"label":"条件"}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["hand"]}],"links":[[7,3,0,8,0,"LATENT"],[14,4,1,12,0,"CLIP"],[15,12,0,6,0,"CLIP"],[16,12,0,7,0,"CLIP"],[17,10,0,13,0,"MODEL"],[20,15,0,3,1,"CONDITIONING"],[21,15,1,3,2,"CONDITIONING"],[24,16,0,15,2,"CONTROL_NET"],[26,18,0,15,3,"IMAGE"],[27,17,1,5,0,"INT"],[32,6,0,23,0,"CONDITIONING"],[33,7,0,23,1,"CONDITIONING"],[34,23,0,15,0,"CONDITIONING"],[35,23,1,15,1,"CONDITIONING"],[36,24,0,23,2,"CONTROL_NET"],[42,27,0,23,3,"IMAGE"],[43,17,0,28,0,"IMAGE"],[44,28,0,27,0,"IMAGE"],[45,28,0,18,0,"IMAGE"],[53,5,0,31,0,"LATENT"],[54,31,0,3,3,"LATENT"],[56,25,0,32,0,"IMAGE"],[64,40,0,44,0,"IMAGE"],[79,47,0,3,0,"MODEL"],[87,8,0,40,0,"IMAGE"],[88,17,0,57,0,"*"],[89,57,0,58,0,"*"],[90,58,0,25,0,"IMAGE"],[91,13,0,47,0,"*"],[94,40,0,25,1,"IMAGE"],[97,4,0,62,0,"MODEL"],[98,4,1,62,1,"CLIP"],[99,62,0,10,0,"MODEL"],[100,62,1,10,1,"CLIP"],[101,4,2,63,0,"*"],[102,63,0,8,1,"VAE"]],"groups":[{"title":"K采样器模块","bounding":[1078,-663,719,610],"color":"#3f789e","font_size":24,"flags":{}},{"title":"CG迷-Diffutoon视频转绘稳定工作流","bounding":[-785,-143,1133,760],"color":"#88A","font_size":24,"flags":{}},{"title":"视频输入设置","bounding":[165,-665,868,496],"color":"#3f789e","font_size":24,"flags":{}},{"title":"Group","bounding":[1970,-470,609,1537],"color":"#3f789e","font_size":24,"flags":{}},{"title":"Controlnet模块","bounding":[390,-14,1049,628],"color":"#8A8","font_size":24,"flags":{}}],"config":{},"extra":{"ds":{"scale":1.3310000000000004,"offset":[68.72701940797384,254.34642095770297]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by huchenlei** [comment]
This is a backend error. Please file it in https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved
