### ISSUE TITLE
[Feature Request]: Adding new keybindings: All Sidebar Tabs | Switch Workflow Tabs

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI_frontend#1097]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Really love the new custom keybinding feature! I've already set mine!

But I would like to set other new keybinds that would also improve user experience:

### 1) All Sidebar Tabs:
Currently, the only sidebar tab available is `Queue`.

![queue_shortcut](https://github.com/user-attachments/assets/3ec71e8a-0b0c-4d4f-87e0-9424a896eaee)

It would be great to have all the others:

- `Workflows`
- `Node Library`
- `Model Library`
--------
### 2) Switch Workflow Tabs

Would be awesome to add a shortcut for switching workflow tabs, like you do in browser:

![switch_workflow_tabs](https://github.com/user-attachments/assets/8a09b810-5334-4107-a635-2184874b5aad)

That would also help people transitioning from the old way of opening new browser tabs.

### Proposed workflow

.

**Comment by JorgeR81** [comment]
> Would be awesome to add a shortcut for switching workflow tabs, like you do in browser:

Yes, this would be very useful.
Sometimes I have multiple PNG's open, with random names, and I just want to check the all the workflows again, one by one.

> Currently, the only sidebar tab available is Queue.
> It would be great to have all the others:
> 
> Workflows
> Node Library
> Model Library

I think the other tabs don't have keybinds because it's assumed that if you want to open them, you'll want to interact with them, via mouse, anyways.

**Comment by LukeG89** [comment]
> I think the other tabs don't have keybinds because it's assumed that if you want to open them, you'll want to interact with them, via mouse, anyways.

In my opinion having shortcuts to open/close them like Queue tab would improve switching between tabs and access to workflows.
