### ISSUE TITLE
SearchBox auto-dismissed on touch devices 

### ISSUE THREAD

**Issue by christian-byrne** [Comfy-Org/ComfyUI_frontend#111]
https://github.com/Comfy-Org/ComfyUI_frontend/blob/86ee0767c3baac19388ca8716f208bebb72e5c29/src/components/NodeSearchBoxPopover.vue#L3-L8

I think `dismissable-mask` is capturing the second click on the initial double click. The second click can also immediately select a search result item. Why does it only happen with touch?

**Comment by huchenlei** [comment]
Issue confirmed on touchscreen device

**Comment by huchenlei** [comment]
> The second click can also immediately select a search result item

This also happens for legacy litegraph searchbox.
