### ISSUE TITLE
Setting panel to manage frontend extensions

### ISSUE THREAD

**Issue by huchenlei** [Comfy-Org/ComfyUI_frontend#1122]
Add a new setting panel to show all frontend extensions and give user option to disable them. This can be helpful for debugging / disable unwanted features.

**Comment by JorgeR81** [comment]
The Manager already allows disabling specific extensions, without uninstalling ( expect for the Manager itself ).

![manager](https://github.com/user-attachments/assets/d7c49c03-e73e-41d1-82f3-1bf71947efe6)

----

Could this new core panel have more advanced features ?


For instance, I would like to select the options that are added by extensions, to my right click menus.
I don't need some of these options, but I want to keep the extensions.
 
![rc](https://github.com/user-attachments/assets/e7970df9-7b32-4ec2-9677-d558c8dc4295)

**Comment by huchenlei** [comment]
> The Manager already allows disabling specific extensions, without uninstalling ( expect for the Manager itself ).
> 
> ![manager](https://private-user-images.githubusercontent.com/72734038/373940616-d7c49c03-e73e-41d1-82f3-1bf71947efe6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMjU2MTMsIm5iZiI6MTcyODIyNTMxMywicGF0aCI6Ii83MjczNDAzOC8zNzM5NDA2MTYtZDdjNDljMDMtZTczZS00MWQxLTgyZjMtMWJmNzE5NDdlZmU2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDE0MzUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzYWY0MzgyZGU1ODJmMzBiYzRhNTBmNjlmYmRlNzU1YThkMDk2MGUwOThhYmQ3NjIwNGY0MGY1YTA4Yjk4OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RpUCYmh_44pLRUNXuUJba1meMY5-n6StFty7PGBzfkE)
> 
> Could this new core panel have more advanced features ?
> 
> For instance, I would like to select the options that are added by extensions, to my right click menus. I don't need some of these options, but I want to keep the extensions.   ![rc](https://private-user-images.githubusercontent.com/72734038/373940622-e7970df9-7b32-4ec2-9677-d558c8dc4295.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMjU2MTMsIm5iZiI6MTcyODIyNTMxMywicGF0aCI6Ii83MjczNDAzOC8zNzM5NDA2MjItZTc5NzBkZjktN2IzMi00ZWMyLTk2NzctZDU1OGM4ZGM0Mjk1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDE0MzUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNzZmODcwZjM2NjJmZDE0YTE5OWZmNTAxOGJiYTUyMGU1ODNhYjE1MzM2ZTBkOTU0YzM3NDFmNGYwZmE2OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.10OoHI0avsNab9Z6_C3USBr5gVTegO96tsDmoPMA2Ls)

This is for frontend extensions, not backend custom packs. For example ComfyUI_custom_scripts registers many frontend extensions, and this feature should allow you selectively disable subset of them.
