### ISSUE TITLE
[Feature Request]: Is there a way to disable built-in workflow manager

### ISSUE THREAD

**Issue by Cedri4** [Comfy-Org/ComfyUI_frontend#1131]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

A way to disable the built-in workflow manager. The button on the side.

### Proposed workflow

In the settings an option to disable it.

### Additional information

Just got reset 3 hours back in time after saving the workflow and then relaunching it. I don't want to mess with it anymore.
Took me 1 day to already fall back to workspace manager.

**Comment by Cedri4** [comment]
The reset probably happened because I had 2 comfyui window open, with workflow A and workflow B. Workflow B probably loaded on workflow A and probably removed any trace of workflow A.

**Comment by LukeG89** [comment]
The same issue has been reported here: https://github.com/comfyanonymous/ComfyUI/issues/5095

@Cedri4 Why not asking to fix the problem instead?

**Comment by Cedri4** [comment]
Well @LukeG89 right now I need 2 comfyui window open. Ltdrdata said that it is risky. With workspace manager there's no problem. But with it comes a bunch of "Unsaved workflows".
![image](https://github.com/user-attachments/assets/7b26972e-7870-4d01-a3f8-40c33012ea56)
While I only use 1 workflow.
That I suppoed are each being loaded

**Comment by huchenlei** [comment]
Please file a bug on workflow management bug instead. Thanks! There are definitely some bugs on it.

**Comment by LukeG89** [comment]
@Cedri4 I loved workspace manager, I installed it when it came out. But then they released the built-in one and workspace has been put into maintainance mode, so I decided to definitely switch to the new one. So I know what you mean.

But in the next frontend version (1.3.x) there will be many changes. They moved the workflow manager to the sidebar and you can open workflows in tabs (and also you can set shortcuts to switch workflows and more):

![workflows_manager](https://github.com/user-attachments/assets/1c14ac43-1b75-4bfa-ac6b-55fc569f0cb0)

It's still in beta, but soon (?) it will be officially implemented in ComfyUI. If you want to try it out you can use the `--front-end-version Comfy-Org/ComfyUI_frontend@latest` argument.

But I guess this issue remains anyway (?) I don't know, I've never experienced it. As I said, it would've been better to ask for a fix.
You can stiil use workspace over the built-in one, there's no need to disable it.

**Comment by Cedri4** [comment]
Huh didn't know that was possible. Having workflows like that. 
It's a case of, If You Know, You Know, when it comes to the latest features.
For the record, I'm using the latest frontend.
Also I somehow created a folder when I saved a workflow by chance, but I don't know how to create a folder for workflows.

**Comment by LukeG89** [comment]
> Huh didn't know that was possible. Having workflows like that.

Yeah, you can enable workflow tabs in the settings (if it's not enabled by default):

![tab_option](https://github.com/user-attachments/assets/1a327def-41a5-4479-825e-fa04bc2066ee)


> Also I somehow created a folder when I saved a workflow by chance, but I don't know how to create a folder for workflows.

You can manually create new folders inside `ComfyUI\user\default\workflows` directory.
Maybe one day there could be an option to directly create them in ComfyUI.

**Comment by Cedri4** [comment]
@LukeG89 Using this folder 'ComfyUI\user\default\workflows' directory can I bulk import of workflows? 
Since I have a bunch on the workspace manager folder. And importing one by one will be a long task.

**Comment by LukeG89** [comment]
That folder is where the built-in workflow manager save and load workflows. You can move all your folders in there like I did.
