### ISSUE TITLE
[Bug]: Must be restart ComfyUI after adding model in the path specified in the extra_model_path.yaml

### ISSUE THREAD

**Issue by lldacing** [Comfy-Org/ComfyUI_frontend#1132]
### Frontend Version

<= 1.3.9

### Expected Behavior

After adding model in the path specified in the extra_model_path.yaml and clicking refresh button or reload page,  the new model can be selected.

### Actual Behavior

The new model is not shown

### Steps to Reproduce

1. Configure additional storage (The base path of ComfyUI is `F:\sdwork\ComfyUI\ComfyUI`)
![image](https://github.com/user-attachments/assets/4128eabf-c783-4f49-b9c7-182d2431bf55)
2. Start ComfyUI
3. Add model `test_1.safetensors` to `G:/AI/ComfyUI/models/checkpoints/`
![image](https://github.com/user-attachments/assets/f3f1c744-17fe-498d-adc3-7893f984405a)

5. Click refresh or reload page
6. Check model (not found)
![image](https://github.com/user-attachments/assets/f70bda57-6f36-4454-a01b-3704046ab70e)

### Debug Logs

```powershell
nothing
```

### Browser Logs

nothing

### What browsers do you use to access the UI ?

Microsoft Edge

**Comment by huchenlei** [comment]
I think that is because the search logic is not implemented yet

https://github.com/Comfy-Org/ComfyUI_frontend/blob/b97331cbab432a5716c04a5ff5112a2cc5675ec5/src/components/sidebar/tabs/ModelLibrarySidebarTab.vue#L190-L192

**Comment by huchenlei** [comment]
@mcmonkey4eva

**Comment by lldacing** [comment]
> I think that is because the search logic is not implemented yet
> 
> https://github.com/Comfy-Org/ComfyUI_frontend/blob/b97331cbab432a5716c04a5ff5112a2cc5675ec5/src/components/sidebar/tabs/ModelLibrarySidebarTab.vue#L190-L192

I don't think so. Because it is not displayed in the LoadCheckpoint node either.

**Comment by huchenlei** [comment]
> > I think that is because the search logic is not implemented yet
> > https://github.com/Comfy-Org/ComfyUI_frontend/blob/b97331cbab432a5716c04a5ff5112a2cc5675ec5/src/components/sidebar/tabs/ModelLibrarySidebarTab.vue#L190-L192
> 
> I don't think so. Because it is not displayed in the LoadCheckpoint node either.

If this only happens for additional checkpoints path configured in yaml, please file an issue in the ComfyUI main repo. It's likely caused by backend code not capturing the change in the additional model path.

**Comment by lldacing** [comment]
> > I think that is because the search logic is not implemented yet
> > https://github.com/Comfy-Org/ComfyUI_frontend/blob/b97331cbab432a5716c04a5ff5112a2cc5675ec5/src/components/sidebar/tabs/ModelLibrarySidebarTab.vue#L190-L192
> 
> I don't think so. Because it is not displayed in the LoadCheckpoint node either.

I think this is a persistent bug and I'm not sure if I should create it here or in ComfyUI

**Comment by mcmonkey4eva** [comment]
if it affects the LoadCheckpoint node's list, then it's a ComfyUI bug not frontend
