### ISSUE TITLE
[Bug]: Issues when you rename workflows

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI_frontend#1146]
### Frontend Version

1.3.10

### Expected Behavior

When you rename a workflow inside subfolders, the workflow stays in the same place and when you open it there are no conflicts.

### Actual Behavior

After renaming it, the workflow is moved to the main folder (expected behavior?), the empty folders disappear (expected behavior?) and there are conflicts when you open it, switch tab and switch back to it.

### Steps to Reproduce

https://github.com/user-attachments/assets/2ea62961-af07-4e5f-876b-d8a1b6013bb9

### Debug Logs

```powershell
E:\>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --disable-all-custom-nodes --disable-xformers --preview-size 1024 --front-end-version Comfy-Org/ComfyUI_frontend@latest
Total VRAM 8192 MB, total RAM 65277 MB
pytorch version: 2.4.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: E:\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.3.10
E:\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Skipping loading of custom nodes
Starting server

To see the GUI go to: http://127.0.0.1:8188
moving 'E:\ComfyUI\user\default\workflows\Rename Test\subtest\rename_test.json' -> 'E:\ComfyUI\user\default\workflows\rename_test01.json'
```

### Browser Logs

15runtime-core.esm-bundler.js:270 TypeError: Cannot read properties of undefined (reading 'load')
    at onWorkflowChange (WorkflowTabs.vue:82:12)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
    at emit (runtime-core.esm-bundler.js:726:5)
    at Proxy.onOptionSelect (index.mjs:95:12)
    at onChange (index.mjs:157:25)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
    at emit (runtime-core.esm-bundler.js:726:5)
    at Proxy.onChange (index.mjs:78:14)
logError @ runtime-core.esm-bundler.js:270
handleError @ runtime-core.esm-bundler.js:252
callWithErrorHandling @ runtime-core.esm-bundler.js:197
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:202
emit @ runtime-core.esm-bundler.js:726
onOptionSelect @ index.mjs:95
onChange @ index.mjs:157
callWithErrorHandling @ runtime-core.esm-bundler.js:195
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:202
emit @ runtime-core.esm-bundler.js:726
onChange @ index.mjs:78
mergeProps.onClick._cache.<computed>._cache.<computed> @ index.mjs:108
callWithErrorHandling @ runtime-core.esm-bundler.js:195
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:202
invoker @ runtime-dom.esm-bundler.js:693
Mostra 15 altri frame
Mostra meno
13workflows.ts:129 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'isOpen')
    at ComfyWorkflowManager.closeWorkflow (workflows.ts:129:19)
    at onCloseWorkflow (WorkflowTabs.vue:87:23)
    at WorkflowTabs.vue:85:25
    at cache2.<computed>.cache2.<computed> (runtime-dom.esm-bundler.js:1472:12)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
    at HTMLButtonElement.invoker (runtime-dom.esm-bundler.js:693:5)
closeWorkflow @ workflows.ts:129
onCloseWorkflow @ WorkflowTabs.vue:87
(anonime) @ WorkflowTabs.vue:85
cache2.<computed>.cache2.<computed> @ runtime-dom.esm-bundler.js:1472
callWithErrorHandling @ runtime-core.esm-bundler.js:195
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:202
invoker @ runtime-dom.esm-bundler.js:693
Mostra 4 altri frame
Mostra meno

### What browsers do you use to access the UI ?

Google Chrome

## Request: Better workflow management
Why is it a normal behavior to move a workflow out of its subfolder and make empty subfolders disappear?

Instead, you should try to improve workflow organization, for example by creating/deleting folders and moving workflows inside and out.

**Comment by huchenlei** [comment]
Bug confirmed reproducable.

**Comment by LukeG89** [comment]
These issues are fixed! No conflicts and workflows stay in their subfolder!
