### ISSUE TITLE
[Feature Request]: Show video outputs in Queue Sidebar

### ISSUE THREAD

**Issue by robinjhuang** [Comfy-Org/ComfyUI_frontend#1153]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

When a workflow produces a video output, show the video in the Queue sidebar. Perhaps just show a thumbnail and play it on click.

### Proposed workflow

1. Run a workflow that produces a video
2. Video output is shown in the queue side bar as a thumbnail
3. Click the thumbnail and the video plays

**Comment by mijuku233** [comment]
Can support be implemented for "videos saved by custom nodes"?[ComfyUI-VideoHelperSuite](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite)
