### ISSUE TITLE
[Feature Request]: The search should not be case-sensitive.

### ISSUE THREAD

**Issue by devrosx** [Comfy-Org/ComfyUI_frontend#1155]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

When i search for example in workflow in current state its case sensitive, sometimes hard to find names....

### Proposed workflow

just search should not be case-sensitive, of by default case-sensitive should be disabled

### Additional information

Thanks for good work

**Comment by huchenlei** [comment]
It's already fixed in 1.3.0+

https://github.com/Comfy-Org/ComfyUI_frontend/blob/2b265141902fa7f0e7804a9e725be78448553152/src/components/sidebar/tabs/WorkflowsSidebarTab.vue#L134-L147
