### ISSUE TITLE
[Bug]: Inconsistent saved/unsaved status

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI_frontend#1165]
### Frontend Version

1.3.11

### Expected Behavior

Saved and unsaved status should reflect the current state of the workflows.

### Actual Behavior

Saved and unsaved status has become even more inconsistent.

### Steps to Reproduce

- If you create a new workflow and save it, even if you modify it, it still keeps the saved status.
  - The status properly works only after closing and reopening it. 
- If you open as existing workflow inside a subfolder and click "save", the status remains as unsaved even though it's saved.
  - During this second test I also catch a bug that make a new tab opens before the already opened one. 

https://github.com/user-attachments/assets/6d13f2a5-3104-429e-b48d-0795fa1eae36

### Debug Logs

```powershell
E:\>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --disable-all-custom-nodes --disable-xformers --preview-size 1024 --front-end-version Comfy-Org/ComfyUI_frontend@latest
Total VRAM 8192 MB, total RAM 65277 MB
pytorch version: 2.4.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: E:\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.3.11
E:\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Skipping loading of custom nodes
Starting server

To see the GUI go to: http://127.0.0.1:8188
```

### Browser Logs

This error occurs when I save the workflow inside subfolder that keeps the unsaved status:
```
workflows.ts:427 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'load')
    at Proxy._save (workflows.ts:427:22)
    at async Proxy.save (workflows.ts:263:15)
```
I also got this error when clicking on the dropdown menu, I don't know if it's related to the issue or not:

```
Blocked aria-hidden on a <a> element because the element that 
just received focus must not be hidden from assistive technology users. 
Avoid using aria-hidden on a focused element or its ancestor. 
Consider using the inert attribute instead, which will also prevent focus. 
For more details, see the aria-hidden section of the WAI-ARIA specification 
at https://w3c.github.io/aria/#aria-hidden. 
<a data-v-2ec1b620 class=​"p-menubar-item-link" tabindex=​"-1" aria-hidden=​"true" data-pc-section=​"itemlink">​…​</a>​flex
```

### What browsers do you use to access the UI ?

Google Chrome

**Comment by LukeG89** [comment]
**Update:** I guess the issue has been introduced in this commit: https://github.com/Comfy-Org/ComfyUI_frontend/commit/a95a6f9b4721ecde4aa6280f9449be08b5708b53

**Comment by LincZero** [comment]
Had a disastrous effect:

If there is a workflow contained in the folder, click the Save button at this time and it is actually saved but the front end shows that it is not saved. This is also the bug mentioned earlier.

I tried to ignore the bug and continue working, but then I restarted the ComfyUI service. At this time, the interface will become a workflow with the same file name, but the content is not the same, at this time I mistakenly click on the save... So my workflow file was overwritten and lost 😭

**Comment by LukeG89** [comment]
> Had a disastrous effect:
> 
> If there is a workflow contained in the folder, click the Save button at this time and it is actually saved but the front end shows that it is not saved. This is also the bug mentioned earlier.
> 
> I tried to ignore the bug and continue working, but then I restarted the ComfyUI service. At this time, the interface will become a workflow with the same file name, but the content is not the same, at this time I mistakenly click on the save... So my workflow file was overwritten and lost 😭

I'm so sorry for that... 😞
This problem happened to other users as well: 
- https://github.com/comfyanonymous/ComfyUI/issues/5095

I see that @huchenlei is working on rewriting Workflows manager, maybe this should solve many of the problems we are experiencing (and also add some workflow management features https://github.com/Comfy-Org/ComfyUI_frontend/issues/1249)

**Comment by LukeG89** [comment]
Now in frontend 1.3.34 everything seems fixed! 🎉
