### ISSUE TITLE
[Bug]: Black canvas on version 1.3.12

### ISSUE THREAD

**Issue by JorgeR81** [Comfy-Org/ComfyUI_frontend#1176]
### Frontend Version

1.3.12

### Expected Behavior

Nodes are visible.

### Actual Behavior

The canvas is black. 
No nodes are visible.

![canvas](https://github.com/user-attachments/assets/f5b3857b-d5b1-4c7c-9a68-800ff019bc6b)

### Steps to Reproduce

Use version 13.12

### Debug Logs

```powershell
.
```

### Browser Logs

![log](https://github.com/user-attachments/assets/60665d98-13a8-4f5e-b78d-e16737510ef5)

### What browsers do you use to access the UI ?

Google Chrome

### Other

Windows 10

**Comment by camoody1** [comment]
I am also getting a black canvas with version 1.3.12. When I try to load a different workflow, this is the error that pops up:

![image](https://github.com/user-attachments/assets/c2cb6f0b-581a-463b-8b91-45c14a915658)

**Comment by JorgeR81** [comment]
> When I try to load a different workflow, this is the error that pops up:

Yes, I'm also getting this error with some workflows.

**Comment by JorgeR81** [comment]
I also noticed that if I load the default workflow on v1.3.11, then close Comfy UI and open v.1.3.12, only links are visible and the canvas is frozen.

![links](https://github.com/user-attachments/assets/bafd620e-e5a6-4265-a539-fe6379e763b4)

**Comment by camoody1** [comment]
> I also noticed that if I load the default workflow on v1.3.11, then close Comfy UI and open v.1.3.12, only links are visible and the canvas is frozen.
> 
> ![links](https://private-user-images.githubusercontent.com/72734038/374740791-bafd620e-e5a6-4265-a539-fe6379e763b4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MjYyOTcsIm5iZiI6MTcyODQyNTk5NywicGF0aCI6Ii83MjczNDAzOC8zNzQ3NDA3OTEtYmFmZDYyMGUtZTVhNi00MjY1LWE1MzktZmU2Mzc5ZTc2M2I0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDIyMTk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZGYyYWZiNTM1MmRmZjViM2ViNGYxNDA4NDE0MDRhNjExZjg5NDI4NjE0ZmZjMTljODk5NWE1MDM2Zjc2MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uQknSuXzFh1NtqW9tTFB4xokSznIfvCOTp7PtrJZRac)

This happened to me when I disabled the new UI and returned to the old Comfy Manager.

Is it possible to roll back to the previous version of the new UI? It was working fine for me earlier this morning.

**Comment by JorgeR81** [comment]
> Is it possible to roll back to the previous version of the new UI?

Yes, you need to edit your `run_nvidia_gpu.bat` file, adding this:  `--front-end-version Comfy-Org/ComfyUI_frontend@1.3.11`

https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#using-the-latest-frontend

You can create a copy of the bat file, for convenience ( e.g. `run_nvidia_gpu_1311.bat`) 

It should look like this:

```
.\python_embeded\python.exe -s ComfyUI\main.py --front-end-version Comfy-Org/ComfyUI_frontend@1.3.11 --windows-standalone-build
pause
```

**Comment by huchenlei** [comment]
Culprit is https://github.com/pythongosssss/ComfyUI-Custom-Scripts/blob/626e001a20c4a6ad8f987153538d7ff750cb2850/web/js/snapToGrid.js#L21

Disable ComfyUI-Custom-Scripts will solve the issue. I am going to implement the always snap to grid as a core extension and disable custom script's impl.

**Comment by camoody1** [comment]
> Culprit is https://github.com/pythongosssss/ComfyUI-Custom-Scripts/blob/626e001a20c4a6ad8f987153538d7ff750cb2850/web/js/snapToGrid.js#L21
> 
> Disable ComfyUI-Custom-Scripts will solve the issue. I am going to implement the always snap to grid as a core extension and disable custom script's impl.

Ouch... That's a rough ask. The extension provides so much more than just that one script. 😢

**Comment by huchenlei** [comment]
> > Culprit is https://github.com/pythongosssss/ComfyUI-Custom-Scripts/blob/626e001a20c4a6ad8f987153538d7ff750cb2850/web/js/snapToGrid.js#L21
> > Disable ComfyUI-Custom-Scripts will solve the issue. I am going to implement the always snap to grid as a core extension and disable custom script's impl.
> 
> Ouch... That's a rough ask. The extension provides so much more than just that one script. 😢

We do have frontend extension management now: https://github.com/Comfy-Org/ComfyUI_frontend/pull/1141

You can find `pysssss.SnapToGrid` and disable it.

**Comment by huchenlei** [comment]
![image](https://github.com/user-attachments/assets/d788d5c9-a5ae-45c2-acd2-bb322f6f5e62)

**Comment by camoody1** [comment]
@huchenlei Yep, sorry. I found that just before you posted. Thank you for following up.

**Comment by camoody1** [comment]
> ![image](https://private-user-images.githubusercontent.com/20929282/374750149-d788d5c9-a5ae-45c2-acd2-bb322f6f5e62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0Mjk3MjMsIm5iZiI6MTcyODQyOTQyMywicGF0aCI6Ii8yMDkyOTI4Mi8zNzQ3NTAxNDktZDc4OGQ1YzktYTVhZS00NWMyLWFjZDItYmIzMjJmNmY1ZTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDIzMTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzNWJlOTlkYzUwYWMxYWExOWI1NjFkNmQyZGNiNTNlMDFkZWQ3YzUwYWI2ZWY5ZjVlNjZkNzNkZmI1MGZmMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vqxreOTt7DZDAxLMzxRoI079m7nTG5gKeBQVrfw-Sy4)

Whoa. How do you get a list like this to come up? I don't have an "Extension" sub-menu like you do.

**Comment by JorgeR81** [comment]
> I am going to implement the always snap to grid as a core extension and disable custom script's impl.

@huchenlei, please consider adding this improvement to make it work better with groups:

https://github.com/pythongosssss/ComfyUI-Custom-Scripts/issues/261

**Comment by huchenlei** [comment]
> > ![image](https://private-user-images.githubusercontent.com/20929282/374750149-d788d5c9-a5ae-45c2-acd2-bb322f6f5e62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0Mjk3MjMsIm5iZiI6MTcyODQyOTQyMywicGF0aCI6Ii8yMDkyOTI4Mi8zNzQ3NTAxNDktZDc4OGQ1YzktYTVhZS00NWMyLWFjZDItYmIzMjJmNmY1ZTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDIzMTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzNWJlOTlkYzUwYWMxYWExOWI1NjFkNmQyZGNiNTNlMDFkZWQ3YzUwYWI2ZWY5ZjVlNjZkNzNkZmI1MGZmMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vqxreOTt7DZDAxLMzxRoI079m7nTG5gKeBQVrfw-Sy4)
> 
> Whoa. How do you get a list like this to come up? I don't have an "Extension" sub-menu like you do.

![image](https://github.com/user-attachments/assets/697b1774-0582-45f7-a5f8-17edc45b5f7c)
You need to enable that experimental feature in settings first to reveal it. I am afraid that people will try disable some core extensions and report the core is somehow not working so it is not shown by default.

**Comment by camoody1** [comment]
@huchenlei It looks like I'm able to resolve my issue with the standard settings, so I'll just leave the Beta feature turned off and avoid the possibility of me accidentally breaking something. Thank you 😊

**Comment by JorgeR81** [comment]
> You need to enable that experimental feature in settings first to reveal it. 

@camoody1, You can also to roll back to v1.3.11 to find that setting, as shown above.

This feature was only added in v1.3.11
