### ISSUE TITLE
[Feature Request]: Fast disconnect links

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI_frontend#1180]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I often need to disconnect links from inputs to make new connections, but everytime I have to do the following:

- Grab the link from input
- Move it on canvas
- Release it
- _`*Search box shows up*`_
- Click on canvas to close search box

And then I can create the new connection. This is pretty tedious and unefficient.

Is it possible to set a keybind to make it faster?

### Proposed workflow

The shortcut could be:
`Alt` + `Click` on input -> The input get disconnected.

The same keybind could be used to also fast disconnect outputs.

### Alternative
There is already a right-click option to disconnect outputs:

![disconnect_links_option](https://github.com/user-attachments/assets/b523295e-5b26-4ecf-8340-5719847a68d0)

A good alternative could be implementing the same option to inputs.

**Comment by huchenlei** [comment]
You can set link release to no action to skip the searchbox/context menu. 
![image](https://github.com/user-attachments/assets/a9279796-ec59-45c6-be4c-dd57f3448377)

**Comment by huchenlei** [comment]
I don't think the keybinding would make it any easier, as it would still requires:
- click the slot
- Move the mouse to correct option
- click the option

Where as the current method is:
- mouse down on slot
- move mouse a bit to empty canvas
- release the mouse

**Comment by christian-byrne** [comment]
> The shortcut could be:
> Alt + Click on input -> The input get disconnected.
>

Alt+Ctrl+LMB disconnects all inputs from the slot. Is that what you mean?

https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#shortcuts

**Comment by LukeG89** [comment]
@christian-byrne That's exacty what I meant! Didn't know there was already a shortcut, thanks! 😄 

Thank you too @huchenlei! Keep up the good work guys! ❤️
