### ISSUE TITLE
[Feature Request]: Drag and Drop guides

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI_frontend#1181]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

After the implementation of the "Snap to grid" option from Custom Scripts in version 1.3.13, my beloved "drag and drop guides" are gone:
![drag_and_drop_guides](https://github.com/user-attachments/assets/69ac267a-8daf-48ac-adfc-04c63cd3ea48)

Since this is now a core feature, can you implement the guides as well?

### Proposed workflow

.

**Comment by tiptinker** [comment]
![image](https://github.com/user-attachments/assets/663c4ef8-a044-4369-bfb4-858e50d472a7)


Mine are still there.

![image](https://github.com/user-attachments/assets/8f423fa4-6708-4e36-9fcc-c83a362b12ac)

**Comment by LukeG89** [comment]
@pandayummy You still have them because you are probably using the 1.3.11 frontend released in ComfyUI. After 1.3.13 they integrated the snap to grid feature in the core and disabled the Custom Scripts one.

I see that @huchenlei requested to split the drag and drop feature so we can have both again.

**Comment by hben35096** [comment]
Maybe like Photoshop, hold down Shift to lock the movement direction

https://github.com/user-attachments/assets/5d902752-56bd-40b8-af35-dd3ffb25af88

**Comment by LukeG89** [comment]
@hben35096 You should open a new feature request only for that feature

**Comment by hben35096** [comment]
OK, thanks for reminding

**Comment by LukeG89** [comment]
@huchenlei I see that @pythongosssss merged your PR, and the Drag and Drop settings are back.

But something went wrong, because the guides still don't appear.


https://github.com/user-attachments/assets/748d91a4-1677-4819-a301-c73112e83317

No errors in Console and just a few nodes enabled when testing.

I see that there is still the Snap to Grid extension disabled (and it can't be enabled)

![stg_disabled](https://github.com/user-attachments/assets/7471a626-484e-4bdd-9f45-443fb2836233)

Could it be the cause?

**Comment by tiptinker** [comment]
Not working +1

**Comment by LukeG89** [comment]
Wait, I just discovered by accident that guide lines only appear when you hold Shift (they were always on before).


https://github.com/user-attachments/assets/929ac982-b1b5-4bb9-b18b-68e6b0318b79

I like it!

But only lines work, not block.

**Comment by LukeG89** [comment]
Guidelines are back! 🎉

Thanks @huchenlei! ❤️

**Comment by geroldmeisinger** [comment]
It broke again, see: https://github.com/pythongosssss/ComfyUI-Custom-Scripts/issues/396

https://github.com/SparknightLLC/ComfyUI-CrosshairGuidelines
if someone needs an alternative

<img width="670" height="560" alt="Image" src="https://github.com/user-attachments/assets/8632f9b6-f864-4845-b05a-70c50608f7a0" />
