### ISSUE TITLE
Fast input connect

### ISSUE THREAD

**Issue by huchenlei** [Comfy-Org/ComfyUI_frontend#120]
![image](https://github.com/user-attachments/assets/ab382f56-d4f8-4321-98f1-573263f04261)

I think we should display a connection handle/dot for all matching types in front of the widgets when the user grabs a connection.

**Comment by nanamicat** [comment]
Unity Amplify Shader Editor:
![image](https://github.com/user-attachments/assets/7a9552e0-cd4e-4e0d-bad4-28dc84933e79)
Proposal:
![1](https://github.com/user-attachments/assets/fd373b60-dc44-4776-a553-5d18dc697309)
![image](https://github.com/user-attachments/assets/414154e1-984f-4842-bb4f-f6c6d90f1617)
