### ISSUE TITLE
[Bug]: Highlight doesn't work in Clip and VAE outputs

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI_frontend#1204]
### Frontend Version

1.3.16

### Expected Behavior

Clip and VAE outputs should highlight when grabbing a link from their input types.

### Actual Behavior

Clip and VAE outputs are not highlighted.

### Steps to Reproduce

https://github.com/user-attachments/assets/90a224f6-3dc8-4198-826f-1ace17a5ac31

### Debug Logs

```powershell
E:\>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --disable-all-custom-nodes --disable-xformers --preview-size 1024 --front-end-version Comfy-Org/ComfyUI_frontend@latest
Total VRAM 8192 MB, total RAM 65277 MB
pytorch version: 2.4.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: E:\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.3.16
E:\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Skipping loading of custom nodes
Starting server

To see the GUI go to: http://127.0.0.1:8188
```

### Browser Logs

No errors.

### What browsers do you use to access the UI ?

Google Chrome

### Other

I noticed this behavior only on Clip and VAE, I don't know if there are other types with the same issue.

**Comment by huchenlei** [comment]
Hmmm, this must be a very old bug. I verified that v1.0.0 has this bug already. Thanks for flagging this!

**Comment by LukeG89** [comment]
This issue is fixed! (I guess after this PR https://github.com/Comfy-Org/ComfyUI_frontend/pull/1339)


https://github.com/user-attachments/assets/02a1a59f-12f6-411d-b039-dc0a0b839ed5
