### ISSUE TITLE
[Bug]:  All forwarding from Muter and Bypasser no longer works (Rgthree Custom Nodes)

### ISSUE THREAD

**Issue by murphylanga** [Comfy-Org/ComfyUI_frontend#1219]
### Frontend Version

[--front-end-version Comfy-Org/ComfyUI_frontend@latest](https://github.com/Comfy-Org/ComfyUI_frontend) V1.3.7 - Latest today

### Expected Behavior

No problems after the update..

### Actual Behavior

All forwarding from Muter and Bypasser (Rgthee Custom Nodes) no longer works. The buttons no longer work when more than one node is to be muted.

[SDXL+Kolors+Flux_BIG_Base_Modul_Styler_V1.01.json](https://github.com/user-attachments/files/17344491/SDXL%2BKolors%2BFlux_BIG_Base_Modul_Styler_V1.01.json)

### Steps to Reproduce

[MiniWorkflowTest.json](https://github.com/user-attachments/files/17344638/MiniWorkflowTest.json)

It's because of the new frontend from yesterday.
Temporary workaround, go back to an old frontend in the
run_nvidia_gpu.bat with:

--front-end-version Comfy-Org/ComfyUI_legacy_frontend@latest

### Debug Logs

```powershell
--
```

### Browser Logs

--

### What browsers do you use to access the UI ?

Microsoft Edge

**Comment by huchenlei** [comment]
The issue should be filed to the custom node repo.

**Comment by murphylanga** [comment]
> The issue should be filed to the custom node repo.

It is already reported there, but I reported it here because I think it is only on the frontend
