### ISSUE TITLE
[Bug]: The batch count in the new Queue version cannot exceed 100.

### ISSUE THREAD

**Issue by cilantrocatsoup** [Comfy-Org/ComfyUI_frontend#1231]
### Frontend Version

1.3.11

### Expected Behavior

More images can be batch processed.

### Actual Behavior

When batch processing hundreds of images, an input number like 224 will be reset to 100.

https://github.com/user-attachments/assets/85623546-54bd-4b63-b9c1-60970d8587a1

### Steps to Reproduce

.

### Debug Logs

```powershell
.
```

### Browser Logs

.

**Comment by huchenlei** [comment]
You can set limit in setting:
![image](https://github.com/user-attachments/assets/bebcda4f-d331-42dc-90e5-7bb2c04f624b)

**Comment by hemosi** [comment]
Thanks, it works great!
