### ISSUE TITLE
[Feature Request]: The latest UI is a disaster, especially for the workflow management

### ISSUE THREAD

**Issue by pandayummy** [Comfy-Org/ComfyUI_frontend#1254]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Now we have workflow related functions on 3 places:

The sidebar:
![image](https://github.com/user-attachments/assets/cf14e649-98b3-4621-9216-17f0034a405a)

Here
![image](https://github.com/user-attachments/assets/6ba1940e-c81b-4dca-ac0a-9cd19fc60cab)

and here
![image](https://github.com/user-attachments/assets/235ba7a6-35c5-4b07-afd8-47e9b4d6161d)

Total mess.  The old way of putting everything on top menu is much better than now.

Now we have to keep the sidebar open in order to have a clear view of workflows, which occupies 1/6 of the screen.
When we need to Save/Save as the workflow, we need to click the top menu **Workflow**, then click one more time.
And the clear workflow is in another top menu **Edit**.

The were one famlily in the past, why do you split them into 3 different places? What's the logic behind all these?

**Comment by LukeG89** [comment]
To be honest, the new frontend is way better of the previous one. For example:

> Now we have to keep the sidebar open in order to have a clear view of workflows, which occupies 1/6 of the screen.

You can toggle on/off all sidebar tabs using a single key. Press `W` to open/close Workflows tab.

> When we need to Save/Save as the workflow, we need to click the top menu Workflow, then click one more time.
And the clear workflow is in another top menu Edit.

You can set custom keybindings, for example to Save/Save As you can set the classic `Ctrl`+`S` and `Ctrl`+`Shift`+`S`.

So, I think it is more a matter of habit. You just need to get used to it.

**Comment by tiptinker** [comment]
I can't agree with that.
The old UI shows everything in one place and most of the operations can be done with **mouse hover** and **left clicks**.
Now we have to use more **right clicks** and **shortcuts**. 
Left click and hover are way much easier than other behaviours, from the aspect of product design, it's better to simplify the operation than making it complex, though it might look more "advanced" with complex operations.
I am not using ComfyUI all day, I use blender,  adobe ps, ai, after effects, cinema4d, tons of software, and the W key has other meanings in them, remembering another set of shortcuts means heavy burden to me.

**Comment by LukeG89** [comment]
Then I would suggest opening a feature request about expanding dropdown menus on mouseover.

Anyway, the 1.3 frontend and the software you mentioned have all the same kind of interactions:

- Shortcuts (you can set your own in Keybindings section)
- Click on dropdown menus.

So you should get used to it easily.
