### ISSUE TITLE
[Bug]: When using Nginx as a reverse proxy with a URL prefix, the sample template is unable to display and retrieve the corresponding workflow JSON due to the use of absolute paths.

### ISSUE THREAD

**Issue by HelloClyde** [Comfy-Org/ComfyUI_frontend#1256]
### Frontend Version

v1.3.11

### Expected Behavior

When using Nginx as a reverse proxy with a URL prefix configured, the sample template work correctly.

### Actual Behavior

![image](https://github.com/user-attachments/assets/7a614af7-d223-4233-a682-63dd842857a0)

### Steps to Reproduce

1. Use a configuration similar to the following to set up Nginx as a reverse proxy
```
 location /comfyui-test/ {
        proxy_pass http://xx.xx.xx.xx:8188/;
        client_max_body_size 20M;
        proxy_set_header    Host            $host;
        proxy_set_header    X-Real-IP       $remote_addr;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_hide_header   X-Powered-By;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
}
```

2. Access ComfyUI using the proxy URL and attempt to use the template feature.

### Debug Logs

```powershell
ignore
```

### Browser Logs

url https://xx/templates/default.jpg 404

url https://xx/templates/default.json 404

### What browsers do you use to access the UI ?

Google Chrome

**Comment by weiwenying** [comment]
ComfyUI version: 0.3.24, ComfyUI_frontend version: v1.10.17, nginx  with a URL prefix configured:

![Image](https://github.com/user-attachments/assets/207b9dc1-324b-4b17-be7a-f4241f52c9c5)

can not load the image. my nginx config:

```ini
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}


server {
    listen 8189;
    listen [::]:8189;

    location /userendpoint/8MRWqVjZf0eomI/ {
        proxy_pass http://127.0.0.1:8188/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
        tcp_nopush on;
        tcp_nodelay on;
    }
}
```
