### ISSUE TITLE
[Bug]: Duplicate a node, with dynamic output, by alt+drag and delete it, also delete the output link of the original node

### ISSUE THREAD

**Issue by numz** [Comfy-Org/ComfyUI_frontend#1261]
### Frontend Version

1.3.11

### Expected Behavior

do not delete original node output links

### Actual Behavior

When I duplicate a custom node defined as shown below using Alt+Drag, it appears it also duplicate the output links , even if it's not visible on UI. When I delete the duplicated node, it also deletes the output links from the original node. This might be specific to my unusual configuration. Let me know if I'm doing something wrong please.

### Steps to Reproduce

Here is the context:

- Let say we have a simple custom node that change input and output type when combo "type" change.

```
class WorkflowInput:
    def __init__(self):
        pass

    @classmethod
    def INPUT_TYPES(cls):
        return {"required": {
            "Name": ("STRING", {"default": ""}),
            "type": (["IMAGE", "MASK"],),
            "default": ("*",)
        }}

    RETURN_TYPES = (AnyType("*"),)
    RETURN_NAMES = ("output",)
    FUNCTION = "execute"
    CATEGORY = "FlowChain ⛓️"
    #OUTPUT_NODE = True

    @classmethod
    def IS_CHANGED(s, Name, type, default, **kwargs):
        m = hashlib.sha256()
        if default is not None:
            m.update(str(default).encode())
        else:
            m.update(Name.encode()+type.encode())
        return m.digest().hex()

    def execute(self, Name, type, default, **kwargs):
        return (default,)
```

I have to use ```AnyType("*")``` because the next node where I connect the output doesn't recognize it otherwise. The validation check fails, and I haven't found another solution, but AnyType("") seems to work.

For the web part, I have something like this during node creation:

```
              nodeType.prototype.onNodeCreated =  function() {
                    chainCallback(this, "onConfigure", function(info) {
                            // Code where I load the data saved for this node (If you need to see let me know)
                    });
                    chainCallback(this, "onSerialize", function(info) {
                        // Code where I save the data for this node (If you need to see let me know)
                    });
                   // Where I declare callback for the COMBO widget
                    this.widgets[1].callback =  ( value ) => {
                        //Function to remove inputs and outputs
                        clearInputs(this);
                       //Now I create input and output for the type I want.
                        switch(value){
                            case "IMAGE":
                                this.addOutput("output", "IMAGE");
                                this.addInput("default", "IMAGE");
                                break;
                            case "MASK":
                                this.addOutput("output", "MASK");
                                this.addInput("default", "MASK");
                                break;
                        }
                    };
                }
```

I have to manage ```onConfigure``` and ```onSerialize``` because the widget and output information fail to reload the previous configuration on refresh. The issue seems to come from LGraphNode.constructor at line 1998 of ```app.ts```. For outputs, for example, it runs the following code:

```
        // line 2062 app.ts
        for (const o in nodeData['output']) {
          let output = nodeData['output'][o]
          if (output instanceof Array) output = 'COMBO'
          const outputName = nodeData['output_name'][o] || output
          const outputIsList = nodeData['output_is_list'][o]
          const outputOptions = outputIsList
            ? { shape: LiteGraph.GRID_SHAPE }
            : {}
          this.addOutput(outputName, output, outputOptions)
        }
``` 
```nodeData['output']``` contains my node definition, which has an output of type ```AnyType("*")```. However, it replaces my correct output data with ```AnyType("*")``` and changes the output name to "".

That’s fine, I handle this with ```onConfigure``` and ```onSerialize``` to bypass it, so it’s not really a big issue.

Now, in the UI, I create this node and choose the ```IMAGE``` type. I then connect the output to a ```Preview Image``` node input—so far, no problems.

Then I duplicate the node using "Alt+Drag". Everything seems fine (though there seems to be a resizing issue when I click on the original node the duplicate node resizing with bad shape, suppose that there is other shared information between original node and duplicated node), but no real problem in the UI.

However, when I delete the duplicated node, it unfortunately also deletes the output link of the original node. I checked, and yes, the links still appear on the output.

https://github.com/user-attachments/assets/75c6663b-4d97-4696-a9f4-56e3fc4f1b9e

### Debug Logs

```powershell
No logs
```

### Browser Logs

No logs

**Comment by webfiltered** [comment]
Alt-clone nukes all references (stringify / JSON.parse) - probably not a Comfy bug.

Sounds like you're passing a ref to `LGraphNode.output.links` (`number[]`) instead of copying only the contents e.g.:
`other.output.links = [...node.output.links]`

**Comment by numz** [comment]
wonderfull, It works :), thanks !!!!!!!!!

**Comment by numz** [comment]
My bad, it doesn't, but you probably right, I have probably miss something

**Comment by numz** [comment]
thanks, works :)
