### ISSUE TITLE
[Feature Request]: Save sidebar width, per tab

### ISSUE THREAD

**Issue by JorgeR81** [Comfy-Org/ComfyUI_frontend#1268]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Each sidebar displays different contents, so each one has an optimal width for me.  

For instance, I like a narrow Queue sidebar, to show more than 3 images per column. 
But I want the Node Library to be wider, to show all node names, in a single line. 

So, each time I change sidebar tabs, I need to change the width.  

### Proposed workflow

When the user manually sets the sidebar width, it will be stored, per tab.

### Additional information

I added this a while back, with other sidebar improvements ( https://github.com/Comfy-Org/ComfyUI_frontend/issues/897 )

But I'm adding it now, as a separate issue, to give it more visibility, because it's the most important one and other users have also shown interest.

**Comment by LukeG89** [comment]
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/1480
