### ISSUE TITLE
[Bug]: The mask does not display successfully, but it can be edited and saved to the node and folder.

### ISSUE THREAD

**Issue by Willy-Shenn** [Comfy-Org/ComfyUI_frontend#1274]
### Frontend Version

1.3.11

### Expected Behavior

After drawing the mask and saving it to the node, the mask displays correctly within the node.

### Actual Behavior

After drawing the mask and saving it to the node, the mask does "not" display correctly within the node. However, when opening the mask editor, the mask displays correctly inside the editor, and the images with the applied masks are correctly saved in the "input" folder. Although the masks are displayed and saved properly, they still do not appear on the edited image in the Load Image node.

### Steps to Reproduce

https://github.com/user-attachments/assets/50df5387-f1a7-4fa0-82d9-ee70b21385b4

### Debug Logs

```powershell
NA
```

### Browser Logs

NA

### What browsers do you use to access the UI ?

Google Chrome

### Other

I have encountered this issue before. However, after removing all custom nodes, the mask displayed correctly. After troubleshooting each node one by one and restoring all nodes to the custom node folder, the issue disappeared, and the mask displayed properly in the Load Image node. But this time, even after removing all custom nodes, the issue persists.
https://github.com/comfyanonymous/ComfyUI/issues/3986

Someone suggested clearing the cookies in the browser, which I also tried, but the issue remains unresolved.
https://github.com/comfyanonymous/ComfyUI/issues/2428

**Comment by huchenlei** [comment]
Cannot reproduce this issue. Can you try disable all custom nodes with `--disable-all-custom-nodes` launch arg? Please open a new issue if the problem persists.
