### ISSUE TITLE
[Bug]: Unable to change the shape of the nodes.

### ISSUE THREAD

**Issue by StellarBeing25** [Comfy-Org/ComfyUI_frontend#1276]
### Frontend Version

V1.3.11

### Expected Behavior

The shape of the node should change according to the shape selected.

### Actual Behavior

Changing node shape has no effect, and it always remains rounded.

### Steps to Reproduce

Right click on a node > Shapes > Select the desired shape

### Debug Logs

```powershell
No Logs
```

### Browser Logs

No Logs

### What browsers do you use to access the UI ?

Mozilla Firefox

**Comment by LukeG89** [comment]
Duplicated of https://github.com/Comfy-Org/litegraph.js/issues/213

They're aware of the problem, you can close this issue.

**Comment by StellarBeing25** [comment]
OK
