### ISSUE TITLE
[Bug]: Can't set shape anymore after update

### ISSUE THREAD

**Issue by 925-Studio** [Comfy-Org/ComfyUI_frontend#1277]
### Frontend Version

v.1.3.11

### Expected Behavior

Change the node shape in the right click menu.

### Actual Behavior

Nodes remain in round shape no matter how I try.

### Steps to Reproduce

Create or select an existing node -> right click on it -> Shapes -> Box -> nothing happen (remain in default round shape)

### Debug Logs

```powershell
Nothing appeared in my terminal.
```

### Browser Logs

Nothing relates with this issue.

### What browsers do you use to access the UI ?

Google Chrome, Apple Safari, Other

### Other

<img width="724" alt="Screenshot 2024-10-22 at 2 07 33 PM" src="https://github.com/user-attachments/assets/d432245f-bc9d-4825-8383-e73781467154">

**Comment by LukeG89** [comment]
Duplicated of https://github.com/Comfy-Org/litegraph.js/issues/213 (and also https://github.com/Comfy-Org/ComfyUI_frontend/issues/1276)

They're aware of the problem, you can close this issue.

**Comment by 925-Studio** [comment]
> Duplicated of [Comfy-Org/litegraph.js#213](https://github.com/Comfy-Org/litegraph.js/issues/213) (and also #1276)
> 
> They're aware of the problem, you can close this issue.

Didn't find that post, thank you for the tip.
