### ISSUE TITLE
[Bug]: Update zod to include model url

### ISSUE THREAD

**Issue by yoland68** [Comfy-Org/ComfyUI_frontend#1278]
### Frontend Version

Latest

### Expected Behavior

Not having alert

### Actual Behavior

![image](https://github.com/user-attachments/assets/f96f5a34-ebcf-4430-8c65-b3f41f71488e)

### Steps to Reproduce

-

### Debug Logs

```powershell
-
```

### Browser Logs

-

**Comment by huchenlei** [comment]
The schema was introduced in https://github.com/Comfy-Org/ComfyUI_frontend/pull/321.

You are seeing the alert because the url field is not a valid URL string. Can you reopen an issue with reproduction workflow?

**Comment by yoland68** [comment]
Actually the url was empty there
