### ISSUE TITLE
[Bug]: Unload & Free Model & Cache message is shown under menu bar

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [Comfy-Org/ComfyUI_frontend#1344]
### Frontend Version

 ComfyUI_frontend v1.3.11

### Expected Behavior

To be able to see the message that is displayed when pressing the buttons. This used to be visible, but now it's displayed under the bar.

### Actual Behavior

![image](https://github.com/user-attachments/assets/248ffcd3-f461-48df-8bfb-8a3eb9258fa3)

### Steps to Reproduce

Get a copy of my computer.
Observe the effect.

### Debug Logs

```powershell
Nothing to log, no errouneous behavior.
```

### Browser Logs

<!DOCTYPE html>

### Setting JSON

[comfy.settings.json](https://github.com/user-attachments/files/17540948/comfy.settings.json)

### What browsers do you use to access the UI ?

Mozilla Firefox

### Other

Firefox 131.0.3 (64-bit)

**Comment by huchenlei** [comment]
Please file the issue in the custom node repo. The feature comes from ComfyUI-Manager.
