### ISSUE TITLE
[Feature Request]: option to hide the "corner" floating panel 

### ISSUE THREAD

**Issue by JorgeR81** [Comfy-Org/ComfyUI_frontend#1345]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

This could be useful on a tablet, but on a computer, I don't need it.

Can we have an option to hide it ? 

![panel](https://github.com/user-attachments/assets/5da338eb-d006-4aa8-969d-165f2aa5529f)

### Proposed workflow

Enable / disable the panel in the user settings. 

### Additional information

If there's a frontend extension I can disable, to hide this, I'll be happy to do that instead.

**Comment by LukeG89** [comment]
You can already do that

![option](https://github.com/user-attachments/assets/08c7c845-0c2f-436a-801d-973f046bffe9)

**Comment by JorgeR81** [comment]
OK. Thanks !
