### ISSUE TITLE
[Bug]: Nodes not "Snapping" to Grid Lines

### ISSUE THREAD

**Issue by camoody1** [Comfy-Org/ComfyUI_frontend#1346]
### Frontend Version

v1.3.25

### Expected Behavior

When I drag a node, it should snap to the grid lines on my graph.

### Actual Behavior

Nodes are not snapping to grid lines. Group boxes snap to grid lines, but nodes do not.

### Steps to Reproduce

Move a node using v1.3.25

### Debug Logs

```powershell
N/A
```

### Browser Logs

N/A

### Setting JSON

N/A

### What browsers do you use to access the UI ?

Microsoft Edge

**Comment by huchenlei** [comment]
Cannot reproduce

https://github.com/user-attachments/assets/83ddad19-46ea-4350-89ff-60aa6bd0a7d1

**Comment by JorgeR81** [comment]
I have this issue in 1.3.11 ( the one that comes with ComfyUI )

But not in the latest version ( 1.3.28 )

**Comment by camoody1** [comment]
The issue resolved itself for me. 🤷🏽
