### ISSUE TITLE
[Bug]: 导出图片时，背景只占了左上角

### ISSUE THREAD

**Issue by clhui** [Comfy-Org/ComfyUI_frontend#1355]
### Frontend Version

[ComfyUI v0.2.4-5-gaf8cf79](https://github.com/comfyanonymous/ComfyUI)
[ComfyUI_frontend v1.3.11](https://github.com/Comfy-Org/ComfyUI_frontend)

### Expected Behavior

预期背景是同一个颜色
![workflow (1)](https://github.com/user-attachments/assets/da325d21-940b-4617-a955-7082943e0bd2)

### Actual Behavior

导出的图片背景只有左上角有颜色，连接线也没显示

### Steps to Reproduce

![WX20241029-154432@2x](https://github.com/user-attachments/assets/a4b7fab1-a24c-4ba6-856d-b655ed9c9d93)

### Debug Logs

```powershell
无
```

### Browser Logs

无

### Setting JSON

comfy.settings.json
[comfy.settings.json](https://github.com/user-attachments/files/17553387/comfy.settings.json)

### What browsers do you use to access the UI ?

Google Chrome

**Comment by huchenlei** [comment]
The export feature comes from ComfyUI-Custom-Scripts. Please file the issue there.

**Comment by clhui** [comment]
好的 ，谢谢
