### ISSUE TITLE
[Bug]: Unable to search properly!

### ISSUE THREAD

**Issue by DreamLoveBetty** [Comfy-Org/ComfyUI_frontend#1379]
### Frontend Version

[舒适用户界面 v0.2.6-2-gdaa1565]

### Expected Behavior

Normal search, displaying node information

### Actual Behavior

Unable to display node name

### Steps to Reproduce

Double-click the workspace to search

### Debug Logs

```powershell
none
```

### Browser Logs

none

### Setting JSON

[comfy.settings.json](https://github.com/user-attachments/files/17577720/comfy.settings.json)

### What browsers do you use to access the UI ?

Microsoft Edge

### Other

After the update, the new version of the search node function can not display the node, the icon shows always read state, the old version can display, but abnormal lag, can not enter the search.
![1](https://github.com/user-attachments/assets/159e5985-8e86-440e-ac91-67e3636066f9)
![2](https://github.com/user-attachments/assets/1aaa9a80-3ed0-4521-b2b2-5fe06b3f35e5)

**Comment by huchenlei** [comment]
Please attach browser logs. Thanks! I cannot reproduce with the information you provided.
