### ISSUE TITLE
[Bug]: Highlight the open workflow currently shown on-screen (when in subfolders)

### ISSUE THREAD

**Issue by Jonseed** [Comfy-Org/ComfyUI_frontend#1388]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

When you have several workflows open, sometimes it can be hard to tell at a glance which one in the sidebar list is currently shown on-screen, especially if the workflows are similar. It would be helpful if the currently shown workflow was highlighted in the list of open workflows.

### Proposed workflow

1. Click on the Workflows sidebar.
2. See the list of open workflows, and the currently shown one is highlighted.

**Comment by Jonseed** [comment]
It looks like the currently shown workflow is noted on the browser tab title (and window title), but it would still be helpful if it was also highlighted in the open workflows list.

**Comment by yehonatan1202** [comment]
It looks like this feature already exists 
![Animation](https://github.com/user-attachments/assets/d84de49d-e4fe-4cd0-89a7-56571d02aa10)

**Comment by Jonseed** [comment]
> It looks like this feature already exists 

Hmm, that's not what it looks like on my screen. I get no highlight unless I am hovering my cursor over one of them. I wonder why it is different. I'm on dark mode in my system/browser, could that affect it?

**Comment by Jonseed** [comment]
So it looks like it only highlights new workflows, but not older more complex workflows... something weird is going on.

![Recording 2024-11-01 085557](https://github.com/user-attachments/assets/e5eb03cb-bb87-4fce-b3bc-5d8430c020d8)

**Comment by Jonseed** [comment]
Think I found the bug. It will only highlight workflows if they are in the root workflow folder. If they are in subfolders, then they don't highlight when active. It is the subfolder logic that seems to be messing up the highlighting.

![Recording 2024-11-01 090417](https://github.com/user-attachments/assets/f44d3ae4-aa45-4bb1-9931-b09a166d513b)

**Comment by Jonseed** [comment]
There seems to be a related bug that workflows in subfolders don't lose the * before the filename when saved. Should I file a separate bug issue?

**Comment by Jonseed** [comment]
Also, when saving workflows under a different name in subfolders, the saved workflow doesn't show up as the now active workflow in the open workflows list. It saves ok, but the previous workflow still shows as the currently open workflow, and if you save again, you will overwrite the previous workflow, not the newly saved workflow. These are probably all related bugs with workflow subfolders.

**Comment by LukeG89** [comment]
Now everything seems fixed in 1.3.34 frontend, after the rework of Workflow Management

**Comment by Jonseed** [comment]
I look forward to testing it.

**Comment by Jonseed** [comment]
Works great! Thanks!
