### ISSUE TITLE
[Bug]: Projects in folders cannot be saved in Workflow Manager

### ISSUE THREAD

**Issue by LincZero** [Comfy-Org/ComfyUI_frontend#1395]
### Frontend Version

v1.2.64

### Expected Behavior

![图片](https://github.com/user-attachments/assets/4b2a7926-2bec-4398-8a2a-08c4a516f1e4)

![图片](https://github.com/user-attachments/assets/6bec6e34-5e4f-45ac-b5e8-1a53efd8cae3)

If I modify the content of the workflow in the second arrow, I can click the Save button to save it smoothly. However, if I modify the workflow content of the first arrow (the workflow is in the folder), I cannot click the save button to save it (there is no reaction after clicking, the workflow name still has a '*').

### Actual Behavior

If I modify the content of the workflow in the second arrow, I can click the Save button to save it smoothly. However, if I modify the workflow content of the first arrow (the workflow is in the folder), I cannot click the save button to save it (there is no reaction after clicking, the workflow name still has a '*').

### Steps to Reproduce

1. Open `\ComfyUI\user\default\workflows\` , and create some folder
2. Put workflow categories into these newly created folders
3. When tested, it doesn't matter whether the pathname is Chinese or not

### Debug Logs

```powershell
None
```

### Browser Logs

Uncaught (in promise) TypeError: workflow is undefined
    #save workflows.ts:437
    save workflows.ts:281
    action index.ts:57
    ComfyButton button.ts:122

### Setting JSON

It has nothing to do with json, only its location.

The default workflow is reproducible

**Comment by LukeG89** [comment]
I reported a similar issue before:
- https://github.com/Comfy-Org/ComfyUI_frontend/issues/1165 (see the video at 0:46)

I think it's just a problem with the saved/unsaved status when workflows are inside subfolders.
But the workflow should be saved when you save it. Have you check that?

**Comment by LincZero** [comment]
I searched before I asked the question, but I'm sorry that I didn't find the issue due to different keywords

Yes, it's the same question. It was successfully saved. When I reloaded, it still showed up as unsaved, and I had to restart the service to get it to the saved state

I will subscribe to #1165 and close this duplicate issue
