### ISSUE TITLE
Issue - This breaks ComfyUI-N-Sidebar custom node

### ISSUE THREAD

**Issue by RamonGuthrie** [Comfy-Org/ComfyUI_frontend#140]
The revamped search box breaks this node and https://github.com/Nuked88/ComfyUI-N-Sidebar Also Ctrl + B doesn't function

**Comment by huchenlei** [comment]
Side bar features will be implemented natively here later this week.

**Comment by huchenlei** [comment]
Actually it's not the search box breaking the side bar. It's the beta menu UI. If you use default menu UI it is fine for now.

There are some legacy issues on canvas resize.

**Comment by huchenlei** [comment]
![image](https://github.com/user-attachments/assets/d3ac94c8-fc62-4a7a-8d48-e7622be933f7)
![image](https://github.com/user-attachments/assets/6bd9fa7e-150d-4442-9690-8cf57a299037)

BTW, you can disable the revamped search box in settings.

**Comment by RamonGuthrie** [comment]
> Side bar features will be implemented natively here later this week.

This is great to hear are you/devs teaming up with the Devs of ComfyUI-N-Sidebar, or is this a different vision of what a Sidebar should be?

**Comment by RamonGuthrie** [comment]
> Actually it's not the search box breaking the side bar. It's the beta menu UI. If you use default menu UI it is fine for now.
> 
> There are some legacy issues on canvas resize.

I'm still getting a few issues, when I boot up ComfyUI I'm not sure if it's a conflict with https://github.com/11cafe/comfyui-workspace-manager which is a great very useful custom node extension

Here is an image of that error
<img width="347" alt="image" src="https://github.com/user-attachments/assets/0403fbae-dfed-4095-8b6b-517f5a652e2c">

And Ctrl + B doesn't work I can't use that shortcut to bypass nodes

**Comment by huchenlei** [comment]
Thanks for the info!

According to my test https://github.com/11cafe/comfyui-workspace-manager and https://github.com/Nuked88/ComfyUI-N-Sidebar together cause the canvas disappear issue. Enabling one of them seem to be fine.

**Comment by huchenlei** [comment]
Merging into https://github.com/Comfy-Org/ComfyUI_frontend/issues/136 as issues other than extension conflicts have been resolved.

**Comment by RamonGuthrie** [comment]
> Thanks for the info!
> 
> According to my test https://github.com/11cafe/comfyui-workspace-manager and https://github.com/Nuked88/ComfyUI-N-Sidebar together cause the canvas disappear issue. Enabling one of them seem to be fine.

There still seems to be an interface bug, with https://github.com/Nuked88/ComfyUI-N-Sidebar I have disabled https://github.com/11cafe/comfyui-workspace-manager in both tests

Without the command line argument --front-end-version Comfy-Org/ComfyUI_frontend@latest
<img width="260" alt="image" src="https://github.com/user-attachments/assets/04241579-7773-4e82-84a1-1bd307d39cc5">

With the command line argument --front-end-version Comfy-Org/ComfyUI_frontend@latest
<img width="250" alt="image" src="https://github.com/user-attachments/assets/f1ad29f1-8651-4407-9a11-7e8cbbfc08f8">

**Comment by christian-byrne** [comment]
> > Thanks for the info!
> > According to my test https://github.com/11cafe/comfyui-workspace-manager and https://github.com/Nuked88/ComfyUI-N-Sidebar together cause the canvas disappear issue. Enabling one of them seem to be fine.
> 
> There still seems to be an interface bug, with https://github.com/Nuked88/ComfyUI-N-Sidebar I have disabled https://github.com/11cafe/comfyui-workspace-manager in both tests
> 
> Without the command line argument --front-end-version Comfy-Org/ComfyUI_frontend@latest <img alt="image" width="260" src="https://private-user-images.githubusercontent.com/156688666/350183530-04241579-7773-4e82-84a1-1bd307d39cc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MTExNjgsIm5iZiI6MTcyMTQxMDg2OCwicGF0aCI6Ii8xNTY2ODg2NjYvMzUwMTgzNTMwLTA0MjQxNTc5LTc3NzMtNGU4Mi04NGExLTFiZDMwN2QzOWNjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQxNzQxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTM3OGU2MzEzNDYzZmNlNmY4NGVmODA4N2FiY2NjMDE1MDM0OTY1ZDc3MWZjNmY0M2VlMTZjZjAyZmE5ODdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WcVPLO7fv098vLGcDSD0cYmNjP0DUxVvxFiwZEKVZbw">
> 
> With the command line argument --front-end-version Comfy-Org/ComfyUI_frontend@latest <img alt="image" width="250" src="https://private-user-images.githubusercontent.com/156688666/350183604-f1ad29f1-8651-4407-9a11-7e8cbbfc08f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MTExNjgsIm5iZiI6MTcyMTQxMDg2OCwicGF0aCI6Ii8xNTY2ODg2NjYvMzUwMTgzNjA0LWYxYWQyOWYxLTg2NTEtNDQwNy05YTExLTdlOGNiYmZjMDhmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQxNzQxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDkxMTU1NTQzYTExZjRjMWRiYzI0YTZhNTkxZjk5YzVhYWUwYjhmODc2ZDc4MTAyYmZiOGFjNzU3YTkxYzI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dzpKo0xm6fivMxaM-63lPKwpLSMstAyaeVyqBtBGyzQ">

That issue appears to also happen on the legacy frontend if you change `Font size` setting in `chrome://settings/appearance` to Small. Height/width of that button is using rem sizing. The new frontend is just shifting the problem so that it occurs on `Medium` root font instead of `Small`, I think.
