### ISSUE TITLE
[Feature Request]: Focus selected node(s) or whole workflow graph using 'F' shortcut key

### ISSUE THREAD

**Issue by cancer32** [Comfy-Org/ComfyUI_frontend#1402]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

The current functionality of navigating and focusing on selected nodes in Comfy UI could be enhanced by implementing a feature that allows users to focus on a selected node(s) using the 'F' key. This would improve accessibility

### Proposed workflow

1. Go to workflow panel

![Step1](https://github.com/user-attachments/assets/ef3173b4-3fef-4eef-8a15-92f169ee5aa1)

2. Select one or mutliple nodes

![Step2](https://github.com/user-attachments/assets/d1d72b1c-06c1-4fbc-bebb-3deb3767e80b)

3. Press 'F' key
4. The graph will zoom in to the selected node(s)

![Step3](https://github.com/user-attachments/assets/56da3935-99e5-46d3-86e4-1b8658ef9ba2)

5. If none of the nodes are selected, it should frame the entire workflow graph

**Comment by bezo97** [comment]
Agree that this would improve accessibility. Looks like an easy win since #1412 added `animateToNode`. I'll set up a key binding too so the shortcut can be customized like other functions.
@huchenlei If you see no objections I'll take this feature request

**Comment by huchenlei** [comment]
> Agree that this would improve accessibility. Looks like an easy win since #1412 added `animateToNode`. I'll set up a key binding too so the shortcut can be customized like other functions. @huchenlei If you see no objections I'll take this feature request

Sure please take it. Adding a new command for fit selected & fit whole graph should be straightforward to do. Do be aware that key `f` is binded on focus mode toggle by default right now.
