### ISSUE TITLE
[Feature Request] Double-click to rename Primitive and Note nodes

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI_frontend#1413]
The "double-click to rename" feature works on every nodes except for Primitives.

https://github.com/user-attachments/assets/ec7bd52c-0f6b-41bd-a546-b5c83c1f923f

Can it be implemented?

**Comment by webfiltered** [comment]
This feature uses the extension hook `nodeCreated`, which only fired for nodes wrapped in `ComfyNode` dynamic classes (created in `app.ts`).

**Comment by LukeG89** [comment]
I just noticed that double-clicking on title doesn't work also on Note nodes. Is it the same issue?

**Comment by webfiltered** [comment]
Exactly the same - note, primitive, and reroute nodes are all created as normal LGraphNode, rather than ComfyNode.  It's doable, just needs to be implemented on their (very normal, not-dynamic) classes.
