### ISSUE TITLE
[Bug]: Save Flow 405

### ISSUE THREAD

**Issue by GitHub4LP** [Comfy-Org/ComfyUI_frontend#1433]
### Frontend Version

latest

### Expected Behavior

Save Flow

### Actual Behavior

Save Flow 405

### Steps to Reproduce

Save Flow

### Debug Logs

```powershell
no care
```

### Browser Logs

![屏幕截图 2024-11-05 132155](https://github.com/user-attachments/assets/53ddff81-3a4b-4de1-8fba-9c85af563e3b)

### Setting JSON

no care

### Other

[ComfyUI](https://github.com/comfyanonymous/ComfyUI/issues/5491#issue-2634451225)

**Comment by huchenlei** [comment]
Closing for lack of details. Cannot repro.
