### ISSUE TITLE
[Bug]: UI crashes when I push a button for instant queue.

### ISSUE THREAD

**Issue by Maelstrom2014** [Comfy-Org/ComfyUI_frontend#1437]
### Frontend Version

new UI crashes when I push a button for instant queue.
All window shifts to left and become narror, cant see.
Only reloading helps.
The same in chrome, firefox. 

### Expected Behavior

-

### Actual Behavior

-

### Steps to Reproduce

-

### Debug Logs

```powershell
-
```

### Browser Logs

-

### Setting JSON

does not matter

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome

### Other

![image](https://github.com/user-attachments/assets/68cfd86a-fa25-4098-b1c5-5d0d56d49006)

**Comment by huchenlei** [comment]
Please make sure you can reproduce this issue with `--disable-all-custom-nodes` launch arg, and re-open with the list of custom nodes you installed.

**Comment by Maelstrom2014** [comment]
> --disable-all-custom-nodes

yes, its rotten apple between custom nodes. 
I have >200 custom noded. I moved them by ~30 to empty setup and all parts of list worked ok. after again I enable all custom nodes. and bug goes away. dont know why and how.
