### ISSUE TITLE
[Bug]: `Ctrl`+`s` opens both "Save Workflow" and "Save browser page" dialogs

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI_frontend#1441]
### Frontend Version

1.3.34

### Expected Behavior

`Ctrl`+`s` just saves the workflow.

### Actual Behavior

`Ctrl`+`s` also opens "Save browser page" dialog.

### Steps to Reproduce

- Register `Ctrl`+`s` as Save in Keybinding
- Use it to save a workflow

https://github.com/user-attachments/assets/fa977d82-528a-4b67-a337-7793e1b38944

### Debug Logs

```powershell
E:\>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --disable-all-custom-nodes --preview-size 1024 --front-end-version Comfy-Org/ComfyUI_frontend@latest
Total VRAM 8192 MB, total RAM 65277 MB
pytorch version: 2.6.0.dev20241101+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
Using pytorch cross attention
Initializing frontend: Comfy-Org/ComfyUI_frontend@latest, requesting version details from GitHub...
[Prompt Server] web root: E:\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.3.34
E:\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Skipping loading of custom nodes
Starting server

To see the GUI go to: http://127.0.0.1:8188
```

### Browser Logs

```
Running on 127.0.0.1:8188
logging.ts:333 ComfyUI Front-end version: 1.3.34
index.mjs:101 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'style')
    at Proxy.updateInkBar (index.mjs:101:16)
    at Proxy.<anonymous> (index.mjs:48:13)
127.0.0.1/:1 Autofocus processing was blocked because a document already has a focused element.
```

### Setting JSON

[comfy.settings.json](https://github.com/user-attachments/files/17650366/comfy.settings.json)

### What browsers do you use to access the UI ?

Google Chrome

**Comment by huchenlei** [comment]
Confirmed reproducable.

**Comment by huchenlei** [comment]
Hmmm, this is a very tricky one, as it only happens when you use keybinding `Ctrl + s` to trigger "Save Workflow" command. Following other cases this bug is not triggered:
- Bind another action on `Ctrl + s`: The action fires correctly without no save page popup
- Binding "Save Workflow" command to another shortcut, e.g. `Ctrl + Shift + S`: The save executed correctly
- Trigger "Save Workflow" via the dropdown menu: Works fine.
