### ISSUE TITLE
[Bug]: Primitive triggers unsaved status

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI_frontend#1454]
### Frontend Version

1.3.36

### Expected Behavior

After the rework of workflow management, saved/unsaved status perfectly works in every situations.

### Actual Behavior

Saved and unsaved status works perfectly, except when you use a primitive.
Primitive triggers unsaved status when opening workflow or switching between workflows.

### Steps to Reproduce

- Create default workflow
- Add a primitive and connect it to a node
- Save the workflow
- Switch workflows a couple of times
- See the unsaved status appear

And also:
- Open a saved workflow with a primitive inside
- See the unsaved status appear when clicking anywhere with the mouse (menus or canvas)

https://github.com/user-attachments/assets/2ea513fc-9a98-47e1-9337-976c032bce42

### Debug Logs

```powershell
E:\>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --disable-all-custom-nodes --preview-size 1024 --front-end-version Comfy-Org/ComfyUI_frontend@latest
Total VRAM 8192 MB, total RAM 65277 MB
pytorch version: 2.6.0.dev20241101+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
Using pytorch cross attention
Initializing frontend: Comfy-Org/ComfyUI_frontend@latest, requesting version details from GitHub...
[Prompt Server] web root: E:\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.3.36
E:\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Skipping loading of custom nodes
Starting server

To see the GUI go to: http://127.0.0.1:8188
```

### Browser Logs

```
Running on 127.0.0.1:8188
logging.ts:333 ComfyUI Front-end version: 1.3.36
index.mjs:101 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'style')
    at Proxy.updateInkBar (index.mjs:101:16)
    at Proxy.<anonymous> (index.mjs:48:13)
```

### Setting JSON

[comfy.settings.json](https://github.com/user-attachments/files/17662574/comfy.settings.json)

### What browsers do you use to access the UI ?

Google Chrome

### Other

I tested both in `control_before_generate` and `control_after_generate` and it does the same thing.

**Comment by huchenlei** [comment]
Hmmm, we should probably implement a change queue to allow us better visualize / debug what has changed to cause that modified status. Currently we are doing simple comparison of serialized graph content (links, nodes, etc) for that modified state, which might not be that robust.

**Comment by LukeG89** [comment]
@huchenlei The bug with primitives seems solved! 🎉 

But... I just found a problem with reroutes... 😅 

If you connect for example `ImpactInt` or `ImpactFloat` or `Seed (rgthree)`  through a reroute, the unsaved status is triggered.


https://github.com/user-attachments/assets/15a11a9c-c9cd-4d20-a3ed-fc97d5b1a9a4

### Debug Logs

```powershell
E:\>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --preview-size 1024 --front-end-version Comfy-Org/ComfyUI_frontend@latest
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-25 18:10:31.608886
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: E:\python_embeded\python.exe
** ComfyUI Path: E:\ComfyUI
** Log path: E:\comfyui.log

Prestartup times for custom nodes:
   2.0 seconds: E:\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 65277 MB
pytorch version: 2.6.0.dev20241115+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
Using pytorch cross attention
Initializing frontend: Comfy-Org/ComfyUI_frontend@latest, requesting version details from GitHub...
[Prompt Server] web root: E:\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.4.10
### Loading: ComfyUI-Impact-Pack (V7.11.5)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.8)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Manager (V2.52)
### ComfyUI Revision: 2860 [61196d88] | Released on '2024-11-25'

Import times for custom nodes:
   0.0 seconds: E:\ComfyUI\custom_nodes\websocket_image_save.py
   0.3 seconds: E:\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds: E:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

**Comment by LukeG89** [comment]
Since the problem with Primitives is solved, I close this issue
