### ISSUE TITLE
[Bug]: Workflow breaks links when using undo / redo

### ISSUE THREAD

**Issue by webfiltered** [Comfy-Org/ComfyUI_frontend#1477]
### Frontend Version

1.3.37

### Expected Behavior

Undo / redo only steps through changes that I've made.

### Actual Behavior

- The undo / redo history has steps that don't represent actions I took (looks like intra-step state, see repro)
- There are steps I took that are not in the undo / redo history (skipped)

### Steps to Reproduce

1. Default workflow
2. Click background of canvas
3. `ctrl` + `z`
4. Drag a link from the `negative` CLIP onto the `positive` input of the KSampler
5. `ctrl` + `z`

Instead of having two links from the clip(s), you're left with just one:
![image](https://github.com/user-attachments/assets/7b4742ce-3267-41bf-9e1f-c30ac973d144)

### Debug Logs

```powershell
-
```

### Browser Logs

-

### Setting JSON

-

### What browsers do you use to access the UI ?

Google Chrome

### Other

Found undo issues in 1.3.35, which prompted [a litegraph fix for reconnecting links](https://github.com/Comfy-Org/litegraph.js/pull/294), but has not resolved the issue in 1.3.37.

Confirmed working in 1.3.28.  I'm looking at changes made to `changeTracker`, but would also be happy to have this fixed for me!

**Comment by huchenlei** [comment]
Issue confirmed reproducable.

**Comment by huchenlei** [comment]
Related issue: https://github.com/Comfy-Org/ComfyUI_frontend/pull/1022

**Comment by webfiltered** [comment]
Edit: That's the one.

**Comment by huchenlei** [comment]
> #1406 looks like the culprit, sorry!

I might want to add a diff lib to properly show the diff. Later that should also help us visualize the diff on the UI.

**Comment by webfiltered** [comment]
Definitely - it is very messy doing diffs on the undo buffer.

**Comment by webfiltered** [comment]
Got it.  Commenting out a `reset(workflowData)` call on workflowService resolves it:

https://github.com/Comfy-Org/ComfyUI_frontend/blob/0161a670cf05d9c03f2330057f3647738d26930d/src/services/workflowService.ts#L237

**Comment by huchenlei** [comment]
> Got it. Commenting out a `reset(workflowData)` call on workflowService resolves it:
> 
> https://github.com/Comfy-Org/ComfyUI_frontend/blob/0161a670cf05d9c03f2330057f3647738d26930d/src/services/workflowService.ts#L237

Ah, I made a blunder there. The changeTracker is also using loadGraphData to load back states, and in such case we shouldn't reset the initial state.
