### ISSUE TITLE
Why is there no difference from the default UI. 

### ISSUE THREAD

**Issue by asshidhak** [Comfy-Org/ComfyUI_frontend#148]
Hi,
I follow the guide and using the below argument. but the UI looks like no difference, did I missing something.
--front-end-version Comfy-Org/ComfyUI_frontend@latest
how it look like on myside
![image](https://github.com/user-attachments/assets/8d091c3e-1b87-4b0b-81c4-0b67081da5c3)
your demo
![image](https://github.com/user-attachments/assets/69320e71-b4f0-470a-a3ea-697c25f94dc4)

**Comment by huchenlei** [comment]
![image](https://github.com/user-attachments/assets/b5a6502e-8418-4745-9542-3a43483cba60)
![image](https://github.com/user-attachments/assets/08ed8a11-6509-4b5e-96fe-ea96dbe52734)

Can you try tweak this config to legacy and back? It's a simple workaround for now.

The first time default value might need to be fixed. I am going to investigate it tomorrow.

**Comment by huchenlei** [comment]
v1.1.7 fixes this.
