### ISSUE TITLE
[Bug]: The workflow "save as" doesn't work as expected.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [Comfy-Org/ComfyUI_frontend#1505]
### Frontend Version

v1.3.39

### Expected Behavior

Selecting workflow > save as to ask if you're sure you want to save as it already exists, and then save the workflow when "ok" is selected.

### Actual Behavior

There is no prompt asking if you want to overwrite the existing save, and it also does not seem to save...unless it's no longer in user/default/workflow.
I've lost 2 updated workflows because of this!

### Steps to Reproduce

Open an existing workflow (w), edit it slightly, then select workflow > save as then click "confirm". Close the workflow and re-open it (using "w") and the changes have not been saved.

### Debug Logs

```powershell
No errors to report.
```

### Browser Logs

NA

### Setting JSON

[comfy.settings.json](https://github.com/user-attachments/files/17703795/comfy.settings.json)

### What browsers do you use to access the UI ?

MS Edge

### Other

I've used the "save" option in the past, and it has also been unreliable and saved workflows with a different name and overwritten existing ones, which is why I use "save as" now.
It sometimes saves with an alternate name, by adding a number to the end of the filename, but doesn't load that one when the workflow is re-loaded. Is this a new "feature" and is there some way to revert it? I use bookmarked workflows, but this save option renders that completely useless.
![Screenshot 2024-11-11 141211](https://github.com/user-attachments/assets/9aa6abe4-a5ac-45d9-a7e8-61dccde7efb9)

**Comment by huchenlei** [comment]
If you don't want to create a new file, please use "save" command instead of "save as" command. The "Save as" command now always creates a new copy of file. Also the "save as" command will not persist change to the original save source.

**Comment by GalaxyTimeMachine** [comment]
This is not a good implementation. Traditionally "save as" allows you to enter a filename that you want to save the file as, but this allows you to enter a name and then automatically changes it.
Also, if you read my "Other" information, you'll see that using just "save" has also been unreliable, because it didn't always save with the expected name and had been overwriting some workflows. I've not identified a pattern to this, which is why I hadn't logged it yet.

**Comment by GalaxyTimeMachine** [comment]
I've just tried using the "save" option, and it also does not prompt if you want to overwrite the existing file or not. There is no indication that it saved, or not.

**Comment by huchenlei** [comment]
> I've just tried using the "save" option, and it also does not prompt if you want to overwrite the existing file or not. There is no indication that it saved, or not.

"Save" command always overwrite existing. You can tell saved is done by the workflow changed from modified state to unmodified.

**Comment by alessandroperilli** [comment]
I am having some problems with this new implementation, too. 

`Save As` gives the user **control** on what file name is chosen and the **visibility** over the intended/unintended overwrite. This is why some people, like me, always prefer it over the Save command.

The way it was previously implemented in ComfyUI always gave me the feeling I knew what was happening and peace of mind. Plus, it's a behaviour consistent with every other app I ever used.

The new implementation, which I discovered by reading this thread*, leaves me uncertain of what's happening at any given time and it makes my process more complicated.

If I choose Save As and specify the same file name I'm already using, I either end up with an error in the UI (which is an unnecessary friction), or with an automatically duplicated file name that I don't see. I don't know which name ComfyUI has chosen for me.

If the file is APW 12.0 EA4.json, now I end up with APW 12.0 EA4 (2).json, APW 12.0 EA4 (3).json, APW 12.0 EA4 (4).json, etc., just like @GalaxyTimeMachine showed.

At that point, to restore my confidence about what's going on and remove clutter, I have to go over the OS file manager and check the modified date of each one of these files, remove all of them but the last one, and manually rename it.

I'm a huge fan of all the work that has been done on the new Front End and re-learning how to save is not the end of the world, but I think the previous implementation was perfectly fine.

Thank you for considering the feedback!


*I doubt very many people will come here to find out what's going on, so I recommend clear communication about this change.

**Comment by alessandroperilli** [comment]
I really appreciate it @huchenlei
