### ISSUE TITLE
[Bug]: Open in mask editor, Unable to load image

### ISSUE THREAD

**Issue by tengshaofeng** [Comfy-Org/ComfyUI_frontend#1512]
### Frontend Version

v1.3.26

### Expected Behavior

when opening in maskEditor, it can load image, than I can draw mask base it.

### Actual Behavior

when opening in maskEditor, it can not load image.
![image](https://github.com/user-attachments/assets/64949701-c718-4361-a556-0d470bf42936)
![image](https://github.com/user-attachments/assets/69ab41af-7fbb-4028-96ae-f76ce5d68ede)

### Steps to Reproduce

git clone https://github.com/comfyanonymous/ComfyUI.git
cd ComfyUI
git reset --hard 65a865918277b9413571c00fa402c5ff0a224225
python main.py

### Debug Logs

```powershell
Client protocols [''] don’t overlap server-known ones ()
Client protocols [''] don’t overlap server-known ones ()
Client protocols [''] don’t overlap server-known ones ()
Client protocols [''] don’t overlap server-known ones ()
Client protocols [''] don’t overlap server-known ones ()
Client protocols [''] don’t overlap server-known ones ()
Client protocols [''] don’t overlap server-known ones ()
Client protocols [''] don’t overlap server-known ones ()
Client protocols [''] don’t overlap server-known ones ()
Client protocols [''] don’t overlap server-known ones ()
```

### Browser Logs

![image](https://github.com/user-attachments/assets/44a28b89-385c-444a-97bb-d3b56f684fa2)

### Setting JSON

[comfy.settings.json](https://github.com/user-attachments/files/17713993/comfy.settings.json)

### What browsers do you use to access the UI ?

Google Chrome  130.0.6723.92（正式版本） (x86_64)

**Comment by huchenlei** [comment]
Cannot reproduce using the steps provided.

**Comment by tengshaofeng** [comment]
> Cannot reproduce using the steps provided.

So sad to hear that.

**Comment by SebastianLavertheDe** [comment]
![image](https://github.com/user-attachments/assets/d7f56b2b-cbbc-4dad-b5b7-9e7dad2cf1df)
 ComfyUI Version:  0.2.7
Me too
