### ISSUE TITLE
Workflow Manager: Display name of current workflow in title.

### ISSUE THREAD

**Issue by a-und-b** [Comfy-Org/ComfyUI_frontend#154]
It would be great if the name of the current workflow was visible in the browser tab.

Background: Due to my personal problems with time tracking, I somehow rely on an app that does it for me in the background by logging and categorizing what I do on my computer, based on the apps used and active browser tabs. 

Maybe this could be handy for some other ADHD folks, and could be generally handy when working in different tabs.

**Comment by mcmonkey4eva** [comment]
This was done, workflow is in the title on current version (v1.3)
