### ISSUE TITLE
[Bug]: Double-click on Note node title does not allow editing

### ISSUE THREAD

**Issue by alessandroperilli** [Comfy-Org/ComfyUI_frontend#1546]
### Frontend Version

1.3.44 (but it has been a bug since the feature was originally implemented)

### Expected Behavior

Double click on the Note node title would enable the edit mode for the title.

### Actual Behavior

Nothing happens

### Steps to Reproduce

Double click the title.

### Debug Logs

```powershell
Not relevant
```

### Browser Logs

None

### Setting JSON

Not relevant

### What browsers do you use to access the UI ?

Other

### Other

Vivaldi on macOS (but the problem is also with Safar)

**Comment by huchenlei** [comment]
Merged into https://github.com/Comfy-Org/ComfyUI_frontend/issues/1547
