### ISSUE TITLE
[Bug]: Title for new group cannot be edited right away

### ISSUE THREAD

**Issue by alessandroperilli** [Comfy-Org/ComfyUI_frontend#1547]
### Frontend Version

1.3.44 (but the bug has been there for some versions)

### Expected Behavior

Once a new group has been created, it's assigned the title `Group`. At this point, double-clicking on that title would enable the user to edit the title, as it normally happens with existing groups.

### Actual Behavior

Double-clicking on a newly created group enables the title edit UI, but nothing being typed appears on screen. It seems like the UI is stuck. The only way to move forward is press Return/Enter, and then type the new title you want. No visual cue appears once you press Enter/Return.

### Steps to Reproduce

1. Create a new group. 
2. Double-click on the title.
3. Try to type a new title. Nothing should appear on screen.
4. Press Return/Enter
5. Try to type a new title again. At this point, you should see the text changing.
6. Hit Return/Enter to save the new title.

### Debug Logs

```powershell
None relevant
```

### Browser Logs

None

### Setting JSON

None relevant

### What browsers do you use to access the UI ?

Other

### Other

Vivaldi on macOS, but it also happens with Safari.

┆Issue is synchronized with this [Notion page](https://www.notion.so/Bug-Title-for-new-group-cannot-be-edited-right-away-15b6d73d365081a0879ae465fd037999) by [Unito](https://www.unito.io)

**Comment by LukeG89** [comment]
I tried to reproduce your issue, but editing group title works fine to me.

The only problem I see is that when you create the group, the edit title dialog appears far from the Group.
You need to close the dialog to be able to double-click to edit the group title.

_**Edit:** There is a custom node that triggers the edit title dialog, it doesn't appear with all custom nodes disabled. Later I'll investigate._

_**Edit 2:** Found the culprit of my little issue: [rgthree-comfy](https://github.com/rgthree/rgthree-comfy). I opened a bug report there:_

- https://github.com/rgthree/rgthree-comfy/issues/372


https://github.com/user-attachments/assets/37722ef1-2271-4d16-be17-a4a657a3c9ad

**Comment by alessandroperilli** [comment]
I don't have that behavior at all. This is what happens to me (every time you see the cursor blink, it's me typing and being ignored):

https://github.com/user-attachments/assets/e635f920-9930-4ebb-b654-322ca119ca97

**Comment by LukeG89** [comment]
I think it's the same bug as this PR should have fixed (but for some reason you still have it):

- https://github.com/Comfy-Org/ComfyUI_frontend/pull/1430

**Comment by alessandroperilli** [comment]
It really seems like it, or at least connected to that.

**Comment by huchenlei** [comment]
Does it still happen with all custom nodes disabled?
