### ISSUE TITLE
[Bug]: Pinned node does not cover the node below

### ISSUE THREAD

**Issue by EasyComfyui** [Comfy-Org/ComfyUI_frontend#1548]
### Frontend Version

lastest

### Expected Behavior

Pinned node does not cover the node below

### Actual Behavior

https://github.com/user-attachments/assets/155846c4-9eb9-4ed9-a816-8387cfcb9c47

### Steps to Reproduce

.

### Debug Logs

```powershell
F:\demo\backup>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --front-end-version Comfy-Org/ComfyUI_frontend@latest --disable-all-custom-nodes
Total VRAM 24576 MB, total RAM 49088 MB
pytorch version: 2.4.1+cu124
xformers version: 0.0.28.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using xformers cross attention
Initializing frontend: Comfy-Org/ComfyUI_frontend@latest, requesting version details from GitHub...
[Prompt Server] web root: F:\demo\backup\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.3.44
Skipping loading of custom nodes
Starting server

To see the GUI go to: http://127.0.0.1:8188
```

### Browser Logs

.

### Setting JSON

.

### What browsers do you use to access the UI ?

Microsoft Edge

**Comment by webfiltered** [comment]
Is this a request to make pinning a node automatically send it behind other nodes?  For your uses, would you say it should immediately drop behind all nodes, or only unpinned nodes?

**Comment by EasyComfyui** [comment]
> Is this a request to make pinning a node automatically send it behind other nodes? For your uses, would you say it should immediately drop behind all nodes, or only unpinned nodes?

in previous versions, i used to pin buttons to hide the buttons i didn't want to show behind the pinned button. but since the update, when i pin a button, the hidden buttons are on top of the pinned button.

**Comment by webfiltered** [comment]
> in previous versions, i used to pin buttons to hide the buttons i didn't want to show behind the pinned button. but since the update, when i pin a button, the hidden buttons are on top of the pinned button.

Apologies, I'm not sure what you mean by pinning buttons to hide buttons.  If you happen to know the versions you updated from & to, that would assist.

**Comment by EasyComfyui** [comment]
> > in previous versions, i used to pin buttons to hide the buttons i didn't want to show behind the pinned button. but since the update, when i pin a button, the hidden buttons are on top of the pinned button.
> 
> Apologies, I'm not sure what you mean by pinning buttons to hide buttons. If you happen to know the versions you updated from & to, that would assist.

https://github.com/Comfy-Org/ComfyUI_frontend/issues/438#event-13912394338

**Comment by EasyComfyui** [comment]
https://github.com/Comfy-Org/litegraph.js/pull/76

it here
