### ISSUE TITLE
[Bug]:  [移动端问题] LoadImage 节点无法正常上传图像 (LoadImage Node Cannot Upload Images on Mobile Browsers)

### ISSUE THREAD

**Issue by xdtxkbf** [Comfy-Org/ComfyUI_frontend#1553]
### Frontend Version

The issue has persisted across all versions, including the latest version.

### Expected Behavior

希望在移动端浏览器（如 iPad 和 iPhone）中，LoadImage 节点的 "Choose File" 按钮能够像桌面端一样正常工作。
The "Choose File" button for the LoadImage node should function as expected on mobile browsers (e.g., iPad and iPhone), just like on desktop browsers.

### Actual Behavior

首先，感谢团队开发和维护了如此优秀的工具！ComfyUI 的强大功能让我受益良多，通过 --listen 在局域网内使用 Web UI 是我日常工作的重要场景。

然而，我发现一个长期存在的问题：
在桌面端（如 Windows PC）使用 LoadImage 节点时，可以通过 "Choose File" 按钮正常上传图像；但在移动端（如 iPad 和 iPhone）上，包括 Safari 和 Edge 等浏览器，该按钮无法正常工作，无法完成图像上传。这给移动端用户带来了不便。

First of all, thank you for developing and maintaining such an excellent tool! ComfyUI has been incredibly helpful for my workflow. Using the Web UI via --listen on a local network is one of my key use cases.

However, I have noticed a longstanding issue:
While the "Choose File" button works perfectly for the LoadImage node on desktop browsers (e.g., Windows PC), it does not function on mobile browsers (e.g., iPad or iPhone), including Safari and Edge. This makes it inconvenient for mobile users.

### Steps to Reproduce

1. 在运行 ComfyUI 的设备上启动 Web UI，并通过 `--listen` 开启局域网访问。  
   Start the ComfyUI Web UI on a host device and enable local network access using `--listen`.  
   
2. 在桌面端浏览器（例如 Windows PC）访问 Web UI，使用 LoadImage 节点，通过 "Choose File" 成功上传图像。  
   Access the Web UI from a desktop browser (e.g., Windows PC) and use the LoadImage node to successfully upload an image via the "Choose File" button.  
   
3. 在移动端（例如 iPad 或 iPhone）的浏览器（Safari 或 Edge）访问 Web UI，尝试使用 LoadImage 节点上传图像。  
   Access the Web UI from a mobile browser (e.g., Safari or Edge on iPad/iPhone) and try to upload an image using the LoadImage node.  
   
4. 观察到移动端无法通过 "Choose File" 按钮正常上传图像。  
   Observe that the "Choose File" button does not work for uploading images on mobile devices.  

### Debug Logs

```powershell
there is not any report
```

### Browser Logs

**Safari 和 iOS 版 Edge 似乎无法直接查看浏览器日志**  
**Safari and the iOS version of Edge seem unable to directly view browser logs.**

### Setting JSON

Default configuration

### What browsers do you use to access the UI ?

Apple Safari, Microsoft Edge, iOS

**Comment by huchenlei** [comment]
We probably won't prioritize the mobile experience for now.
