### ISSUE TITLE
[bug] No menu in 1.1.7

### ISSUE THREAD

**Issue by melMass** [Comfy-Org/ComfyUI_frontend#156]
Since the 1.1.7 update I can't seem to spawn the menu anymore.

Looking at the webconsole I get this on load:

<details><summary>traceback</summary>

```sh
ComfyUI Front-end version: 1.1.7 logging.ts:331:13
Failed to init Vue app TypeError: input is not iterable
    getNodeOptions nodeSearchService.ts:109
    getNodeOptions nodeSearchService.ts:108
    getAllNodeOptions nodeSearchService.ts:84
    getAllNodeOptions nodeSearchService.ts:83
    NodeFilter nodeSearchService.ts:77
    InputTypeFilter nodeSearchService.ts:97
    NodeSearchService nodeSearchService.ts:177
    init2 App.vue:41
    setup App.vue:55
    createHook runtime-core.esm-bundler.js:1808
    callWithErrorHandling runtime-core.esm-bundler.js:195
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:202
    __weh runtime-core.esm-bundler.js:1788
    flushPostFlushCbs runtime-core.esm-bundler.js:379
    render2 runtime-core.esm-bundler.js:5805
    mount runtime-core.esm-bundler.js:3062
    mount runtime-dom.esm-bundler.js:1530
    <anonymous> main.ts:23
logging.ts:331:13
    type logging.ts:331
    setup App.vue:57
    createHook runtime-core.esm-bundler.js:1808
    callWithErrorHandling runtime-core.esm-bundler.js:195
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:202
    __weh runtime-core.esm-bundler.js:1788
    flushPostFlushCbs runtime-core.esm-bundler.js:379
    render2 runtime-core.esm-bundler.js:5805
    mount runtime-core.esm-bundler.js:3062
    mount runtime-dom.esm-bundler.js:1530
    <anonymous> main.ts:23
```
</details>

Which traceback to this line on `input` deconstruction:
https://github.com/Comfy-Org/ComfyUI_frontend/blob/c2e7ef11ec822ee7bcc90b5e4892aaf691fb181f/src/services/nodeSearchService.ts#L109

**Comment by huchenlei** [comment]
I think this is some custom node not properly setting input value. I need to get the zod schema check on /obj_info up to guard against this situation.

**Comment by melMass** [comment]
Probably mine 😅 
In case it's useful here is my full list of extensions (not a lot):

```sh
websocket_image_save.py
cg-use-everywhere
ComfyUI-Advanced-ControlNet
ComfyUI-Frame-Interpolation
ComfyUI_IPAdapter_plus
efficiency-nodes-comfyui
ComfyUI-AnimateDiff-Evolved
comfyui_controlnet_aux
ComfyUI-Custom-Scripts
comfyui-liveportrait
ComfyUI-KJNodes
ComfyUI-VideoHelperSuite
ComfyUI-Flowty-TripoSR_fork
comfy_mtb
```

**Comment by huchenlei** [comment]
I think it's the mtb node.
![image](https://github.com/user-attachments/assets/3d62a51e-61de-4301-bc9d-0f858d28bb73)

I also need to look deeper into the code to see how "*" is handled.

**Comment by melMass** [comment]
> I also need to look deeper into the code to see how "*" is handled.

For inputs it was supported, not for outputs although to me [it worked fine](https://github.com/comfyanonymous/ComfyUI/pull/3329) too, and allows to take various types to the same input, a better thing would probably be some Union type to be able to say `("INT" | "FLOAT")`

**Comment by huchenlei** [comment]
I added the transform function to automatically convert `"*"` to `["*", {}]` now. An some other obvious illegal spec format fixes are PRed.
