### ISSUE TITLE
[Feature Request]: Why is the refresh button on the UI missing?

### ISSUE THREAD

**Issue by IAFFeng** [Comfy-Org/ComfyUI_frontend#1602]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Why is the refresh button on the UI missing?

### Proposed workflow

Why is the refresh button on the UI missing?

**Comment by LukeG89** [comment]
It has been moved to the Edit menu

![image](https://github.com/user-attachments/assets/3946d910-4f09-46d6-a1e6-f7efbc0a7842)
