### ISSUE TITLE
[Bug]: The front end does not respond to the combo widget left and right switching parameters

### ISSUE THREAD

**Issue by mijuku233** [Comfy-Org/ComfyUI_frontend#1603]
### Frontend Version

1.4.3

### Expected Behavior

The front end should correctly respond to the behavior of 'switching the parameters of the combo widget left and right'
![1344](https://github.com/user-attachments/assets/67d70404-c4ce-4f08-b986-91c31a13b047)

![143](https://github.com/user-attachments/assets/3f19655b-9296-4488-bfc0-d6bfc49e7ffc)

### Actual Behavior

The front end does not respond correctly to 'Switch combo widget parameters left and right', but 'Switch parameters with drop-down list' can be responded to correctly.
In fact, when #1389  was merged, I encountered this bug when I wrote code to test the new function.

>             const onWidgetChanged = nodeType.prototype.onWidgetChanged;
>             nodeType.prototype.onWidgetChanged = function () {
>                 onWidgetChanged?.apply(this, arguments);
>                 if (this.widgets[1].name === "convert_images") {
>                     this.widgets[0].advanced = true;
>                     if (this.widgets[1].value === "images"){
>                         this.showAdvanced = true;
>                     }
>                 }
>             };

> `convert_images` is a combo widget, and when it is switched to `images`, the advanced widget should be displayed. In fact, switching the parameters of the combo widget left and right has no effect, but switching to `images` through the drop-down list can make the advanced widget display normally.

But I just thought there was something wrong with my code, so I didn't care.
However, at some point, the problem reappeared on the vhs node, and I realized that this was a bug in the front end.

### Steps to Reproduce

.

### Debug Logs

```powershell
.
```

### Browser Logs

.

### Setting JSON

.

**Comment by huchenlei** [comment]
Issue confirmed reproducible.
