### ISSUE TITLE
[Bug]: Custom Keybindings are gone in version 1.4.4

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI_frontend#1612]
### Frontend Version

1.4.4

### Expected Behavior

All my custom keybindings are present.

![image](https://github.com/user-attachments/assets/137683c2-d77a-4647-917f-74d5149e7375)

### Actual Behavior

All my custom keybindings are gone.

![image](https://github.com/user-attachments/assets/906d997f-a237-4ffc-91d3-694240968c02)

### Steps to Reproduce

- Run ComfyUI with 1.4.4 frontend version
- Check Keybindings

### Debug Logs

```powershell
E:\>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --disable-all-custom-nodes --preview-size 1024 --front-end-version Comfy-Org/ComfyUI_frontend@latest
Total VRAM 8192 MB, total RAM 65277 MB
pytorch version: 2.6.0.dev20241115+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
Using pytorch cross attention
Initializing frontend: Comfy-Org/ComfyUI_frontend@latest, requesting version details from GitHub...
[Prompt Server] web root: E:\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.4.4
Skipping loading of custom nodes
Starting server

To see the GUI go to: http://127.0.0.1:8188
```

### Browser Logs

![image](https://github.com/user-attachments/assets/0d095013-92ce-479c-bd54-98cb7e2d82a3)

### Setting JSON

[comfy.settings.json](https://github.com/user-attachments/files/17831127/comfy.settings.json)

### What browsers do you use to access the UI ?

Google Chrome

### Other

Issue already mentioned here: https://github.com/Comfy-Org/ComfyUI_frontend/issues/1601#issuecomment-2488173606

**Comment by huchenlei** [comment]
Culprit reverted

**Comment by huchenlei** [comment]
We shall find a better way to migrate keybindings.

**Comment by TheToxin-git** [comment]
@LukeG89 Are they gone in 1.7.3 for you?

**Comment by LukeG89** [comment]
> @LukeG89 Are they gone in 1.7.3 for you?

@TheToxin-git Yep, they're gone... 

![image](https://github.com/user-attachments/assets/cc6140ea-e8db-432c-98e1-611410ea9194)

@huchenlei What happened?

**Comment by LukeG89** [comment]
Ok, I just saw they are about to fix it:
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/2176

**Edit:** Nevermind, the bug still persists in v1.7.4. Just opened a bug report here: https://github.com/Comfy-Org/ComfyUI_frontend/issues/2183
