### ISSUE TITLE
[Bug]: Searchbox doesn't show suggested nodes in version 1.4.4

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI_frontend#1613]
### Frontend Version

1.4.4

### Expected Behavior

Searchbox suggests the most frequently used nodes.

https://github.com/user-attachments/assets/a03b587b-3ef2-43bf-895e-7c4fdf15ec07

### Actual Behavior

Suggested nodes are not the most frequently used ones. It also doesn't show the node frequency.

![image](https://github.com/user-attachments/assets/3e9200fb-ed5d-4f74-a92a-bb4d4a7740ae)

https://github.com/user-attachments/assets/29ea58b7-8c87-48dd-b0d3-f17710956d68

### Steps to Reproduce

- Run ComfyUI with 1.4.4 frontend
- Release a link to open searchbox
- See the suggested nodes

### Debug Logs

```powershell
E:\>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --disable-all-custom-nodes --preview-size 1024 --front-end-version Comfy-Org/ComfyUI_frontend@latest
Total VRAM 8192 MB, total RAM 65277 MB
pytorch version: 2.6.0.dev20241115+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
Using pytorch cross attention
Initializing frontend: Comfy-Org/ComfyUI_frontend@latest, requesting version details from GitHub...
[Prompt Server] web root: E:\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.4.4
Skipping loading of custom nodes
Starting server

To see the GUI go to: http://127.0.0.1:8188
```

### Browser Logs

```console
Running on 127.0.0.1:8188
logging.ts:333 ComfyUI Front-end version: 1.4.4
Uncaught Error: NOT_REACHED
    at unsetKeybinding (keybindingStore.ts:234:11)
    at Proxy.loadUserKeybindings (keybindingStore.ts:259:23)
    at Proxy.wrappedAction (pinia.mjs:1405:26)
    at requestIdleCallback.timeout (GraphView.vue:152:28)
```

### Setting JSON

[comfy.settings.json](https://github.com/user-attachments/files/17831545/comfy.settings.json)

### What browsers do you use to access the UI ?

Google Chrome

**Comment by huchenlei** [comment]
I suspect it is related to https://github.com/Comfy-Org/ComfyUI_frontend/issues/1612. I cannot reproduce this locally. Please reopen if it still persists in v1.4.5.

**Comment by LukeG89** [comment]
That was it! Now it works well in 1.4.5
