### ISSUE TITLE
[Feature Request]: Electron feature being able 

### ISSUE THREAD

**Issue by yoland68** [Comfy-Org/ComfyUI_frontend#1623]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Support pasting into xterm for electron commands
Currently the pasting is blocked (due to litegraph keyhandling?)
![image](https://github.com/user-attachments/assets/5d35fe9e-ab9d-4d7c-a8f6-b18d5de71bd5)

### Proposed workflow

Click on CommandTerminal and being able to paste command into it

**Comment by webfiltered** [comment]
Does `Shift` + `Ins` work?  Terminal might need config to understand `Ctrl` + `V`.
