### ISSUE TITLE
[Feature Request]: Keybinding for "Fit Group To Nodes"

### ISSUE THREAD

**Issue by PrometheusDante** [Comfy-Org/ComfyUI_frontend#1631]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Having a keybinding option for the _"Fit Group To Nodes"_ function would be a helpful addition for me, as I use it all the time.

### Proposed workflow

-

### Additional information

Manually going through the process of right-clicking and selecting "Fit Group To Nodes" from the dropdown menu gets tedious when working with lots of groups and the nodes snap to the grid differently than the groups.

**Comment by brayevalerien** [comment]
+1

Additionally, having an (optional) way of making the group take the exact needed size for the nodes inside would be great. I'm thinking of something like what Blender node editor does.

**Comment by huchenlei** [comment]
@webfiltered Can you take a look? I am thinking a button to auto optimize group size on the canvas. However, that would require traverse the canvas object tree bottom up. I am not very sure such data structure is available right now.

**Comment by PrometheusDante** [comment]
@huchenlei Automatically adjusting groups might cause issues the moment a node is only temporarily in a place. 
For example when alt-duplicating a prompt input to keep as backup. The moment you let go of a node that crosses the group boundary it could escalate into encompassing a whole nother section of the workflow by itself.
![Untitled-1](https://github.com/user-attachments/assets/9de43786-5960-4f30-8372-e6eed0fc2161)
Or when opening collapsed nodes like in this case:
![Untitled-2](https://github.com/user-attachments/assets/2dd98f7a-d913-44c3-b611-a48fbc8be219)

**Comment by spiritparticle** [comment]
Additional to this since it is related to organization and nodes stuff. Is there an option instead of "Resize" that sort of shrinks down nodes to the same size. To have an option where a resize could be done where nodes all stretch to the size of the longest node or maybe if I select multiple nodes and resize one it will resize all selected nodes along with it? It would really help with my OCD.
