### ISSUE TITLE
[Bug]: Queue Tab Results preview up to 8 outputs only.

### ISSUE THREAD

**Issue by TheToxin-git** [Comfy-Org/ComfyUI_frontend#1639]
### Frontend Version

1.4.7. Pinpointed to 1.4.3+

![1732268077_912009355](https://github.com/user-attachments/assets/8656af1c-4ebd-4de5-bd9d-063ba22641e1)

### Expected Behavior

Queue Tab Results should preview all outputs. 

Under 1.4.2:

https://github.com/user-attachments/assets/972c2b53-3d97-4ddd-a58b-33bf77f9a695

### Actual Behavior

Queue Tab Results preview only 8 of it.

https://github.com/user-attachments/assets/c212a897-7cdb-4003-960d-ec40df1e5eb7

### Steps to Reproduce

1. Generate 9+ outputs 
2. Make sure you are using 1.4.3+ Frontend version
3. Open Queue tab and check results

Demonstration shown can be reproduced with this [workflow](https://github.com/user-attachments/files/17867798/QueueAmountTest.json) and [resources](https://github.com/user-attachments/files/17867854/numbers.zip) (unpack to ComfyUI/input/ folder)

### Debug Logs

```powershell
Total VRAM 11934 MB, total RAM 31885 MB
pytorch version: 2.5.1+cu124
xformers version: 0.0.28.post3
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
Using xformers cross attention
Initializing frontend: Comfy-Org/ComfyUI_frontend@latest, requesting version details from GitHub...
[Prompt Server] web root: /home/thetoxin/root/downloads/github/ComfyUI/web_custom_versions/Comfy-Org_ComfyUI_frontend/1.4.7
Skipping loading of custom nodes
Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
Prompt executed in 0.13 seconds
got prompt
Prompt executed in 0.02 seconds
```

### Browser Logs

Start-up:
```
unreachable code after return statement three.module.js:8173:11
load and start tracking of workflow workflows/QueueAmountTest.json workflowStore.ts:73:12
[workflowStore] open workflow workflows/QueueAmountTest.json workflowStore.ts:191:12
```

Execution: 
```
queued task 4e46e534-4924-434e-aeca-78ace17431cc with 18 nodes executionStore.ts:176:12
queued task a5992927-95dc-4f2c-94a2-6ee9385081bd with 21 nodes executionStore.ts:176:12
```

### Setting JSON

[comfy.settings.json](https://github.com/user-attachments/files/17867902/comfy.settings.json)
I believe settings are unrelated

### What browsers do you use to access the UI ?

Mozilla Firefox

### Other

Same behaviour with text output, so this is, probably, any output related.

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-1639-Bug-Queue-Tab-Results-preview-up-to-8-outputs-only-1656d73d365081839073c2afc5e0b6cc) by [Unito](https://www.unito.io)

**Comment by LukeG89** [comment]
I guess this is the culprit:
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/1586

**Comment by huchenlei** [comment]
@pythongosssss PTAL

**Comment by LukeG89** [comment]
I just noticed that the 8 outputs are not only inside the single task, but also in the global tasks


https://github.com/user-attachments/assets/7f5b261f-7c7e-41cf-a475-1a8bd95bc23a

**Comment by christian-byrne** [comment]
Is this the same issue? This is on 1.6.4



https://github.com/user-attachments/assets/f1c4166f-5df3-4d65-a872-889f20681125

**Comment by LukeG89** [comment]
> Is this the same issue? This is on 1.6.4

@christian-byrne Seems related, but previously was consistent. Now I see it happens occasionaly. Maybe it's caused by the memory leak fixng?
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/2012
