### ISSUE TITLE
[Bug]: Open MaskEditor But can not draw anything 

### ISSUE THREAD

**Issue by Hazukiaoi** [Comfy-Org/ComfyUI_frontend#1640]
### Frontend Version

ComfyUI Front-end version: 1.3.44

### Expected Behavior

right click Load Image Node and Open MaskEditor should be open a draw window and I can draw anything.

### Actual Behavior

when i right click Load Image Node and Open MaskEditor, the editor look like it:
<img width="359" alt="nc8Q2e3IFq" src="https://github.com/user-attachments/assets/fd308401-9572-40f8-be73-76f84c2f6d06">
<img width="721" alt="msedge_Txf6xx6GIa" src="https://github.com/user-attachments/assets/93cebed8-ac62-4840-a91e-e504d2bdf17b">
there have nothing and can't draw anything.

### Steps to Reproduce

1. add a Load Image Node, and select an image.
2. right click the node and Select [Open In MaskEditor]
I use the Flux Example workflow and disable all custoom node:
https://comfyanonymous.github.io/ComfyUI_examples/flux/

### Debug Logs

```powershell
nothing output in terminal
```

### Browser Logs

[192.168.31.104-1732268061208.log](https://github.com/user-attachments/files/17868080/192.168.31.104-1732268061208.log)

### Setting JSON

[comfy.settings.json](https://github.com/user-attachments/files/17868093/comfy.settings.json)

### What browsers do you use to access the UI ?

Microsoft Edge

**Comment by LukeG89** [comment]
Have you tried disabling your custom nodes with the `--disable-all-custom-nodes` argument?
There could be a conflict with one of them

**Comment by Hazukiaoi** [comment]
yes, i do it.
![image](https://github.com/user-attachments/assets/79ba8bb4-19da-4afd-9e9c-2c7cbd28036e)
![image](https://github.com/user-attachments/assets/fd08e708-28ea-4051-89bb-32d667ba6615)

**Comment by Hazukiaoi** [comment]
And Maybe you need my python environment version?
[pipVersion.txt](https://github.com/user-attachments/files/17868218/pipVersion.txt)

**Comment by LukeG89** [comment]
Just to try it: Could you use the latest frontend version using this argument? `--front-end-version Comfy-Org/ComfyUI_frontend@latest`

They recently implemented this new Mask Editor, it will be added in the next release on ComfyUI:
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/1284

**Comment by Hazukiaoi** [comment]
It work, Thanks!

**Comment by makisekurisu-jp** [comment]
The keyboard shortcuts in the mask editor are not working.
