### ISSUE TITLE
[Feature Request]: Option to enable confirmation when deleting a workflow

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI_frontend#1657]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

When you right-click on a workflow, you can easily click on "Delete" and the workflow is gone. 

It would be better to add a confirmation to avoid accidental deletion (like when you close an unsaved workflow)

### Proposed workflow

1. Right-click on workflow
2. Click "Delete"
3. A confirmation pops up

**Comment by TheToxin-git** [comment]
I would like to see this enhancement implemented as an option under **Settings > Comfy > Workflow**, with wording like "Require confirmation when deleting workflow" (similar to "Require confirmation when clearing workflow") and defaults to True / Yes.

![1732400961_134544420](https://github.com/user-attachments/assets/82313e38-47a5-4d41-a085-b2232ca4af7a)
