### ISSUE TITLE
[Feature Request]: Option to set the task limit in Queue window

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI_frontend#1660]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Besides this bug that is limiting to 8 https://github.com/Comfy-Org/ComfyUI_frontend/issues/1639, the tasks displayed in Queue tab is limited by default to 64.
I would like to overcome this limit.

Would it be possible to add an option in the Settings?

### Proposed workflow

It may be similar to the Queue Button option.
Default value: 64 (as it is now)

![queue-button](https://github.com/user-attachments/assets/ffbbdac8-80ff-4e96-ac0d-e8f272ba7437)

**Comment by huchenlei** [comment]
The major concern here is the performance. We don't have pagination in the backend API now so increasing the limit would mean that each update would require more processing. That was why the queue limit was fixed at 64 on the first place.

**Comment by LukeG89** [comment]
Yeah, I thought the limit was because of performance issues.
Having an option to decide the limit can be used both ways: users can reduce the number of tasks to improve performance. 

I would just add a tooltip to warn users that high values will have an impact on performance.

This option can be just considered as a temporary solution until something better is found (even a way to have no more limits).

@huchenlei What do you think?
