### ISSUE TITLE
[Bug]: Fit View button no longer has equivalent behavior as legacy Reset View

### ISSUE THREAD

**Issue by jujaga** [Comfy-Org/ComfyUI_frontend#1667]
### Frontend Version

v1.3.44

### Expected Behavior

The Fit View button on the new canvas menu used to have the same functional behavior as the legacy Reset View button.

### Actual Behavior

The Fit View button now contextually zooms based on the nodes selected. There is no equivalent Reset View button available in the new UI.

### Steps to Reproduce

Set UI to legacy menu > Click Reset View button - Canvas zooms to default zoom level and frame indicated by blue bounding box. (Desired Behaviour)
Set UI to new bar design > Click Fit View button - Canvas zooms based on nodes selected, or none. The legacy "Reset View" behaviour is no longer present for snapping back to the blue frame and zoom.

### Debug Logs

```powershell
N/A
```

### Browser Logs

N/A

### Setting JSON

[comfy.settings.json](https://github.com/user-attachments/files/17894710/comfy.settings.json)

### What browsers do you use to access the UI ?

Mozilla Firefox

### Other

Suggestion is to reintroduce the Reset View as a separate button from the Fit View button in the floating canvas menu so that both functionalities can be preserved and used.

**Comment by LukeG89** [comment]
If you want, you can add a shortcut to Reset View:

![image](https://github.com/user-attachments/assets/ceb33ac1-b7d9-4812-9aef-079e24bf0632)



Anyways, the blue bounding box has been removed:
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/1549

**Comment by jujaga** [comment]
Would it be possible to consider adding in a button to the floating canvas menu as a future toggleable option? I can see with the linked issues and PRs that this was done with good intentions, but as a user that does not usually use keyboard shortcuts to work with flows, it is an extremely jarring process to be relegated to using a keyboard shortcut for this. Thanks.
