### ISSUE TITLE
[Bug]: Save workflow 405(Method Not Allowed) When using Nginx reverse proxy

### ISSUE THREAD

**Issue by ashish-aesthisia** [Comfy-Org/ComfyUI_frontend#1677]
### Frontend Version

COMFYUI: v0.3.4

### Expected Behavior

When using a reverse proxy e.g. nginx, Save workflow should work, in previous version this issue was not there. 

### Actual Behavior

Here is the api that doesn't work:
`https://dev-ashishguptajiit-transfer-25052242.thinkdiffusion.xyz/api/userdata/workflows%2Ftest2102.json?overwrite=false&full_info=true`

This works
`https://dev-ashishguptajiit-transfer-25052242.thinkdiffusion.xyz/api/userdata/workflows_test2102.json?overwrite=false&full_info=true`

But when i replace %2F to something like _ underscore, it works fine. 

With Underscore
<img width="1003" alt="Screenshot 2024-11-25 at 11 43 22 AM" src="https://github.com/user-attachments/assets/47a4b586-9765-4969-b438-125a9392fec2">

Without replacement
<img width="1009" alt="Screenshot 2024-11-25 at 11 43 04 AM" src="https://github.com/user-attachments/assets/67a9f11f-ea8b-4986-8a87-ed681b210d36">

### Steps to Reproduce

- Setup nginx & run comfyui through proxy pass 

Here is my proxy pass configuration
```

location / {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection Upgrade;
    add_header Content-Security-Policy upgrade-insecure-requests;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://127.0.0.1:7860/;
    error_page  405     =200 $uri;
    error_page 502 /errorpage.html;
    error_page 404 /errorpage.html;
}
```

### Debug Logs

```powershell
NA
```

### Browser Logs

https://<host>/api/userdata/workflows%2Ftest2.json?overwrite=false&full_info=true 405 (Method Not Allowed)

### Setting JSON

```
{
    "Comfy.Settings.ExtensionPanel": false
}
```

### What browsers do you use to access the UI ?

Google Chrome

### Other

Please remove space from this api or replace this with underscore.

**Comment by imprsnst** [comment]
Removing slash from nginx proxy configuration works as suggested by Comfy team

from
`proxy_pass http://127.0.0.1:7860/;`
to
`proxy_pass http://127.0.0.1:7860;`

Thanks

**Comment by energy162** [comment]
Is there another solution for this question without changing the Nginx proxy configuration?

**Comment by Temikus** [comment]
@energy162 this needs to be merged: https://github.com/Comfy-Org/ComfyUI_frontend/pull/2182

**Comment by gg22mm** [comment]
```python

location ~* ^/comfyui/ {
        
        rewrite ^/comfyui/(.*) /$1 break;# 关键修复：路径重写
        
        proxy_pass http://localhost:8188;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400s;
    }

```

我的还是无效 http://www.diyyq.com/comfyui/
