### ISSUE TITLE
[Feature Request]: Unable to switch workflows on the browser, using shortcut keys, interface not controlled by mouse

### ISSUE THREAD

**Issue by yatoubusha** [Comfy-Org/ComfyUI_frontend#1694]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Unable to switch workflows on the browser, using shortcut keys, interface not controlled by mouse

### Proposed workflow

Unable to switch workflows on the browser, using shortcut keys, interface not controlled by mouse

### Additional information

Unable to switch workflows on the browser, using shortcut keys, interface not controlled by mouse

**Comment by LukeG89** [comment]
@yatoubusha Make sure everything is up-to-date (ComfyUI and all custom nodes). 

If you still have the problem, try disabling your nodes with `--disable-all-custom-nodes` argument and see if the problem is gone.
There might be an extension that is causing the issue.

**Comment by huchenlei** [comment]
Closing for insufficient information.
