### ISSUE TITLE
Slider not smoothing in lastest frontend

### ISSUE THREAD

**Issue by EasyComfyui** [Comfy-Org/ComfyUI_frontend#1696]
https://github.com/user-attachments/assets/afe7d234-e979-464b-8128-fea586efcc60

**Comment by LukeG89** [comment]
I can confirm, just tested with only [ComfyUI_essentials](https://github.com/cubiq/ComfyUI_essentials) enabled

From 1.4.3 version, slider widget has this problem (@webfiltered I guess another victim of Canvas Pointer API 😅 )
