### ISSUE TITLE
Search function sometimes doesn't work as intended to be for some nodes

### ISSUE THREAD

**Issue by kayselmecnun** [Comfy-Org/ComfyUI_frontend#174]
I'm facing this problem every time I use the "SDXL Empty Latent Size Picker" node.

Typing "latent s" brings the node, while typing any other letter returns no results such as "latent sdxl", "empty latent", "sdxl latent"

![chrome_zdjvsCYAJx](https://github.com/user-attachments/assets/a6ff2eab-1218-4382-b5f0-be8d06a08f9e)
![chrome_WLRXyufouW](https://github.com/user-attachments/assets/48d8b1d7-99f2-44a7-952d-16280e6c2894)

**Comment by kayselmecnun** [comment]
Update: With the latest v1.1.9, the search function works a bit differently. It doesn't act like the previous version and shows results. But the search function still doesn't act normally. See the examples below; The Goal is accessing the "SDXL Empty Latent Size Picker" node, when I type "SDXL Empty" it brings the correct node on top, but when I type "SDXL Laten", it brings unrelated results with my keywords on the top, and the node I'm looking is placed 8 scrolling below.
![chrome_y1NKNZ3KOL](https://github.com/user-attachments/assets/cf33ace9-c693-4c1d-8337-f16fbb9378cb)
![chrome_3ksoEPT0bQ](https://github.com/user-attachments/assets/d6df0d41-588d-4e1b-96e4-415cb2686c03)

**Comment by huchenlei** [comment]
The search impl comes from https://www.fusejs.io/. As far as I know it just performs string distance based fuzzy search, i.e. how many operations is required to convert one string to another. So SDXL Latent gets you Empty"SD3Latent"Image is expected.

I am not sure if we need to use a more powerful search provider if later we expand the search range to all sorts of things.

**Comment by huchenlei** [comment]
BTW, the theme of search box seem to be wrong. Can you share your browser console log, and screenshot? The searchbox theme should follow your ComfyUI theme.

**Comment by christian-byrne** [comment]
The field length norm might be too high. After using it a while, it does seem to give a lot lower weight to longer names

**Comment by huchenlei** [comment]
You can tune the fuse search params to try get better experience. It does offer option to weight down or disable field norm / location.
```
    this.nodeFuseSearch = new FuseSearch(data, {
      keys: ["display_name"],
      includeScore: true,
      threshold: 0.6,
      shouldSort: true,
      ignoreFieldNorm: true,
      ignoreLocation: true,
    });
```

**Comment by kayselmecnun** [comment]
> BTW, the theme of search box seem to be wrong. Can you share your browser console log, and screenshot? The searchbox theme should follow your ComfyUI theme.

![chrome_HaWi7jXdOx](https://github.com/user-attachments/assets/d06a690b-301f-4bf6-95c9-80a11200b2ef)
[127.0.0.1-1721639801108.log](https://github.com/user-attachments/files/16330870/127.0.0.1-1721639801108.log)

**Comment by SirVeggie** [comment]
The current search functionality should fix this issue, so this can probably be closed.
