### ISSUE TITLE
[Bug]: After the update, the export for the API does not save the node title.

### ISSUE THREAD

**Issue by berkut0** [Comfy-Org/ComfyUI_frontend#1752]
### Frontend Version

with the ```--front-end-version Comfy-Org/ComfyUI_frontend@latest``` command, the problem persists.
My guess is that the latest version is 1.5.3
also 3.5.0v "backend" https://github.com/comfyanonymous/ComfyUI/releases/tag/v0.3.5

### Expected Behavior

For example, if I save a workflow that has a CLIPTextEncoder and the title of the node is ‘POSITIVE’, I expect that title to be saved in JSON as in previous versions.

### Actual Behavior

For some reason, with the upgrade to the new version, the API stopped saving the title of the node. And now I can't select a specific node in JSON via title.

### Steps to Reproduce

Create a workflow, put any node (like CLIPTextEncoder), give it a name (and colour), save normally first, then export for API.

### Debug Logs

```json
{
  "1": {
    "inputs": {
      "text": ""
    },
    "class_type": "CLIPTextEncode"
  }
}
```

It used to look like this:

```json
{
  "1": {
    "inputs": {
      "text": ""
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "POSITIVE"
  }
}
```

### Browser Logs

none

### Setting JSON

not sure

**Comment by berkut0** [comment]
https://github.com/comfyanonymous/ComfyUI/issues/5850

**Comment by pythongosssss** [comment]
Do you have the Dev Mode setting enabled?

**Comment by berkut0** [comment]
@pythongosssss Yeah, I totally forgot about that.
But actually including metadata by default seems like the best option.

**Comment by bigcat88** [comment]
> But actually including metadata by default seems like the best option.

I agree, since now the button to export in API format is always available regardless of the `dev` mode, then why not save the `_meta` field by default?

**Comment by webfiltered** [comment]
Hi there, this issue is closed.  If you're having an issue, please open an issue and include a link to this one.
