### ISSUE TITLE
[Bug]: Canvas pan using middle-click does not work on DOM widgets

### ISSUE THREAD

**Issue by webfiltered** [Comfy-Org/ComfyUI_frontend#1773]
### Frontend Version

*

### Expected Behavior

Middle click and drag pans the canvas (unless intentionally blocked by overlay / modal).

### Actual Behavior

DOM elements intercept the middle click, and it never reaches the canvas.  Middle click and drag does nothing.

### Steps to Reproduce

Middle click DOM element and drag

### Debug Logs

```powershell
-
```

### Browser Logs

-

### Setting JSON

-

### What browsers do you use to access the UI ?

Google Chrome

┆Issue is synchronized with this [Notion page](https://www.notion.so/Bug-Canvas-pan-using-middle-click-does-not-work-on-DOM-widgets-15b6d73d365081ff855bd13051739e72) by [Unito](https://www.unito.io)

**Comment by LukeG89** [comment]
You can't even zoom in/out with scrollwheel on DOM widgets

**Comment by webfiltered** [comment]
That I believe was intentional - not great when the dom widgets have no scroll bar, but still.
