### ISSUE TITLE
[Bug]: Settings window can be opened multiple times

### ISSUE THREAD

**Issue by webfiltered** [Comfy-Org/ComfyUI_frontend#1781]
### Frontend Version

1.5.4

### Expected Behavior

Only one instance of the settings dialog can ever be open at once.

### Actual Behavior

Using the `Ctrl + ,` shortcut, multiple instances of settings can be opened.

### Steps to Reproduce

Video:
1. 6x `Ctrl + ,`
2. 2x Click overlay background
3. 1x `Escape`

https://github.com/user-attachments/assets/64e2a10a-c5b2-4344-8c79-1aeea1d5279e

### Debug Logs

```powershell
-
```

### Browser Logs

-

### Setting JSON

-

**Comment by huchenlei** [comment]
Related pr: https://github.com/Comfy-Org/ComfyUI_frontend/pull/1695

**Comment by huchenlei** [comment]
@hayden-fr Can you take a look?

**Comment by hayden-cn** [comment]
Maybe it's caused by multiple clicks in a short period of time or other reasons? The solution is to add a unique key when showDialog.

Because the some function is not complete yet, I haven't had time to add key ​​to the existing dialog. I think I can fix this defect now.

**Comment by webfiltered** [comment]
@hayden-fr If you're already on it, awesome!  Seems we thought the same:

> I think there was a recent change to add a dialog stack (which is great), but we probably need a "unique/dynamic" flag so things like settings can't be opened twice.  Move to top of stack instead.

**Comment by hayden-cn** [comment]
> I think there was a recent change to add a dialog stack (which is great), but we probably need a "unique/dynamic" flag so things like settings can't be opened twice. Move to top of stack instead.

This is the original functional design.

**Comment by hayden-cn** [comment]
Since I didn't consider opening the dialog through shortcut keys before, I postponed adding a key to the existing dialog and now add it.

I think there may be a lack of solution for managing unique keys to avoid duplication of them.
