### ISSUE TITLE
[Dev1.2][Known Issue] Top menu bar shifts up by 4px when first interacted with the litegraph canvas in Chromium

### ISSUE THREAD

**Issue by huchenlei** [Comfy-Org/ComfyUI_frontend#179]
https://github.com/user-attachments/assets/2942fc6d-e147-46aa-957c-bd0178a0bab2

The bug only happens on Chromium based browser. Firefox and safari does not have this issue.

**Comment by pythongosssss** [comment]
Try setting `overflow: hidden` on `#graph-canvas-container`

**Comment by huchenlei** [comment]
> Try setting `overflow: hidden` on `#graph-canvas-container`

Thanks! Setting overflow hidden works!
