### ISSUE TITLE
[Bug]: When you zoom a web page,The relative position of groups and nodes changes.

### ISSUE THREAD

**Issue by wencxxxxxx** [Comfy-Org/ComfyUI_frontend#1881]
### Frontend Version

comfyui version 1c8d11e 2014-12-10

### Expected Behavior

When you zoom a web page,The relative position of groups and nodes does not change.
![屏幕截图 2024-12-12 043035](https://github.com/user-attachments/assets/8db7bfbe-4bcd-456f-a208-59897476f406)

### Actual Behavior

 When you zoom a web page,The relative position of groups and nodes changes.
![屏幕截图 2024-12-12 043114](https://github.com/user-attachments/assets/f27240fa-892f-4ba2-8485-9dcc3ee79fbf)

### Steps to Reproduce

.

### Debug Logs

```powershell
.
```

### Browser Logs

.

### Setting JSON

.

**Comment by wencxxxxxx** [comment]
Edge browser

**Comment by LukeG89** [comment]
Have you tried upgrading all your nodes or disabling them with `--disable-all-custom-nodes` argument?
Seems like a bug caused by an extension

**Comment by huchenlei** [comment]
Cannot reproduce with clean install.
