### ISSUE TITLE
[Bug]: Settings menu is incompatible with small screens/viewports

### ISSUE THREAD

**Issue by SirVeggie** [Comfy-Org/ComfyUI_frontend#1895]
### Frontend Version

v1.5.12

### Expected Behavior

Settings can be changed even on small screens. Setting categories collapse into a burger menu or similar, while the settings themselves remain visible.

### Actual Behavior

![Screenshot_20241212_232650_Brave](https://github.com/user-attachments/assets/00244466-35e9-47e9-93b4-31eedd09f8c0)

### Steps to Reproduce

Resize browser window width until the settings popup collapses and hides the settings.

### Debug Logs

```powershell
-
```

### Browser Logs

-

### Setting JSON

-

### What browsers do you use to access the UI ?

Brave

┆Issue is synchronized with this [Notion page](https://www.notion.so/1895-Bug-Settings-menu-is-incompatible-with-small-screens-viewports-15b6d73d365081bd98aadf9279f015be) by [Unito](https://www.unito.io)

**Comment by EasyComfyui** [comment]
Have you tried disable all custom nodes?

**Comment by huchenlei** [comment]
> Have you tried disable all custom nodes?

This is confirmed to be a CSS issue that not caused by custom nodes.
