### ISSUE TITLE
[Feature Request]: When change locale language the ndoe rank got messed up

### ISSUE THREAD

**Issue by ycyy** [Comfy-Org/ComfyUI_frontend#1898]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

default
![PixPin_2024-12-13_13-48-04](https://github.com/user-attachments/assets/69d7d4e6-8c24-4d84-9efc-1dba940d7aa4)
chinese
![PixPin_2024-12-13_13-48-43](https://github.com/user-attachments/assets/8d57cab0-1003-41cc-8e66-4f34c9da1501)

### Proposed workflow

I think comfyui default nodes should be in one grouping and other third party nodes in another, regardless of language.

┆Issue is synchronized with this [Notion page](https://www.notion.so/Feature-Request-When-change-locale-language-the-ndoe-rank-got-messed-up-15b6d73d365081f49333dbdad82bc987) by [Unito](https://www.unito.io)

**Comment by huchenlei** [comment]
![Screenshot 2024-12-13 at 8 21 12 AM](https://github.com/user-attachments/assets/c999e366-528d-48eb-9bb1-d026eb1b4025)

That grouping feature is added by custom node. The sreenshot shows the menu without any custom node installd. Please file the issue in the custom node repo instead. Thanks!
