### ISSUE TITLE
[Bug]: Renamed input/output slots are reset on refresh

### ISSUE THREAD

**Issue by SirVeggie** [Comfy-Org/ComfyUI_frontend#1899]
### Frontend Version

tested v1.4.13 and v1.5.14, clean install no extensions (except manager)

### Expected Behavior

Renaming an input or output slot is persistent within the current workflow.

### Actual Behavior

Renamed slots are reset when the workflow is loaded. (refresh / load from saved workflows / load from image).
![image](https://github.com/user-attachments/assets/a28f87e4-ba9b-41cb-8ad7-8401f4616b89)
->
![image](https://github.com/user-attachments/assets/9289919e-08b7-44bc-8476-beefdcc53797)

### Steps to Reproduce

1. Spawn node
2. Rename a slot
3. Refresh
4. Slots are reset to their original values

### Debug Logs

```powershell
nothing
```

### Browser Logs

nothing

### Setting JSON

default settings (clean install)

### What browsers do you use to access the UI ?

Brave

┆Issue is synchronized with this [Notion page](https://www.notion.so/Bug-Renamed-input-output-slots-are-reset-on-refresh-15b6d73d3650816ea812ffdbba888bb8) by [Unito](https://www.unito.io)

**Comment by huchenlei** [comment]
Confirmed to be reproducible.
