### ISSUE TITLE
slider not show number 

### ISSUE THREAD

**Issue by EasyComfyui** [Comfy-Org/ComfyUI_frontend#1913]
old 
![image](https://github.com/user-attachments/assets/bf12aff7-710f-43e3-be7a-dd27f6e2ed1c)

new
![image](https://github.com/user-attachments/assets/681db91a-47ce-44c6-8c03-4d3fdc7cb571)
![image](https://github.com/user-attachments/assets/a67e593b-446e-4e76-91d9-ffb4190b77b3)

┆Issue is synchronized with this [Notion page](https://www.notion.so/1913-slider-not-show-number-15d6d73d36508157adc8df2122f3f440) by [Unito](https://www.unito.io)

**Comment by LukeG89** [comment]
Bug confirmed, the issue started in version 1.5.14
![slider_bug](https://github.com/user-attachments/assets/f63e9f9a-230a-4790-8e8b-e79252b8e5e3)

Version 1.5.13 is ok
![slider_ok](https://github.com/user-attachments/assets/a3dcdbab-99c4-4cf9-84d3-91bc48e7134d)

**Comment by huchenlei** [comment]
The issue actually happens between v1.5.12 and v1.5.13. The culprit is https://github.com/Comfy-Org/ComfyUI_frontend/pull/1883
