### ISSUE TITLE
[Feature Request]: [ Aesthetics  ] Match the "small" Sidebar to the Topbar dimensions

### ISSUE THREAD

**Issue by JorgeR81** [Comfy-Org/ComfyUI_frontend#1992]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

The "normal" Sidebar, it's to wide for me. 
I like the "small" Sidebar, but it's a bit too narrow.

I have a 27 inch, FHD monitor ( 1920 x 1080 )
The narrow sidebar has a 40 pixel width.
But the Top Bar it's 44 pixels high.

If we make the "small" Sidebar 44 pixels wide, it would look better and be more usable. 

I think "small" Sidebar had the same dimensions of the Topbar, when it was introduced. 
But then the Topbar got a little taller. I think it was because of the workflow tabs. 

---

**Small SideBar** ( current )

![z01](https://github.com/user-attachments/assets/3e7594d7-75ab-4e5b-a333-caa5d1d7464b)

**Mockup** ( same width as Topbar )

![z02](https://github.com/user-attachments/assets/f17bb91b-5ae7-4eee-bd0f-9873b3f095d6)

----

The "normal" Sidebar it's 64 pixels wide, so there is still plenty of difference between both options.

**Normal Sidebar:**

![z03](https://github.com/user-attachments/assets/019cc718-a673-4e7a-a1f5-fd16f4c34fa0)

### Proposed workflow

.

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-1992-Feature-Request-Aesthetics-Match-the-small-Sidebar-to-the-Topbar-dimensions-1616d73d3650815a801bc6a81591fdf0) by [Unito](https://www.unito.io)

**Comment by webfiltered** [comment]
Drag the "Queue" action bar off the top bar.  😄

**Comment by JorgeR81** [comment]
> Drag the "Queue" action bar off the top bar. 😄

Ah OK, so that's why the Topbar got taller !

---

Maybe a more consistent behaviour would be, for the Topbar to always be 44 pixel height, even without the "Queue" bar.

Or keep the Topbar to always at 40 pixels, and "trim" the "Queue" bar, a bit, when it's in there.

I think "Queue" button would look better if it had the same dimensions of the other buttons ( like before ), when it's added to the Topbar.
