### ISSUE TITLE
[Feature Request]: option to turn off workflow tabs

### ISSUE THREAD

**Issue by miurgh** [Comfy-Org/ComfyUI_frontend#2003]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Please implement an option to turn off workflow tabs.
I often drop workflows and images into my web browser, which causes more tabs on the front end to overwhelm the screen. Each time I do this, I delete the tabs.
The web browser is better at managing tabs.
Of course, we need tabs on ComfyUI desktop app.

### Proposed workflow

1. Go to ....
2. Press ....
3. ...

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-2003-Feature-Request-option-to-turn-off-workflow-tabs-1636d73d365081adb38af666895048ee) by [Unito](https://www.unito.io)

**Comment by LukeG89** [comment]
@miurgh You already can: Select `sidebar` in "Opened workflows position" option

![image](https://github.com/user-attachments/assets/33d1d07a-be81-47fe-bb9c-2668b7684d0b)

**Comment by miurgh** [comment]
Thank you. I was not aware of that.
