### ISSUE TITLE
[Feature Request]: Cut links between the nodes with a shortcut + gesture.

### ISSUE THREAD

**Issue by j-jasz** [Comfy-Org/ComfyUI_frontend#2018]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I'd like to propose a functionality for cutting links between the nodes with a shortcut + gesture combo.
I attached a short clip with how this works in Blender - holding Ctrl and RMB then dragging mouse over a link cuts it.
Our keybinding can be different but this should not be a problem as long as we can edit the bindings.

### Proposed workflow

1. In the viewport.
2. Press Ctrl and RMB then drag the cursor over an existing node link.
3. Link should be deleted.

### Additional information

https://github.com/user-attachments/assets/4bc74b3a-c675-4b62-9d33-a741299c7d74

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-2018-Feature-Request-Cut-links-between-the-nodes-with-a-shortcut-gesture-1646d73d3650813eb4d7f2a9c5d862db) by [Unito](https://www.unito.io)

**Comment by webfiltered** [comment]
Duplicate of https://github.com/Comfy-Org/ComfyUI_frontend/issues/4755
