### ISSUE TITLE
[Feature Request]: Add reroute on a node link with shortcut + gesture.

### ISSUE THREAD

**Issue by j-jasz** [Comfy-Org/ComfyUI_frontend#2019]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I'd like to propose a functionality for adding a reroute on a node link with a shortcut + gesture combo.
I attached a short clip with how this works in Blender - holding Shift and RMB then dragging mouse over a link adds a reroute where a link was crossed.
Our keybinding can be different but this should not be a problem as long as we can edit the bindings.

### Proposed workflow

1. In the viewport.
2. Press Ctrl and RMB then drag the cursor over an existing node link.
3. Reroute should be added on a link in a place where the cursor crossed it.

### Additional information

https://github.com/user-attachments/assets/bd9ff4bc-86f8-47d5-8615-649699998ace

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-2019-Feature-Request-Add-reroute-on-a-node-link-with-shortcut-gesture-1646d73d3650810287c5cac180772fc0) by [Unito](https://www.unito.io)

**Comment by webfiltered** [comment]
Duplicate of https://github.com/Comfy-Org/ComfyUI_frontend/issues/4755
