### ISSUE TITLE
[Bug]: Since version 1.4.3, it doesn't work that shift drag link to create a new link

### ISSUE THREAD

**Issue by lldacing** [Comfy-Org/ComfyUI_frontend#2048]
### Frontend Version

test 1.4.0 1.4.1 1.4.2 1.4.3 1.4.6 1.5.2 1.6.6
1.4.0 1.4.1 1.4.2 working
1.4.3 1.4.6 1.5.2 1.6.6 not woking

### Expected Behavior

hope same in the Readme
![image](https://github.com/user-attachments/assets/bd88d25b-e474-4f55-8a97-9a2831254a67)

### Actual Behavior

fail to new link

### Steps to Reproduce

 shift drag link 

### Debug Logs

```powershell
nothing
```

### Browser Logs

nothing

### Setting JSON

no need

### What browsers do you use to access the UI ?

Microsoft Edge

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-2048-Bug-Since-version-1-4-3-it-doesn-t-work-that-shift-drag-link-to-create-a-new-link-1676d73d36508168b512ff1f139f3d94) by [Unito](https://www.unito.io)

**Comment by LukeG89** [comment]
@lldacing I think you need to specify more information, since it's working (I'm on v1.6.6 and with all my nodes enabled):


https://github.com/user-attachments/assets/08b7cfea-2d53-4afd-8f47-f0190b793d71

Maybe there is a custom node that is causing the issue?

**Comment by lldacing** [comment]
> @lldacing I think you need to specify more information, since it's working (I'm on v1.6.6 and with all my nodes enabled):
> 
>  Shift+Drag.mp4 
> Maybe there is a custom node that is causing the issue?

It's not a custom node problem, I had disabled custom nodes.

I find the reason now. 
Before version 1.4.2, I can't create a new line on the line like you do, I can only drag at the end of the line. 
Now it only work on the link.

1.4.2
![image](https://github.com/user-attachments/assets/52dfb17c-9bfb-478a-999b-0770630aadfa)

![PixPin_2024-12-25_18-29-28](https://github.com/user-attachments/assets/1f055ee0-cb8b-4969-a2fc-d69de13bd228)

1.6.6
![image](https://github.com/user-attachments/assets/67f59e1c-8295-46e8-9997-4549273a96b2)
![PixPin_2024-12-25_18-33-10](https://github.com/user-attachments/assets/32b97299-8462-45ac-86ed-d7334885a425)

**Comment by LukeG89** [comment]
@lldacing Ah yes, there is a bug report in litegraph about that:
- https://github.com/Comfy-Org/litegraph.js/issues/375
