### ISSUE TITLE
Load Image displays the contents of deep subfolders

### ISSUE THREAD

**Issue by huchenlei** [Comfy-Org/ComfyUI_frontend#205]
https://github.com/comfyanonymous/ComfyUI/issues/4086

### Feature Idea

Hope that `Load Image` node can support the display of deep subfolder contents
![image](https://github.com/user-attachments/assets/30d247e2-ee65-417e-ab98-6f6dbec3ee7b)

**Comment by Amorano** [comment]
Not just sub-folders, but also be rooted anywhere I want via configuration. The outputs folder should not be locked inside the comfyui root and should be a part of the extra_paths configuration.

**Comment by mcmonkey4eva** [comment]
![image](https://github.com/user-attachments/assets/58b1a9b8-7170-48c8-9cef-fa271a806f1e)

It looks like the load image node already displays images in subfolders?

**Comment by LukeG89** [comment]
@mcmonkey4eva I still don't see subfolder images

![load_image](https://github.com/user-attachments/assets/814a5f98-f641-4dc2-8804-dc78ed48bc78)
![input_folder](https://github.com/user-attachments/assets/6b197878-1fc0-4a93-9fbd-3bf26f087f96)

**Comment by mcmonkey4eva** [comment]
That's... weird, why is it inconsistent? 0.o

Regardless, it's a core comfy issue rather than frontend - the relevant code function is https://github.com/comfyanonymous/ComfyUI/blob/master/nodes.py#L1543 which indeed has no subfolder listing capabilities (making me rather confused why it worked before? 0.o)

**Comment by LukeG89** [comment]
@mcmonkey4eva My real question is: Why is it still not a normal feature? 🤔 

Currently to easily browse subfolders I use `Load image with metadata` from [Crystools](https://github.com/crystian/ComfyUI-Crystools) and have all the subfolders well organized thanks to [rgthree](https://github.com/rgthree/rgthree-comfy)'s auto nest feature

![crystools_image_loader](https://github.com/user-attachments/assets/ed5b2259-3e85-45e8-bcc9-33e363b20566)
![rgthree_auto_nesting](https://github.com/user-attachments/assets/37d60011-5825-4bc9-bd5a-9dcbcc1f3154)
