### ISSUE TITLE
[Feature Request]: User setting to disable Combo box scaling

### ISSUE THREAD

**Issue by JorgeR81** [Comfy-Org/ComfyUI_frontend#2067]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

This would be an user setting to disable the scaling of the Combo box, when we zoom in the nodes graph. 

The Combo box scaling can be useful, if you have  a small screen. 

But for me, it's just an annoyance. 

I have a 27 inch monitor, FHD ( 1920 x 1080 )

When I scale the node's graph manually ( with the mousewheel ), if I zoom in a little too much, the combo box will be slightly upscaled.  
And this will result in a blurry combo box. 

The normal size combo box it's perfectly fine for me. I don't need it to be upscaled. 
I just get a worse quality, blurry image.

---

**upscaled combo box** 

![t1](https://github.com/user-attachments/assets/3b9a0531-0dfb-4ad2-bee7-4e87cd8b2029)

---

**normal size combo box**

![t2](https://github.com/user-attachments/assets/350a7c98-fd67-4104-ae21-bfe62aea4e05)

 

### Proposed workflow

.

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-2067-Feature-Request-User-setting-to-disable-Combo-box-scaling-1686d73d3650812ca97ef1fb5e3b71ed) by [Unito](https://www.unito.io)

**Comment by webfiltered** [comment]
Duplicate of #1798
