### ISSUE TITLE
Invoking the two search boxes by double-clicking

### ISSUE THREAD

**Issue by adbrasi** [Comfy-Org/ComfyUI_frontend#234]
![image](https://github.com/user-attachments/assets/d5d219d1-cd92-4395-ac98-8ac864ea69a5)

This bug makes it almost impossible to use the new frontend.
I have everything up to date, I've deactivated several custom nodes, but it's still there

nodes:
comfyui_controlnet_aux
ComfyUI-Manager
ComfyUI-Impact-Pack
Derfuu_ComfyUI_ModdedNodes
was-node-suite-comfyui
ComfyUI-Custom-Scripts
feidorian-ComfyNodes
ComfyUI_Comfyroll_CustomNodes
comfyui-art-venture
comfyui-prompt-control
mikey_nodes
ComfyUI-Eagle-PNGInfo
rgthree-comfy
comfyui-dream-project
ComfyUI_essentials
cg-image-picker
cg-use-everywhere
ComfyUI-KJNodes
ComfyUI-Crystools
ComfyUI-mape-Helpers
ComfyUI-JakeUpgrade
SaltAI
ComfyUI-QualityOfLifeSuit_Omar92
masquerade-nodes-comfyui
ComfyUI_Custom_Nodes_AlekPet
ComfyUI-Chibi-Nodes
ComfyUI_LayerStyle
ComfyUI-Gemini
ComfyUI-Universal-Styler
ComfyUI-Inspire-Pack
stability-ComfyUI-nodes
ComfyUI-Frame-Interpolation
ComfyUI_IPAdapter_plus
ComfyUI-AnimateDiff-Evolved
comfyui-portrait-master-zh-cn
ComfyUI-SUPIR
ComfyMath
comfyui-reactor-node
comfyui-mixlab-nodes
comfyui-portrait-master
efficiency-nodes-comfyui
ComfyUI_UltimateSDUpscale
ComfyUI_toyxyz_test_nodes
comfyui-inpaint-nodes
comfyui-browser
ComfyUI-VideoHelperSuite
anynode
ComfyUI-IF_AI_tools
ComfyUI-ArtGallery
comfy_mtb
ComfyUI_tinyterraNodes
ComfyUI_omost
ComfyUI_FizzNodes
ComfyUI_TiledKSampler
ComfyUI-ToonCrafter
ComfyUI-TiledDiffusion
comfyui-dynamicprompts
aegisflow_utility_nodes
Jovimetrix
ComfyUI-Florence2
ComfyUI-Inpaint-CropAndStitch
ComfyI2I
images-grid-comfy-plugin
ComfyUI_Fill-Nodes
ComfyUI-fastblend
comfyui-propost
DZ-FaceDetailer
ComfyUI-Logic
comfy-nodes
ComfyUI-N-Sidebar
ComfyUI-Image-Filters
ComfyUI_MaraScott_Nodes
cgem156-ComfyUI
ComfyUI_StoryDiffusion
comfyui_storydiffusion
ComfyUI_densediffusion
ComfyUI-Advanced-ControlNet
AuraSR-ComfyUI
trNodes
comfyui-common-util
virtuoso-nodes
ComfyUI-WD14-Tagger
ComfyUI-BiRefNet-ZHO
ComfyUI_YFG_Comical
ComfyUI_ezXY
ComfyUI_VLM_nodes
ComfyUI-YOLO
ComfyUI-LJNodes
ComfyUI_experiments
WAS_Extras
ComfyUI-xereca
comfy-easy-grids
ComfyUI-LogicUtils

**Comment by huchenlei** [comment]
It's not related to the custom node. Can you toggle this setting a few times to see if the issue is still there? 
![image](https://github.com/user-attachments/assets/0ded2ed9-cfc8-4c6b-b2d9-2e19cffdc4f3)

**Comment by huchenlei** [comment]
The setting management is completely refactored in https://github.com/Comfy-Org/ComfyUI_frontend/pull/202. Hopefully next release will fix this fundamentally.

**Comment by huchenlei** [comment]
Also, please try disable all custom nodes by adding `--disable-all-custom-nodes` flag to see if the problem is still there. Just to be sure.

**Comment by tuangd** [comment]
I got the same bug then tested mine with --disable-all-custom-nodes then the bug was gone.
So, it's one of the custom nodes.
I tested one at a time and find the culprit. It's **ComfyUI-LJNodes** after disable that custom node it works perfectly.
