### ISSUE TITLE
Queue panel becomes less responsive over time

### ISSUE THREAD

**Issue by christian-byrne** [Comfy-Org/ComfyUI_frontend#241]
After using the app for a while, if I have the queue panel open, I start to skip a lot of frames. 

![Selection_120](https://github.com/user-attachments/assets/002f3c19-db95-4a44-b74a-5ce5dd5ea4c3)

It seems to improve when I add a `max_items` arg to this call to `api.getHistory`. Can the `update` action be separated per task type?

https://github.com/Comfy-Org/ComfyUI_frontend/blob/980ed0083dd5c1d4230d1ad3cecb10a680a6d20b/src/stores/queueStore.ts#L177-L181

**Comment by huchenlei** [comment]
Hmmm, it's indeed an issue. I think the workaround for now is to reduce the max_items. But the fundamental solution would be make the update incremental instead every update we fetch the full history again.

**Comment by christian-byrne** [comment]
The overhead seems to come from the validation and class transformation instead of the fetching so maybe there can be reconciliation with the current state using an id, instead of validating and transforming the entire history every time.

**Comment by Amorano** [comment]
Is this related to the slowdown I see when rendering large batches? Over time the renders slowly add about 30% more overhead as they trigger the nodes running through the network.

I dont see these problems when sending everything though the API, so I assumed it came from frontend changes.

**Comment by christian-byrne** [comment]
All fixed by #393. Queue panel is very smooth now with large histories/batches.
