### ISSUE TITLE
Compatibility Issue: Help Mixlab - Some nodes may fail.

### ISSUE THREAD

**Issue by longgui0318** [Comfy-Org/ComfyUI_frontend#258]
When you right-click on a node in Mixlab, a help interface appears, popping up a window that explains the project. However, this functionality does not work with the [ComfyUI-ChatTTS](https://github.com/AIFSH/ComfyUI-ChatTTS) node.
![WX20240730-001637](https://github.com/user-attachments/assets/551df092-c6b4-48d9-a6be-457d969c4057)
![WX20240730-001722](https://github.com/user-attachments/assets/c5cbfa6a-c739-4ffb-912f-42ddc1f712aa)

This issue may also manifest another outcome, where the comfyui-manager badge functionality becomes inoperative.
![WX20240730-001955](https://github.com/user-attachments/assets/343895a4-3b4a-4f72-a85b-bbef64086ebe)

Uncertain if it's the same issue, a simple conjecture might be that there is a problem with the processing somewhere, resulting in the node being unable to locate its affiliated project.

**Comment by longgui0318** [comment]
At the same time, there may also be instances of corresponding disorder. It is uncertain whether this is an issue with other projects, as similar issues were not noticed before.
![WX20240730-002814](https://github.com/user-attachments/assets/7c0de0cd-8067-411c-8731-57709aa29d22)
![WX20240730-002905](https://github.com/user-attachments/assets/6788d869-489e-454a-b4ad-80c8132e68c2)
![WX20240730-002833](https://github.com/user-attachments/assets/e8878699-c4ff-4229-9fe0-a099b75cb544)

**Comment by huchenlei** [comment]
Please file the issue to the MixLab node / ComfyUI manager repo. Thanks!

**Comment by longgui0318** [comment]
Yes, I apologize for not paying attention to the situation before switching. It seems that this issue is related to the query method of custom_nodes. The ComfyUI manager is also in a state of being unable to resolve this problem.
