### ISSUE TITLE
defaultInput widget option isn't working

### ISSUE THREAD

**Issue by UrzasLegacy** [Comfy-Org/ComfyUI_frontend#276]
I dug around for quite a while and unfortunately couldn't figure this one out myself. forceInput is working properly, but defaultInput is not.

It seems that the widget options dictionary is not properly initializing with defaultInput as shown in this debug pic:

![defaultInputBug](https://github.com/user-attachments/assets/719d2fc0-51ad-41c9-8d69-ddbdad120e40)

**Comment by huchenlei** [comment]
Fixed in https://github.com/Comfy-Org/ComfyUI_frontend/pull/273

**Comment by UrzasLegacy** [comment]
oh dang, y'all fast! :)

**Comment by huchenlei** [comment]
> oh dang, y'all fast! :)

It was fixed before you asked. Jovix spot that issue yesterday. I just didn't get a chance to release it. 🙃
