### ISSUE TITLE
Can't Copy a Node

### ISSUE THREAD

**Issue by TyrianOtter** [Comfy-Org/ComfyUI_frontend#289]
CTRL+C won't copy the selected node.

Setting a breakpoint here:

https://github.com/Comfy-Org/ComfyUI_frontend/blob/244cd3c920139da45162cff5e6182368941baa9d/src/scripts/app.ts#L1160-L1164

then trying to copy a node results in only one break, for which `e.target` is  `div.graph-container-canvas`. Since it has no `.litegraph`, it skips the body of the if statement. Commenting out the check for `.litegraph` resolved the issue.

**Comment by huchenlei** [comment]
`litegraph` class exists on document body. Can you consistently reproduce it? What are reproduction steps?
https://github.com/Comfy-Org/ComfyUI_frontend/blob/244cd3c920139da45162cff5e6182368941baa9d/index.html#L25

**Comment by huchenlei** [comment]
BTW, we do have copy and paste browser test here:
https://github.com/Comfy-Org/ComfyUI_frontend/blob/main/browser_tests/copyPaste.spec.ts

So at least in the CI environment we are sure basic copy and paste is not broken.

**Comment by TyrianOtter** [comment]
Oh, it looks like it's related to the "[Beta] Use new menu and workflow management. Note: On small screens the menu will always be at the top." option. I can repro it as follows:

1) run `comfy --workspace $ws install`
2) run `comfy --workspace $ws launch -- --front-end-version Comfy-Org/ComfyUI_frontend@latest`
3) open ComfyUI in the browser
4) set the aforementioned "Use new menu..." setting to "Top".
5) Add any node.
6) Select the node.
7) Hit CTRL+C
8) Hit CTRL+V

The node will not be copy pasted.

Skipping step 4 results in it copying the node successfully, with `e.target` being `body.litegraph` in that case.

**Comment by christian-byrne** [comment]
Seems to only happen on firefox. Was able to reproduce there, didn't have to enable the new menu. Event target was `div.graph-container-canvas`

**Comment by TyrianOtter** [comment]
Not sure why I thought copy-paste worked without the new menu enabled because it's not working now. And yeah, I'm on Firefox; forgot to mention. An issue template to recommend some of the common stuff worth mentioning could be useful.

**Comment by huchenlei** [comment]
> Not sure why I thought copy-paste worked without the new menu enabled because it's not working now. And yeah, I'm on Firefox; forgot to mention. An issue template to recommend some of the common stuff worth mentioning could be useful.

Template added 1h ago https://github.com/Comfy-Org/ComfyUI_frontend/pull/290

**Comment by Amorano** [comment]
Copy-paste is pretty much a standard thing from 1990 -- so is this a priority bug? It is making it really hard to work in Firefox and I don't want to use an entire other browser just for Comfyui?
