### ISSUE TITLE
[Feature Request]: Ability to HIDE fields from Preview display

### ISSUE THREAD

**Issue by Amorano** [Comfy-Org/ComfyUI_frontend#309]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

![image](https://github.com/user-attachments/assets/fcc95760-6de5-449b-8259-5a7d37cc3b32)

It would add a meta attr to the field define to hide it from display in the preview box.

This would also go along to resolve issue #302 

### Proposed workflow

`
"VERTEX_PROGRAM": ("STRING", {"default": GLSLShader.PROG_VERTEX})
`
==>
`
"VERTEX_PROGRAM": ("STRING", {"default": GLSLShader.PROG_VERTEX, "hide": True})
`

**Comment by huchenlei** [comment]
Have you considered putting the metadata into `hidden`?

https://github.com/Comfy-Org/ComfyUI_frontend/blob/1b96c16cca55ac2f51be492eb1d0b79b9f1e0706/src/types/apiTypes.ts#L259-L261

**Comment by Amorano** [comment]
> Have you considered putting the metadata into `hidden`?
> 
> https://github.com/Comfy-Org/ComfyUI_frontend/blob/1b96c16cca55ac2f51be492eb1d0b79b9f1e0706/src/types/apiTypes.ts#L259-L261

Hidden is neato, but it literally removes the node from being seen, anywhere. The fields are still used as display on the node they just do not need to show their defaults as obnoxious as they do.

**Comment by Amorano** [comment]
![image](https://github.com/user-attachments/assets/b4609f43-9119-4c17-8d93-60c7859d8425)
![image](https://github.com/user-attachments/assets/d37626be-1ea6-4b68-9e70-698bfb349dd6)

hide from preview; still used.
