### ISSUE TITLE
[Bug]: ComfyUI workflow does not load - Only black screen appears

### ISSUE THREAD

**Issue by Scorpinaus** [Comfy-Org/ComfyUI_frontend#317]
### Frontend Version

1.2.10

### Expected Behavior

Upon start-up, it loads normally

### Actual Behavior

Upon start-up, the entire screen is a black-screen, where the workflow does not load upon start-up. See images below: 
![image](https://github.com/user-attachments/assets/f68e3ca3-671a-4789-9639-a6566eebbf85)
https://media.discordapp.net/attachments/1243610878314807337/1270173318808342703/image.png?ex=66b2bc95&is=66b16b15&hm=f5153b2f21059e120d9f2b287008bc9a9920519b541a3465576e8d757e2c6d16&=&format=webp&quality=lossless&width=720&height=305

### Steps to Reproduce

click on start_up

### Debug Logs

```powershell
Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\Users\Admin\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
```

### Browser Logs

NA

### What browsers do you use to access the UI ?

Mozilla Firefox

**Comment by huchenlei** [comment]
Please re-open with browser logs. Thanks!
