### ISSUE TITLE
[Bug]: ComfyUI workflow does not load - Only black screen appears

### ISSUE THREAD

**Issue by Scorpinaus** [Comfy-Org/ComfyUI_frontend#319]
### Frontend Version

1.2.11

### Expected Behavior

Upon start-up, it loads normally and load in a workflow

### Actual Behavior

Upon start-up, the entire screen is a black-screen, where the workflow does not load upon start-up. See images below:
![image](https://github.com/user-attachments/assets/149df686-f19f-4010-9fb3-8b1227200383)
![image](https://github.com/user-attachments/assets/e6fd6981-3c26-43fa-8a33-2cdb61ec2220)

### Steps to Reproduce

open comfyUI

### Debug Logs

```powershell
Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\Users\Admin\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
```

### Browser Logs

Loading failed for the <script> with source “http://127.0.0.1:8188/node_modules/reflect-metadata/Reflect.js”. [127.0.0.1:8188:15:275](http://127.0.0.1:8188/)
ComfyUI Front-end version: 1.2.11 [index.html:4:11](http://127.0.0.1:8188/index.html?html-proxy&index=0.js)
Error loading extension /extensions/canvas_tab/page/bspaint.js ReferenceError: feltTip is not defined
    <anonymous> http://127.0.0.1:8188/extensions/canvas_tab/page/bspaint.js:11
[app.ts:1749:20](http://127.0.0.1:8188/src/scripts/app.ts)
canvas_tab/web/page/main.js  - executing [main.js:1:9](http://127.0.0.1:8188/extensions/canvas_tab/page/main.js)
Error loading extension /extensions/canvas_tab/page/paintTools.js ReferenceError: circleBrush is not defined
    <anonymous> http://127.0.0.1:8188/extensions/canvas_tab/page/paintTools.js:185
[app.ts:1749:20](http://127.0.0.1:8188/src/scripts/app.ts)
Error loading extension /extensions/ComfyUI-Impact-Pack/impact-wildcard.js TypeError: refresh_btn2 is null
    <anonymous> http://127.0.0.1:8188/extensions/ComfyUI-Impact-Pack/impact-wildcard.js:14
[app.ts:1749:20](http://127.0.0.1:8188/src/scripts/app.ts)
init:canvas_tab [main.js:57:13](http://127.0.0.1:8188/extensions/canvas_tab/main.js)
Skipping invalid node definition: 0246.HighwayBatch. See debug log for more information. [api.ts:257:18](http://127.0.0.1:8188/src/scripts/api.ts)
Invalid ComfyNodeDef: {"input":{"required":{"_query":["STRING",{"default":">data; <data","multiline":false}]},"optional":{"_way_in":["HIGHWAY_PIPE"]},"hidden":{"_prompt":"PROMPT","_id":"UNIQUE_ID","_workflow":"EXTRA_PNGINFO"}},"output":["HIGHWAY_PIPE"],"output_is_list":{},"output_name":["_way_out"],"name":"0246.HighwayBatch","display_name":"Highway Batch","description":"","python_module":"custom_nodes.ComfyUI-0246","category":"0246","output_node":false}
Validation error: Expected array, received object at "output_is_list" [api.ts:260:18](http://127.0.0.1:8188/src/scripts/api.ts)
Skipping invalid node definition: 0246.BoxRange. See debug log for more information. [api.ts:257:18](http://127.0.0.1:8188/src/scripts/api.ts)
Invalid ComfyNodeDef: {"input":{"required":{"script_box_regex":["STRING",{"default":"(?P<x>^x$)|(?P<y>^y$)|(?P<w>^width$)|(?P<h>^height$)|(^@x$)|(^@y$)|(^@w$)|(^@h$)|(^%x$)|(^%y$)|(^%w$)|(^%h$)","multiline":false}],"script_order":["STRING",{"default":"box","multiline":false}],"box_range":["BOX_RANGE",{"ratio":{"data":{"width":512,"height":512}},"row_count":10,"col_count":10,"flex":{"share":1,"min_h":50,"center":true}}]},"hidden":{"_id":"UNIQUE_ID"}},"output":["*"],"output_is_list":{},"output_name":["_data"],"name":"0246.BoxRange","display_name":"Box Range","description":"","python_module":"custom_nodes.ComfyUI-0246","category":"0246","output_node":false}
Validation error: Expected array, received object at "output_is_list" [api.ts:260:18](http://127.0.0.1:8188/src/scripts/api.ts)
Skipping invalid node definition: 0246.ScriptNode. See debug log for more information. [api.ts:257:18](http://127.0.0.1:8188/src/scripts/api.ts)
Invalid ComfyNodeDef: {"input":{"required":{"script_node":[["KSampler","CheckpointLoaderSimple","CLIPTextEncode","CLIPSetLastLayer","VAEDecode","VAEEncode","VAEEncodeForInpaint","VAELoader","EmptyLatentImage","LatentUpscale","LatentUpscaleBy","LatentFromBatch","RepeatLatentBatch","SaveImage","PreviewImage","LoadImage","LoadImageMask","ImageScale","ImageScaleBy","ImageInvert","ImageBatch","ImagePadForOutpaint","EmptyImage","ConditioningAverage","ConditioningCombine","ConditioningConcat","ConditioningSetArea","ConditioningSetAreaPercentage","ConditioningSetAreaStrength","ConditioningSetMask","KSamplerAdvanced","SetLatentNoiseMask","LatentComposite","LatentBlend","LatentRotate","LatentFlip","LatentCrop","LoraLoader","CLIPLoader","UNETLoader","DualCLIPLoader","CLIPVisionEncode","StyleModelApply","unCLIPConditioning","ControlNetApply","ControlNetApplyAdvanced","ControlNetLoader","DiffControlNetLoader","StyleModelLoader","CLIPVisionLoader","VAEDecodeTiled","VAEEncodeTiled","unCLIPCheckpointL…
[api.ts:260:18](http://127.0.0.1:8188/src/scripts/api.ts)
Skipping invalid node definition: 0246.Script. See debug log for more information. [api.ts:257:18](http://127.0.0.1:8188/src/scripts/api.ts)
Invalid ComfyNodeDef: {"input":{"required":{"_exec_mode":[["pass","act"]],"_sort_mode":["STRING",{"default":"INT","multiline":false}]},"optional":{"_script_in":["SCRIPT_PIPE"]},"hidden":{"_prompt":"PROMPT","_id":"UNIQUE_ID","_workflow":"EXTRA_PNGINFO"}},"output":["SCRIPT_PIPE"],"output_is_list":{},"output_name":["_script_out"],"name":"0246.Script","display_name":"Script","description":"","python_module":"custom_nodes.ComfyUI-0246","category":"0246","output_node":false}
Validation error: Expected array, received object at "output_is_list" [api.ts:260:18](http://127.0.0.1:8188/src/scripts/api.ts)
Skipping invalid node definition: 0246.Hub. See debug log for more information. [api.ts:257:18](http://127.0.0.1:8188/src/scripts/api.ts)
Invalid ComfyNodeDef: {"input":{"required":{},"hidden":{"_prompt":"PROMPT","_id":"UNIQUE_ID","_workflow":"EXTRA_PNGINFO"}},"output":{},"output_is_list":{},"output_name":{},"name":"0246.Hub","display_name":"Hub","description":"","python_module":"custom_nodes.ComfyUI-0246","category":"0246","output_node":false}
Validation error: Expected array, received object at "output"; Expected array, received object at "output_is_list"; Expected array, received object at "output_name" [api.ts:260:18](http://127.0.0.1:8188/src/scripts/api.ts)
Skipping invalid node definition: 0246.Cloud. See debug log for more information. [api.ts:257:18](http://127.0.0.1:8188/src/scripts/api.ts)
Invalid ComfyNodeDef: {"input":{"required":{},"optional":{"cloud":["CLOUD_DATA"]},"hidden":{"_prompt":"PROMPT","_id":"UNIQUE_ID","_workflow":"EXTRA_PNGINFO"}},"output":["CLOUD_PIPE"],"output_is_list":{},"output_name":["_cloud_out"],"name":"0246.Cloud","display_name":"Cloud","description":"","python_module":"custom_nodes.ComfyUI-0246","category":"0246","output_node":false}
Validation error: Expected array, received object at "output_is_list" [api.ts:260:18](http://127.0.0.1:8188/src/scripts/api.ts)
Skipping invalid node definition: 0246.Switch. See debug log for more information. [api.ts:257:18](http://127.0.0.1:8188/src/scripts/api.ts)
Invalid ComfyNodeDef: {"input":{"required":{},"hidden":{"_id":"UNIQUE_ID","_prompt":"PROMPT","_workflow":"EXTRA_PNGINFO"}},"output":{},"output_is_list":{},"output_name":{},"name":"0246.Switch","display_name":"Switch","description":"","python_module":"custom_nodes.ComfyUI-0246","category":"0246","output_node":false}
Validation error: Expected array, received object at "output"; Expected array, received object at "output_is_list"; Expected array, received object at "output_name" [api.ts:260:18](http://127.0.0.1:8188/src/scripts/api.ts)
Skipping invalid node definition: 0246.Meta. See debug log for more information. [api.ts:257:18](http://127.0.0.1:8188/src/scripts/api.ts)
Invalid ComfyNodeDef: {"input":{"required":{},"optional":{"data":["*"]},"hidden":{"_prompt":"PROMPT","_id":"UNIQUE_ID","_workflow":"EXTRA_PNGINFO"}},"output":["INT","INT","STRING","STRING","STRING","STRING"],"output_is_list":{},"output_name":["batch_size","data_size","key_list","type_list","comfy_type","py_type"],"name":"0246.Meta","display_name":"Meta","description":"","python_module":"custom_nodes.ComfyUI-0246","category":"0246","output_node":false}
Validation error: Expected array, received object at "output_is_list" [api.ts:260:18](http://127.0.0.1:8188/src/scripts/api.ts)
Skipping invalid node definition: Automatic CFG - Attention modifiers. See debug log for more information. [api.ts:257:18](http://127.0.0.1:8188/src/scripts/api.ts)
Invalid ComfyNodeDef: {"input":{"required":{"sigma_start":["FLOAT",{"default":1000,"min":0,"max":10000,"step":0.1,"round":0.01}],"sigma_end":["FLOAT",{"default":0,"min":0,"max":10000,"step":0.1,"round":0.01}],"self_attn_mod_eval":["STRING",{"multiline":true},{"default":""}],"unet_block_id_input":["STRING",{"multiline":false},{"default":""}],"unet_block_id_middle":["STRING",{"multiline":false},{"default":""}],"unet_block_id_output":["STRING",{"multiline":false},{"default":""}],"unet_attn":[["attn1","attn2","both"]]},"optional":{"join_parameters":["ATTNMOD",{"forceInput":true}]}},"output":["ATTNMOD","STRING"],"output_is_list":[false,false],"output_name":["Attention modifier","Parameters as string"],"name":"Automatic CFG - Attention modifiers","display_name":"Automatic CFG - Attention modifiers","description":"","python_module":"custom_nodes.ComfyUI-AutomaticCFG","category":"model_patches/Automatic_CFG/experimental_attention_modifiers","output_node":false}
Validation error: Array must contain at most 2 element(s) at "input.required.self_attn_mod_eval"; Array must contain at most 2 element(s) at "input.required.unet_block_id_input"; Array must contain at most 2 element(s) at "input.required.unet_block_id_middle"; Array must contain at most 2 element(s) at "input.required.unet_block_id_output" [api.ts:260:18](http://127.0.0.1:8188/src/scripts/api.ts)
Skipping invalid node definition: PixelSort. See debug log for more information. [api.ts:257:18](http://127.0.0.1:8188/src/scripts/api.ts)
Invalid ComfyNodeDef: {"input":{"required":{"image":["IMAGE"],"mask":["IMAGE"],"direction":[["horizontal","vertical"]],"span_limit":["INT",{"default":null,"min":0,"max":100,"step":5}],"sort_by":[["hue","saturation","value"]],"order":[["forward","backward"]]}},"output":["IMAGE"],"output_is_list":[false],"output_name":["IMAGE"],"name":"PixelSort","display_name":"PixelSort","description":"","python_module":"custom_nodes.ComfyUI-post-processing-nodes","category":"postprocessing/Effects","output_node":false}
Validation error: Array must contain at most 1 element(s) at "input.required.span_limit" [api.ts:260:18](http://127.0.0.1:8188/src/scripts/api.ts)
Skipping invalid node definition: ttN conditioning. See debug log for more information. [api.ts:257:18](http://127.0.0.1:8188/src/scripts/api.ts)
Invalid ComfyNodeDef: {"input":{"required":{"model":["MODEL"],"clip":["CLIP"],"loras":["STRING",{"placeholder":"<lora:loraName:weight:optClipWeight>","multiline":true}],"positive":["STRING",{"default":"Positive","multiline":true,"dynamicPrompts":true}],"positive_token_normalization":[["none","mean","length","length+mean"]],"positive_weight_interpretation":[["comfy","A1111","compel","comfy++","down_weight"]],"negative":["STRING",{"default":"Negative","multiline":true,"dynamicPrompts":true}],"negative_token_normalization":[["none","mean","length","length+mean"]],"negative_weight_interpretation":[["comfy","A1111","compel","comfy++","down_weight"]]},"optional":{"optional_lora_stack":["LORA_STACK"],"prepend_positive":["STRING",{"default":null,"forceInput":true}],"prepend_negative":["STRING",{"default":null,"forceInput":true}]},"hidden":{"ttNnodeVersion":"1.0.0","my_unique_id":"UNIQUE_ID"}},"output":["MODEL","CONDITIONING","CONDITIONING","CLIP","STRING","STRING"],"output_is_list":[false,false,false,false,false,false],"output_name":["model","positive","negative","clip","pos_string","neg_string"],"name":"ttN conditioning","display_name":"tinyConditioning","description":"","python_module":"custom_nodes.ComfyUI_tinyterraNodes","category":"🌏 tinyterra/base","output_node":false}
Validation error: Array must contain at most 1 element(s) at "input.optional.prepend_positive"; Array must contain at most 1 element(s) at "input.optional.prepend_negative" [api.ts:260:18](http://127.0.0.1:8188/src/scripts/api.ts)
Skipping invalid node definition: ttN pipeLoader_v2. See debug log for more information. [api.ts:257:18](http://127.0.0.1:8188/src/scripts/api.ts)
Invalid ComfyNodeDef: {"input":{"required":{"ckpt_name":[["sd3_medium.safetensors","svd_xt_1_1.safetensors"]],"config_name":[["Default","anything_v3.yaml","v1-inference.yaml","v1-inference_clip_skip_2.yaml","v1-inference_clip_skip_2_fp16.yaml","v1-inference_fp16.yaml","v1-inpainting-inference.yaml","v2-inference-v.yaml","v2-inference-v_fp32.yaml","v2-inference.yaml","v2-inference_fp32.yaml","v2-inpainting-inference.yaml"],{"default":"Default"}],"vae_name":[["Baked VAE","ae.sft","apricotsVAESeries_apricotsQuantizerV10.safetensors","apricotsVAESeries_apricotsVaeV10.safetensors","apricotsVAESeries_tensorQuantizerV10.safetensors"]],"clip_skip":["INT",{"default":-1,"min":-24,"max":0,"step":1}],"loras":["STRING",{"placeholder":"<lora:loraName:weight:optClipWeight>","multiline":true}],"positive":["STRING",{"default":"Positive","multiline":true,"dynamicPrompts":true}],"positive_token_normalization":[["none","mean","length","length+mean"]],"positive_weight_interpretation":[["comfy","A1111","compel","comfy++","down_weight"]],"negative":["STRING",{"default":"Negative","multiline":true,"dynamicPrompts":true}],"negative_token_normalization":[["none","mean","length","length+mean"]],"negative_weight_interpretation":[["comfy","A1111","compel","comfy++","down_weight"]],"empty_latent_aspect":[["width x height [custom]","512 x 512 [S] 1:1","768 x 768 [S] 1:1","910 x 910 [S] 1:1","512 x 682 [P] 3:4","512 x 768 [P] 2:3","512 x 910 [P] 9:16","682 x 512 [L] 4:3","768 x 512 [L] 3:2","910 x 512 [L] 16:9","512 x 1024 [P] 1:2","1024 x 512 [L] 2:1","1024 x 1024 [S] 1:1"],{"default":"512 x 512 [S] 1:1"}],"empty_latent_width":["INT",{"default":512,"min":64,"max":16384,"step":8}],"empty_latent_height":["INT",{"default":512,"min":64,"max":16384,"step":8}],"batch_size":["INT",{"default":1,"min":1,"max":64}],"seed":["INT",{"default":0,"min":0,"max":18446744073709552000}]},"optional":{"model_override":["MODEL"],"clip_override":["CLIP"],"optional_lora_stack":["LORA_STACK"],"optional_controlnet_stack":["CONTROL_NET_STACK"],"prepend_positive":["STRING",{"default":null,"forceInput":true}],"prepend_negative":["STRING",{"default":null,"forceInput":true}]},"hidden":{"prompt":"PROMPT","ttNnodeVersion":"2.1.0","my_unique_id":"UNIQUE_ID"}},"output":["PIPE_LINE","MODEL","CONDITIONING","CONDITIONING","LATENT","VAE","CLIP","INT","INT","INT","STRING","STRING"],"output_is_list":[false,false,false,false,false,false,false,false,false,false,false,false],"output_name":["pipe","model","positive","negative","latent","vae","clip","seed","width","height","pos_string","neg_string"],"name":"ttN pipeLoader_v2","display_name":"pipeLoader","description":"","python_module":"custom_nodes.ComfyUI_tinyterraNodes","category":"🌏 tinyterra/pipe","output_node":false}
Validation error: Array must contain at most 1 element(s) at "input.optional.prepend_positive"; Array must contain at most 1 element(s) at "input.optional.prepend_negative" [api.ts:260:18](http://127.0.0.1:8188/src/scripts/api.ts)
Skipping invalid node definition: ttN pipeLoaderSDXL_v2. See debug log for more information. [api.ts:257:18](http://127.0.0.1:8188/src/scripts/api.ts)
Invalid ComfyNodeDef: {"input":{"required":{"ckpt_name":[["sd3_medium.safetensors","svd_xt_1_1.safetensors"]],"config_name":[["Default","anything_v3.yaml","v1-inference.yaml","v1-inference_clip_skip_2.yaml","v1-inference_clip_skip_2_fp16.yaml","v1-inference_fp16.yaml","v1-inpainting-inference.yaml","v2-inference-v.yaml","v2-inference-v_fp32.yaml","v2-inference.yaml","v2-inference_fp32.yaml","v2-inpainting-inference.yaml"],{"default":"Default"}],"vae_name":[["Baked VAE","ae.sft","apricotsVAESeries_apricotsQuantizerV10.safetensors","apricotsVAESeries_apricotsVaeV10.safetensors","apricotsVAESeries_tensorQuantizerV10.safetensors"]],"clip_skip":["INT",{"default":-2,"min":-24,"max":0,"step":1}],"loras":["STRING",{"placeholder":"Loras - <lora:loraName:weight:optClipWeight>","multiline":true}],"refiner_ckpt_name":[["None","sd3_medium.safetensors","svd_xt_1_1.safetensors"]],"refiner_config_name":[["Default","anything_v3.yaml","v1-inference.yaml","v1-inference_clip_skip_2.yaml","v1-inference_clip_skip_2_fp16.yaml","v1-inference_fp16.yaml","v1-inpainting-inference.yaml","v2-inference-v.yaml","v2-inference-v_fp32.yaml","v2-inference.yaml","v2-inference_fp32.yaml","v2-inpainting-inference.yaml"],{"default":"Default"}],"positive_g":["STRING",{"placeholder":"Linguistic Positive (positive_g)","multiline":true,"dynamicPrompts":true}],"positive_l":["STRING",{"placeholder":"Supporting Terms (positive_l)","multiline":true,"dynamicPrompts":true}],"negative_g":["STRING",{"placeholder":"negative_g","multiline":true,"dynamicPrompts":true}],"negative_l":["STRING",{"placeholder":"negative_l","multiline":true,"dynamicPrompts":true}],"conditioning_aspect":[["width x height [custom]","1x Empty Latent Aspect","2x Empty Latent Aspect","3x Empty Latent Aspect","4x Empty Latent Aspect","5x Empty Latent Aspect","6x Empty Latent ASpect","7x Empty Latent Aspect","8x Empty Latent Aspect"],{"default":"1x Empty Latent Aspect"}],"conditioning_width":["INT",{"default":2048,"min":64,"max":16384,"step":8}],"conditioning_height":["INT",{"default":2048,"min":64,"max":16384,"step":8}],"crop_width":["INT",{"default":0,"min":0,"max":16384}],"crop_height":["INT",{"default":0,"min":0,"max":16384}],"target_aspect":[["width x height [custom]","1x Empty Latent Aspect","2x Empty Latent Aspect","3x Empty Latent Aspect","4x Empty Latent Aspect","5x Empty Latent Aspect","6x Empty Latent ASpect","7x Empty Latent Aspect","8x Empty Latent Aspect"],{"default":"1x Empty Latent Aspect"}],"target_width":["INT",{"default":1024,"min":0,"max":16384}],"target_height":["INT",{"default":1024,"min":0,"max":16384}],"positive_ascore":["INT",{"default":6,"min":0,"step":0.1}],"negative_ascore":["INT",{"default":2,"min":0,"step":0.1}],"empty_latent_aspect":[["width x height [custom]","1024 x 1024 [S] 1:1","640 x 1536 [P] 9:21","704 x 1472 [P] 9:19","768 x 1344 [P] 9:16","768 x 1216 [P] 5:8","832 x 1216 [P] 2:3","896 x 1152 [P] 3:4","1536 x 640 [L] 21:9","1472 x 704 [L] 19:9","1344 x 768 [L] 16:9","1216 x 768 [L] 8:5","1216 x 832 [L] 3:2","1152 x 896 [L] 4:3"],{"default":"1024 x 1024 [S] 1:1"}],"empty_latent_width":["INT",{"default":1024,"min":64,"max":16384,"step":8}],"empty_latent_height":["INT",{"default":1024,"min":64,"max":16384,"step":8}],"batch_size":["INT",{"default":1,"min":1,"max":64}],"seed":["INT",{"default":0,"min":0,"max":18446744073709552000}]},"optional":{"model_override":["MODEL"],"clip_override":["CLIP"],"optional_lora_stack":["LORA_STACK"],"optional_controlnet_stack":["CONTROL_NET_STACK"],"refiner_model_override":["MODEL"],"refiner_clip_override":["CLIP"],"prepend_positive_g":["STRING",{"default":null,"forceInput":true}],"prepend_positive_l":["STRING",{"default":null,"forceInput":true}],"prepend_negative_g":["STRING",{"default":null,"forceInput":true}],"prepend_negative_l":["STRING",{"default":null,"forceInput":true}]},"hidden":{"prompt":"PROMPT","ttNnodeVersion":"2.1.0","my_unique_id":"UNIQUE_ID"}},"output":["PIPE_LINE_SDXL","MODEL","CONDITIONING","CONDITIONING","VAE","CLIP","MODEL","CONDITIONING","CONDITIONING","CLIP","LATENT","INT","INT","INT","STRING","STRING"],"output_is_list":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],"output_name":["sdxl_pipe","model","positive","negative","vae","clip","refiner_model","refiner_positive","refiner_negative","refiner_clip","latent","seed","width","height","pos_string","neg_string"],"name":"ttN pipeLoaderSDXL_v2","display_name":"pipeLoaderSDXL","description":"","python_module":"custom_nodes.ComfyUI_tinyterraNodes","category":"🌏 tinyterra/pipe","output_node":false}
Validation error: Array must contain at most 1 element(s) at "input.optional.prepend_positive_g"; Array must contain at most 1 element(s) at "input.optional.prepend_positive_l"; Array must contain at most 1 element(s) at "input.optional.prepend_negative_g"; Array must contain at most 1 element(s) at "input.optional.prepend_negative_l" [api.ts:260:18](http://127.0.0.1:8188/src/scripts/api.ts)
Skipping invalid node definition: Text Find. See debug log for more information. [api.ts:257:18](http://127.0.0.1:8188/src/scripts/api.ts)
Invalid ComfyNodeDef: {"input":{"required":{"text":["STRING",{"forceInput":true}],"substring":["STRING",{"default":"","multiline":false}],"pattern":["STRING",{"default":"","multiline":false}]}},"output":"BOOLEAN","output_is_list":[false,false,false,false,false,false,false],"output_name":"found","name":"Text Find","display_name":"Text Find","description":"","python_module":"custom_nodes.was-node-suite-comfyui","category":"WAS Suite/Text/Search","output_node":false}
Validation error: Expected array, received string at "output"; Expected array, received string at "output_name" [api.ts:260:18](http://127.0.0.1:8188/src/scripts/api.ts)
TypeError: undefined has no properties
    transformSingleInputSpec nodeDefStore.ts:124
    transformInputSpecRecord nodeDefStore.ts:95
    <anonymous> nodeDefStore.ts:81
    applyCustomTransformations TransformOperationExecutor.js:373
    applyCustomTransformations TransformOperationExecutor.js:372
    _loop_1 TransformOperationExecutor.js:308
    transform TransformOperationExecutor.js:337
    _loop_1 TransformOperationExecutor.js:307
    transform TransformOperationExecutor.js:337
    plainToInstance ClassTransformer.js:28
    plainToClass index.js:17
    updateNodeDefs nodeDefStore.ts:302
    wrapAction pinia.mjs:1380
    registerNodes app.ts:1963

### What browsers do you use to access the UI ?

Mozilla Firefox

### Other

It works when there all custom nodes are disabled...

**Comment by huchenlei** [comment]
Can you narrow down which custom node causes it? You can narrow the problem down with Comfy CLI's bisect feature: https://github.com/Comfy-Org/comfy-cli#bisect-custom-nodes
