### ISSUE TITLE
[Feature Request]: use "Ctrl+up/down/left/right" to move nodes

### ISSUE THREAD

**Issue by metsweet999** [Comfy-Org/ComfyUI_frontend#337]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

when pressing "Ctrl+up/down/left/right" , the selecting nodes can move correspondingly。
just like the default frontend of comfyui does.
or provide a button that can cativate this feature ( before submitting this issue , i tried to find such a buttton but din't found it ).
very helpful for a Obsessive-compulsive disorder (as me ) to do node-movings.
### Proposed workflow

this feature is not as complicated as needing a step by step describing, i think, personally.

**Comment by huchenlei** [comment]
I don't think we do the move node shortcut in the legacy JS frontend. It might come from an extension you installed. That extension might have issue loading in the new frontend though. Can you list all extensions you installed?

**Comment by metsweet999** [comment]
> I don't think we do the move node shortcut in the legacy JS frontend. It might come from an extension you installed. That extension might have issue loading in the new frontend though. Can you list all extensions you installed?



yes, thank u.
the data listed by console:
"

 Import times for custom nodes:
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\example_node.py
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\Cup-ClipBoard
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\websocket_image_save.py
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_ResolutionSelector
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\efficiency-nodes-comfyui
 

 0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_Noise
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\sdxl_prompt_styler
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\myNodes
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_densediffusion
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-openpose-editor
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\masquerade-nodes-comfyui
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_TiledKSampler
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\stability-ComfyUI-nodes
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\comfyui_controlnet_aux
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-IC-Light-Native
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Eagle-PNGInfo
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_InstantID
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\cg-use-everywhere
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_VisualStylePrompting
 

 0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Logic
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_omost
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\comfyui-lama-remover
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyLiterals
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_essentials
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\Comfy_KepListStuff
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\comfyui-inpaint-nodes
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Video-Matting
 

 0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\comfyui-prompt-composer
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-layerdiffuse
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\comfyui_bmad_nodes
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-IC-Light
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\comfy-qr
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
 

 0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\rgthree-comfy
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Marigold
0.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
0.1 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\comfy_mtb
0.1 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
0.1 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
0.1 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_smZNodes
0.1 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-KJNodes
0.1 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\comfyui-portrait-master
0.1 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\comfyui-workspace-manager
0.1 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_FaceAnalysis
0.1 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\comfyui_segment_anything
0.2 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-IDM-VTON
0.4 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Crystools
0.8 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\comfyui-reactor-node
 

 0.9 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Easy-Use
0.9 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_LayerStyle
1.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\clipseg.py
1.3 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Anyline
1.7 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Manager
2.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Vextra-Nodes
2.2 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyMath
2.8 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\was-node-suite-comfyui
3.2 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-SUPIR
3.2 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\comfyui-mixlab-nodes
3.9 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\comfyui-art-venture
4.0 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
 

 5.8 seconds: E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-Allor
 

 Starting server
 

 To see the GUI go to: http://192.168.0.102:8188 or http://127.0.0.1:8188
To see the GUI go to: https://192.168.0.102:8189 or https://127.0.0.1:8189
 
"

**Comment by metsweet999** [comment]
maybe i should find out which extension enabled this feature by trying disabling some extensions, i will may have it done in few days.

**Comment by metsweet999** [comment]
![屏幕截图 2024-08-11 091331](https://github.com/user-attachments/assets/74a690b7-8400-4326-9bcf-d2fe5ddab65c)
i manually added ".disabled" to each folder of the costum_nodes.
after doing that, restart comfyui, "Ctrl+up/down/left/right" still works, fresh the broswer, still the same.

**Comment by metsweet999** [comment]
![屏幕截图 2024-08-23 112840](https://github.com/user-attachments/assets/94a4bdd7-5289-4278-b368-683bd2946e8f)
look at this, 
the bar displaying "IDLE" comes from rgthree exteension,
though i uninstalled rgthree extension and restarted, still the bar displays,
i just think the ui function added by extensions may won't be deleted from the extensions being deleted.
any way can delete the ui funciotn added by extensions? otherwise i just don't think i can find out which extension enable the ui function.

**Comment by mcmonkey4eva** [comment]
Yeah, you have extensions that aggressively installed themselves elsewhere, possibly into the `(ComfyUI)/web/` folder? not sure.

But yeah either way, not a main frontend issue, relates to extensions
