### ISSUE TITLE
[Feature Request]: Display magnifying glass view when UI zooms to the point where the details of the node can't be seen clearly.

### ISSUE THREAD

**Issue by metsweet999** [Comfy-Org/ComfyUI_frontend#353]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

feature suggestion:
Display magnifying glass view when UI zooms to the point where the details of the node can't be seen clearly, the magnifying glass view can be always at the corner which is far away from the cursor.
or set a button that can activate this feature.

benefit:
so, when u zoomed UI and can't see details of nodes, 
1.
u can quickly see details of any node by just putting cursor on it, don't have to scroll the wheel on mouse a lot.
2.
u can quickly connect input/output between two nodes far away from each other without dragging the two nodes very close before doing it, or aiming ur cursor difficultly.

### Proposed workflow

1. Go to setting menu, find a button.
2. Press this button to activate the magnifying feature.
3. magnifying feature activated as described in "What would your feature do ?" column.

**Comment by huchenlei** [comment]
There is a custom node that can save you from the long connection. https://github.com/chrisgoringe/cg-use-everywhere.

**Comment by huchenlei** [comment]
Internally we have discussed and concluded that our goal is to make it possible that users don't need to make these long connections and large graphs by providing easy-to-use subgraph support.

**Comment by Amorano** [comment]
This should honestly be re-evaluated. One has nothing to do with the other. I have super large graphs that have no need of sub-graphs. Sub-graphs are NOT A SOLUTION to large workflows they are merely a solution for repetition/instancing. There will be large workflows made, with sub-graphs that are also super huge, with even MORE sub-graphs inside. Again, those are not mutually exclusive features for working with DAGs
