### ISSUE TITLE
[Bug]: Invalid workflow against zod schema

### ISSUE THREAD

**Issue by Beamhi** [Comfy-Org/ComfyUI_frontend#357]
### Frontend Version

1.2.14

### Expected Behavior

The workflow is meant to load and display the graph

### Actual Behavior

I just get the error popup as soon as I try to reload the flow
![CleanShot 2024-08-10 at 10 54 57@2x](https://github.com/user-attachments/assets/392e22f9-1c27-4661-a50f-d7ade59ea07d)

### Steps to Reproduce

[tilediff-upscale-new.json](https://github.com/user-attachments/files/16569974/tilediff-upscale-new.json)

### Debug Logs

```powershell
Invalid workflow against zod schema:
Validation error: Expected number, received string
at "links[84][3]"; Expected number, received
string at "links[84][4]"; Expected number,
received string at "links[85][3]"; Expected
number, received string at "links[85][4]";
Expected number, received string at "links[86]
[3]"; Expected number, received string at
"links[86][4]"
```

### Browser Logs

Invalid workflow against zod schema:
Validation error: Expected number, received string
at "links[84][3]"; Expected number, received
string at "links[84][4]"; Expected number,
received string at "links[85][3]"; Expected
number, received string at "links[85][4]";
Expected number, received string at "links[86]
[3]"; Expected number, received string at
"links[86][4]"

**Comment by nux1111** [comment]
![CleanShot 2024-08-10 at 12 33 21@2x](https://github.com/user-attachments/assets/05eb1b79-bea0-4393-8f5c-05efb59a638f)
Turning off validation new update fixes this.

**Comment by Tanglinling** [comment]
There is the same problem in version 1.5.19.
![{D05388F9-F392-423B-800A-2B66F4BA5B15}](https://github.com/user-attachments/assets/41cb92d5-dca3-4b2b-919d-2eabc208ebf0)
