### ISSUE TITLE
[Bug]: Z-Index inconsistencies 

### ISSUE THREAD

**Issue by melMass** [Comfy-Org/ComfyUI_frontend#363]
### Frontend Version

1.2.15

### Expected Behavior

Custom DOM widgets shouldn't go "outside" the graph.

I'm wondering if it shouldn't just be about targeting `graph-canvas-container` instead of body here: https://github.com/Comfy-Org/ComfyUI_frontend/blob/3e7b0a49076588b1b34b312743832ea6fb00aa26/src/scripts/domWidget.ts#L267

![image](https://github.com/user-attachments/assets/63867fc7-2983-4504-8444-19d377f516e2)

### Actual Behavior

![image](https://github.com/user-attachments/assets/2176a01e-4dd5-443e-928c-c79ebbc9809f)

### Steps to Reproduce

Thanks to @AustinMroz for the sample workflow:
[zindex.json](https://github.com/user-attachments/files/16570961/zindex.json)

Here you can see some but not all `textarea` overlapping with the UI

### Debug Logs

```powershell
-
```

### Browser Logs

-

### What browsers do you use to access the UI ?

Apple Safari

**Comment by huchenlei** [comment]
Fixed by https://github.com/Comfy-Org/ComfyUI_frontend/pull/364
