### ISSUE TITLE
我直接使用的main.py进行启动的comfyui应该如何更新新的ui界面呢，求助

### ISSUE THREAD

**Issue by guchendesigndog** [Comfy-Org/ComfyUI_frontend#367]
尝试直接再main.py里面添加 - -windows - standalone - build - -front - end - version
    Comfy - Org / ComfyUI_frontend @ latest
    pause，但是并没有用

**Comment by huchenlei** [comment]
`python main.py --front-end-version Comfy-Org/ComfyUI_frontend@latest`
