### ISSUE TITLE
[Feature Request]: Improve the text formatting in nodes and settings.

### ISSUE THREAD

**Issue by StellarBeing25** [Comfy-Org/ComfyUI_frontend#369]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

At the moment, ComfyUI's nodes and settings lack appropriate text formatting. There isn't even any space between the words in the new setting daialog. Please provide proper text formatting for nodes and settings in the new frontend to make UI easy to use and understand, like SwarmUI has done with samplers.
![SUI](https://github.com/user-attachments/assets/9d19a27c-d874-4ff1-b8bf-76199126f247)

**Comment by huchenlei** [comment]
I think the node display name formatting should be fixed in the backend instead of formatting in the frontend, as the inconsistency might create hardtime when users/devs try find corresponding code in backend by searching node display name.
