### ISSUE TITLE
[Feature Request]: about group selection and moving

### ISSUE THREAD

**Issue by metsweet999** [Comfy-Org/ComfyUI_frontend#382]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

feature1:
when "alt" is pressing,,
boxing a region with mouse,
in this region, nodes won't be selected, but groups which have any overlapping area with this area will be selected.
after this,
now,
if cursor on any area of these selected groups, 
  (1) now if drag the mouse, the group which the cursor suspending on will be moved following the cursor;  
  (2) now if pressing "shift" and drag the mouse, the groups which are now selected will be moved following the cursor;
benefit:
makes groups easier to be selected and moved.

feature2:
when a group or some groups being selected,
now, 
right click the mouse, 
in the pop-up menu, these's a button named as "create parent group",
then parent group will be set for being selected groups.
when parent group being moved by cursor, all its children groups move along it.
the parent group also can have its parent group.
benefit:
make it easier to do group moving when managing large workflows.

### Proposed workflow

all described in "What would your feature do ?" column maybe.

**Comment by alessandroperilli** [comment]
I don't think Parent Groups is a thing. I tried many times to put a group inside another and then move the parent. It's a mess. The child group can become unreachable, and the nodes of the child group move with the parent group but not the child group.

**Comment by huchenlei** [comment]
Should be resolved by https://github.com/Comfy-Org/ComfyUI_frontend/pull/1416
