### ISSUE TITLE
[Bug]: I can't delete saved workflows. 

### ISSUE THREAD

**Issue by JorgeR81** [Comfy-Org/ComfyUI_frontend#383]
### Frontend Version

I'm on the lastest ( v1.2.17 )

### Expected Behavior

To be able to delete saved workflows. 

### Actual Behavior

When I click the delete icon it stays red for a few seconds, but nothing happens. 

![wf](https://github.com/user-attachments/assets/13fc7ebc-147d-4a29-8ae9-1cd23d690230)

### Steps to Reproduce

Just click the icon

### Debug Logs

( nothing in shown in the console )

### Browser Logs

There are a few errors related to custom nodes.
But nothing else shows up after trying to delete the workflow.
```

index.html:4 ComfyUI Front-end version: 1.2.17
:8188/api/userdata/workflows%2F.index.json:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
api.ts:257 Skipping invalid node definition: 0246.HighwayBatch. See debug log for more information.
(anonymous) @ api.ts:257
api.ts:257 Skipping invalid node definition: 0246.BoxRange. See debug log for more information.
(anonymous) @ api.ts:257
api.ts:257 Skipping invalid node definition: 0246.ScriptNode. See debug log for more information.
(anonymous) @ api.ts:257
api.ts:257 Skipping invalid node definition: 0246.Script. See debug log for more information.
(anonymous) @ api.ts:257
api.ts:257 Skipping invalid node definition: 0246.Hub. See debug log for more information.
(anonymous) @ api.ts:257
api.ts:257 Skipping invalid node definition: 0246.Cloud. See debug log for more information.
(anonymous) @ api.ts:257
api.ts:257 Skipping invalid node definition: 0246.Switch. See debug log for more information.
(anonymous) @ api.ts:257
api.ts:257 Skipping invalid node definition: 0246.Meta. See debug log for more information.
(anonymous) @ api.ts:257
api.ts:257 Skipping invalid node definition: Automatic CFG - Attention modifiers. See debug log for more information.
(anonymous) @ api.ts:257
components-manager.js:767 Empty components: policy ignored
linkRenderMode.js:9 [🐍 pysssss] Skipping LinkRenderMode as core extension found
:8188/api/userdata/workflows%2F.index.json:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/extensions/ComfyUI-Custom-Scripts/js/assets/favicon-active.user.ico:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/api/pysssss/autocomplete:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/extensions/ComfyUI-Custom-Scripts/js/assets/favicon.user.ico:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/api/userdata/workflows%2F.index.json:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/api/userdata/workflows%2F.index.json:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)

```

### What browsers do you use to access the UI ?

Google Chrome
I'm on windows 10

### Other

This issue also happens in the old front end.

**Comment by huchenlei** [comment]
Hi @pythongosssss , Can you take a look? I cannot reproduce this locally though.

**Comment by JorgeR81** [comment]
After today's updates I tried again and sometimes it works. 

Sometimes you need to click multiple times for it to work.

**Comment by pythongosssss** [comment]
Could you please check your browser dev tools network tab when you are clicking delete to see if it is sending the request or not

**Comment by JorgeR81** [comment]
OK, now it works more often than not. 
But the times it did not work, there was no entry added to logs.

![logs](https://github.com/user-attachments/assets/a5ceaeba-a3cc-4988-ae44-9791d08832a7)

**Comment by JorgeR81** [comment]
Also, now that I've created and deleted many workflows to test this, I noticed other issues. 

---
- Sometimes a workflow seems to be deleted but it is not. 
( e.g. I just deleted "test2" but I can't create another workflow with the same name. 
And if I close and start Comfy UI again, the "test2" shows up on the list ).

![log6](https://github.com/user-attachments/assets/74773e19-4a6e-4ee4-89eb-6efd1d6cd998)

---
- After changing names on a few workflows, I also had an error where a workflow seems to show up under a different name.
So I can't delete it or change the name ( I have an error msg ).
But after closing and starting Comfy UI again, it shows up with the correct name and can be deleted. 

![log2](https://github.com/user-attachments/assets/89d3255f-65ff-4005-9eab-4ca4597be2d3)
![log3](https://github.com/user-attachments/assets/b0560a97-470d-43bb-b241-9b75478c8604)



---
Also, I've been creating and deleting workflows, while changing between the old and the new frontend. 
Not sure if that contributed to all these issues.

**Comment by JorgeR81** [comment]
Even with the new menu ( version 1.31 ) I still have issues.

Sometimes the sidebar is not updated, when deleting a saved workflow.
Usually this is solved by refreshing the browser.

Refreshing the browser, before deleting a workflow, also seems to prevent this issues.

---

If the sidebar was not updated and I try to delete again, without refreshing, I have "file not found" error.
Usually after this the sidebar is also updated. 

![wf1](https://github.com/user-attachments/assets/60ce37c5-280f-4be8-8cf7-8799a1a8765d)

**Comment by JorgeR81** [comment]
I'm closing this, since we have a new issue, for the new menu / sidebar.
