### ISSUE TITLE
[Bug]: Kijay's Set/Get nodes don't appear in v1.2.17

### ISSUE THREAD

**Issue by alessandroperilli** [Comfy-Org/ComfyUI_frontend#384]
### Frontend Version

1.2.17

### Expected Behavior

Set/Get nodes, part of [KJNodes for ComfyUI](https://github.com/kijai/ComfyUI-KJNodes), should appear in the workflow and the search UI elements. 

### Actual Behavior

Set/Get nodes appear as red boxes in the workflow + an attempt to find them via the sidebar or the canvas search UI doesn't show them (or I'm blind).

<img width="740" alt="Screenshot 2024-08-12 at 08 20 23" src="https://github.com/user-attachments/assets/d24575d2-2591-424f-b9b0-3289ba178b87">

<img width="877" alt="Screenshot 2024-08-12 at 14 05 29" src="https://github.com/user-attachments/assets/63a957ab-5e72-43ad-b4c0-8997771e73ec">

### Steps to Reproduce

Create a workflow with some set/get nodes.

### Debug Logs

```powershell
No output in the terminal.
```

### Browser Logs

The errors are too many to capture (due to the dozen of set/get nodes I use in APW). This is a subset of them:

<img width="952" alt="Screenshot 2024-08-12 at 14 10 48" src="https://github.com/user-attachments/assets/16be37cd-7764-4811-ab5f-aa2b0eff5969">

<img width="944" alt="Screenshot 2024-08-12 at 14 16 19" src="https://github.com/user-attachments/assets/814780e2-cd8a-4995-b7c4-10675062d7d6">

### What browsers do you use to access the UI ?

Other

### Other

Vivaldi on macOS

**Comment by huchenlei** [comment]
Culprit reverted in https://github.com/Comfy-Org/ComfyUI_frontend/releases/tag/v1.2.18

**Comment by alessandroperilli** [comment]
This bug report has been closed, as the revert fixed the red boxes. But I still can't find set/get nodes anywhere in the node catalog or via the search UI. I must be blind.
