### ISSUE TITLE
[Bug]: Very slow zoom & pan

### ISSUE THREAD

**Issue by alessandroperilli** [Comfy-Org/ComfyUI_frontend#388]
### Frontend Version

1.2.18 (but same issue observed with 1.2.17).

### Expected Behavior

Fast zoom and pan of the canvas.

### Actual Behavior

Compared to the old frontend, the new frontend offers a much smoother zoom experience (no jitter), but it's exceptionally slow in both zooming and panning the canvas. Very hard to use with a large workflow like APW.

This is me moving the mouse (or zooming) as fast as I can:
https://drive.google.com/file/d/1UvYxTJTu0yc6wngvN2pIYnMRa_1BHZM4/view?usp=sharing

### Steps to Reproduce

Load [APW 10.0](https://perilli.com/ai/comfyui), but it's a lot of custom nodes.

### Debug Logs

```powershell
No relevant logs.
```

### Browser Logs

No relevant logs.

### What browsers do you use to access the UI ?

Other

### Other

Vivaldi on macOS.

**Comment by alessandroperilli** [comment]
I think I discovered the problem @huchenlei: when APW has complete a run, the workflow end up in a state with *at least* half dozen preview image nodes displaying something. Oftentimes, some of these nodes (used for monitoring and debug the various functions of the workflow) can display upscaled images, so 4K or bigger.

A different workflow with just one image displayed in a preview node shows no performance issue.

The old frontend has no problem handling all those images on the canvas and the zooming and panning speed is always fine.

**Comment by alessandroperilli** [comment]
I take it back: even without previewed images, the canvas is very slow in zooming and panning. Just tested with new version 1.2.20.

**Comment by christian-byrne** [comment]
Is it also slow when you zoom with Ctrl+Shift+Click+Drag or just with mouse wheel zoom?

**Comment by alessandroperilli** [comment]
@christian-byrne I didn't even know there was this shortcut... 

It's faster, but way more jittery. It moves in quicksand for the first 1-2ms and then it gets "unstuck". I thought it was the YouTube video loaded via MTB Note+ node, but after deleting it, nothing changes. 

I'm not sure what element/s are causing this.

**Comment by alessandroperilli** [comment]
In version 1.2.23 the performance is better, but still subpar compared to the old front-end.

**Comment by christian-byrne** [comment]
I just did a performance profile with the AP Workflow. It's really good for stress-testing. You're right that it's much smoother on the old front-end. 

The major bottleneck seems to actually be the DOM widgets (multiline text inputs), rather than the images or YouTube videos. After fixing #470, it improved a lot.

**Comment by alessandroperilli** [comment]
@christian-byrne First of all, thanks for looking into this. The upcoming APW 11.0, which I am working on right now, is even bigger, but organized in a different way. It's not public yet, but I'd be happy to share it with you if you want to use it for stress-testing. 

Feel free to reach out on Discord: `@perilli`

I'll write another reply as soon as #470 is committed.

**Comment by alessandroperilli** [comment]
@christian-byrne 1.2.26 improves the performance a bit, but still far from the old frontend. The left side of the workflow, where all the multiline widgets are is really unusable. The right side of the workflow is fine in terms of speed.

**Comment by christian-byrne** [comment]
No problem. Looking forward to it.

I did not actually push the fix I made. It seemed like something the maintainer would want to implement himself so I just reported all the info I had in an issue. I can comment again when progress has been made.

**Comment by alessandroperilli** [comment]
Solved by 1.2.29. Thank you!

(I believe it's still a tad slower than the original frontend but at least now it can be used without problems)
