### ISSUE TITLE
[Feature Request]: Dragging Off Outputs Popup Speed

### ISSUE THREAD

**Issue by Amorano** [Comfy-Org/ComfyUI_frontend#406]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Popup for pulling off is no where as workflow friendly to speed as the old menu. There should be a setting for the animation and/or speed of the popup.

### Proposed workflow

1. Open Setting Panel
2. Turn off delay for popup
3. Rejoice

**Comment by huchenlei** [comment]
I think generally people want the dialog like searchbox to appear faster. So I made the transition faster as default in https://github.com/Comfy-Org/ComfyUI_frontend/pull/410.

**Comment by Amorano** [comment]
Great. How about removing the overlay? I only need the box to popup, not the entire screen to go black. Or should I add that as yet another feature request for more settings?
