### ISSUE TITLE
when i enable the new interface i can't hide nodes under another node.

### ISSUE THREAD

**Issue by tu1997tu** [Comfy-Org/ComfyUI_frontend#438]
![image](https://github.com/user-attachments/assets/bacf4508-7bc8-413d-a390-3f8a4ae2809c)
when i enable the new interface i can't hide nodes under another node.

**Comment by JorgeR81** [comment]
Yes, please make this work like on the old frontend.

I usually hide the AE? nodes behind the main node.

But I can't do it with the new frontend.

**_Old frontend_** 

![01](https://github.com/user-attachments/assets/97cb3fe0-ce13-4c10-bdf1-ecf3af3a7804)

_**Old frontend** ( main node minimized )_

![02](https://github.com/user-attachments/assets/1312446d-46ef-44da-b14b-e624e70fb2d6)

**_New frontend_** 

![03](https://github.com/user-attachments/assets/0dd50391-67f5-4d80-93df-d2eead073733)

**Comment by huchenlei** [comment]
@pythongosssss Can you take a look at this issue?

**Comment by marduk191** [comment]
more things that using the client a single time would have caught. the code quality in main has hit rock bottom.

**Comment by EasyComfyui** [comment]
![image](https://github.com/user-attachments/assets/289a080c-801d-4bea-b2cd-ac85ef60abc6)
The node with the larger id will be on top of the node with the smaller id. Another problem is that after updating the new interface, the preview image node does not display the image until the ksampler process finishes running. 1 ksampler is not affected, but a process with 2 ksamplers does not work.
