### ISSUE TITLE
[Feature Request]: Font Size for Text Input Areas

### ISSUE THREAD

**Issue by doggeddalle** [Comfy-Org/ComfyUI_frontend#439]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I would like to request an accessibility feature to adjust the font size for Text Input Areas, like for Clip Encode Nodes or Text Box nodes.

Current approach for old frontend is using this extension which ads the option for font change in the Settings menu https://github.com/blib-la/blibla-comfyui-extensions

### Proposed workflow

1. Go to Settings [Gear Icon]
2. Change option for Font Size by value

**Comment by cicalooo** [comment]
blib-la now updated for new frontend
