### ISSUE TITLE
[Bug]: language issue

### ISSUE THREAD

**Issue by pandayummy** [Comfy-Org/ComfyUI_frontend#442]
### Frontend Version

Some Chinese characters. 

### Expected Behavior

English

### Actual Behavior

![image](https://github.com/user-attachments/assets/8a847967-91fa-4c0e-9033-02a8436a195b)

![image](https://github.com/user-attachments/assets/f3072344-798e-430a-a401-07653bccc37f)

Some Chinese characters. How to make them English?

### Steps to Reproduce

none

### Debug Logs

```powershell
none
```

### Browser Logs

none

### What browsers do you use to access the UI ?

Google Chrome

**Comment by huchenlei** [comment]
Currently language is auto detected from browser setting.
