### ISSUE TITLE
[Bug]: When double clicking, there are 2 search modules

### ISSUE THREAD

**Issue by pandayummy** [Comfy-Org/ComfyUI_frontend#443]
### Frontend Version

When double clicking, there are 2 search module, how to hide the 2nd one (old one)?

![image](https://github.com/user-attachments/assets/0f7dea88-a831-4525-b23f-0884367abfad)

### Expected Behavior

none

### Actual Behavior

none

### Steps to Reproduce

none

### Debug Logs

```powershell
none
```

### Browser Logs

none

**Comment by huchenlei** [comment]
Please properly fill out the information fields and reopen. Thanks!

**Comment by huchenlei** [comment]
For this particular issue, can you also attach the file content of `ComfyUI/user/default/comfy.setting.json`?

**Comment by tiptinker** [comment]
The issue is actually when Double-Click LMB, the old and new quick search palette both popup.

![image](https://github.com/user-attachments/assets/3d2050b4-a099-49cf-b766-4e593f28508d)


{
    "Crystools.newSave": true,
    "Crystools.projectNameText": "workflow",
    "Comfy.CustomColorPalettes": {
        "obsidian": {
            "version": 102,
            "id": "obsidian",
            "name": "Obsidian",
            "colors": {
                "node_slot": {
                    "CLIP": "#FFD500",
                    "CLIP_VISION": "#A8DADC",
                    "CLIP_VISION_OUTPUT": "#ad7452",
                    "CONDITIONING": "#FFA931",
                    "CONTROL_NET": "#6EE7B7",
                    "IMAGE": "#64B5F6",
                    "LATENT": "#FF9CF9",
                    "MASK": "#81C784",
                    "MODEL": "#B39DDB",
                    "STYLE_MODEL": "#C2FFAE",
                    "VAE": "#FF6E6E",
                    "TAESD": "#DCC274",
                    "PIPE_LINE": "#7737AA",
                    "PIPE_LINE_SDXL": "#7737AA",
                    "INT": "#29699C",
                    "XYPLOT": "#74DA5D",
                    "X_Y": "#38291f"
                },
                "litegraph_base": {
                    "BACKGROUND_IMAGE": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAQBJREFUeNrs1rEKwjAUhlETUkj3vP9rdmr1Ysammk2w5wdxuLgcMHyptfawuZX4pJSWZTnfnu/lnIe/jNNxHHGNn//HNbbv+4dr6V+11uF527arU7+u63qfa/bnmh8sWLBgwYJlqRf8MEptXPBXJXa37BSl3ixYsGDBMliwFLyCV/DeLIMFCxYsWLBMwSt4Be/NggXLYMGCBUvBK3iNruC9WbBgwYJlsGApeAWv4L1ZBgsWLFiwYJmCV/AK3psFC5bBggULloJX8BpdwXuzYMGCBctgwVLwCl7Be7MMFixYsGDBsu8FH1FaSmExVfAxBa/gvVmwYMGCZbBg/W4vAQYA5tRF9QYlv/QAAAAASUVORK5CYII=",
                    "CLEAR_BACKGROUND_COLOR": "#222222",
                    "NODE_TITLE_COLOR": "rgba(255,255,255,.75)",
                    "NODE_SELECTED_TITLE_COLOR": "#FFF",
                    "NODE_TEXT_SIZE": 14,
                    "NODE_TEXT_COLOR": "#b8b8b8",
                    "NODE_SUBTEXT_SIZE": 12,
                    "NODE_DEFAULT_COLOR": "rgba(0,0,0,.8)",
                    "NODE_DEFAULT_BGCOLOR": "rgba(22,22,22,.8)",
                    "NODE_DEFAULT_BOXCOLOR": "rgba(255,255,255,.75)",
                    "NODE_DEFAULT_SHAPE": "box",
                    "NODE_BOX_OUTLINE_COLOR": "#236692",
                    "DEFAULT_SHADOW_COLOR": "rgba(0,0,0,0)",
                    "DEFAULT_GROUP_FONT": 24,
                    "WIDGET_BGCOLOR": "#242424",
                    "WIDGET_OUTLINE_COLOR": "#333",
                    "WIDGET_TEXT_COLOR": "#a3a3a8",
                    "WIDGET_SECONDARY_TEXT_COLOR": "#97979c",
                    "LINK_COLOR": "#9A9",
                    "EVENT_LINK_COLOR": "#A86",
                    "CONNECTING_LINK_COLOR": "#AFA"
                },
                "comfy_base": {
                    "fg-color": "#fff",
                    "bg-color": "#242424",
                    "comfy-menu-bg": "rgba(24,24,24,.9)",
                    "comfy-input-bg": "#262626",
                    "input-text": "#ddd",
                    "descrip-text": "#999",
                    "drag-text": "#ccc",
                    "error-text": "#ff4444",
                    "border-color": "#29292c",
                    "tr-even-bg-color": "rgba(28,28,28,.9)",
                    "tr-odd-bg-color": "rgba(19,19,19,.9)"
                }
            }
        },
        "obsidian_dark": {
            "version": 102,
            "id": "obsidian_dark",
            "name": "Obsidian Dark",
            "colors": {
                "node_slot": {
                    "CLIP": "#FFD500",
                    "CLIP_VISION": "#A8DADC",
                    "CLIP_VISION_OUTPUT": "#ad7452",
                    "CONDITIONING": "#FFA931",
                    "CONTROL_NET": "#6EE7B7",
                    "IMAGE": "#64B5F6",
                    "LATENT": "#FF9CF9",
                    "MASK": "#81C784",
                    "MODEL": "#B39DDB",
                    "STYLE_MODEL": "#C2FFAE",
                    "VAE": "#FF6E6E",
                    "TAESD": "#DCC274",
                    "PIPE_LINE": "#7737AA",
                    "PIPE_LINE_SDXL": "#7737AA",
                    "INT": "#29699C",
                    "XYPLOT": "#74DA5D",
                    "X_Y": "#38291f"
                },
                "litegraph_base": {
                    "BACKGROUND_IMAGE": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAAAACXBIWXMAAAsTAAALEwEAmpwYAAAGlmlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgOS4xLWMwMDEgNzkuMTQ2Mjg5OSwgMjAyMy8wNi8yNS0yMDowMTo1NSAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iIHhtbG5zOnBob3Rvc2hvcD0iaHR0cDovL25zLmFkb2JlLmNvbS9waG90b3Nob3AvMS4wLyIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0RXZ0PSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VFdmVudCMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIDI1LjEgKFdpbmRvd3MpIiB4bXA6Q3JlYXRlRGF0ZT0iMjAyMy0xMS0xM1QwMDoxODowMiswMTowMCIgeG1wOk1vZGlmeURhdGU9IjIwMjMtMTEtMTVUMDI6MDQ6NTkrMDE6MDAiIHhtcDpNZXRhZGF0YURhdGU9IjIwMjMtMTEtMTVUMDI6MDQ6NTkrMDE6MDAiIGRjOmZvcm1hdD0iaW1hZ2UvcG5nIiBwaG90b3Nob3A6Q29sb3JNb2RlPSIzIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOmIyYzRhNjA5LWJmYTctYTg0MC1iOGFlLTk3MzE2ZjM1ZGIyNyIgeG1wTU06RG9jdW1lbnRJRD0iYWRvYmU6ZG9jaWQ6cGhvdG9zaG9wOjk0ZmNlZGU4LTE1MTctZmQ0MC04ZGU3LWYzOTgxM2E3ODk5ZiIgeG1wTU06T3JpZ2luYWxEb2N1bWVudElEPSJ4bXAuZGlkOjIzMWIxMGIwLWI0ZmItMDI0ZS1iMTJlLTMwNTMwM2NkMDdjOCI+IDx4bXBNTTpIaXN0b3J5PiA8cmRmOlNlcT4gPHJkZjpsaSBzdEV2dDphY3Rpb249ImNyZWF0ZWQiIHN0RXZ0Omluc3RhbmNlSUQ9InhtcC5paWQ6MjMxYjEwYjAtYjRmYi0wMjRlLWIxMmUtMzA1MzAzY2QwN2M4IiBzdEV2dDp3aGVuPSIyMDIzLTExLTEzVDAwOjE4OjAyKzAxOjAwIiBzdEV2dDpzb2Z0d2FyZUFnZW50PSJBZG9iZSBQaG90b3Nob3AgMjUuMSAoV2luZG93cykiLz4gPHJkZjpsaSBzdEV2dDphY3Rpb249InNhdmVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOjQ4OWY1NzlmLTJkNjUtZWQ0Zi04OTg0LTA4NGE2MGE1ZTMzNSIgc3RFdnQ6d2hlbj0iMjAyMy0xMS0xNVQwMjowNDo1OSswMTowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIDI1LjEgKFdpbmRvd3MpIiBzdEV2dDpjaGFuZ2VkPSIvIi8+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJzYXZlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDpiMmM0YTYwOS1iZmE3LWE4NDAtYjhhZS05NzMxNmYzNWRiMjciIHN0RXZ0OndoZW49IjIwMjMtMTEtMTVUMDI6MDQ6NTkrMDE6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCAyNS4xIChXaW5kb3dzKSIgc3RFdnQ6Y2hhbmdlZD0iLyIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9yeT4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz4OTe6GAAAAx0lEQVR42u3WMQoAIQxFwRzJys77X8vSLiRgITif7bYbgrwYc/mKXyBoY4VVBgsWLFiwYFmOlTv+9jfDOjHmr8u6eVkGCxYsWLBgmc5S8ApewXvgYRksWLBgKXidpeBdloL3wMOCBctgwVLwCl7BuyyDBQsWLFiwTGcpeAWv4D3wsAwWLFiwFLzOUvAuS8F74GHBgmWwYCl4Ba/gXZbBggULFixYprMUvIJX8B54WAYLFixYCl5nKXiXpeA98LBgwTJYsGC9tg1o8f4TTtqzNQAAAABJRU5ErkJggg==",
                    "CLEAR_BACKGROUND_COLOR": "#000",
                    "NODE_TITLE_COLOR": "rgba(255,255,255,.75)",
                    "NODE_SELECTED_TITLE_COLOR": "#FFF",
                    "NODE_TEXT_SIZE": 14,
                    "NODE_TEXT_COLOR": "#b8b8b8",
                    "NODE_SUBTEXT_SIZE": 12,
                    "NODE_DEFAULT_COLOR": "rgba(0,0,0,.8)",
                    "NODE_DEFAULT_BGCOLOR": "rgba(22,22,22,.8)",
                    "NODE_DEFAULT_BOXCOLOR": "rgba(255,255,255,.75)",
                    "NODE_DEFAULT_SHAPE": "box",
                    "NODE_BOX_OUTLINE_COLOR": "#236692",
                    "DEFAULT_SHADOW_COLOR": "rgba(0,0,0,0)",
                    "DEFAULT_GROUP_FONT": 24,
                    "WIDGET_BGCOLOR": "#242424",
                    "WIDGET_OUTLINE_COLOR": "#333",
                    "WIDGET_TEXT_COLOR": "#a3a3a8",
                    "WIDGET_SECONDARY_TEXT_COLOR": "#97979c",
                    "LINK_COLOR": "#9A9",
                    "EVENT_LINK_COLOR": "#A86",
                    "CONNECTING_LINK_COLOR": "#AFA"
                },
                "comfy_base": {
                    "fg-color": "#fff",
                    "bg-color": "#242424",
                    "comfy-menu-bg": "rgba(24,24,24,.9)",
                    "comfy-input-bg": "#262626",
                    "input-text": "#ddd",
                    "descrip-text": "#999",
                    "drag-text": "#ccc",
                    "error-text": "#ff4444",
                    "border-color": "#29292c",
                    "tr-even-bg-color": "rgba(28,28,28,.9)",
                    "tr-odd-bg-color": "rgba(19,19,19,.9)"
                }
            }
        }
    },
    "VHS.AdvancedPreviews": true,
    "Comfy.DOMClippingEnabled": false,
    "Comfy.InvertMenuScrolling": true,
    "Comfy.NodeSuggestions.number": "66",
    "pysssss.SnapToGrid": true,
    "Comfy.ColorPalette": "dark",
    "Comfy.LinkRenderMode": "2",
    "pysssss.UseNumberInputPrompt": false,
    "pysssss.WidgetDefaults": "[]",
    "pysssss.Workflows.Default": "[ComfyUI Default]",
    "pysssss.ImageFeed.Location": "right",
    "DZ.Debug.enabled": true,
    "mtb.Debug.enabled": true,
    "Comfy.DevMode": true,
    "Comfy.MenuPosition": true,
    "komojini.ShowSystemStatus": false,
    "komojini.NodeAutoColor": true,
    "komojini.AdvancedPreviews": true,
    "Crystools.switchHDD": false,
    "Crystools.switchRAM": true,
    "Crystools.inputRate": "1",
    "pysssss.ShowImageOnMenu": true,
    "AE.showlinks": 4,
    "AE.details": true,
    "KJNodes.browserStatus": true,
    "Comfy.EasyUse.queueProcessBar": false,
    "Comfy.SnapToGrid.GridSize": "14",
    "Comfy.DisableFloatRounding": false,
    "Comfy.EasyUse.MenuNestSub": false,
    "Comfy.UseNewMenu": "Top",
    "Crystools.switchCPU": true,
    "Crystools.switchGPU0": true,
    "Crystools.switchTemperature0": true,
    "Crystools.switchVRAM0": true,
    "Crystools.showStatus": true,
    "Comfy.EasyUse.NodeTemplateShortcut": false,
    "Comfy.Logging.Enabled": false,
    "Comfy.EasyUse.toolBar": false,
    "ADE.ShowExperimental": false,
    "pysssss.ImageFeed.Deduplication": "0.5",
    "mtb.imageFeed.enabled": false,
    "Comfy.LJNodes.UIHelpers.NodeTitleEditTrigger": "Double Click",
    "pysssss.ModelInfo.NsfwLevel": "Blocked"
}

**Comment by tiptinker** [comment]
![image](https://github.com/user-attachments/assets/67d36f8e-86b8-476b-b85d-297588b8dc7a)

**Comment by huchenlei** [comment]
Please fill all info fields including the frontend version you are using. I am unable to reproduce with your settings. Please also follow the instruction to disable all custom nodes and see the issue is still there?

**Comment by oliverban** [comment]
Hi @huchenlei ! We "spoke" in the other thread over on the main comfy git. Here is a list of my extensions. As I said, you won't like it since it is really long I know, sorry about that! :P 

 comfyui-default-values-manager
 ComfyUI-Photopea
 ComfyUI-LJNodes
 ComfyUI-Texture-Simple
 canvas_tab
 websocket_image_save.py
 ComfyUI-Image-Selector
 ComfyUI-mape-Helpers
 LoadLoraWithTags
 SD-Latent-Interposer
 Image-Captioning-in-ComfyUI
 ComfyUI-SEGAttention
 Stable-Diffusion-temperature-settings
 ComfyUI-Adaptive-Guidance Uncond-Zero-for-ComfyUI
 extended-saveimage-comfyui
 attention-couple-ComfyUI
 prompt_injection
 ComfyUI_Noise
 ComfyUI-Fast-Style-Transfer
 ComfyUI-HQ-Image-Save
 lora-info
 sd-dynamic-thresholding
 ComfyUi_NNLatentUpscale
 ComfyUI-Logic
 ComfyUI_ADV_CLIP_emb
 cg-use-everywhere
 ComfyUI-Latent-Modifiers
 ComfyUI_IPAdapter_plus
 efficiency-nodes-comfyui
 comfyui-fitsize
 SD-Advanced-Noise
 ComfyUI-VideoHelperSuite
 ComfyUI_Cutoff
 stability-ComfyUI-nodes
 masquerade-nodes-comfyui
 ComfyUI_SimpleTiles
 sd-perturbed-attention
 ComfyUI-AutomaticCFG
 cg-noisetools
 ComfyUI-Fluxtapoz
 wlsh_nodes
 comfyui-lama-remover
 ComfyUI-WD14-Tagger
 ComfyUI_experiments
 ComfyUI-SuperBeasts
 comfyui-inpaint-nodes
 comfyui-tooling-nodes
 ComfyUI_JPS-Nodes
 comfyui_controlnet_aux
 ComfyUI-QualityOfLifeSuit_Omar92
 ComfyUI_FL-Trainer
 ComfyUI-mxToolkit
 ComfyUI-RefUNet
 ComfyUI-Path-Helper
 ComfyUI_ELLA
 ComfyUI-DepthAnythingV2
 ComfyUI_essentials
 comfyui-various
 ComfyUI-Impact-Pack
 ComfyMath
 mikey_nodes
 ComfyUI_UltimateSDUpscale ComfyUI-Florence2
 ComfyUI-post-processing-nodes
 ComfyUI-FLATTEN
 comfyui-browser
 ComfyUI-Custom-Scripts
 ComfyUI-Frame-Interpolation
 save-image-extended-comfyui
 ComfyUI-KJNodes
 ComfyUI-moondream
 ComfyUI-Advanced-ControlNet
 Derfuu_ComfyUI_ModdedNodes
 ComfyUI-segment-anything-2
 ComfyUI-BrushNet
 ComfyUI-LivePortraitKJ
 rgthree-comfy
 ComfyUI_ExtraModels
 ComfyUI-Geowizard
 ComfyUI-MimicMotionWrapper
 ComfyUI-BiRefNet
 ComfyUI-Veevee
 ComfyUI-AnimateDiff-Evolved
 ComfyUI_Comfyroll_CustomNodes
 comfyui-workspace-manager   
 facerestore_cf
 ComfyUI_toyxyz_test_nodes   
 comfyui-tensorops
 comfyui-prompt-reader-node
 ComfyUI-TiledDiffusion
 ComfyUI_smZNodes
 ComfyUI-Inspire-Pack
 ComfyUI_tinyterraNodes
 ComfyUI-Crystools
 comfyui_segment_anything
 comfy_mtb
 ComfyUI-RK-Sampler
 comfyui-reactor-node
 ComfyUI-LLaVA-OneVision
 ComfyUI_Fill-Nodes
 eden_comfy_pipelines
 comfy_PoP
 ComfyUI_FizzNodes
 ComfyUI-fastblend
 comfyui_facetools
 ComfyUI-Easy-Use
 ComfyUI-Manager
 ComfyUI-Inspyrenet-Rembg
 ComfyUI-Allor
 ComfyUI-Vextra-Nodes
 ComfyUI-ADMotionDirector
 ComfyUI-APISR
 ComfyUI-DirGir
 was-node-suite-comfyui
 ComfyUI_Custom_Nodes_AlekPet
 comfyui-art-venture

**Comment by tiptinker** [comment]
ComfyUI-LJNodes
websocket_image_save.py
ComfyUI-Inpaint-CropAndStitch
ComfyUI-Prompt-Preview
ComfyUI-WD14-Tagger
comfyui-inpaint-nodes
ComfyUI_IPAdapter_plus
ComfyUI-layerdiffuse
ComfyUI-Custom-Scripts
ComfyUI_essentials
ComfyUI_UltimateSDUpscale
ComfyUI-Frame-Interpolation
rgthree-comfy
ComfyUI-AnimateDiff-Evolved
ComfyUI-Inspire-Pack
ComfyUI-Manager
ComfyUI-Impact-Pack
ComfyUI-Crystools
comfyui-reactor-node
ComfyUI-VideoHelperSuite
clipseg.py
ComfyUI_LayerStyle
was-node-suite-comfyui
ComfyUI-PhotoMaker-Plus
ComfyUI-Easy-Use
ComfyUI-MimicBrush

**Comment by huchenlei** [comment]
The culprit is ComfyUI-LJNodes. https://github.com/coolzilj/ComfyUI-LJNodes/blob/8172f7221071bc9b04e0230aed7648944c62c350/js/ui_helpers.js#L79

Please disable that node and you should be good.

**Comment by oliverban** [comment]
> The culprit is ComfyUI-LJNodes. https://github.com/coolzilj/ComfyUI-LJNodes/blob/8172f7221071bc9b04e0230aed7648944c62c350/js/ui_helpers.js#L79
> 
> Please disable that node and you should be good.

Thanks so much! Have informed (and so have you and others) the author of it! :)

**Comment by gonzalu** [comment]
For me, it looks like it might be the ComfyUI Manager custom node itself :( When all nodes are disabled, all works well. When I just install manager, the problem shows up.
