### ISSUE TITLE
[Feature Request]:拖拽连线时，无法快捷选择转节点，用起来很难受

### ISSUE THREAD

**Issue by opplus** [Comfy-Org/ComfyUI_frontend#448]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

拖拽连线时，无法快捷选择转节点，用起来很难受

### Proposed workflow

1. Go to ....
2. Press ....
3. ...

**Comment by huchenlei** [comment]
You can still fall back to the legacy litegraph searchbox for now while we work on the solution.
![image](https://github.com/user-attachments/assets/c48be3dd-c61f-49fd-9564-601f82255370)
