### ISSUE TITLE
Default workflow behavior.

### ISSUE THREAD

**Issue by comfyanonymous** [Comfy-Org/ComfyUI_frontend#450]
Old frontend: If the v1-5-pruned-emaonly.ckpt isn't in the checkpoints list it picks the first one from the list instead.

Now: It behaves just like loading a regular workflow.

**Comment by huchenlei** [comment]
https://github.com/user-attachments/assets/59c293b0-058d-481a-bb69-b9cf228e0f16

**Comment by comfyanonymous** [comment]
Clear your browser cache and load up ComfyUI like a first time user would.
![image](https://github.com/user-attachments/assets/0895083d-2503-44c0-ac2b-1eec939b8309)

**Comment by huchenlei** [comment]
Still not reproducable after clearing browser cache. 
![image](https://github.com/user-attachments/assets/a37110cb-88ab-4c0a-a60a-f5276384ad3f)

The combo list options are provided by the backend. The frontend simply loads the default value. If not specified, the first value in the combo list will be used. 
![image](https://github.com/user-attachments/assets/2c422bb5-7f93-4b8b-85c0-10536b572f78)

**Comment by comfyanonymous** [comment]
Oh, I did some tests and it only happens in Firefox, Chromium is fine.

**Comment by mcmonkey4eva** [comment]
I loaded in a private Firefox window and it correctly selected the sd_xl_1.0 model I have as the only model in this test environment

![image](https://github.com/user-attachments/assets/fc653232-165e-4154-b366-fce6baad264a)
