### ISSUE TITLE
[Feature Request]: Please add Chinese support for node search - 节点搜索请添加中文支持

### ISSUE THREAD

**Issue by eokoo** [Comfy-Org/ComfyUI_frontend#464]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

平时用中文界面, 不能用中文搜索节点很是不便, 请求支持, 谢谢大佬

I usually use the Chinese interface, and it is very inconvenient that I cannot search for nodes in Chinese. I request support. Thank you.

### Proposed workflow

中文搜索节点支持
Chinese search node support

**Comment by mcmonkey4eva** [comment]
I translated your original message to English using Google Translate so all maintainers can understand the request.

Have you tried https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation to see if this works for you?

-----

我使用 Google 翻译将您的原始消息翻译成英文，以便所有维护人员都能理解该请求。

您是否尝试过 https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation 来看看这是否适合您？

**Comment by cjc999** [comment]
The plugin cannot resolve the issue of being unable to search in Chinese, and there is an urgent need to add the functionality of Chinese search in the search box.

**Comment by hben35096** [comment]
In the old version of search, you can use:
![PixPin_2024-08-30_23-00-46](https://github.com/user-attachments/assets/d8a95c8f-f37a-4f13-80dc-ea02b1e20636)

---

The search in the new front-end is:
![PixPin_2024-08-30_23-05-09](https://github.com/user-attachments/assets/a6aade10-a7cf-416d-a3f9-a2f16bddc586)

**Comment by mcmonkey4eva** [comment]
Ah so the issue here is unicode characters are not being handled properly by the search function

**Comment by mcmonkey4eva** [comment]
@huchenlei looked into it and said the way the translation plugin updates the names is not properly updating the data source that the search uses

**Comment by huchenlei** [comment]
Done in https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/pull/275
