### ISSUE TITLE
[Feature Request]: Video/gif support for Queue media preview !

### ISSUE THREAD

**Issue by toyxyz** [Comfy-Org/ComfyUI_frontend#465]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Thanks for the great work as always! 

The new media preview is very cool.

Is it possible to show thumbnails or gifs of videos created with Animatediff or svd here? 

![image](https://github.com/user-attachments/assets/1635ee48-5522-4953-a58d-9b01b89e0942)

### Proposed workflow

1. Go to ....
2. Press ....
3. ...

**Comment by huchenlei** [comment]
https://github.com/Comfy-Org/ComfyUI_frontend/pull/513
