### ISSUE TITLE
DOMWidgets re-rendering excessively

### ISSUE THREAD

**Issue by christian-byrne** [Comfy-Org/ComfyUI_frontend#470]
There are two separate methods checking whether a DOM widget should be hidden.

This `LGraphCanvas.computeVisibleNodes` patch toggles the widget's visibility based on whether it's on- or off-screen:

https://github.com/Comfy-Org/ComfyUI_frontend/blob/d1715972e337a6fafc75da6f585fad4d92b4cd54/src/scripts/domWidget.ts#L217-L223

The widget's `draw` method toggles the widget's visibility based on whether the node is collapsed or the canvas is zoomed out:

https://github.com/Comfy-Org/ComfyUI_frontend/blob/d1715972e337a6fafc75da6f585fad4d92b4cd54/src/scripts/domWidget.ts#L310-L317

Both are called every frame and every mouse move. If the methods disagree (e.g., node is off-screen but not collapsed, node is on-screen but the canvas is zoomed out, etc.), then the visibility will be toggled on and off hundreds of thousands of times.

You can see the effect on performance by how much time is spent in `set hidden` and `Recalculate Stlye`:

![Selection_254](https://github.com/user-attachments/assets/584fcbf9-2660-4537-a2fe-5473b149e3c3)

**Comment by mcmonkey4eva** [comment]
Could you test https://github.com/Comfy-Org/ComfyUI_frontend/pull/475 and see if it properly resolves the recalculateStyle spam?

Potentially a `if (display != val) { display = val }` is needed to avoid set handlers from running, but hopefully browser is smart enough to not need that?
