### ISSUE TITLE
[Feature Request]: Allow negative weights in Comfy.EditAttention core extension

### ISSUE THREAD

**Issue by pamparamm** [Comfy-Org/ComfyUI_frontend#474]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Comfy.EditAttention clamps weight values at 0, making it rather inconvenient to use hotkeys together with NegPip extension which can utilize negative weights.

Is it possible to add some sort of a switch to the settings to make `incrementWeight` function skip `if (newWeight < 0)` condition?

### Proposed workflow

1. Open Settings/Comfy/Edit Attention
2. Activate checkbox "Allow negative weights"
3. It's now possible to set attention weights to negative values by using ctrl+down hotkey

**Comment by mcmonkey4eva** [comment]
PR to allow this https://github.com/Comfy-Org/ComfyUI_frontend/pull/476
