### ISSUE TITLE
the preview image node does not display the image until the ksampler process finishes running

### ISSUE THREAD

**Issue by tu1997tu** [Comfy-Org/ComfyUI_frontend#477]
problem is that after updating the new interface, the preview image node does not display the image until the ksampler process finishes running. 1 ksampler is not affected, but a process with 2 ksamplers does not work.

https://github.com/user-attachments/assets/2726152b-248e-42c8-af3c-41a2fe301a7e

**Comment by mcmonkey4eva** [comment]
I think this is a ComfyUI issue related to 2666 (Execution Inversion) rather than specific to this new frontend repo?

**Comment by EasyComfyui** [comment]
> I think this is a ComfyUI issue related to 2666 (Execution Inversion) rather than specific to this new frontend repo?

it only happens when i update to the new interface

**Comment by mcmonkey4eva** [comment]
Execution Inversion and the new frontend were merged on the same day, which is slightly awkward

I relayed this issue direct to comfy and he pushed a fix https://github.com/comfyanonymous/ComfyUI/commit/14af129c5509d10504113a1520c45b0ebcf81f14
