### ISSUE TITLE
[Feature Request]: Queue preview Image should pull from save image node or last (not first) image preview

### ISSUE THREAD

**Issue by JLuke73** [Comfy-Org/ComfyUI_frontend#479]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Currently in a workflow with multiple preview images, the new Queue feature's image history pulls from the first image preview node. So, for example, in a ControlNet workflow you might get a preview of an unchanging depth map as you iterate over several seeds, or in a SEGM workflow you might get a mask preview.

### Proposed workflow

1. Scan for right-most or final (?) preview image or save image node, or the one completed last
2. Pull that image into the queue preview

**Comment by hartmark** [comment]
+1 this works be nice and also if possible to see all generated images
