### ISSUE TITLE
[Feature Request]: Add Escape keydown event for queue interrupting

### ISSUE THREAD

**Issue by DmitryFX** [Comfy-Org/ComfyUI_frontend#485]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Escape key should invoke api.interrupt() to stop all computations.

### Proposed workflow

1. Press Escape
2. Queue interrupted

### Additional information

It's pretty simple from my point of view.
While using old UI I have simply added something like

```
if( e.key === 'Escape' ) {
	api.interrupt();
}
```
to app.js

And everything worked as expected.

**Comment by huchenlei** [comment]
The interrupt action is already bounded to Ctrl + Alt + Enter here:
https://github.com/Comfy-Org/ComfyUI_frontend/blob/05c6193a1d6cdc4787375fbe7c29ed0d5a206387/src/extensions/core/keybinds.ts#L10-L20

The keybinding management/customization is on our roadmap. Currently we just can't converge on a keybinding that satisfies everyone.
