### ISSUE TITLE
[Bug]: Missing nodes from nodes selector

### ISSUE THREAD

**Issue by rgthree** [Comfy-Org/ComfyUI_frontend#494]
### Frontend Version

1.2.23

### Expected Behavior

Opening the node selector shows same nodes as old UI did.

### Actual Behavior

New UI's node selector is missing many nodes.

### Steps to Reproduce

Open the new UI node selector, either from the left bar or by double clicking. Search for "rgthree" to filter to rgthree-comfy nodes.

Notice the list is missing many nodes, including the popular Bookmark, Reroute, Fast Group Muter, etc.

### Debug Logs

```powershell
N/a
```

### Browser Logs

None applicable.

### Other

Note, the missing nodes are virtual nodes, extended from LiteGraph LGraphNode and doing the normal registration process. I notice other virtual nodes appear, like "Note" etc. AND these used to appear fine in the old UI, so my expectation is these should appear here as well.

![Screenshot 2024-08-17 150357](https://github.com/user-attachments/assets/c2c24c67-8d3e-4f8a-8bb4-4b355cf67cca)

**Comment by rgthree** [comment]
Originally reported here https://github.com/comfyanonymous/ComfyUI/issues/4445

**Comment by JorgeR81** [comment]
Some custom nodes are in a different folder.
Not sure why.

![rg](https://github.com/user-attachments/assets/50bbedee-851c-4ed9-b435-25a02166d0ee)

**Comment by rgthree** [comment]
Nice, just pulled the latest and it looks like it was fixed between 1.2.23 and 1.2.26. I do wish they were in their real folder, but at least we can get to them now.
