### ISSUE TITLE
[Bug]: Load image node not accepting image drop in FireFox

### ISSUE THREAD

**Issue by huchenlei** [Comfy-Org/ComfyUI_frontend#498]
### Frontend Version

1.2.26

### Expected Behavior

Load image node accepts a image drop and load the image

### Actual Behavior

The workflow is loaded instead.

### Steps to Reproduce

1. Open firefox
2. Add a `Load Image` node
3. Drag a image from file explore on the load image node
4. Observe the workflow in the image metadata is loaded

### Debug Logs

```powershell
N/A
```

### Browser Logs

No browser log when dropping the image.

### What browsers do you use to access the UI ?

Mozilla Firefox

**Comment by christian-byrne** [comment]
Seems like it was fixed at some point. On 1.2.47:


https://github.com/user-attachments/assets/1e0cf053-7596-4dfa-94e5-98496da0eee0
