### ISSUE TITLE
[Bug]: what is this? how can I close it?

### ISSUE THREAD

**Issue by botnang** [Comfy-Org/ComfyUI_frontend#503]
### Frontend Version

latest

### Expected Behavior

close it

### Actual Behavior

I don't know what is it, and the "close" button not working,

![image](https://github.com/user-attachments/assets/3371d9a5-3b97-41dd-b610-c8468eab50a7)

### Steps to Reproduce

start comfyui

### Debug Logs

```powershell
no any errors
```

### Browser Logs

no any errors

### What browsers do you use to access the UI ?

Microsoft Edge

**Comment by JorgeR81** [comment]
Try disabling: 
- ComfyUI-3D-Pack
- ComfyUI-N-Sidebar

https://github.com/comfyanonymous/ComfyUI/issues/3894#issuecomment-2198589767

**Comment by botnang** [comment]
> Try disabling: 
> 
> * ComfyUI-3D-Pack
> * ComfyUI-N-Sidebar
> 
> [comfyanonymous/ComfyUI#3894 (comment)](https://github.com/comfyanonymous/ComfyUI/issues/3894#issuecomment-2198589767)

thanx :-)
