### ISSUE TITLE
[Bug]: Stuck searching for nodes 

### ISSUE THREAD

**Issue by visaeon** [Comfy-Org/ComfyUI_frontend#504]
### Frontend Version

latest comfy commit 

### Expected Behavior

Double click presents all nodes 

### Actual Behavior

double click just shows a search bar and does not display anything

### Steps to Reproduce

Im not sure how to reproduce it on another machine

### Debug Logs

```powershell
Nothing to note in terminal logs relating to the issue
```

### Browser Logs

TypeError: nodeSearchService is undefined
    setup NodeSearchFilter.vue:53
    createHook runtime-core.esm-bundler.js:1808
    callWithErrorHandling runtime-core.esm-bundler.js:195
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:202
    __weh runtime-core.esm-bundler.js:1788
    flushPostFlushCbs runtime-core.esm-bundler.js:379
    flushJobs runtime-core.esm-bundler.js:415
    flushJobs runtime-core.esm-bundler.js:419
    promise callback*queueFlush runtime-core.esm-bundler.js:319
    queueJob runtime-core.esm-bundler.js:313
    effect runtime-core.esm-bundler.js:5258
    resetScheduling reactivity.esm-bundler.js:262
    triggerEffects reactivity.esm-bundler.js:306
    triggerRefValue reactivity.esm-bundler.js:1071
    set value reactivity.esm-bundler.js:1118
    canvasEventHandler NodeSearchBoxPopover.vue:132
    processMouseDown litegraph.es.js:4532
    processMouseDown changeTracker.ts:176
    processMouseDown simpleTouchSupport.ts:102
    processMouseDown rgthree.js:224
    processMouseDown app.ts:1200
runtime-core.esm-bundler.js:270:12
TypeError: useNodeDefStore().nodeSearchService is undefined
    search3 NodeSearchBox.vue:103
    0 index-D8Zp4vRl.js:70915
    callWithErrorHandling runtime-core.esm-bundler.js:195
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:202
    emit runtime-core.esm-bundler.js:726
    search2 index.mjs:826
    onFocus4 index.mjs:339
    0 index.mjs:1132
    callWithErrorHandling runtime-core.esm-bundler.js:195
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:202
    invoker runtime-dom.esm-bundler.js:693
    reFocusInput NodeSearchBox.vue:121
    createHook runtime-core.esm-bundler.js:1808
    callWithErrorHandling runtime-core.esm-bundler.js:195
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:202
    __weh runtime-core.esm-bundler.js:1788
    flushPostFlushCbs runtime-core.esm-bundler.js:379
    flushJobs runtime-core.esm-bundler.js:415
    flushJobs runtime-core.esm-bundler.js:419
    promise callback*queueFlush runtime-core.esm-bundler.js:319
    queueJob runtime-core.esm-bundler.js:313
    effect runtime-core.esm-bundler.js:5258
    resetScheduling reactivity.esm-bundler.js:262
    triggerEffects reactivity.esm-bundler.js:306
    triggerRefValue reactivity.esm-bundler.js:1071
    set value reactivity.esm-bundler.js:1118
    canvasEventHandler NodeSearchBoxPopover.vue:132
    processMouseDown litegraph.es.js:4532
    processMouseDown changeTracker.ts:176
    processMouseDown simpleTouchSupport.ts:102
    processMouseDown rgthree.js:224
    processMouseDown app.ts:1200
runtime-core.esm-bundler.js:270:12
Source map error: request failed with status 404
Resource URL: http://127.0.0.1:8188/extensions/ComfyUI_smZNodes/js/exif.js
Source Map URL: /sm/4f4f84956292156efc04b79e1131dc7c3a51794b7b3d62b43ed5eaca1b36d71e.map
Source map error: request failed with status 404
Resource URL: http://127.0.0.1:8188/kjweb_async/purify.min.js
Source Map URL: purify.min.js.map
Source map error: request failed with status 404
Resource URL: http://127.0.0.1:8188/extensions/comfy_mtb/extern/shodown.min.js
Source Map URL: showdown.min.js.map
Source map error: request failed with status 404
Resource URL: http://127.0.0.1:8188/extensions/comfy_mtb/extern/dom-purify.js
Source Map URL: purify.min.js.map
unreachable code after return statement Reflect.js:897:21
unreachable code after return statement Reflect.js:1029:21
unreachable code after return statement Reflect.js:1288:21
unreachable code after return statement Reflect.js:1354:21
The connection to ws://127.0.0.1:8188/ws was interrupted while the page was loading. api.ts:108:18
Firefox can’t establish a connection to the server at ws://127.0.0.1:8188/ws?clientId=c80b6c955c2a43ea93ae6e04dd494969. api.ts:108:18
Firefox can’t establish a connection to the server at ws://127.0.0.1:8188/ws?clientId=c80b6c955c2a43ea93ae6e04dd494969. api.ts:108:18
Firefox can’t establish a connection to the server at ws://127.0.0.1:8188/ws?clientId=c80b6c955c2a43ea93ae6e04dd494969. api.ts:108:18
Firefox can’t establish a connection to the server at ws://127.0.0.1:8188/ws?clientId=c80b6c955c2a43ea93ae6e04dd494969. api.ts:108:18

### What browsers do you use to access the UI ?

Mozilla Firefox

**Comment by huchenlei** [comment]
Please follow the instruction in bug report to disable all custom nodes and reopen if the issue persists. 

> - **3:** You confirmed that the bug is not caused by a custom node. You can disable all custom nodes by passing
        `--disable-all-custom-nodes` command line argument.

**Comment by visaeon** [comment]
The problem is solved when i disable all nodes. But as soon as i add a node such as manager the problem returns.
Ive spent hours trying to resolve it using chat gpt and claude but i cant seem to narrow down the problem,

I have tried several browsers, also a new version of comfy.

Im happy to provide any information that you may find helpfull

**Comment by huchenlei** [comment]
> The problem is solved when i disable all nodes. But as soon as i add a node such as manager the problem returns. Ive spent hours trying to resolve it using chat gpt and claude but i cant seem to narrow down the problem,
> 
> I have tried several browsers, also a new version of comfy.
> 
> Im happy to provide any information that you may find helpfull

So you can reproduce this issue with ComfyUI core + ComfyUI manager alone?

**Comment by visaeon** [comment]
The issue for me was 
ComfyUI_NestedNodeBuilder. I removed it, and everything is fine now.

You can now close this as solved

**Comment by gonzalu** [comment]
I do not have NestedNodeBuilder installed but, problem exists for me. I have a lot of custom nodes installed. Not sure if I can figure out which one might be causing the issue without a lot of work. Hopefully there is a way to debug this in a way that can find the culprit without re-installing each one at a time :( 

Thank you all.

**Comment by huchenlei** [comment]
> I do not have NestedNodeBuilder installed but, problem exists for me. I have a lot of custom nodes installed. Not sure if I can figure out which one might be causing the issue without a lot of work. Hopefully there is a way to debug this in a way that can find the culprit without re-installing each one at a time :(
> 
> Thank you all.

ComfyCLI has a bisect feature that can help you locate culprit custom node: https://github.com/Comfy-Org/comfy-cli#bisect-custom-nodes

**Comment by gonzalu** [comment]
> > I do not have NestedNodeBuilder installed but, problem exists for me. I have a lot of custom nodes installed. Not sure if I can figure out which one might be causing the issue without a lot of work. Hopefully there is a way to debug this in a way that can find the culprit without re-installing each one at a time :(
> > Thank you all.
> 
> ComfyCLI has a bisect feature that can help you locate culprit custom node: https://github.com/Comfy-Org/comfy-cli#bisect-custom-nodes

How do I use it? I am sorry I can;t figure it out... do I just run 

```
$comfy blah blah
```

??

**Comment by huchenlei** [comment]
> > > I do not have NestedNodeBuilder installed but, problem exists for me. I have a lot of custom nodes installed. Not sure if I can figure out which one might be causing the issue without a lot of work. Hopefully there is a way to debug this in a way that can find the culprit without re-installing each one at a time :(
> > > Thank you all.
> > 
> > 
> > ComfyCLI has a bisect feature that can help you locate culprit custom node: https://github.com/Comfy-Org/comfy-cli#bisect-custom-nodes
> 
> How do I use it? I am sorry I can;t figure it out... do I just run
> 
> ```
> $comfy blah blah
> ```
> 
> ??

Install it first by `pip install comfy-cli` (ref: https://github.com/Comfy-Org/comfy-cli#installation)

**Comment by gonzalu** [comment]
Thank you, I have it installed when I added my custom nodes to the registry. 

So, just use it as that? While comfy is running or not?

**Comment by gonzalu** [comment]
OK, the bisect did not find anything that was causing it... will ALL NODES disabled, it is still there. So, it is MANAGER. 

If I disable the MANAGER, the problem goes away...

**Comment by christian-byrne** [comment]
> OK, the bisect did not find anything that was causing it... will ALL NODES disabled, it is still there. So, it is MANAGER.
> 
> If I disable the MANAGER, the problem goes away...

Did you try updating or reinstalling the manager? You should post browser logs.

**Comment by gonzalu** [comment]
I did not try to reinstall manager. I did update it as I update Comfyui regularly via the manager itself. 

Let me look at the browser logs

Thank you

**Comment by gonzalu** [comment]
no joy. Only time it works is if I have NO custom nodes installed... not even the manager. 

So,  should I share my browser logs here? If so, how should I go about that? 

Thank you again.

**Comment by gonzalu** [comment]
```

logging.ts:331  TypeError: Cannot read properties of undefined (reading 'nodeFilters')
    at NodeSearchFilter.vue:53:37
    at runtime-core.esm-bundler.js:1808:40
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:1788:19)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:379:35)
    at flushJobs (runtime-core.esm-bundler.js:415:5)
    at flushJobs (runtime-core.esm-bundler.js:419:7)
console.<computed> @ logging.ts:331
logError @ runtime-core.esm-bundler.js:270
handleError @ runtime-core.esm-bundler.js:252
callWithErrorHandling @ runtime-core.esm-bundler.js:197
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:202
hook.__weh.hook.__weh @ runtime-core.esm-bundler.js:1788
flushPostFlushCbs @ runtime-core.esm-bundler.js:379
flushJobs @ runtime-core.esm-bundler.js:415
flushJobs @ runtime-core.esm-bundler.js:419
Promise.then
queueFlush @ runtime-core.esm-bundler.js:319
queueJob @ runtime-core.esm-bundler.js:313
(anonymous) @ runtime-core.esm-bundler.js:5258
resetScheduling @ reactivity.esm-bundler.js:262
triggerEffects @ reactivity.esm-bundler.js:306
triggerRefValue @ reactivity.esm-bundler.js:1071
set value @ reactivity.esm-bundler.js:1118
canvasEventHandler @ NodeSearchBoxPopover.vue:128
LGraphCanvas.processMouseDown @ litegraph.es.js:4532
LGraphCanvas.processMouseDown @ changeTracker.ts:176
LGraphCanvas.processMouseDown @ simpleTouchSupport.ts:102
LGraphCanvas.processMouseDown @ rgthree.js:224
LGraphCanvas.processMouseDown @ app.ts:1204
Show 16 more frames
Show less
[NEW] Explain Console errors by using Copilot in Edge: click
         
         to explain an error. 
        Learn more
        
          
          
          Don't show again
        
logging.ts:331  TypeError: Cannot read properties of undefined (reading 'searchNode')
    at search (NodeSearchBox.vue:115:26)
    at createVNode.onComplete._cache.<computed>._cache.<computed> (NodeSearchBox.vue:148:28)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
    at emit (runtime-core.esm-bundler.js:726:5)
    at Proxy.search (index.mjs:826:12)
    at Proxy.onFocus (index.mjs:339:14)
    at _ctx.multiple.mergeProps.onFocus._cache.<computed>._cache.<computed> (index.mjs:1132:51)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
console.<computed> @ logging.ts:331
logError @ runtime-core.esm-bundler.js:270
handleError @ runtime-core.esm-bundler.js:252
callWithErrorHandling @ runtime-core.esm-bundler.js:197
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:202
emit @ runtime-core.esm-bundler.js:726
search @ index.mjs:826
onFocus @ index.mjs:339
_ctx.multiple.mergeProps.onFocus._cache.<computed>._cache.<computed> @ index.mjs:1132
callWithErrorHandling @ runtime-core.esm-bundler.js:195
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:202
invoker @ runtime-dom.esm-bundler.js:693
reFocusInput @ NodeSearchBox.vue:133
(anonymous) @ runtime-core.esm-bundler.js:1808
callWithErrorHandling @ runtime-core.esm-bundler.js:195
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:202
hook.__weh.hook.__weh @ runtime-core.esm-bundler.js:1788
flushPostFlushCbs @ runtime-core.esm-bundler.js:379
flushJobs @ runtime-core.esm-bundler.js:415
flushJobs @ runtime-core.esm-bundler.js:419
Promise.then
queueFlush @ runtime-core.esm-bundler.js:319
queueJob @ runtime-core.esm-bundler.js:313
(anonymous) @ runtime-core.esm-bundler.js:5258
resetScheduling @ reactivity.esm-bundler.js:262
triggerEffects @ reactivity.esm-bundler.js:306
triggerRefValue @ reactivity.esm-bundler.js:1071
set value @ reactivity.esm-bundler.js:1118
canvasEventHandler @ NodeSearchBoxPopover.vue:128
LGraphCanvas.processMouseDown @ litegraph.es.js:4532
LGraphCanvas.processMouseDown @ changeTracker.ts:176
LGraphCanvas.processMouseDown @ simpleTouchSupport.ts:102
LGraphCanvas.processMouseDown @ rgthree.js:224
LGraphCanvas.processMouseDown @ app.ts:1204
Show 26 more frames
Show less
2logging.ts:331  TypeError: Cannot read properties of undefined (reading 'searchNode')
    at search (NodeSearchBox.vue:115:26)
    at createVNode.onComplete._cache.<computed>._cache.<computed> (NodeSearchBox.vue:148:28)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
    at emit (runtime-core.esm-bundler.js:726:5)
    at Proxy.search (index.mjs:826:12)
    at index.mjs:418:22
console.<computed> @ logging.ts:331
logError @ runtime-core.esm-bundler.js:270
handleError @ runtime-core.esm-bundler.js:252
callWithErrorHandling @ runtime-core.esm-bundler.js:197
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:202
emit @ runtime-core.esm-bundler.js:726
search @ index.mjs:826
(anonymous) @ index.mjs:418
setTimeout
onInput @ index.mjs:417
_ctx.multiple.mergeProps.onInput._cache.<computed>._cache.<computed> @ index.mjs:1141
callWithErrorHandling @ runtime-core.esm-bundler.js:195
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:202
invoker @ runtime-dom.esm-bundler.js:693
Show 12 more frames
Show less

```

**Comment by christian-byrne** [comment]
It may be the case of custom nodes creating persistent files outside of custom_nodes folder. If you cloned ComfyUI, you can navigate to ComfyUI folder in command prompt and share output when you enter `git status`.

Otherwise you should make a copy of important folders like `models`, `input`, `output`, `extra_model_paths.yaml`, then delete and reinstall ComfyUI.

**Comment by gonzalu** [comment]
Thank you... here is what is odd... just now, without restarting Comfy or making any changes since I posted the above, it now works ....  WTF? 

![image](https://github.com/user-attachments/assets/f8f01e40-87f4-4ff0-9629-cfb2609c9f30)

**Comment by gonzalu** [comment]
> It may be the case of custom nodes creating persistent files outside of custom_nodes folder. If you cloned ComfyUI, you can navigate to ComfyUI folder in command prompt and share output when you enter `git status`.
> 
> Otherwise you should make a copy of important folders like `models`, `input`, `output`, `extra_model_paths.yaml`, then delete and reinstall ComfyUI.

I installed ComfyUI portable from the 7z file back in January 2024 and have just been updating via manager ever since.
