### ISSUE TITLE
ComfyUI UI-update. Mouse behavior changed?  // Also viewport browsing is totally broken in lates FIREFOX.

### ISSUE THREAD

**Issue by bkmikaelo7** [Comfy-Org/ComfyUI_frontend#515]
Hello. Did you change the mouse middle button behaviour for the latest UI update? The mouse wheel now scrolls instead of zooming. I just can't live with this. zoomin in and out is 90% of the UI work so pressing cmd/cntrl is really cumbersome. Cannot find a setting to revert to old behaviour of middle wheel zooming. Please add one if possible.

In Firefox I can't move or zoom the viewport at all !

**Comment by huchenlei** [comment]
Just tried firefox. Works fine. You can try disable all custom nodes and reopen if the issue persists. Please use the bug template to file bug. The bug template contains guide to do basic diagnose.

https://github.com/user-attachments/assets/a032b428-b852-4334-b170-c6aca70ad808

**Comment by bkmikaelo7** [comment]
Solved! It was a conflicting node. Particularly Comfyui-tbox which caused both issues! Thank you and sorry for the inconvenience.
