### ISSUE TITLE
[Feature Request]: To prevent non-square images from being cropped in the Queue media preview.

### ISSUE THREAD

**Issue by toyxyz** [Comfy-Org/ComfyUI_frontend#525]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Thanks for adding GIFs to the media preview!

Images/GIFs that are not square in the media preview will be cropped. 

It would be very convenient if you could add a margin option to view long horizontal/vertical images that are not in a 1:1 ratio so they don't get cropped. 

![image](https://github.com/user-attachments/assets/f2a7a034-793c-4b9b-89dc-56076ea397ca)

### Proposed workflow

1. Go to ....
2. Press ....
3. ...

**Comment by huchenlei** [comment]
Done in https://github.com/Comfy-Org/ComfyUI_frontend/pull/646
