### ISSUE TITLE
[Feature Request]: Suggestions for setting the display size of node lists

### ISSUE THREAD

**Issue by 807502278** [Comfy-Org/ComfyUI_frontend#528]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Regarding the settings here, can two items be added to adjust the font size and line spacing of the plugin name and node name in the new node list?
![image](https://github.com/user-attachments/assets/134d8bbc-9823-4e84-baa2-8be31e59e435)
![image](https://github.com/user-attachments/assets/435478e7-1930-48bd-8ddf-599a1bc6bef5)

### Proposed workflow

For example, after adjusting the font size and line spacing in the settings (it is recommended that the font size range is  6  ~  32 pixel, and the spacing range is  -2  ~  16 pixel).
![image](https://github.com/user-attachments/assets/235c97bc-5b49-4eb9-bad5-dbb8369204de)
The font and spacing in this list will become similar to the ones on the left.  

### Additional information

Adjustment reason: Because there are too many plugins in ComfyUI. For example, when creating a new node in the right-click menu, the font is set very small to display more. However, for the current new list, although it is more convenient to find nodes, the font and spacing have become larger. If there are many search results, it will take a long time to scroll the mouse. Adding this setting can facilitate everyone to adjust it according to their own preferences.

**Comment by Amorano** [comment]
related item #407 -- the overall CSS needs to be tighter to start.

All those nodes and no Jovimetrix. Sad.

**Comment by 807502278** [comment]
Indeed. Currently the arrangements in places related to the node list are not compact. a large number of nodes it is very inconvenient to operate in this way.

It feels that the workload of these modifications is too large and cannot be completed in a short time.

**Comment by toyxyz** [comment]
It would be very convenient if users could create folders to organize their custom nodes into categories. 

A simple custom icon and color change would make it even more visible.
