### ISSUE TITLE
[Bug]: Website not Reachable, "NS-ERROR-NET-RESET" response

### ISSUE THREAD

**Issue by njalooo** [Comfy-Org/ComfyUI_frontend#536]
### Frontend Version

1.2.26

### Expected Behavior

See a Website

### Actual Behavior

The connection was reset Error. In Firefox debug, GET response was NS-ERROR-NET-RESET.

### Steps to Reproduce

Install on debian:
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.0
apt update -y
apt install -y git
git clone https://github.com/comfyanonymous/ComfyUI.git
apt install -y cargo cmake g++ gcc python3-dev musl-dev make nasm
pip install -r /ComfyUI/requirements.txt

chmod +x /ComfyUI/main.py

### Debug Logs

```powershell
Total VRAM 20464 MB, total RAM 31803 MB
pytorch version: 2.4.0+rocm6.0
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 7900 XT : native
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
/ComfyUI/comfy/extra_samplers/uni_pc.py:19: SyntaxWarning: invalid escape sequence '\h'
"""Create a wrapper class for the forward SDE (VP type).
[Prompt Server] web root: /ComfyUI/web
/usr/local/lib/python3.12/site-packages/kornia/feature/lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
@torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Skipping loading of custom nodes
Starting server
To see the GUI go to: http://127.0.0.1:8188
```

### Browser Logs

{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "Firefox",
      "version": "129.0"
    },
    "browser": {
      "name": "Firefox",
      "version": "129.0"
    },
    "pages": [
      {
        "id": "page_2",
        "pageTimings": {
          "onContentLoad": -11563,
          "onLoad": -1724096122754
        },
        "startedDateTime": "2024-08-19T21:35:22.754+02:00",
        "title": "http://127.0.0.1:8188/"
      }
    ],
    "entries": [
      {
        "startedDateTime": "2024-08-19T21:35:22.754+02:00",
        "request": {
          "bodySize": 0,
          "method": "GET",
          "url": "http://127.0.0.1:8188/",
          "httpVersion": "",
          "headers": [
            {
              "name": "Host",
              "value": "127.0.0.1:8188"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0"
            },
            {
              "name": "Accept",
              "value": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.5"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, br, zstd"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Cookie",
              "value": "ai_dock_f560305a_token=$2a$14$AKtDtzyPMO3o7LUQFNNURuMl8zF6Yvv6A7m8I5AKQlTV0wWM7Z3VS"
            },
            {
              "name": "Upgrade-Insecure-Requests",
              "value": "1"
            },
            {
              "name": "Sec-Fetch-Dest",
              "value": "document"
            },
            {
              "name": "Sec-Fetch-Mode",
              "value": "navigate"
            },
            {
              "name": "Sec-Fetch-Site",
              "value": "none"
            },
            {
              "name": "Sec-Fetch-User",
              "value": "?1"
            },
            {
              "name": "Priority",
              "value": "u=0, i"
            }
          ],
          "cookies": [],
          "queryString": [],
          "headersSize": 577
        },
        "response": {
          "status": 0,
          "statusText": "",
          "httpVersion": "",
          "headers": [],
          "cookies": [],
          "content": {
            "mimeType": "",
            "size": 0,
            "encoding": "base64",
            "text": ""
          },
          "redirectURL": "",
          "headersSize": 0,
          "bodySize": 0
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": 1,
          "connect": 1,
          "ssl": 0,
          "send": 1,
          "wait": 0,
          "receive": 0
        },
        "time": 3,
        "_securityState": "insecure",
        "pageref": "page_2"
      }
    ]
  }
}

### What browsers do you use to access the UI ?

Mozilla Firefox

**Comment by huchenlei** [comment]
Is this a browser specific bug? Do you get expected result from other browsers?

**Comment by njalooo** [comment]
No, using chromium i got a simple unable to connect.

**Comment by njalooo** [comment]
Alright, solved the issue. Appearently you need to pass the --listen argument to main.py, when running it in a vm. Because localhost of course isn't really localhost, even with port-passthrough.
