### ISSUE TITLE
[Bug]: Cropping issue in Queue media gallery

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI_frontend#537]
### Frontend Version

1.2.28

### Expected Behavior

Watch the preview images in full screen

### Actual Behavior

Large images are cropped on the vertical side, especially portrait images.

### Steps to Reproduce

https://github.com/user-attachments/assets/76249880-ec7d-4d6f-94ce-767d3666f650

### Debug Logs

```powershell
No debug logs needed (I guess)
```

### Browser Logs

No browser logs needed (I guess)

### What browsers do you use to access the UI ?

Google Chrome

### Other

I had already mentioned the issue in my previous feature request (https://github.com/Comfy-Org/ComfyUI_frontend/issues/512).
@huchenlei  I don't know if you had already seen it, I opened this bug report just to be sure.

**Comment by huchenlei** [comment]
@LukeG89 Thanks for raising this issue! Please create a new issue for each of the bugs later as I might be unable to catch up with GitHub notifications in time. Thanks!
