### ISSUE TITLE
[Bug]: "Overlay mask prevents clicking."

### ISSUE THREAD

**Issue by shadowcz007** [Comfy-Org/ComfyUI_frontend#552]
### Frontend Version

ComfyUI Front-end version: 1.2.26

### Expected Behavior

init

### Actual Behavior

"The mouse cannot click."

### Steps to Reproduce

0

### Debug Logs

```powershell
0
```

### Browser Logs

![1724119668113](https://github.com/user-attachments/assets/09439370-5ff3-4f6c-af22-04bcb3cecfd3)

**Comment by huchenlei** [comment]
https://github.com/Comfy-Org/ComfyUI_frontend/issues/495
