### ISSUE TITLE
[Bug]: Fail to import the custom node that i worte myself

### ISSUE THREAD

**Issue by Govee-Chan** [Comfy-Org/ComfyUI_frontend#555]
### Frontend Version

Hello fellows!
I had a few custom nodes work fine until the version bfc214f434e9c92d05d755857c597733a7fd3b91 ([Use new TS frontend uncompressed). (5 works fine, 1 fail)

When I load the workflow than contains the node, it just turn red.

The node load phrase seems fine:
![WX20240820-122041@2x](https://github.com/user-attachments/assets/638c3a8c-54d4-4275-a447-880527cfd169)

I wonder if the import rules have been change, or due to the UI/UX change. 

### Expected Behavior

x

### Actual Behavior

![WX20240820-121701@2x](https://github.com/user-attachments/assets/c26fb385-1dad-4202-bec2-190eae0d0ac4)

### Steps to Reproduce

x

### Debug Logs

```powershell
x
```

### Browser Logs

x

### What browsers do you use to access the UI ?

Google Chrome

**Comment by huchenlei** [comment]
Please reopen a bug report with all information asked including your extension code. We won't be able to know what happened based on the information you offered now.
