### ISSUE TITLE
[Bug]: fuse.js extended search unintuitive results

### ISSUE THREAD

**Issue by christian-byrne** [Comfy-Org/ComfyUI_frontend#562]
### Frontend Version

1.2.28

### Expected Behavior

Search to behave similar to other search features.

### Actual Behavior

From the [fuse.js docs on extended search option](https://www.fusejs.io/examples.html#extended-search), when enabled:

> White space acts as an AND operator

This leads to unexepcted behavior when searching multiple words, like getting this when searching "Save Image":
![Selection_280](https://github.com/user-attachments/assets/5009f76a-0632-4701-a71c-9f2fa3540559)

Or this when searching "VAE Decode":

![Selection_281](https://github.com/user-attachments/assets/ab7e962c-10db-4175-9b0a-0bebd6289fea)

This was pointed out by SirVeggie on discord.

### Steps to Reproduce

1. Search multi-word phrases in search

### Debug Logs

```powershell
.
```

### Browser Logs

.

### What browsers do you use to access the UI ?

Google Chrome

### Other

When extended search is enabled, "VAE Decode" matches to "VAE Decode" with a score of 0.06403390388180329 and "VAEDecodeAudio" with a score of 0.0155. When extended search is disabled, "VAE Decode" matches to "VAE Decode" with a perfect score (0) and "VAEDecodeAudio" with a score of 0.3.

**Comment by christian-byrne** [comment]
The suggested solution was to keep `useExtendedSearch` enabled, since the tokenization improves accuracy of mixed-word-order searches, and to implement a custom sort function that sorted matches with very similar scores based on length. It was also suggested that the issue should be solved by using Bayesian search with telemetry data.

**Comment by SirVeggie** [comment]
Here's my suggestion for the custom sort function that seems to work well:
`Math.abs(a.score - b.score) > 0.01 ? a.score - b.score : (a.item[1]['v']['length'] - b.item[1]['v']['length'] || a.idx - b.idx)`
![image](https://github.com/user-attachments/assets/82503b27-7b04-4c09-b099-725786c58b51)

**Comment by christian-byrne** [comment]
> Here's my suggestion for the custom sort function that seems to work well: `Math.abs(a.score - b.score) > 0.01 ? a.score - b.score : (a.item[1]['v']['length'] - b.item[1]['v']['length'] || a.idx - b.idx)` ![image](https://private-user-images.githubusercontent.com/32365239/359643468-82503b27-7b04-4c09-b099-725786c58b51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxOTc0ODAsIm5iZiI6MTcyNDE5NzE4MCwicGF0aCI6Ii8zMjM2NTIzOS8zNTk2NDM0NjgtODI1MDNiMjctN2IwNC00YzA5LWIwOTktNzI1Nzg2YzU4YjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDIzMzk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZTcyOTQ0NGFmZDQzYjUwY2E4ZmMyOTI2YmVlOWJkOWU3MGFkM2EzNmI4Y2UzNjkxNWZiYjNmZThiYzQzMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XSWhaFxjFHdnz4DdnR_pApq-iwk2h5ZaTXO5anofAMs)

[Comparison of current method vs. sorting function](https://editor.mergely.com/wbahHuoh) using all token permutations. It seems better in almost every scenario.

**Comment by huchenlei** [comment]
Thanks for the comparison function and benchmark!

**Comment by huchenlei** [comment]
I think the sort function is a bit off in some cases: 
![image](https://github.com/user-attachments/assets/8f6178dd-08d5-4e87-8246-e60731f2a0bc)

**Comment by christian-byrne** [comment]
> I think the sort function is a bit off in some cases: ![image](https://private-user-images.githubusercontent.com/20929282/360048884-8f6178dd-08d5-4e87-8246-e60731f2a0bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNjcwNjcsIm5iZiI6MTcyNDI2Njc2NywicGF0aCI6Ii8yMDkyOTI4Mi8zNjAwNDg4ODQtOGY2MTc4ZGQtMDhkNS00ZTg3LTgyNDYtZTYwNzMxZjJhMGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDE4NTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkN2UzNTJkODk0ZDExYTBhYWU4YzNlYjMzMDg0YmE5ZjZjZGU0MTUyNGI3MDgzYjFhNmRkZjk0NzM3NDFiNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QLADJeHZd0VmpSm8Qj4qZgYJT62133NSOxBNEPyJRgo)

Are you getting "CLIP Text Encode (Prompt)" as the first option normally?

For me this is with vs. without sorting function:

![Selection_281](https://github.com/user-attachments/assets/414cf921-de11-4eaa-8dbf-4851d39310c5)

I only get "CLIP Text Encode (Prompt)" as first result after I disable the extended search in fuse config.

**Comment by christian-byrne** [comment]
[Extended search vs. no extended search comparison](https://editor.mergely.com/epsEmEob)

Extended search has a lot of upsides when the ordering of words is incorrect in search phrase e.g. "Encode VAE" or "Image Save"

**Comment by huchenlei** [comment]
I do get the correct one when "CLIP Text Encode" is used as query before. And that one is used in the playwright test unfortunately. 
![image](https://github.com/user-attachments/assets/946fcb0c-0126-4d0c-b35c-c71542a987b2)

**Comment by christian-byrne** [comment]
I see, it's "CLIPTextEncode." I misunderstood

https://github.com/Comfy-Org/ComfyUI_frontend/blob/f2de9b0d3c547c814baeb736dbecaedd3c41705e/browser_tests/nodeSearchBox.spec.ts#L39

![Selection_282](https://github.com/user-attachments/assets/537ba0c8-b007-45c2-86af-a5351dd0f734)

**Comment by SirVeggie** [comment]
the reason why it's correct in the test you mentioned, is that when you type the exact node id, the old method is better in this outlier case, if you're missing even one letter, the old method results are equally bad.

![image](https://github.com/user-attachments/assets/e6becfed-0031-4a15-a7ef-f30f15d78024)
![image](https://github.com/user-attachments/assets/349bd718-d805-47b1-a340-7d666ff2d23f)

Fixing exact matches can be done fairly easily by adding an additional condition `Math.min(a.score, b.score) < 0.0001`:
```sortFn: (a, b) => Math.min(a.score, b.score) < 0.0001 || Math.abs(a.score - b.score) > 0.01 ? a.score - b.score : (a.item[1]['v']['length'] - b.item[1]['v']['length'] || a.idx - b.idx)```

I have another version that uses the node index instead of node title length. this one is "less correct", since it doesn't prioritize match accuracy, but in exchange it is closer to the og. sort order of the old UI. I think it's determined by the order in which the nodes are loaded? I'm not exactly sure. it also fixes many of the same problems the previous version aimed to fix.

this one basically prioritizes core nodes first, and based on their definition/load order. as a downside it's slightly worse for custom nodes, as the load/definition order of those is pretty "random". it should yield results that are more familiar, even if less accurate.

```sortFn: (a, b) => Math.abs(a.score - b.score) > 0.01 ? a.score - b.score : a.idx - b.idx```

![image](https://github.com/user-attachments/assets/388c8abc-9692-4a62-858e-883964dc594a)
![image](https://github.com/user-attachments/assets/f69abd60-a6f3-4f2f-9acf-eb9316300023)
