### ISSUE TITLE
[Feature Request]: Flow with multiple generated images should prioritize Saved Image

### ISSUE THREAD

**Issue by hartmark** [Comfy-Org/ComfyUI_frontend#570]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I have a workflow that has a "preview image" and then I do a reactor face swap and I save the resulting image.

I see that two images have been created, but the thumbnail shows the preview image.
![image](https://github.com/user-attachments/assets/ef7fd0d1-36b8-4c6e-b7b6-19ca07503e16)

You can try my workflow embedded in this image:
![ComfyUI_01067_](https://github.com/user-attachments/assets/4c457ab3-d955-4696-af46-68f322951b28)

### Proposed workflow

If multiple images are generated the image that has "Save" should be shown before any preview images.

Also it would be nice to be able to see both two generated images if possible

**Comment by hartmark** [comment]
It would also be quite cool if the spinner in the queue would show the previewed picture when it's available and not wait for the whole workflow to be completed.

I don't know if you have the intermediate results available before the workflow is completed so that is just a nice to have feature. Especially if you have a slow upscaler step and want to see what have been generated so far in the workflow.

**Comment by huchenlei** [comment]
Duplicated https://github.com/Comfy-Org/ComfyUI_frontend/issues/479.



> It would also be quite cool if the spinner in the queue would show the previewed picture when it's available and not wait for the whole workflow to be completed.
> 
> I don't know if you have the intermediate results available before the workflow is completed so that is just a nice to have feature. Especially if you have a slow upscaler step and want to see what have been generated so far in the workflow.

Can you file a new request for this live preview feature? I think the current backend API does support that. It's a good suggestion.
