### ISSUE TITLE
[Feature Request]: Clicking on ends of a connection allows you to reroute or delete that connection

### ISSUE THREAD

**Issue by memo** [Comfy-Org/ComfyUI_frontend#577]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

In some node based software, there are handles on either end of a connection which allows you to disconnect that end and reconnect to another node.
This makes debugging and editing node graphs much easier.
(Note, this kind of already works in comfyui on the outgoing end of a connection if you click on the input port of the connected node, but it doesn't work on the incoming end of a connection, because the connected output port can have multiple outgoing connections. Which is why Max opted for additional handles near the ends of the connections).

Max is a really good example of this. See attached video
(I've separated hilighting and rereouting into separate issues. See also #575)

https://github.com/user-attachments/assets/0ec9f99a-faf0-4d49-88e0-104f08609e76

**Comment by huchenlei** [comment]
Batch drag and batch disconnect implemented in 1.2.7. See https://github.com/Comfy-Org/ComfyUI_frontend?tab=readme-ov-file#qol-changes section for videos.
