### ISSUE TITLE
[Feature Request]: Show intermediate images on workflows that are running

### ISSUE THREAD

**Issue by hartmark** [Comfy-Org/ComfyUI_frontend#581]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Load this simple workflow
![ComfyUI_01070_](https://github.com/user-attachments/assets/38f314cf-5629-4f3c-b86a-78e444caa66c)

I took a screenshot while KSampler is running, it would be nice if that preview would be shown instead of the spinning black box
![image](https://github.com/user-attachments/assets/d764593c-703c-475f-b4a4-5b53db042d04)

### Proposed workflow

While workflow is running the latest generated image should show instead this empty box with a spinner
![image](https://github.com/user-attachments/assets/08910366-1768-4854-8568-196a5c09287f)

### Additional information

When adding prompts via the API you get no feedback at all so this would make it more possible to check on the current progress of an API-added workflow.

**Comment by huchenlei** [comment]
@bezo97 is working on this issue
