### ISSUE TITLE
[Possible Bug]: Unexpected Jump to Shorcut while try write in label

### ISSUE THREAD

**Issue by Milor123** [Comfy-Org/ComfyUI_frontend#592]
### Frontend Version

commit 0466c797253caba83c357c5dca7f9138a5d805b7 (HEAD -> main, origin/main, origin/HEAD)
Author: bymyself <abolkonsky.rem@gmail.com>
Date:   Wed Aug 21 18:28:12 2024 -0700

    Fix right-click save image in gallery (firefox) (#588)

### Expected Behavior

Allow me write normally without jumps

### Actual Behavior

It jumps to the bookmark
![image](https://github.com/user-attachments/assets/269a8532-52f4-44a7-80ba-e7ed681a7521)

### Steps to Reproduce

Doble click in the label for edit in the custom panel
but when try change value like numbers press from my keyboard it jumps to the bookmarks

### Debug Logs

```powershell
No bugs show here
```

### Browser Logs

[127.0.0.1-1724336245532.log](https://github.com/user-attachments/files/16712000/127.0.0.1-1724336245532.log)

### What browsers do you use to access the UI ?

Other

### Other

Vivaldi in Manjaro

**Comment by huchenlei** [comment]
Cannot reproduce. Please try disable all custom nodes and re-open if issue persists.

**Comment by christian-byrne** [comment]
I think the bug has always existed.

The keybinds ignore event in `TEXTAREA` and `INPUT` elements:

https://github.com/Comfy-Org/ComfyUI_frontend/blob/0466c797253caba83c357c5dca7f9138a5d805b7/src/extensions/core/keybinds.ts#L29-L32

But the litegraph properties panel inputs are `SPAN`

**Comment by Milor123** [comment]
> I think the bug has always existed.
> 
> The keybinds ignore event in `TEXTAREA` and `INPUT` elements:
> 
> https://github.com/Comfy-Org/ComfyUI_frontend/blob/0466c797253caba83c357c5dca7f9138a5d805b7/src/extensions/core/keybinds.ts#L29-L32
> 
> But the litegraph properties panel inputs are `SPAN`

Guys thanks, question where should I report it? in the comfyui github ?

**Comment by christian-byrne** [comment]
> > I think the bug has always existed.
> > The keybinds ignore event in `TEXTAREA` and `INPUT` elements:
> > https://github.com/Comfy-Org/ComfyUI_frontend/blob/0466c797253caba83c357c5dca7f9138a5d805b7/src/extensions/core/keybinds.ts#L29-L32
> > 
> > But the litegraph properties panel inputs are `SPAN`
> 
> Guys thanks, question where should I report it? in the comfyui github ?

This is the right place. I will PR a fix for it.

**Comment by Milor123** [comment]
Thank guy very much for all guys!! I love this project ❤️
