### ISSUE TITLE
[Feature Request]: change Ctrl+Shift+Drag to select addition node

### ISSUE THREAD

**Issue by bedovyy** [Comfy-Org/ComfyUI_frontend#625]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Current: Ctrl + Shift + Drag is zooming screen
Request: Ctl + Shift + Drag to select additional nodes

Currently, select additional nodes is also possible with Ctrl + Drag then Shift,
But it is easy to mistake.

Zooming is also possible with wheel, also it is not has to be Ctrl+ Shift.
Alt + Drag is moving screen, so zooming can be changed to Alt + (Shift or Ctlr) + Drag.

### Proposed workflow

1. Ctrl + Drag (or Ctrl + Shift + Drag) to select multiple node.
2. Ctrl + Shift Drag to select addition node.

**Comment by huchenlei** [comment]
What do you mean by select additional node? If you want to select multiple nodes, you can hold `Ctrl` and click multiple nodes to select them all.

**Comment by bedovyy** [comment]
> What do you mean by select additional node? If you want to select multiple nodes, you can hold `Ctrl` and click multiple nodes to select them all.

Or you can Ctrl + Drag empty area to select multiple nodes in dragged area.
I much prefer this method than Ctrl + Click node.
![image](https://github.com/user-attachments/assets/11e682f2-478e-4ced-9fc3-95ea7b89e962)

And I wish Ctrl + Shift + Drag also do as current Ctrl + Drag then keep pressing Shift behaviour.

**Comment by huchenlei** [comment]
Just to make sure you are proposing we give an option to turn off the behavior of Shift-Ctrl-drag and replace it with the current Ctrl+drag behavior?

**Comment by bedovyy** [comment]
> Just to make sure you are proposing we give an option to turn off the behavior of Shift-Ctrl-drag and replace it with the current Ctrl+drag behavior?

I am suggesting to move shift+ctrl+drag to other shortcut, such as alt + (some) + drag, because alt + drag is screen relative behaviour,
> Alt + Drag is moving screen, so zooming can be changed to Alt + (Shift or Ctlr) + Drag.

_edit: alt + drag is actuall copy select node by drag. space + drag was screen relative.
so, what about ctrl + space + drag?_


then shift+ctrl+drag to current `ctrl+drag, shift` behaviour.
ctrl+drag and ctrl+drag, shift is diffrent.
when there's already selected nodes, ctrl+drag discard current selected nodes and select nodes newly from area, but ctrl+drag, shift keep current selected nodes and add additional nodes to selection from area i dragged.
