### ISSUE TITLE
[Feature Request]: Multiple groups selection and movement

### ISSUE THREAD

**Issue by alessandroperilli** [Comfy-Org/ComfyUI_frontend#645]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Today, there's no way to select multiple groups and move them. If you try selecting two groups, for example, you only end up selecting all the nodes from both groups and you move those nodes, not the two groups (and their nodes).

It would great if the user could select two or more groups in the same way we select nodes and drag them around, while preserving the relationship with their respective nodes.

### Proposed workflow

Click somewhere on the canvas, drag a rectangle that encompasses n groups, then drag by clicking and holding the title bar of any of the selected groups.

**Comment by tavyscrolls** [comment]
You've been able to do this by right-click > add group, placing workflow items on it and moving the group.

**Comment by SirVeggie** [comment]
This is one of the reasons why I don't use groups anymore. You can't select and move multiple of them at the same time, which makes workflow organization - which I do a lot of - feel pretty clunky.

**Comment by huchenlei** [comment]
Resolved by https://github.com/Comfy-Org/ComfyUI_frontend/pull/1416
