### ISSUE TITLE
[Bug]: How to fix: missing node PrepImageForInsightFace ... - ComfyUI

### ISSUE THREAD

**Issue by sothenthun** [Comfy-Org/ComfyUI_frontend#660]
### Frontend Version

[How to fix: missing node PrepImageForInsightFace ... - ComfyUI](https://comfyui-guides.runcomfy.com/ultimate-comfyui-how-tos-a-runcomfy-guide/how-to-fix-missing-node-prepimageforinsightface-ipadapterapplyfaceid-ipadapterapply-or-insightfaceloader)

### Expected Behavior

[How to fix: missing node PrepImageForInsightFace ... - ComfyUI](https://comfyui-guides.runcomfy.com/ultimate-comfyui-how-tos-a-runcomfy-guide/how-to-fix-missing-node-prepimageforinsightface-ipadapterapplyfaceid-ipadapterapply-or-insightfaceloader)

### Actual Behavior

[How to fix: missing node PrepImageForInsightFace ... - ComfyUI](https://comfyui-guides.runcomfy.com/ultimate-comfyui-how-tos-a-runcomfy-guide/how-to-fix-missing-node-prepimageforinsightface-ipadapterapplyfaceid-ipadapterapply-or-insightfaceloader)

### Steps to Reproduce

[How to fix: missing node PrepImageForInsightFace ... - ComfyUI](https://comfyui-guides.runcomfy.com/ultimate-comfyui-how-tos-a-runcomfy-guide/how-to-fix-missing-node-prepimageforinsightface-ipadapterapplyfaceid-ipadapterapply-or-insightfaceloader)

### Debug Logs

```powershell
How to fix: missing node PrepImageForInsightFace ... - ComfyUI
```

### Browser Logs

[How to fix: missing node PrepImageForInsightFace ... - ComfyUI](https://comfyui-guides.runcomfy.com/ultimate-comfyui-how-tos-a-runcomfy-guide/how-to-fix-missing-node-prepimageforinsightface-ipadapterapplyfaceid-ipadapterapply-or-insightfaceloader)

### Other

[How to fix: missing node PrepImageForInsightFace ... - ComfyUI](https://comfyui-guides.runcomfy.com/ultimate-comfyui-how-tos-a-runcomfy-guide/how-to-fix-missing-node-prepimageforinsightface-ipadapterapplyfaceid-ipadapterapply-or-insightfaceloader)

**Comment by LukeG89** [comment]
That is not a front-end bug and not even related to this repository, you should've opened this issue in [ComfyUI_IPAdapter_plus](https://github.com/cubiq/ComfyUI_IPAdapter_plus). 

However, `PrepImageForInsightFace` and other nodes no longer exist since Cubiq (the owner of IPAdapter Plus) made a breaking update at the end of March. Many old nodes are missing and you need change them with the new ones.
