### ISSUE TITLE
[Bug]: [Bug]: Model search box, go to the secondary model list search box and disappear, it is not easy to find the model，

### ISSUE THREAD

**Issue by k10719** [Comfy-Org/ComfyUI_frontend#661]
### Frontend Version

[Bug]: Model search box, go to the secondary model list search box and disappear, it is not easy to find the model，

### Expected Behavior

[Bug]: Model search box, go to the secondary model list search box and disappear, it is not easy to find the model，

### Actual Behavior

[Bug]: Model search box, go to the secondary model list search box and disappear, it is not easy to find the model，

### Steps to Reproduce

[Bug]: Model search box, go to the secondary model list search box and disappear, it is not easy to find the model，

### Debug Logs

```powershell
[Bug]: Model search box, go to the secondary model list search box and disappear, it is not easy to find the model，
```

### Browser Logs

[Bug]: Model search box, go to the secondary model list search box and disappear, it is not easy to find the model，

### What browsers do you use to access the UI ?

Microsoft Edge

**Comment by huchenlei** [comment]
Please file a feature request instead
