### ISSUE TITLE
[Bug]: Custom Color Palette is not being applied to all parts of the UI.

### ISSUE THREAD

**Issue by StellarBeing25** [Comfy-Org/ComfyUI_frontend#662]
### Frontend Version

1.2.30

### Expected Behavior

Color Palette should be applied to whole UI including Node Library Bar, Workflow Menu and Settings.

### Actual Behavior

![SSCUI](https://github.com/user-attachments/assets/bb636755-61a8-4ea5-9ded-c40ceadca96b)

### Steps to Reproduce

----

### Debug Logs

```powershell
----
```

### Browser Logs

----

### What browsers do you use to access the UI ?

Mozilla Firefox

**Comment by huchenlei** [comment]
The theme of menu and sidebar is now managed by PrimeVue's theme system. We will find a way to expose it as settings later.

You can read more here: https://primevue.org/theming/styled/ if you want to try tackle this task.
