### ISSUE TITLE
[Bug]: Flickering

### ISSUE THREAD

**Issue by tavyscrolls** [Comfy-Org/ComfyUI_frontend#665]
### Frontend Version

1.2.30

### Expected Behavior

No flickering

### Actual Behavior

'frames' of the UI from the last job (possibly many) flickers in with new ones, forcing a restart of comfy

### Steps to Reproduce

Starting with a freshly loaded workflow running in Firefox on Ubuntu, queue a prompt and let it run for a minute. Then any input comfyui receives will cause previous images of the workflow to flicker over the current workflow.

### Debug Logs

```powershell
Terminal doesn't output anything, refreshing or resetting view do nothing, oddly the flickering stops if mouse hovers comfy queue manager though it is equally likely to display old settings as new ones when it stops.
```

### Browser Logs

ComfyUI Front-end version: 1.2.30 index.html:4:11
Empty components: policy ignored components-manager.js:767:11
____
so nothing, but bringing the console up makes editing settings possible without the flicker. After closing it, the flicker becomes worse than before.

### What browsers do you use to access the UI ?

Mozilla Firefox

### Other

It hadn't done this until I updated nvidia, comfyui and reinstalled all packages since running last version of comfyui (~1 month old) and the only new extension is the cogvideox wrapper

**Comment by huchenlei** [comment]
Have you tested other OS / Browsers?

**Comment by tavyscrolls** [comment]
Would have to install on a completely separate build to test OS, but I installed Brave to check it. The first time, it froze the entire computer, which doesn't happen in Firefox. After rebooting, it ran pretty fine so I left Firefox open for another Brave test and it is definitely an issue related to Firefox, same everything else.

**Comment by blepping** [comment]
@tavyscrolls it's an issue with recent versions of the Nvidia driver on Linux and hardware acceleration.

you can disable hardware acceleration in Firefox by navigating to `about:config` and searching for `gfx.webrender.software`. toggle the setting to `true` and then restart the browser. Compositing should show as `WebRender (Software)` in `about:support`.

not an ideal fix but it seems to work. alternatively, upgrading to the latest git version of `egl-wayland` may also work too.

*edit*: removed the part about disabling hardware acceleration in the normal preferences as that does not seem to help.

**Comment by blepping** [comment]
i know it's been a while, but an alternative solution is to set `gfx.canvas.accelerated` to `false` instead. probably a better approach than just completely disabling all hardware acceleration.

(also, i don't really think this should be closed as it's an ongoing issue. should be left open for visibility at the least.)
