### ISSUE TITLE
[Bug]: Double-clicking node title region moves connections but also prompts for title change

### ISSUE THREAD

**Issue by ronan36880** [Comfy-Org/ComfyUI_frontend#666]
### Frontend Version

v1.2.38

### Expected Behavior

When I drag node B on top of node A and double click its title, node B will get all the incoming and outgoing connections from the node B.
![chrome_2024-03-27_12-12-42](https://github.com/user-attachments/assets/efcb9833-1dc9-4794-a32e-44ad93c979a7)

### Actual Behavior

When I drag node B on top of node A and double click its title, node B will also prompt me to change its title, which isn't what I want to do.
![Uploading chrome_2024-08-28_18-14-58.gif…]()

### Steps to Reproduce

Take the node `#5` and drag it over node `#5`. Then, double click the title region of the node. 
[workflow-bug.json](https://github.com/user-attachments/files/16786864/workflow-bug.json)

### Debug Logs

```powershell
N/A
```

### Browser Logs

N/A

### What browsers do you use to access the UI ?

Google Chrome

### Other

This "feature" was introduced in PR https://github.com/Comfy-Org/ComfyUI_frontend/pull/655 without any setting to disable renaming the node.

**Comment by huchenlei** [comment]
Set double click to None in ComfyUI-manager.

![image](https://github.com/user-attachments/assets/57de8d46-df58-429e-aef2-e8ee19de35db)

**Comment by ronan36880** [comment]
> Set double click to None in ComfyUI-manager.

@huchenlei thanks for the quick reply! My double-click setting is already set to what I want.
![image](https://github.com/user-attachments/assets/646ec596-1d2c-4b17-ba8c-9f157f07f642)

I want to disable the double-clicking title to rename nodes. Can we please reopen this issue until a setting for that gets implemented?

**Comment by huchenlei** [comment]
I can add a setting for that. For now you just need to remember to double click node body to trigger the ComfyUI-manager's db click behavior.

**Comment by huchenlei** [comment]
The setting will be available in today's nightly release.

**Comment by ronan36880** [comment]
> I can add a setting for that. For now you just need to remember to double click node body to trigger the ComfyUI-manager's db click behavior.

That change is _far from ideal_, but sure. I would personality want a setting to disable rename on double-click, but it's not something to really fight over.

Thanks a lot for the hardwork at improving the rough edges of Comfy's UI ❤️
