### ISSUE TITLE
[Bug]: 'Primitive' nodes for INT and FLOAT shrink after loading .json file

### ISSUE THREAD

**Issue by martin-rizzo** [Comfy-Org/ComfyUI_frontend#676]
### Frontend Version

v1.2.30

### Expected Behavior

When saving a workflow to a .json file and reloading it, 'Primitive' nodes representing integers (INT) and floating points (FLOAT) should retain their original size, ensuring that all options, including 'control_after_generate,' are visible and accessible.

### Actual Behavior

After saving the workflow to a .json file and reloading it, the 'Primitive' nodes for INT and FLOAT change in size, becoming smaller. This change not only appears to be a bug, but it also results in a size so small that the 'control_after_generate' options are not visible.

### Steps to Reproduce

Steps to Reproduce:
1. Create a new workflow in ComfyUI.
2. Add 'Primitive' nodes for INT and FLOAT.
3. Adjust the size of these nodes to ensure they are large enough to display all options.
4. Save the workflow as a .json file.
5. Reload the workflow from the .json file.
6. Observe that the size of the 'Primitive' nodes has shrunk, and the 'control_after_generate' option is no longer visible.
![bug-report](https://github.com/user-attachments/assets/08e22110-451f-4608-a874-271fdee459b8)
[bug-primitive-size.json](https://github.com/user-attachments/files/16790257/bug-primitive-size.json)

### Debug Logs

```powershell
Total VRAM 9913 MB, total RAM 31808 MB
pytorch version: 2.4.0+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: /home/aiman/AIMan/Repos/comfyui/web
Import times for custom nodes:
   0.0 seconds: /home/aiman/AIMan/Repos/comfyui/custom_nodes/websocket_image_save.py
Starting server
To see the GUI go to: http://127.0.0.1:8086
```

### Browser Logs

```
Uncaught TypeError: slot.widget[GET_CONFIG] is not a function
    at getWidgetConfig (widgetInputs.ts:376:55)
    at _RerouteNode.onConnectionsChange (rerouteNode.ts:172:34)
    at rerouteNode.ts:30:18
```

### What browsers do you use to access the UI ?

Google Chrome

### Other

1. This resizing issue does not occur with Primitive nodes that are of the STRING type.
2. I am using ComfyUI on Linux.

**Comment by huchenlei** [comment]
@pythongosssss Can you take a look at this? I am not very familiar with the impl of primitive node.

**Comment by pythongosssss** [comment]
Issue was caused as the PrimitiveNode adds the widgets dynamically, which causes litegraph to automatically resize the node.
