### ISSUE TITLE
[Feature Request]: In the view of historical images, add the option of right-clicking Save As 

### ISSUE THREAD

**Issue by hben35096** [Comfy-Org/ComfyUI_frontend#687]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

在浏览器中，历史图像列表，可以查看，却无法将图像另存为。
另外，似乎无法像以前一样，在任务列表中，取消正在进行的任务，或者删除将要进行的任务？
In the browser, a list of historical images can be viewed, but images cannot be saved as.
Also, it seems that it is not possible to cancel an ongoing task in the task list, or delete a task that will be carried out, as before?

### Proposed workflow

No

**Comment by huchenlei** [comment]
You can still delete with right click context menu.
![image](https://github.com/user-attachments/assets/e1f73db7-8f3d-43bd-98cb-6aeb8ae811c5)

Are you proposing an better way to access the delete method?

**Comment by hben35096** [comment]
Thanks for your reply, it helped me understand how to cancel the task.
Could you please provide an option to save the image when displaying it?
![PixPin_2024-08-30_22-44-32](https://github.com/user-attachments/assets/4de49901-26b2-4be5-9d87-894f1a006b08)
