### ISSUE TITLE
Some questions and suggestions about this project

### ISSUE THREAD

**Issue by JorgeR81** [Comfy-Org/ComfyUI_frontend#69]
I've just found this project. 
Not sure what the final goal is. 
Could this replace Comfy UI and Swarm UI ?

I assume you want to have the power of Comfy UI with some of the user friendly features of a traditional Frontend.
If so, here is my suggestion:

Add a Sidebar, similar to the new [Beta] Menu Bar, in Comfy UI.
This bar would be used to pin down node widgets.
The user could pin down widgets from multiple nodes, including the text prompt fields.
The widgets would be duplicated on the Sidebar, so the values could be changed on the node or the Sidebar.
The pinned widgets could be stored in the workflow, so we could build a sidebar configuration for each workflow.

The sidebar would look similar to a traditional GUI, like Invoke AI, but fully customizable.
This would have the advantages of a Frontend with all the flexibility of Comfy UI.

**Comment by huchenlei** [comment]
The goal is to replace the existing js frontend with full backward compatibility. See https://github.com/comfyanonymous/ComfyUI/pull/3897 for the plan. You will be able to use the TS frontend with `--front-end-version=main@latest` after the PR lands.

Your suggestions are mostly covered by our internal discussion. We will publish a more formal roadmap + timeline on implement these features once some technical directions are agreed by all parties.
