### ISSUE TITLE
[Bug]: Inconsistent JSON format for node position ("pos") between frontend v1.2.30 and v1.2.40

### ISSUE THREAD

**Issue by martin-rizzo** [Comfy-Org/ComfyUI_frontend#710]
### Frontend Version

v1.2.40

### Expected Behavior

I expected the workflow JSON files saved with ComfyUI frontend v1.2.40 to be compatible with those saved using previous versions, such as v1.2.30. This consistency would ensure backward compatibility and prevent any issues when loading workflows created in different versions.

### Actual Behavior

With ComfyUI frontend v1.2.40, the JSON format for storing node positions ("pos") has changed from an array to a dictionary format. For example, in v1.2.30, the "pos" data was stored as an array:
```
"pos": [
  600,
  340
]
```
In contrast, v1.2.40 stores the "pos" data as a dictionary with additional elements:
```
"pos": {
  "0": 600,
  "1": 340,
  "2": 0,
  "3": 0,
  "4": 0,
  "5": 0,
  "6": 0,
  "7": 0,
  "8": 0,
  "9": 0
}
```
While saving and loading workflows within the same frontend version (v1.2.40) works fine, this change could lead to incompatibility issues between different versions. There is already a related bug report that may be linked to this issue: [Issue #4743](https://github.com/comfyanonymous/ComfyUI/issues/4743)

### Steps to Reproduce

1. Save the same workflow using ComfyUI frontend v1.2.30 and another using v1.2.40.
2. Compare the resulting JSON files from each version.
3. Observe the differences in the "pos" data storage format between the two versions.

I've attached the two JSON files saved from each frontend version and a screenshot highlighting the differences between them.
[workflow-v1.2.30.json](https://github.com/user-attachments/files/16839981/workflow-v1.2.30.json)
[workflow-v1.2.40.json](https://github.com/user-attachments/files/16839983/workflow-v1.2.40.json)
![workflow-diff](https://github.com/user-attachments/assets/6760b684-5b1b-4229-8ef1-aa9c64b7a7cd)

### Debug Logs

```powershell
Total VRAM 9906 MB, total RAM 31809 MB
pytorch version: 2.4.0+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: /home/aiman/AIMan/Repos/comfyui/web
/home/aiman/AIMan/VEnv/comfyui-venv/lib64/python3.10/site-packages/kornia/feature/lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Skipping loading of custom nodes
Starting server
To see the GUI go to: http://127.0.0.1:8086
```

### Browser Logs

\-

### What browsers do you use to access the UI ?

Google Chrome

**Comment by martin-rizzo** [comment]
I did some more tests:
 - I tested older versions of the frontend, and they did not have any issues loading the new JSON files.
 - The error reported in [Issue #4743](https://github.com/comfyanonymous/ComfyUI/issues/4743) seems to be related to some external validation script. The change in the "pos" format within the JSON might not be a significant problem. I am not sure how the code handles this internally when loading workflows.
 - I don´t know if this is reserved for a future expansion, but it is still a bit unusual for 'pos' to have 9 elements in the dictionary.

**Comment by huchenlei** [comment]
Update your ComfyUI-Custom-Scripts extension to include following commit.
https://github.com/pythongosssss/ComfyUI-Custom-Scripts/commit/013894fa8278068d900ef56794ea66fd5bba33c6

Or simply disable the lock script.

**Comment by huchenlei** [comment]
Bug confirmed reproducable.

**Comment by huchenlei** [comment]
I think its following code causing the issue.
https://github.com/Comfy-Org/litegraph.js/blob/8a8ebb49067129739ab8eee441a25835d945bfcf/src/litegraph.js#L2352

The code has been there for a long while, but the bug is only triggered recently after a refactor on node construction in https://github.com/Comfy-Org/litegraph.js/pull/98.

**Comment by iamrohitanshu** [comment]
@martin-rizzo Hey if you don't mind, could you please tell me what application's screenshot that is, that you posted?
Also, how did you compare the two files, is it manual or the functionality of the application itself?

**Comment by huchenlei** [comment]
The fix will be available in today's nightly release 1.2.44. Follow https://github.com/Comfy-Org/ComfyUI_frontend#nightly-release to opt-in nightly release.

**Comment by martin-rizzo** [comment]
> Hey if you don't mind, could you please tell me what application's screenshot that is, that you posted? Also, how did you compare the two files, is it manual or the functionality of the application itself?

@iamrohitanshu, the screenshot shows a 'diff' between the two JSON files, there are several commands and tools that can do this automatically. The one I used is Meld on Linux.
Here’s a list of these utilities: https://en.wikipedia.org/wiki/Comparison_of_file_comparison_tools. I hope this helps.

**Comment by Dam88en** [comment]
Comfyui with Cloudflare on colab right? I had no issues before and out of nowhere I tried loading up comfyui and it doesn't load, but I get the link for it though

**Comment by iamrohitanshu** [comment]
> @iamrohitanshu, the screenshot shows a 'diff' between the two JSON files, there are several commands and tools that can do this automatically. The one I used is Meld on Linux. Here’s a list of these utilities: https://en.wikipedia.org/wiki/Comparison_of_file_comparison_tools. I hope this helps.

@martin-rizzo Thanks for the detailed reply. I use a plugin in np++ on Windows but it doesn't look as good, that's why I asked. I'll try some of those in this list.
