### ISSUE TITLE
[Bug]: Change Group Title Dialog often appears at edge of viewport or out of viewport

### ISSUE THREAD

**Issue by deepfree2023** [Comfy-Org/ComfyUI_frontend#730]
### Frontend Version

Like this image, I must move the group to the top of the viewport, then right click -> edit group -> Title, the Change Group Title Dialog appears just at bottom of the viewport. If I move the group lower,  the Change Group Title Dialog will be out of viewport.

This is quite annoying.

![image](https://github.com/user-attachments/assets/41dab672-8f61-4859-b1d8-a2793dea0f6a)

### Expected Behavior

Wherever the group is, the Change Group Title Dialog appears at the center of the viewport.

### Actual Behavior

 the Change Group Title Dialog appears at the edge of viewport, or out of viewport.

### Steps to Reproduce

 right click group title-> edit group -> Title

### Debug Logs

```powershell
无
```

### Browser Logs

无

### What browsers do you use to access the UI ?

Google Chrome, Other

**Comment by huchenlei** [comment]
We now supports group title edit by double click. The legacy way of title edit will be removed later. https://github.com/Comfy-Org/ComfyUI_frontend/pull/714
