### ISSUE TITLE
The image preview node cannot be stretched or enlarged. Only by saving the image node can it be stretched or enlarged!

### ISSUE THREAD

**Issue by aiise117** [Comfy-Org/ComfyUI_frontend#748]
The latest version of the image preview node only displays tiny thumbnails. Also, I found that double clicking on the search pop-up now causes a long delay before it appears。Hope for continuous improvement. Thank you！

**Comment by huchenlei** [comment]
Image resize not reproducable. Did you pin the node so it becomes not resizable?

https://github.com/user-attachments/assets/42bd071f-d246-42e9-9b75-f96c62a1966c

Searchbox issue should be addressed by https://github.com/Comfy-Org/ComfyUI_frontend/pull/713

**Comment by aiise117** [comment]
I don't know if it was set incorrectly. But all settings are default! I only encountered this issue after updating the version. The image preview window can be stretched and enlarged, but the images inside will not change, and the thumbnail size is still very small.
