### ISSUE TITLE
[Bug]: workflow saved and load not working

### ISSUE THREAD

**Issue by frankyifei** [Comfy-Org/ComfyUI_frontend#754]
### Frontend Version

1.2.47

### Expected Behavior

save and load should work properly, It worked before this recent update

### Actual Behavior

Can't load saved workflow, although it shows everything in \user\default\workflows, the error message is "127.0.0.1:8188 says Error loading workflow file '2x SDXL hand refiner v3.json': 404 Not Found " and nothing is loading
Can't save properly, when I did save, the actually saved file name is come with a leading string of "workflows%2F" and it is under \user\default\. 

### Steps to Reproduce

just save and load workflow from top bar

### Debug Logs

```powershell
none from terminal, so I believe it is a frontend issue
```

### Browser Logs

not relevant here

### What browsers do you use to access the UI ?

Google Chrome

**Comment by christian-byrne** [comment]
Same issue as:

- comfyanonymous/ComfyUI#4753
