### ISSUE TITLE
[Bug]: Error loading workflow file 'xxxxxxx.json': 404 Not Found

### ISSUE THREAD

**Issue by neugii** [Comfy-Org/ComfyUI_frontend#758]
### Frontend Version

1.2.47
Running in --disable-all-custom-nodes mode
![Screenshot from 2024-09-08 16-25-14](https://github.com/user-attachments/assets/ba05065e-9a2a-43f6-93ac-eb3cf2d36905)

### Expected Behavior

Should load saved workflow

### Actual Behavior

Javascript Error: Error loading workflow file 'xyz.json': 404 Not Found
Saving Workflow produced a file in the wrong directory with filename ./ComfyUI/user/default/worflows%2FnewFlow.json
![Screenshot from 2024-09-08 16-24-27](https://github.com/user-attachments/assets/1fd44342-ee74-424d-903d-ca57d951fe99)

### Steps to Reproduce

Open ComfyUI and try to load workflow via select box in Browser
![Screenshot from 2024-09-08 16-23-43](https://github.com/user-attachments/assets/2b9b18c7-ba0b-49c9-8ec2-aeb100796fe3)

### Debug Logs

```powershell
WebDeveloper Flow: 

GET http://127.0.0.1:8188/api/userdata/workflows%2Fxyz.json 404 (Not Found)
fetchApi @ api.ts:73
getUserData @ api.ts:565
getWorkflowData @ workflows.ts:292
load @ workflows.ts:315
onclick @ workflows.ts:773
```

### Browser Logs

WebDeveloper Flow: 

GET http://127.0.0.1:8188/api/userdata/workflows%2Fxyz.json 404 (Not Found)
fetchApi @ api.ts:73
getUserData @ api.ts:565
getWorkflowData @ workflows.ts:292
load @ workflows.ts:315
onclick @ workflows.ts:773

### What browsers do you use to access the UI ?

Google Chrome

**Comment by neugii** [comment]
WebDeveloper Error

![Screenshot from 2024-09-08 16-26-01](https://github.com/user-attachments/assets/e661008a-817c-4487-ba31-6d7188363e5c)

**Comment by christian-byrne** [comment]
Same issue as:

- comfyanonymous/ComfyUI#4753
