### ISSUE TITLE
[Bug]: Side bar shows drag/resize arrow without being resizable

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [Comfy-Org/ComfyUI_frontend#761]
### Frontend Version

v1.2.40

Please make the version copyable.
As it is, dragging anywhere around the UI of the Settings bar just moves the panel around.

### Expected Behavior

The sidebar has a resize-arrow, but does not allow resizing

### Actual Behavior

![image](https://github.com/user-attachments/assets/f507c545-9008-4062-b264-59c3b5e7e43f)

### Steps to Reproduce

On Firefox browser

### Debug Logs

```powershell
No logs available.
```

### Browser Logs

No logs available.

### What browsers do you use to access the UI ?

Firefox 130.0

**Comment by huchenlei** [comment]
This is the N-sidebar sidebar. Not the core sidebar. You can try disable N-Sidebar extension.https://github.com/Nuked88/ComfyUI-N-Sidebar
