### ISSUE TITLE
[Bug]: Can't fetch JavaScript files from ComfyUI backend custom_nodes by "/api/extensions" 

### ISSUE THREAD

**Issue by SongOnWater** [Comfy-Org/ComfyUI_frontend#775]
### Frontend Version

1.2.48

### Expected Behavior

Can get the data of custom_nodes JS files. 

### Actual Behavior

Response with no data. 

### Steps to Reproduce

Load Main page. 

### Debug Logs

```powershell
No
```

### Browser Logs

no 

### Other

as title

**Comment by huchenlei** [comment]
Cannot reproduce. Directly access `localhost:8188/api/extensions` should give you following result
![image](https://github.com/user-attachments/assets/ec981db2-aa17-4205-8d3e-e36e23eab4ac)
