### ISSUE TITLE
[Bug]: Node Locking doesn't seem to be working (doesn't fix either the position or the values (or both)

### ISSUE THREAD

**Issue by CaptainGrock** [Comfy-Org/ComfyUI_frontend#785]
### Frontend Version

ComfyUI: 2644[483004](2024-09-03)

### Expected Behavior

I thought that node locking would prevent a user from moving nodes around (wasn't sure if it locked the values as well)

### Actual Behavior

See video, you can lock nodes but they still can be dragged around (and the values also can be changed)
Video link: https://www.dropbox.com/scl/fi/gcg787os502tx3n4lvdms/node_locking_issue.mp4?rlkey=lznp5th1mansh0bzpi7yq9iu7&dl=0

### Steps to Reproduce

1. Right click a node and choose lock
2. Drag locked nodes around (and you can change values)

### Debug Logs

```powershell
none needed here
```

### Browser Logs

none needed here

**Comment by huchenlei** [comment]
The locking feature from ComfyUI-Custom-Scripts is replaced by node pinning in https://github.com/Comfy-Org/ComfyUI_frontend/pull/734
