### ISSUE TITLE
[Bug]: NodeBadge report errors and page is stuck when i use the custom color palette. 

### ISSUE THREAD

**Issue by yolain** [Comfy-Org/ComfyUI_frontend#793]
### Frontend Version

v.1.2.49

### Expected Behavior

```typescript
// NodeBadge.ts line 67: this.colorPalette.value is undefined cause by the colorPalettes only contain comfy default palettes 
this.colorPalette = computed(
  () => colorPalettes[settingStore.get('Comfy.ColorPalette')]
)
```

### Actual Behavior

The page is stuck and cannot be operated
<img width="1139" alt="stuck" src="https://github.com/user-attachments/assets/c912037f-2b6c-4422-a2c4-1d2192d07473">

### Steps to Reproduce

Choose one custom color palette

### Debug Logs

```powershell
nodeBadge.ts:114 Uncaught TypeError: Cannot read properties of undefined (reading 'colors')
```

### Browser Logs

![1726120763857](https://github.com/user-attachments/assets/6d010874-043a-4239-a29a-75ca930eeffa)

**Comment by LukeG89** [comment]
Slightly off topic, but opening a new bug report would've been too much for that. 
Just wanted to report this small graphical bug with badges when nodes are collapsed.

https://github.com/user-attachments/assets/67865a36-2ac3-4254-9625-468114fd78d3
