### ISSUE TITLE
[Bug]: Add node: Node confusion

### ISSUE THREAD

**Issue by yincangshiwei** [Comfy-Org/ComfyUI_frontend#802]
### Frontend Version

1.2.50

### Expected Behavior

![image](https://github.com/user-attachments/assets/008f80f7-11e8-4255-9896-285737ca0111)
![image](https://github.com/user-attachments/assets/a0b299c7-7af9-4d87-a726-a55d804e5f5d)

### Actual Behavior

![image](https://github.com/user-attachments/assets/008f80f7-11e8-4255-9896-285737ca0111)
![image](https://github.com/user-attachments/assets/a0b299c7-7af9-4d87-a726-a55d804e5f5d)

### Steps to Reproduce

add node

### Debug Logs

```powershell
no error logs
```

### Browser Logs

no error

**Comment by huchenlei** [comment]
Bug confirmed to be reproducable.
