### ISSUE TITLE
[Bug]: Nodes not rendered, canvas frozen

### ISSUE THREAD

**Issue by alessandroperilli** [Comfy-Org/ComfyUI_frontend#816]
### Frontend Version

1.2.52

### Expected Behavior

Stuff works as usual :)

### Actual Behavior

<img width="1560" alt="Screenshot 2024-09-13 at 09 55 40" src="https://github.com/user-attachments/assets/e2b2b40f-9698-44f2-bc56-6ed91c4ebffb">

Notice that, for a few milliseconds, all nodes appear on the canvas. Then, most of them disappear, and I end up in this situation. The canvas is completely frozen and it won't pan or zoom either.

### Steps to Reproduce

I just did a git pull like every morning.

I went back to front-end version 1.2.51 and the issue is not present.

### Debug Logs

```powershell
No warning or error.
```

### Browser Logs

<img width="692" alt="Screenshot 2024-09-13 at 09 59 01" src="https://github.com/user-attachments/assets/92ad3a9a-3d01-48b1-b1c4-5e08d1ac38a1">

### What browsers do you use to access the UI ?

Other

### Other

Vivaldi on macOS

**Comment by LukeG89** [comment]
Same to me

![freezed_workflow](https://github.com/user-attachments/assets/5a25e4bf-f925-470e-ab05-1e0d9d403b6b)

I can't even switch to other workflows

**Comment by LukeG89** [comment]
Just found out there is a conflict with [rgthree-comfy](https://github.com/rgthree/rgthree-comfy), the problem is gone if I disable it
