### ISSUE TITLE
[Feature Request]: The top menu (beta new menu) should really display the batch count at all times

### ISSUE THREAD

**Issue by rainlizard** [Comfy-Org/ComfyUI_frontend#842]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

For anyone who switches batch counts it's very annoying to hit the queue button and unexpectedly queue up 18 things because you genuinely forgot what number it was set to before.

There's actually a good reason why this happens - after you queue a bunch of stuff with a high batch count set, you will minimize the window or alt-tab and then time passes while you do something else, at that point you forget what number it was previously set to.

So you can see how this kind of thing will happen to absolutely everybody: Time passes while performing a long queue -> you forget what number it was, because so much time passed.

### Proposed workflow

![Untitled](https://github.com/user-attachments/assets/a03570aa-75ef-4acf-919f-cb4761de8567)

There might be a more elegant solution than this. I don't really care how it's done, you could even just change the text color of "Queue" to yellow whenever it's set to more than 1, even that would solve the problem.

**Comment by huchenlei** [comment]
Fixed by https://github.com/Comfy-Org/ComfyUI_frontend/pull/968
