### ISSUE TITLE
[Bug]: Shift+Drag node resets node position

### ISSUE THREAD

**Issue by christian-byrne** [Comfy-Org/ComfyUI_frontend#856]
### Frontend Version

1.2.55

### Expected Behavior

Shift+Drag to move all selected nodes.

### Actual Behavior

When Shift+Dragging, the selected nodes are put at default position and their `pos` value are set to `NaN` after releasing mouse.

### Steps to Reproduce

1. Click+Drag a node while holding Shift key

### Browser Logs

index.html:19 ComfyUI Front-end version: 1.2.55

18:14:38.650 index.ts:188 Uncaught (in promise) TypeError: app.ui.restoreMenuPosition is not a function
    at onChange (index.ts:188:18)
    at ComfySettingsDialog.addSetting (settings.ts:190:7)
    at new ComfyAppMenu (index.ts:160:48)
    at new ComfyApp (app.ts:157:17)
    at app.ts:2981:20
onChange @ index.ts:188
addSetting @ settings.ts:190
ComfyAppMenu @ index.ts:160
ComfyApp @ app.ts:157
(anonymous) @ app.ts:2981Understand this error
18:14:38.757 api.ts:74 
        
        
       GET http://localhost:5173/api/userdata/workflows%2F.index.json net::ERR_ABORTED 404 (Not Found)
fetchApi @ api.ts:74
getUserData @ api.ts:566
loadWorkflows @ workflows.ts:41
setup @ app.ts:1833
await in setup
(anonymous) @ GraphCanvas.vue:109
(anonymous) @ runtime-core.esm-bundler.js:1808
callWithErrorHandling @ runtime-core.esm-bundler.js:195
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:202
hook.__weh.hook.__weh @ runtime-core.esm-bundler.js:1788
flushPostFlushCbs @ runtime-core.esm-bundler.js:379
flushJobs @ runtime-core.esm-bundler.js:415
Promise.then
queueFlush @ runtime-core.esm-bundler.js:319
queuePostFlushCb @ runtime-core.esm-bundler.js:339
queueEffectWithSuspense @ runtime-core.esm-bundler.js:1760
scheduler @ runtime-core.esm-bundler.js:6113
resetScheduling @ reactivity.esm-bundler.js:262
triggerEffects @ reactivity.esm-bundler.js:306
triggerRefValue @ reactivity.esm-bundler.js:1071
set value @ reactivity.esm-bundler.js:1118
finalizeNavigation @ vue-router.mjs:3460
(anonymous) @ vue-router.mjs:3325
Promise.then
pushWithRedirect @ vue-router.mjs:3292
push @ vue-router.mjs:3217
install @ vue-router.mjs:3659
use @ runtime-core.esm-bundler.js:2984
(anonymous) @ main.ts:27Understand this error
18:14:42.014 api.ts:74 
        
        
       GET http://localhost:5173/api/userdata/workflows%2F.index.json net::ERR_ABORTED 404 (Not Found)
fetchApi @ api.ts:74
getUserData @ api.ts:566
loadWorkflows @ workflows.ts:41
load @ workflows.ts:361
#updateActive @ workflows.ts:84
setWorkflow @ workflows.ts:115
loadGraphData @ app.ts:2200
app.loadGraphData @ changeTracker.ts:102
loadWorkflow @ app.ts:1876
setup @ app.ts:1883
await in setup
(anonymous) @ GraphCanvas.vue:109
(anonymous) @ runtime-core.esm-bundler.js:1808
callWithErrorHandling @ runtime-core.esm-bundler.js:195
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:202
hook.__weh.hook.__weh @ runtime-core.esm-bundler.js:1788
flushPostFlushCbs @ runtime-core.esm-bundler.js:379
flushJobs @ runtime-core.esm-bundler.js:415
Promise.then
queueFlush @ runtime-core.esm-bundler.js:319
queuePostFlushCb @ runtime-core.esm-bundler.js:339
queueEffectWithSuspense @ runtime-core.esm-bundler.js:1760
scheduler @ runtime-core.esm-bundler.js:6113
resetScheduling @ reactivity.esm-bundler.js:262
triggerEffects @ reactivity.esm-bundler.js:306
triggerRefValue @ reactivity.esm-bundler.js:1071
set value @ reactivity.esm-bundler.js:1118
finalizeNavigation @ vue-router.mjs:3460
(anonymous) @ vue-router.mjs:3325
Promise.then
pushWithRedirect @ vue-router.mjs:3292
push @ vue-router.mjs:3217
install @ vue-router.mjs:3659
use @ runtime-core.esm-bundler.js:2984
(anonymous) @ main.ts:27Understand this error

### What browsers do you use to access the UI ?

Google Chrome

### Other

https://github.com/user-attachments/assets/06ca85e1-9f61-4451-8897-dd1252de77ee

**Comment by huchenlei** [comment]
I cannot reproduce this issue. Is this the stable version 1.2.55 or the head of main?

**Comment by christian-byrne** [comment]
This is 1.2.55. But it seems to happen because of a setting value, which makes it hard to isolate to a specific version.

After pulling today (from 1.2.49), the `Comfy.SnapToGrid.GridSize` setting was using `0` as its default value, despite having a `min` of `1`. The setting was not explicitly set prior. I was not able to find a custom node that would cause it.
