### ISSUE TITLE
[Bug]: Sidebar displays are confusing

### ISSUE THREAD

**Issue by water110** [Comfy-Org/ComfyUI_frontend#865]
### Frontend Version

V1.2.47

### Expected Behavior

![image](https://github.com/user-attachments/assets/76f90483-e211-4793-9d5b-4f455820dbb9)

### Actual Behavior

![image](https://github.com/user-attachments/assets/de1366a6-0107-4785-a886-c29e03104d0e)
I also installed the plug-in ComfyUI-N-Sidebar and adjusted its sidebar to be displayed on the left. When I started comfyui for the first time, everything was normal, but when I refreshed the page or opened a new tab, The sidebar will be displayed on the left, but I set it to the right,And the translation plug-in is no longer effective. It was supposed to be translated into Chinese, but it is still displayed in English. I don’t know whether the conflict is caused by ComfyUI-N-Sidebar or ComfyUI_frontend.I am using Google Chrome (version 127.0.6533.120) and will not have the above problem. When I use edge browser (version 128.0.2739.79), Quark browser (version 1.7.5.114), Cent browser (version 5.1. 1130.129, 64-bit, Chromium 118.0.5993.159), the above problem will occur;

### Steps to Reproduce

ComfyUI-N-Sidebar:https://github.com/Nuked88/ComfyUI-N-Sidebar
Quark browser:https://www.quark.cn/
Cent browser:http://www.centbrowser.cn/

### Debug Logs

```powershell
Starting server
To see the GUI go to: http://192.168.56.1:8188 or http://127.0.0.1:8188
To see the GUI go to: https://192.168.56.1:8189 or https://127.0.0.1:8189

E:\FreeSoft\sd\comfyui_standalone\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe-lightbox.esm.min.js

E:\FreeSoft\sd\comfyui_standalone\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe.min.css



FETCH DATA from: E:\FreeSoft\sd\comfyui_standalone\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

 [DONE]

E:\FreeSoft\sd\comfyui_standalone\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/pickr.min.js

['furry_lora.safetensors', 'yizhuanhua\\anime_lora.safetensors', 'yizhuanhua\\art_lora.safetensors', 'yizhuanhua\\disney_lora.safetensors', 'yizhuanhua\\mjv6_lora.safetensors', 'yizhuanhua\\realism_lora.safetensors', 'yizhuanhua\\scenery_lora.safetensors']

['furry_lora.safetensors', 'yizhuanhua\\anime_lora.safetensors', 'yizhuanhua\\art_lora.safetensors', 'yizhuanhua\\disney_lora.safetensors', 'yizhuanhua\\mjv6_lora.safetensors', 'yizhuanhua\\realism_lora.safetensors', 'yizhuanhua\\scenery_lora.safetensors']

E:\FreeSoft\sd\comfyui_standalone\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/classic.min.css

E:\FreeSoft\sd\comfyui_standalone\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/model-viewer.min.js

E:\FreeSoft\sd\comfyui_standalone\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.min.js


E:\FreeSoft\sd\comfyui_standalone\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.css

['furry_lora.safetensors', 'yizhuanhua\\anime_lora.safetensors', 'yizhuanhua\\art_lora.safetensors', 'yizhuanhua\\disney_lora.safetensors', 'yizhuanhua\\mjv6_lora.safetensors', 'yizhuanhua\\realism_lora.safetensors', 'yizhuanhua\\scenery_lora.safetensors']

['furry_lora.safetensors', 'yizhuanhua\\anime_lora.safetensors', 'yizhuanhua\\art_lora.safetensors', 'yizhuanhua\\disney_lora.safetensors', 'yizhuanhua\\mjv6_lora.safetensors', 'yizhuanhua\\realism_lora.safetensors', 'yizhuanhua\\scenery_lora.safetensors']
```

### Browser Logs

![image](https://github.com/user-attachments/assets/cf6d18bd-da4b-4060-8b68-cae08fe02561)
[127.0.0.1-1726588822978.log](https://github.com/user-attachments/files/17031682/127.0.0.1-1726588822978.log)

### What browsers do you use to access the UI ?

Google Chrome, Microsoft Edge, Other

**Comment by huchenlei** [comment]
This issue is caused by custom node's CSS setting. Please try disable custom node one by one to pin point the issue.
