### ISSUE TITLE
`widget.serialize` isn't part of the API, these should be `widget.serializeValue = () => {}`

### ISSUE THREAD

**Issue by doctorpangloss** [Comfy-Org/ComfyUI_frontend#866]
https://github.com/Comfy-Org/ComfyUI_frontend/blob/415a2e7fa5ff3c31276f80a0f7b9a2ca609770f6/src/extensions/core/uploadAudio.ts#L102

**Comment by webfiltered** [comment]
Hrm, to me it looks like it should just be `.options.serialize = false`.
