### ISSUE TITLE
[Feature Request]: Blender-like node interface

### ISSUE THREAD

**Issue by XJF2332** [Comfy-Org/ComfyUI_frontend#870]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Feature Idea

I’ve noticed that the current node interface in ComfyUI has its own unique approach, but I believe adopting Blender’s node design could significantly enhance user experience.

### Existing Solutions

Consider implementing Blender’s node design, where each node has both a text input box and a connection input. Here’s a visual example of what I’m referring to:
![image](https://github.com/user-attachments/assets/6e892d95-6879-4d19-a9e9-080c537fac46)
In ComfyUI, users must manually convert their desired input, which can be time-consuming and less intuitive compared to Blender’s approach.
Here are some advantages of Blender's node interface:
- Dual Input Mode: Nodes should display both a text input box and a connection port. This allows for quick adjustments and direct connections.
- Automatic Textbox Disable: When a node’s input is connected to another node’s output, the text input box should be automatically disabled. This prevents conflicting inputs and streamlines the workflow.

### Proposed workflow

i don't know how it works, but you may can check blender's source code, it is open source.

**Comment by JorgeR81** [comment]
100% agree.

For me, converting from widget to input, and vice-versa, is the most tedious part of building workflows.

**Comment by drmbt** [comment]
coming here from https://github.com/comfyanonymous/ComfyUI/issues/947 to bump this

**Comment by DrMechanica** [comment]
Commenting to add support for this change.
Looks like this is also being requested in issue #120. This is a much desired change.

**Comment by LukeG89** [comment]
I see that Pythongosssss is working on something: https://github.com/Comfy-Org/ComfyUI_frontend/pull/1021

**Comment by LukeG89** [comment]
This feature request can be closed after the implementation of this awesome feature: https://github.com/Comfy-Org/ComfyUI_frontend/commit/a2bd2a9bae1d6fc6135f7f56301b0e3682e834ee

**Comment by OneMonkeyArmy** [comment]
It works when dragging to a WIDGET, so it become an input and the connection is made....
But if I delete the connection, it remains as input... should get back to WIDGET with the value that was there in first place...

Exactly like this  here:  https://github.com/comfyanonymous/ComfyUI/issues/5294
that is taken from Unreal Blueprints....

Why arguing on a FACT, the UNREAL method, that I describe in the link above is the best solution.

**Comment by JorgeR81** [comment]
> But if I delete the connection, it remains as input... should get back to WIDGET with the value that was there in first place...

There is another issue to add this :

- https://github.com/Comfy-Org/ComfyUI_frontend/issues/1064
