### ISSUE TITLE
[Feature Request]: groups inside groups should be dragged

### ISSUE THREAD

**Issue by chrisgoringe** [Comfy-Org/ComfyUI_frontend#871]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

If I drag a group, all the nodes in it move with it. But if there is another group within in, the internal group doesn't move.

That makes it hard to have nested groups (which is useful for using the group bypass), because when you move the main group, the subgrouping gets broken.

Could be considered with #645 (but not the same issue)

### Proposed workflow

When a group is dragged, not only are all nodes that are part of that group moved with it, but all groups that overlap with it.

Example:
![Screenshot 2024-09-18 124137](https://github.com/user-attachments/assets/dd8a1fd4-ea07-40e5-a591-30cda820f21d)

Current behaviour, if I drag the outer group down, is:
![Screenshot 2024-09-18 124146](https://github.com/user-attachments/assets/59b7c474-c8ac-46b1-bce4-bf44caf10070)

Ideally it would be this:
![Screenshot 2024-09-18 124250](https://github.com/user-attachments/assets/37bb005f-a8cc-4239-a067-34933a0053c6)

**Comment by huchenlei** [comment]
Resolved by https://github.com/Comfy-Org/ComfyUI_frontend/pull/1416
