### ISSUE TITLE
[Bug]: 节点和连线错乱

### ISSUE THREAD

**Issue by BannyLon** [Comfy-Org/ComfyUI_frontend#873]
### Frontend Version

不知道为什么，我升级最新版后，就看到下面这一幕。
![11](https://github.com/user-attachments/assets/efb56759-39a2-4abb-ad88-ea3a01039f97)

### Expected Behavior

如何恢复正常

### Actual Behavior

不知道为什么，我升级最新版后，就看到下面这一幕。
![11](https://github.com/user-attachments/assets/efb56759-39a2-4abb-ad88-ea3a01039f97)

### Steps to Reproduce

不知道为什么，我升级最新版后，就看到下面这一幕。
![11](https://github.com/user-attachments/assets/efb56759-39a2-4abb-ad88-ea3a01039f97)

### Debug Logs

```powershell
不知道为什么，我升级最新版后，就看到下面这一幕。
![11](https://github.com/user-attachments/assets/efb56759-39a2-4abb-ad88-ea3a01039f97)
```

### Browser Logs

不知道为什么，我升级最新版后，就看到下面这一幕。
![11](https://github.com/user-attachments/assets/efb56759-39a2-4abb-ad88-ea3a01039f97)

### Other

不知道为什么，我升级最新版后，就看到下面这一幕。
![11](https://github.com/user-attachments/assets/efb56759-39a2-4abb-ad88-ea3a01039f97)

**Comment by zjf2671** [comment]
目前的我这里有种暂时的解决办法是，把电脑的分辩率改到100%
![d7a3d93c70c57226a6eb3c8a70e23d7](https://github.com/user-attachments/assets/da266ac9-df36-429b-aa79-b64f1c3dbb5c)

**Comment by BannyLon** [comment]
> 目前的我这里有种暂时的解决办法是，把电脑的分辩率改到100% ![d7a3d93c70c57226a6eb3c8a70e23d7](https://private-user-images.githubusercontent.com/25733810/368415182-da266ac9-df36-429b-aa79-b64f1c3dbb5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MzIxNDQsIm5iZiI6MTcyNjYzMTg0NCwicGF0aCI6Ii8yNTczMzgxMC8zNjg0MTUxODItZGEyNjZhYzktZGYzNi00MjliLWFhNzktYjY0ZjFjM2RiYjVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDAzNTcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZWZhYzI1YTYzN2Y1MDVlYTU3NTc1NjJkMjQwOTE3MGE2ZTBmM2I1MGEwNmM2OWZmMWIxNDNiNDBjOTg3N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y51iHGCuyigECCT8cZHqWjHI1lew0NXCiG8Co-SC-NM)

谢谢你！我改到100%后还是这样错乱的状态。

**Comment by BannyLon** [comment]
连线和节点完全分离。怎么会出现这种低级bug
![1726632044469](https://github.com/user-attachments/assets/d543d98b-89fe-42fe-92e6-0d47d15ad956)

**Comment by water110** [comment]
我也是遇到这个问题，前端版本是1.2.47，我是双显示器，一个显示器正常，一个不正常，我两个显示器分辨率都是2k的，尺寸不同,缩放到125%就会出现上述问题，100%不会出现此问题

**Comment by BannyLon** [comment]
> 我也是遇到这个问题，前端版本是1.2.47，我是双显示器，一个显示器正常，一个不正常，我两个显示器分辨率都是2k的，尺寸不同,缩放到125%就会出现上述问题，100%不会出现此问题

大家努力推动下，希望官方快点解决这个bug，

**Comment by water110** [comment]
可以关注其他类似问题反馈，https://github.com/yolain/ComfyUI-Easy-Use/issues/391，

https://github.com/shadowcz007/comfyui-mixlab-nodes/issues/324

**Comment by christian-byrne** [comment]
The issue is that Mixlab nodes changed to be compatible with ComfyUI_frontend v1.2.48 (Issue: https://github.com/shadowcz007/comfyui-mixlab-nodes/issues/318, Commit https://github.com/shadowcz007/comfyui-mixlab-nodes/commit/b2479ebff2fa9acfbfd9b5c80c6934f9c6b9535e), but stable release uses v1.2.47

Solution: add the following command line argument to your ComfyUI launch script to use latest release:

```
--front-end-version Comfy-Org/ComfyUI_frontend@latest
```

Edit: was fixed in Mixlab https://github.com/shadowcz007/comfyui-mixlab-nodes/commit/d9edbd535eb6f5705583833e3133b11cc95b27c4

**Comment by hillleaf** [comment]
更新mixlab到最新版既可以解决（卸载，再安装）。
