### ISSUE TITLE
[Bug]: IPAdapterUnifiedLoader ClipVision model not found. 

### ISSUE THREAD

**Issue by hiralidobariya** [Comfy-Org/ComfyUI_frontend#874]
### Frontend Version

..

### Expected Behavior

I added all the models, but I can't get any output

### Actual Behavior

I keep getting an error like 'IPAdapterUnifiedLoader ClipVision model not found.

### Steps to Reproduce

..

### Debug Logs

```powershell
File "E:\comfy ui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 559, in load_models
    raise Exception("ClipVision model not found.")
Exception: ClipVision model not found.
```

### Browser Logs

 File "E:\comfy ui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 559, in load_models
    raise Exception("ClipVision model not found.")
Exception: ClipVision model not found.

### What browsers do you use to access the UI ?

Brave

### Other

..

**Comment by EasyComfyui** [comment]
rename file 
CLIP-ViT-bigG-14-laion2B-39B-b160k.safetensors -> CLIP-ViT-bigG-14-laion2B-39B.b160k.safetensors
CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors -> CLIP-ViT-H-14-laion2B-s32B.b79K.safetensors
