### ISSUE TITLE
[Bug]: Workflows can't be dragged into the browser for display

### ISSUE THREAD

**Issue by flybirdxx** [Comfy-Org/ComfyUI_frontend#884]
### Frontend Version

v1.2.47

### Expected Behavior

Dragging workflows and images with workflows into the browser does not respond and does not show any workflow nodes.

### Actual Behavior

https://github.com/user-attachments/assets/dca0bcab-319f-499a-b3eb-c59d28f014c3

### Steps to Reproduce

The problem occurred after the update the day before yesterday, dragging in images and workflows did not work, there was no response at all.

### Debug Logs

```powershell
no errors
```

### Browser Logs

no errors

**Comment by huchenlei** [comment]
Please attach the image you used and open a new issue.

**Comment by flybirdxx** [comment]
https://github.com/user-attachments/assets/f84842da-46b4-4ccd-9445-35dd5af6bfaf
