### ISSUE TITLE
[Bug]: Workflows can't be dragged into the browser for display

### ISSUE THREAD

**Issue by flybirdxx** [Comfy-Org/ComfyUI_frontend#885]
### Frontend Version

v1.2.47

### Expected Behavior

Dragging workflows and images with workflows into the browser does not respond and does not show any workflow nodes.

### Actual Behavior

[

https://github.com/user-attachments/assets/bbce7112-60d1-4882-b0c4-447f84a90a97

](url)

### Steps to Reproduce

![20240919_125117](https://github.com/user-attachments/assets/a48fd63a-3034-420b-acb8-6a88ffab6a1e)

### Debug Logs

```powershell
no errors
```

### Browser Logs

no errors

### What browsers do you use to access the UI ?

Microsoft Edge

**Comment by flybirdxx** [comment]
我尝试过换浏览器和修改注册表也是同样的问题

**Comment by huchenlei** [comment]
You are attaching videos, while I need the exact image you dragged into the browser.

**Comment by flybirdxx** [comment]
No, I drag anything comfyui page does not respond, after I try other pages drag and drop is no problem!
