### ISSUE TITLE
[Bug]: Console errors about `/api/userdata/workflows%2F.index.json`

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI_frontend#899]
### Frontend Version

1.2.60 (same in previous versions)

### Expected Behavior

No console errors

### Actual Behavior

I always get these errors about `/api/userdata/workflows%2F.index.json`

### Steps to Reproduce

Check the console

### Debug Logs

```powershell
E:\>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --disable-all-custom-nodes --front-end-version Comfy-Org/ComfyUI_frontend@latest
Total VRAM 8192 MB, total RAM 65277 MB
pytorch version: 2.4.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: E:\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.2.60
E:\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Skipping loading of custom nodes
Starting server

To see the GUI go to: http://127.0.0.1:8188
```

### Browser Logs

After startup:
![error](https://github.com/user-attachments/assets/2200f86d-76a6-4cee-8912-25c8b72c93a9)

After refreshing the page:
![browser_errors](https://github.com/user-attachments/assets/116d3e8c-6049-43e2-be0e-7afa39ad9190)

### What browsers do you use to access the UI ?

Google Chrome

**Comment by pythongosssss** [comment]
This just means you don't have any favorites which are stored in that file, there is no actual error. The browser console just logs 404s and various other HTTP statuses to the console even if they are handled

**Comment by LukeG89** [comment]
@pythongosssss Thanks for your answer! Just added a workflow in the favorites and the errors are gone!
