### ISSUE TITLE
[Bug]: Not working in a reverse proxy environment from version 1.2.49

### ISSUE THREAD

**Issue by K-I-M-J-I-N** [Comfy-Org/ComfyUI_frontend#941]
### Frontend Version

1.2.49~

### Expected Behavior

works fine.

### Actual Behavior

No UI is generated except for the menu, and functionalities such as double-clicking, right-clicking, and loading workflows are also not working properly. The UI for ComfyUI Manager or rgthree is also not visible.

![image](https://github.com/user-attachments/assets/d5217696-600a-4ae9-93c5-ab6f44cb15c5)

New UI

![image](https://github.com/user-attachments/assets/9b63af16-24f4-44c5-936f-1e7bcfd89fc7)

Old UI

When trying to load a workflow, 

TypeError: can't access property "configure", this.graph is undefined

### Steps to Reproduce

Using JupyterHub and accessing ComfyUI through JupyterHub's reverse proxy.
The URL is as follows:
https://.../user/{username}/proxy/8188/

### Debug Logs

```powershell
python main.py --front-end-version Comfy-Org/ComfyUI_frontend@1.2.49 --disable-all-custom-nodes
Total VRAM 40339 MB, total RAM 1031868 MB
pytorch version: 2.4.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA A100-SXM4-40GB : cudaMallocAsync
Using pytorch cross attention
Failed to initialize frontend: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/Comfy-Org/ComfyUI_frontend/releases
Falling back to the default frontend.
[Prompt Server] web root: /home/jin/ComfyUI/web
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Skipping loading of custom nodes
Starting server

To see the GUI go to: http://127.0.0.1:8188
```

### Browser Logs

ComfyUI Front-end version: 1.2.60

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome

**Comment by mcmonkey4eva** [comment]
this PR should fix that https://github.com/Comfy-Org/ComfyUI_frontend/pull/939

**Comment by mcmonkey4eva** [comment]
Working as intended once again on frontend v1.3.1

**Comment by K-I-M-J-I-N** [comment]
not working from version 1.3.36. 

1.3.35 seems ok.

**Comment by mcmonkey4eva** [comment]
yep, it's broken again, cc @huchenlei 

I'd guess something in the router changes @ https://github.com/Comfy-Org/ComfyUI_frontend/commit/5e4439b905aa2e40bcfdf353014fc533d6074dc2 mixed up subrouting

**Comment by mcmonkey4eva** [comment]
~~re-fixed in v1.3.40, thanks hcl~~
EDIT: nope I tested wrong, I saw https://github.com/Comfy-Org/ComfyUI_frontend/commit/d1e019589d782bbe967c402d231191bcfdd155c7 edited router file and thought that fixed it, but nope I just accidentally was still testing 35.

Still broken on latest :(

**Comment by mcmonkey4eva** [comment]
fixed now via https://github.com/Comfy-Org/ComfyUI_frontend/pull/1532

**Comment by mcmonkey4eva** [comment]
Issue has appeared again, see here https://github.com/Comfy-Org/ComfyUI_frontend/issues/6995
