### ISSUE TITLE
[Feature Request]: Add shortcut to open settings

### ISSUE THREAD

**Issue by christian-byrne** [Comfy-Org/ComfyUI_frontend#942]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Open the settings menu when the shortcut is pressed.

### Proposed workflow

1. The shortcut sequence is pressed
2. The settings menu opens

### Additional information

[Apple HIG](https://developer.apple.com/design/human-interface-guidelines/keyboards#:~:text=Open%20the%20app%E2%80%99s%20settings%20window) and [GNOME HIG](https://developer.gnome.org/hig/reference/keyboard.html#:~:text=Opens%20the%20preferences%20window) recommend `Ctrl+,` for the shortcut that opens the settings window.

**Comment by mcmonkey4eva** [comment]
PR to add this: https://github.com/Comfy-Org/ComfyUI_frontend/pull/991
