### ISSUE TITLE
[dev1.3] Model preview should only appear when there is meaningful data to display

### ISSUE THREAD

**Issue by huchenlei** [Comfy-Org/ComfyUI_frontend#944]
Currently the model preview card always appear no matter if there is actually meaningful data to display

![image](https://github.com/user-attachments/assets/c490116b-482c-4467-b0ed-40c131324aa9)

**Comment by mcmonkey4eva** [comment]
https://github.com/Comfy-Org/ComfyUI_frontend/pull/949
