### ISSUE TITLE
[dev1.3] Hide total leaf count for model directories that are not loaded

### ISSUE THREAD

**Issue by huchenlei** [Comfy-Org/ComfyUI_frontend#945]
Currently all not loaded folder show a count of `1` on total leaves, which can be confusing. Please change it to `?` or just remove the chip if the folder is not loaded. @mcmonkey4eva You might want to do changes to `TreeExplorerNode.vue` to get this behavior implemented.

https://github.com/user-attachments/assets/0713e8c7-1dee-42af-954d-203a0ecbc520

**Comment by mcmonkey4eva** [comment]
https://github.com/Comfy-Org/ComfyUI_frontend/pull/953
