### ISSUE TITLE
[Bug]: Unable to See Workflow List with Menu Positioned at Bottom of Screen

### ISSUE THREAD

**Issue by camoody1** [Comfy-Org/ComfyUI_frontend#948]
### Frontend Version

ComfyUI_frontend v1.2.62

### Expected Behavior

When I position the Menu at the bottom of the screen, the Workflow list should open upwards into the grid area.

### Actual Behavior

Instead of opening upwards into the grid area, the list opens downward off the bottom of the browser window and isn't useable.

### Steps to Reproduce

1. Move Menu position to bottom of screen.
2. Click on the Workflow drop-list button.

### Debug Logs

```powershell
N/A
```

### Browser Logs

N/A

### What browsers do you use to access the UI ?

Microsoft Edge

### Other

![image](https://github.com/user-attachments/assets/7c5f2b21-b85c-48a1-8608-e9c056733bf5)

**Comment by huchenlei** [comment]
Top/Bottom menu position will be removed in dev1.3.

![image](https://github.com/user-attachments/assets/db09ccf4-e1c5-4316-97d4-33e8e7bb164a)

**Comment by LukeG89** [comment]
@camoody1 The bug is caused by [Crystools](https://github.com/crystian/ComfyUI-Crystools) after adapting Resource Monitor to the new menu.
I just opened a bug report about it https://github.com/crystian/ComfyUI-Crystools/issues/126

**Comment by camoody1** [comment]
> @camoody1 The bug is caused by [Crystools](https://github.com/crystian/ComfyUI-Crystools) after adapting Resource Monitor to the new menu. I just opened a bug report about it [crystian/ComfyUI-Crystools#126](https://github.com/crystian/ComfyUI-Crystools/issues/126)

Thank you, sir
