### ISSUE TITLE
[Bug]: Bypassed nodes look like muted nodes

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI_frontend#962]
### Frontend Version

1.2.63

### Expected Behavior

Bypassed nodes should look different to muted nodes.

### Actual Behavior

Bypassed and muted nodes look the same.

### Steps to Reproduce

https://github.com/user-attachments/assets/47854218-eeb8-461e-8e41-9659ad80706f

### Debug Logs

```powershell
No errors
```

### Browser Logs

No errors

### What browsers do you use to access the UI ?

Google Chrome

### Other

Node opacity was at 1 when testing

**Comment by JorgeR81** [comment]
I actually like the dark color on the bypassed nodes.

I've opened a feature request ( https://github.com/Comfy-Org/ComfyUI_frontend/issues/964 ), to allow customizing the colors, or at least switch the current colors, like this:
- dark = bypassed
- pink = muted

**Comment by huchenlei** [comment]
Culprit suspected https://github.com/Comfy-Org/ComfyUI_frontend/pull/947

**Comment by christian-byrne** [comment]
Sorry didn't see it until now
