### ISSUE TITLE
[Bug]: Pressing Refresh changes non-existing models to first in list.

### ISSUE THREAD

**Issue by nathanshipley** [Comfy-Org/ComfyUI_frontend#963]
### Frontend Version

1.2.47

### Expected Behavior

Press refresh on a workflow to update newly downloaded models should keep current non-existing model until I change it.

### Actual Behavior

Pressing refresh switches all selectable models to be the first one in the list, then I don't know what they were before I refreshed.

Example:
https://github.com/user-attachments/assets/108c927b-9da1-4860-9e0c-edfc04aea036

### Steps to Reproduce

see screencast

### Debug Logs

```powershell
n/a
```

### Browser Logs

n/a

### What browsers do you use to access the UI ?

Google Chrome

### Other

I'll often load a workflow from someone else and need to reconnect or gather models they're using.  i download some, put them in their folders, but when i click refresh to, say, update the list of checkpoints or LoRAs, all of the model selection nodes change from what was in the first workflow to whatever is the first of my current list.  which messes me up.  i might have the LoRA, it's just in a different place, but refresh jumbles what was in the saved workflow.

**Comment by mcmonkey4eva** [comment]
PR for this https://github.com/Comfy-Org/ComfyUI_frontend/pull/998
