### ISSUE TITLE
[Bug]: The resource monitoring is missing

### ISSUE THREAD

**Issue by yincangshiwei** [Comfy-Org/ComfyUI_frontend#992]
### Frontend Version

1.3.1

### Expected Behavior

1. Resource usage monitoring is displaying normally.
2. The text in the upper left corner can be displayed normally.

### Actual Behavior

1. Cannot see resource usage status.
old：
![H9`RSMF8_NP7 XY OK6BAHB](https://github.com/user-attachments/assets/4d0fbb64-1dad-4737-afc1-6c56e8326279)
new:
![image](https://github.com/user-attachments/assets/a2745ca6-118e-487c-9efb-1a6f804a4cd9)
2. Strange content appears in the upper left corner, which should be a progress bar.
![image](https://github.com/user-attachments/assets/bcb1a2fe-08f6-422b-9e0f-1f0066705c00)
![image](https://github.com/user-attachments/assets/9ab28af0-8632-49af-8e5e-7b125721e5e7)

### Steps to Reproduce

all workflow 

### Debug Logs

```powershell
no error log.
```

### Browser Logs

![image](https://github.com/user-attachments/assets/b7955871-46ab-4b5a-93f1-5f5c2c190901)

**Comment by mcmonkey4eva** [comment]
That status bar came from an extension, not from the core frontend.

The current modern v1.3.1 beta UI appearance without any extensions is:
![image](https://github.com/user-attachments/assets/14eab3a5-8a85-4bc1-b890-cb4729e3a99e)
