### ISSUE TITLE
[Bug]: Workflows not opening in new tabs

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI_frontend#995]
### Frontend Version

1.3.1

### Expected Behavior

As shown in this merged pull request https://github.com/Comfy-Org/ComfyUI_frontend/pull/952, workflows should now open in new tabs.

### Actual Behavior

Workflows open in the same window as before.

### Steps to Reproduce

![opened_workflows](https://github.com/user-attachments/assets/3e658962-55f4-4df4-8383-deddfb3a780c)

### Debug Logs

```powershell
E:\>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --disable-all-custom-nodes --preview-size 1024 --front-end-version Comfy-Org/ComfyUI_frontend@latest
Total VRAM 8192 MB, total RAM 65277 MB
pytorch version: 2.4.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: E:\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.3.1
E:\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Skipping loading of custom nodes
Starting server

To see the GUI go to: http://127.0.0.1:8188
```

### Browser Logs

```
Running on 127.0.0.1:8188
logging.ts:331 ComfyUI Front-end version: 1.3.1
```

### What browsers do you use to access the UI ?

Google Chrome

**Comment by mcmonkey4eva** [comment]
This is not a bug, that feature was intentionally hidden in PR https://github.com/Comfy-Org/ComfyUI_frontend/pull/984
It's possible to manually edit `(ComfyUI)/user/default/comfy.settings.json` to have `"Comfy.Workflow.WorkflowTabsPosition": "Topbar"` to get access to this behavior.

I'm not sure why it's hidden though? @huchenlei

**Comment by LukeG89** [comment]
Sorry, I didn't catch that! Thank you @mcmonkey4eva!

**Comment by huchenlei** [comment]
> This is not a bug, that feature was intentionally hidden in PR #984 It's possible to manually edit `(ComfyUI)/user/default/comfy.settings.json` to have `"Comfy.Workflow.WorkflowTabsPosition": "Topbar"` to get access to this behavior.
> 
> I'm not sure why it's hidden though? @huchenlei

It was a decision from @yoland68
