### ISSUE TITLE
[Bug]: Sidebar not updated after deleting an workflow

### ISSUE THREAD

**Issue by JorgeR81** [Comfy-Org/ComfyUI_frontend#996]
### Frontend Version

v1.31

### Expected Behavior

The sidebar is updated every time I delete a workflow.

### Actual Behavior

Sometimes the sidebar is not updated, when deleting a saved workflow.
Usually this is solved by refreshing the browser.

Refreshing the browser, before deleting a workflow, also seems to prevent this issue.

But, if the sidebar was not updated and I try to delete again, without refreshing, I have a "404 Not Found" error.
Usually after this the sidebar is also updated.

### Steps to Reproduce

- Save the current workflow.
- Delete the workflow.

### Debug Logs

```powershell
.
```

### Browser Logs

This is the browser log after successfully deleting the "Test04" workflow.
( As I mentioned above, I refreshed the browser before deleting, to make sure the GUI would update ).

![log1](https://github.com/user-attachments/assets/a4c0b921-2dfb-4b85-bccd-f81e4558149e)

---

Then I saved a "Test05" workflow, and delete it. The GUI was not updated, but I had the same log.
And an 404 error log ( in red ) when I tried to delete again.

![log2](https://github.com/user-attachments/assets/e719c949-510f-404b-93d5-f88e8eb9e3af)

### What browsers do you use to access the UI ?

Google Chrome

### Other

This is probably related to an issue I had before ( https://github.com/Comfy-Org/ComfyUI_frontend/issues/383 )
But I opened a new issue, because:
- this also happens with the new menu / sidebar 
- I didn't identify the problem correctly in the first issue. ( The workflow can be deleted; the issue is the GUI not updating ).

**Comment by mcmonkey4eva** [comment]
tested locally on Firefox and saw the same behavior - inconsistent, but it did happen.
